# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "/home/user/KoreaFun/.build")
from addlib import append

E = [
# --- Dated / in-window Busan events ---
("🎆","21st Busan Fireworks Festival (부산불꽃축제)","✅ CONFIRMED — Sat Nov 7, 2026 · Gwangalli Beach",
 "Korea's biggest fireworks festival — an hour of multi-barge pyrotechnics fired along Gwangalli Beach and off Gwangan Bridge itself, with the bridge used as a 7.4 km set piece",
 "Main show **~19:00–20:00**; viewing areas open **10:00**, paid-seat entry from **15:00**",
 "Standing on the beach **FREE**; R/S reserved seats sold from ~**Sep 1** via the official site",
 "[busanfireworks.com](https://www.busanfireworks.com) · [english.visitbusan.net](https://english.visitbusan.net)",
 "**The single biggest event of your entire trip.** Expect 1M+ people; Gwangan Station will be one-way-controlled and the subway will run late. Free alternative viewpoints: **Igidae Park**, **Dongbaekseom**, **Hwangnyeongsan summit**, **Millak Waterside Park**. Arrive by 15:00 for a beach spot, or 17:00 for Igidae."),

("🎮","G-STAR 2026 — Korea's Game Show (지스타)","👀 WATCH — mid-Nov 2026 · BEXCO",
 "Asia's biggest game expo outside Tokyo — 3,000+ booths, esports stages, indie showcase and Korea's whole games industry in one hall. 2025 ran Nov 14–17, so the 2026 edition is expected in the same mid-November slot",
 "Typically **10:00–18:00** over four days (trade day first)",
 "Typically **₩12,000–₩15,000** per day; pre-sale cheaper",
 "[gstar.or.kr](https://www.gstar.or.kr) · [bexco.co.kr](https://www.bexco.co.kr)",
 "Line 2 BEXCO (Centum City) Station. **Dates not yet published for 2026** — check gstar.or.kr in September. If it lands mid-November it sits perfectly in your window."),

("🕯️","Turn Toward Busan Ceremony (턴 투워드 부산)","✅ CONFIRMED — Nov 11, 2026 · 11:00",
 "The worldwide minute of silence for UN Korean War dead, observed at **exactly 11:00 on Nov 11** at the UN Memorial Cemetery in Busan — the only UN cemetery in the world",
 "Ceremony at **11:00**; cemetery open daily **09:00–17:00** (Nov)",
 "**FREE**",
 "[unmck.or.kr](https://www.unmck.or.kr) · [Ministry of Patriots & Veterans Affairs](https://www.mpva.go.kr)",
 "Line 2 Daeyeon Station Exit 3, 15-min walk. Genuinely moving, and the cemetery grounds in autumn colour are beautiful. Attend even if you miss the 11:00 moment."),

("💡","Seomyeon Light Festival (서면 빛축제)","✅ CONFIRMED — Nov 2026 – Feb 2027",
 "Busan's downtown winter illumination along Seomyeon 1st Street — light tunnels, tree canopies and installations through the main shopping district",
 "Nightly, roughly **18:00–24:00**",
 "**FREE**",
 "[english.visitbusan.net](https://english.visitbusan.net) · [Busanjin-gu](https://www.busanjin.go.kr)",
 "Line 1/2 Seomyeon Station. Usually switches on in early-to-mid November, so most of your trip should catch it. Zero planning needed — it's on your way to dinner."),

("✨","Millak Luce Festa (민락 루체페스타)","✅ CONFIRMED — Nov 2026 – Jan 2027 (ref. Nov 1 – Jan 31)",
 "Light festival on the Millak waterfront just east of Gwangalli — illuminated sea-front promenade facing Gwangan Bridge",
 "Nightly **18:00–23:30**",
 "**FREE**",
 "[english.visitbusan.net](https://english.visitbusan.net) · [Suyeong-gu](https://www.suyeong.go.kr)",
 "Line 2 Gwangan Station. Walk Gwangalli Beach east to Millak — you get the bridge light show and the festa in one loop."),

("🎇","Busan Christmas Tree Festival build-up (부산크리스마스트리문화축제)","👀 WATCH — installation from late Nov",
 "The Gwangbok-ro festival itself starts in December, but the tree and light installations go up through **late November** — you may catch the build and the switch-on rehearsals",
 "Installation period; lights typically on from **~18:00**",
 "**FREE**",
 "[english.visitbusan.net](https://english.visitbusan.net) · [Jung-gu](https://www.bsjunggu.go.kr)",
 "Line 1 Nampo Station. Worth a walk on Nov 20–22 to see whether the switch-on has happened early."),

# --- Museums & culture ---
("🏛️","Busan Museum (부산박물관)","🔁 Tue–Sun (FREE)",
 "The city's main history museum — Gaya and Silla artefacts, the Joseon Japan-trade waegwan, colonial Busan and the wartime capital years",
 "Tue–Sun **09:00–18:00** (closed Mondays)",
 "**FREE**",
 "[museum.busan.go.kr](https://museum.busan.go.kr)",
 "Line 2 Daeyeon Station Exit 3 — same walk as the UN Cemetery. Do both in one morning."),

("🏺","Bokcheon Museum & Bokcheon-dong Tomb Park (복천박물관)","🔁 Tue–Sun (FREE)",
 "Museum built over an excavated Gaya-era tomb cluster — 169 tombs on the hill above, with a glass-roofed excavation shelter you can walk into",
 "Tue–Sun **09:00–18:00** (closed Mondays)",
 "**FREE**",
 "[museum.busan.go.kr/bokcheon](https://museum.busan.go.kr/bokcheon)",
 "Line 1 Dongnae Station or Line 3 Suan. The open-air tomb park behind the museum is free and has a great city view."),

("🖼️","Busan Museum of Art (부산시립미술관)","🔁 Tue–Sun (FREE)",
 "The city art museum at Centum City, with the separate **Lee Ufan Space** — a dedicated building for Korea's most internationally significant living artist",
 "Tue–Sun **10:00–18:00** (closed Mondays)",
 "Permanent collection **FREE**; special exhibitions ticketed",
 "[art.busan.go.kr](https://art.busan.go.kr)",
 "Line 2 Busan Museum of Art Station Exit 5. The Lee Ufan Space alone is worth the trip — a quiet, near-empty building of stone-and-steel works."),

("🎬","Busan Cinema Center — BIFF venue (영화의전당)","🔁 daily",
 "The architectural landmark of Busan — a 163 m cantilevered LED roof, the world's largest, over an outdoor cinema plaza. BIFF's home venue, screening films year-round",
 "Building open daily; roof light show nightly around **19:00–21:00**; screenings throughout the day",
 "Roof light show **FREE**; films typically **₩7,000–₩10,000**",
 "[dureraum.org](https://www.dureraum.org)",
 "Line 2 Centum City Station Exit 6. BIFF is October, but the Cinema Center runs an independent/classic programme all year and the roof at night is free."),

("🕰️","Busan Modern History Museum (부산근대역사관)","🔁 Tue–Sun (FREE)",
 "In the former Oriental Development Company building (later a US information centre) — the story of colonial Busan, the port, and the Korean War refugee city",
 "Tue–Sun **09:00–18:00** (closed Mondays)",
 "**FREE**",
 "[modern.busan.go.kr](https://modern.busan.go.kr)",
 "Line 1 Jungang Station Exit 5. Small, free, and it explains almost everything you'll see in Nampo-dong."),

("🇰🇷","Provisional Capital Memorial Hall (임시수도기념관)","🔁 Tue–Sun (FREE)",
 "The house where President Syngman Rhee lived when **Busan was South Korea's capital (1950–53)** — preserved as it was, plus an exhibition hall on the refugee city",
 "Tue–Sun **09:00–18:00** (closed Mondays)",
 "**FREE**",
 "[busan.go.kr/mtcapital](https://www.busan.go.kr/mtcapital)",
 "Line 1 Toseong Station Exit 2. The single best place to understand why Busan feels different from every other Korean city."),

("🏯","Busan Metropolitan City Yongdusan Park & Busan Tower (용두산공원·부산타워)","🔁 daily",
 "The 120 m tower on the hill above Nampo-dong, modelled on the Bulguksa Dabotap pagoda finial, with a 360° observation deck over the port",
 "Daily **10:00–22:00**",
 "Observation deck adult **₩12,000**; park **FREE**",
 "[busan.go.kr](https://www.busan.go.kr) · [Jung-gu tourism](https://www.bsjunggu.go.kr)",
 "Line 1 Nampo Station Exit 1, then the free outdoor escalators up. The park itself is free and the view from the base is already good."),

("🐚","Busan National Science Museum (국립부산과학관)","🔁 Tue–Sun",
 "National science museum in Gijang themed on the industries of the southeast — cars, ships, aerospace and nuclear power, all hands-on",
 "Tue–Sun **09:30–17:30** (closed Mondays)",
 "Adult **₩7,000**; youth ₩5,000; child ₩3,000",
 "[sciport.or.kr](https://www.sciport.or.kr)",
 "Donghae Line to Osiria Station. Combine with Lotte Premium Outlets and Haedong Yonggungsa on the same Gijang trip."),

("📚","Busan Metropolitan Library & F1963 Complex (F1963)","🔁 Tue–Sun (FREE)",
 "A former Kiswire steel-rope factory converted into a cultural complex — Kukje Gallery Busan, a Praha 993 brewery, YES24 used bookstore, bamboo garden and a concert hall",
 "Most venues Tue–Sun **10:00–19:00** (closed Mondays)",
 "Grounds and most galleries **FREE**",
 "[f1963.org](https://www.f1963.org)",
 "Line 2 Mangmi Station + short bus/taxi. One of the best industrial conversions in Korea and almost no foreign tourists go."),

# --- Coast, nature, walks ---
("🌊","Igidae Coastal Walk (이기대 해안산책로)","🔁 daily (FREE)",
 "The 4.7 km cliff-edge boardwalk on the headland facing Gwangalli — suspension bridges, rock platforms and the best skyline view of Gwangan Bridge",
 "Always open; **do it in daylight**, ~2 h one way",
 "**FREE**",
 "[english.visitbusan.net](https://english.visitbusan.net) · [Nam-gu](https://www.bsnamgu.go.kr)",
 "Bus 22/24/27 to Igidae. **This is also the premium free viewpoint for the Nov 7 fireworks** — you see the whole bridge in frame."),

("🌉","Oryukdo Skywalk & Islands (오륙도 스카이워크)","🔁 Tue–Sun (FREE)",
 "Glass-floored walkway 35 m above the sea at the point where the East Sea meets the South Sea, looking out at the five-or-six islands that name it",
 "Tue–Sun **09:00–18:00** (closed Mondays and in high wind)",
 "**FREE** (shoe covers provided)",
 "[english.visitbusan.net](https://english.visitbusan.net) · [Nam-gu](https://www.bsnamgu.go.kr)",
 "Bus 27 from Kyungsung Univ. Station. The Igidae trail ends here — walk one, bus back."),

("🌅","Haeundae Dalmaji-gil & Moontan Road (달맞이길·문탠로드)","🔁 daily (FREE)",
 "The 'moon-greeting' road above Haeundae — a wooded 2.2 km night-walking trail through pines, plus a cafe and gallery street with sea views",
 "Always open; the trail is **lit for night walking**",
 "**FREE**",
 "[english.visitbusan.net](https://english.visitbusan.net) · [Haeundae-gu](https://www.haeundae.go.kr)",
 "Bus from Haeundae Station Exit 7. Korea's only officially designated night-walking trail — pleasantly weird and completely safe."),

("🚂","Haeundae Blueline Park Beach Train & Sky Capsule (해운대 블루라인파크)","🔁 daily",
 "The old Donghae rail line along the coast reborn as a slow beach train and pastel four-person **Sky Capsules** running above the shore from Mipo to Cheongsapo",
 "Daily roughly **09:00–19:00** (Nov, shorter than summer)",
 "Beach train day pass **₩13,000**; Sky Capsule from **₩30,000** (2 people, one way)",
 "[bluelinepark.com](https://www.bluelinepark.com)",
 "Sky Capsules **sell out** — book online days ahead. If they're gone, the beach train covers the same coast for a third of the price."),

("🪨","Taejongdae Resort Park & Danubi Train (태종대)","🔁 daily",
 "The dramatic cliff park at the southern tip of Yeongdo — lighthouse, sea-rock platform, observatory and a road train that loops the headland",
 "Park daily **04:00–24:00**; Danubi train roughly **09:00–19:00**",
 "Park **FREE**; Danubi train **₩4,000**",
 "[taejongdae.bisco.or.kr](https://taejongdae.bisco.or.kr)",
 "Bus 8/30/66/88 to Taejongdae. Walk down to the lighthouse and the *jagalmadang* pebble beach; ride the train back up the hill."),

("🌉","Huinnyeoul Culture Village (흰여울문화마을)","🔁 daily (FREE)",
 "A cliffside refugee village on Yeongdo, whitewashed houses stacked above the sea with a narrow coastal path beneath — the *Nameless Gangster* filming location",
 "Alleys always open; cafes roughly **10:00–20:00**",
 "**FREE**",
 "[english.visitbusan.net](https://english.visitbusan.net) · [Yeongdo-gu](https://www.yeongdo.go.kr)",
 "Bus 6/9/71 from Nampo. Residential — keep the noise down. The seaside tunnel path below is the photograph everyone comes for."),

("⛰️","Geumjeongsanseong Fortress Wall Walk (금정산성)","🔁 daily (FREE)",
 "Korea's **largest mountain fortress** — an 18.8 km wall with four gates around Geumjeongsan, above northern Busan",
 "Always open; the popular North Gate–East Gate section is ~3 h",
 "**FREE**; cable car separate",
 "[english.visitbusan.net](https://english.visitbusan.net) · [Korea Heritage Service](https://www.khs.go.kr)",
 "Take the **Geumgang Park cable car** (Line 1 Oncheonjang Station) up and walk the ridge — that skips the climb entirely."),

("🧘","Beomeosa Temple (범어사)","🔁 daily (FREE)",
 "Founded 678, one of Korea's great Zen temples, on the wooded eastern slope of Geumjeongsan — famous for its one-pillar gate and autumn maples",
 "Daily roughly **08:30–17:30**; templestay by booking",
 "**FREE**",
 "[beomeosa.co.kr](http://www.beomeosa.co.kr) · [eng.templestay.com](https://eng.templestay.com)",
 "Line 1 Beomeosa Station Exit 5/7 + bus 90. **Mid-November is peak foliage here** — one of Busan's best autumn days out."),

("♨️","Heosimcheong Spa, Dongnae Hot Springs (허심청)","🔁 daily",
 "One of Asia's largest hot-spring bathhouses — 40+ pools fed by the 1,000-year-old Dongnae springs, in a complex that holds 3,000 bathers",
 "Daily **05:30–21:00**",
 "Adult **₩11,000–₩13,000**",
 "[hotelnongshim.com](https://www.hotelnongshim.com)",
 "Line 1 Oncheonjang Station Exit 1. Real geothermal water, not heated tap — and Dongnae *pajeon* restaurants are on the same street."),

("🦆","Nakdong Estuary Eco Center & Migratory Birds (낙동강하구에코센터)","🔁 Tue–Sun (FREE)",
 "Korea's most important migratory bird wetland at the Nakdong River mouth — **November is peak arrival season** for swans, geese and ducks from Siberia",
 "Tue–Sun **09:00–18:00** (closed Mondays)",
 "**FREE**; telescopes provided",
 "[wetland.busan.go.kr](https://wetland.busan.go.kr)",
 "Line 1 Hadan Station + bus 58/58-1. A Natural Monument site. Go in the morning; bring binoculars if you have them."),

("🌾","Samnak Ecological Park & Eulsukdo Island (삼락생태공원)","🔁 daily (FREE)",
 "Vast riverside park on the Nakdong — silver-grass fields, cycle paths and the Eulsukdo bird sanctuary and cultural centre",
 "Always open",
 "**FREE**",
 "[parks.busan.go.kr](https://parks.busan.go.kr)",
 "Line 2 Deokpo/Sasang + bus. The silver grass here holds well into November and it's flat, easy cycling."),

("🏞️","Hwangnyeongsan Mountain Observatory (황령산 전망대)","🔁 daily (FREE)",
 "The 427 m peak in the middle of Busan with a road to a summit observatory — the definitive night panorama of Gwangan Bridge, Haeundae and the port",
 "Always open; best after dark",
 "**FREE**",
 "[english.visitbusan.net](https://english.visitbusan.net)",
 "Taxi from Seomyeon (~15 min) is the practical way up. **A prime free fireworks viewpoint on Nov 7** — arrive very early, the road gets closed."),

("🌲","Amnam Park & Songdo Yonggung Suspension Bridge (암남공원)","🔁 daily (FREE)",
 "Cliff park at the end of Songdo Beach with the 127 m **Songdo Yonggung Cloud Bridge** running out to a rock islet over open sea",
 "Bridge daily **09:00–18:00** (Nov); park always open",
 "**FREE**",
 "[english.visitbusan.net](https://english.visitbusan.net) · [Seo-gu](https://www.bsseogu.go.kr)",
 "Bus 6/30/71 to Amnam Park. Closes in high wind. Combine with the Songdo Skywalk and the cable car."),

("🚶","Songdo Beach Skywalk (송도구름산책로)","🔁 daily (FREE)",
 "A 365 m glass-panelled walkway curving out over the sea from Korea's **first public beach (opened 1913)**",
 "Daily roughly **06:00–23:00**",
 "**FREE**",
 "[english.visitbusan.net](https://english.visitbusan.net)",
 "Line 1 Jagalchi Station + bus 6/30/71. Free, five minutes, and it pairs with the cable car directly above."),

("🐋","Gijang Ilgwang Beach & Haedong Yonggungsa Coast Walk","🔁 daily (FREE)",
 "The quieter Gijang coastline north of Haeundae — Ilgwang Beach, fishing villages, and the coastal approach to the seaside temple",
 "Always open",
 "**FREE**",
 "[english.visitbusan.net](https://english.visitbusan.net) · [Gijang-gun](https://www.gijang.go.kr)",
 "Donghae Line to Ilgwang Station. Far emptier than Haeundae in November, and the seafood is cheaper."),

("🌅","Dadaepo Beach Sunset Fountain of Dreams (다대포 꿈의낙조분수)","🔁 seasonal / daily (FREE)",
 "The world's largest floor fountain, at the Nakdong estuary beach with Busan's best sunset — the music fountain show runs in season",
 "Beach always open; **fountain shows are seasonal (Apr–Oct) — expect the fountain off in November**",
 "**FREE**",
 "[english.visitbusan.net](https://english.visitbusan.net) · [Saha-gu](https://www.saha.go.kr)",
 "Line 1 Dadaepo Beach Station Exit 4. Come for the sunset over the mudflats, not the fountain — sunset is ~**17:20** in November."),

# --- Markets, food, neighbourhoods ---
("🐟","Jagalchi Market Second-Floor Cook-Your-Catch (자갈치시장)","🔁 daily",
 "Korea's largest seafood market — buy live fish from the ground-floor tanks, then pay a small fee for a second-floor restaurant to prepare it as sashimi and stew",
 "Daily roughly **05:00–22:00** (closed 1st & 3rd Tuesday)",
 "Market free; preparation fee typically **₩5,000–₩10,000** per person plus the fish",
 "[jagalchimarket.or.kr](http://www.jagalchimarket.or.kr) · [english.visitbusan.net](https://english.visitbusan.net)",
 "Line 1 Jagalchi Station Exit 10. Agree the price **before** they weigh the fish. The *maeuntang* stew made from the bones is included."),

("🍜","BIFF Square Street Food & Ssiat Hotteok (비프광장)","🔁 daily",
 "The old cinema square in Nampo-dong with handprints of film stars, and the origin of **ssiat hotteok** — a seed-stuffed fried pancake found nowhere else in Korea",
 "Stalls roughly **10:00–22:00**",
 "Hotteok **₩2,000**; most street food under ₩5,000",
 "[english.visitbusan.net](https://english.visitbusan.net)",
 "Line 1 Jagalchi Station Exit 7. The seed hotteok queue moves fast and it is worth joining."),

("🥟","Gukje Market & Kkangtong Night Market (국제시장·깡통야시장)","🔁 daily",
 "The market that grew out of the Korean War refugee economy — and the covered **Kkangtong night market**, one of Korea's only true nightly street-food markets",
 "Day market roughly **09:00–20:00**; **night market 19:30–23:30**",
 "**FREE** to browse; dishes ₩3,000–₩8,000",
 "[english.visitbusan.net](https://english.visitbusan.net) · [Jung-gu](https://www.bsjunggu.go.kr)",
 "Line 1 Jagalchi Station Exit 7. The night market only sets up after 19:30 — don't come at 18:00 and wonder where it is."),

("🍲","Bupyeong Kkangtong Market Dwaeji-gukbap Alley (돼지국밥거리)","🔁 daily",
 "Busan's signature dish — pork-broth rice soup, invented by wartime refugees — served in a cluster of specialist shops open around the clock",
 "Many shops **24 h**",
 "**₩8,000–₩11,000** a bowl",
 "[english.visitbusan.net](https://english.visitbusan.net)",
 "Line 1 Jagalchi/Toseong. Add the chive salad and shrimp sauce they bring you — that's the local method."),

("🥞","Dongnae Pajeon & Dongnae Old Town Walk (동래파전)","🔁 daily",
 "Dongnae's thick seafood-and-scallion pancake is a designated Busan intangible cultural asset, eaten in the old town beside Dongnae-eupseong fortress",
 "Restaurants roughly **11:00–21:00**",
 "Pajeon **₩20,000–₩30,000** (shared)",
 "[english.visitbusan.net](https://english.visitbusan.net) · [Dongnae-gu](https://www.dongnae.go.kr)",
 "Line 1/4 Dongnae Station. Order it with *dongdongju* rice wine — that's the traditional pairing and it's cheap."),

("🌶️","Choryang Ibagu-gil & 168 Steps Monorail (초량 이바구길)",'🔁 daily (FREE)',
 "The 'storytelling road' up the hillside above Busan Station — refugee-era houses, the 168-step staircase with a free monorail, and a harbour view at the top",
 "Always open; monorail roughly **05:00–24:00**",
 "**FREE** including the monorail",
 "[english.visitbusan.net](https://english.visitbusan.net) · [Dong-gu](https://www.bsdonggu.go.kr)",
 "Line 1 Busan Station Exit 7. Ten minutes from the KTX platform — a perfect first or last hour in Busan."),

("🎨","Gamcheon Culture Village Stamp Trail (감천문화마을 스탬프 투어)","🔁 daily",
 "The official stamp-collecting route through the painted hillside village — buy a map, collect stamps at nine points, trade a full sheet for a postcard set",
 "Village always open; information centre **09:00–18:00**",
 "Map **₩2,000**; village entry **FREE**",
 "[gamcheon.or.kr](https://www.gamcheon.or.kr)",
 "Line 1 Toseong Station Exit 6 + village bus. The stamp route forces you into the good alleys instead of just the main photo street."),

("🐡","Millak Raw Fish Town (민락회타운)","🔁 daily",
 "A whole building of *hoe* (sashimi) restaurants on the Millak waterfront — buy fish downstairs, eat it upstairs looking at Gwangan Bridge",
 "Roughly **10:00–24:00**",
 "Sashimi platters from **₩40,000** (shared)",
 "[english.visitbusan.net](https://english.visitbusan.net)",
 "Line 2 Gwangan Station Exit 3/5. Locals eat here instead of on Gwangalli Beach — same view, half the price."),

("🌃","Gwangan Bridge Night Lighting & Beach Promenade","🔁 nightly (FREE)",
 "The 7.4 km Diamond Bridge runs a programmed light display every night, with the beach promenade and its cafe strip facing it",
 "Lighting roughly **sunset–24:00**; **special weekend programmes** at set times",
 "**FREE**",
 "[english.visitbusan.net](https://english.visitbusan.net)",
 "Line 2 Gwangan Station Exit 3/5. Pair with the **free Saturday M Drone Light Show** already listed in this guide."),

("🏬","Shinsegae Centum City — world's largest department store","🔁 daily",
 "Guinness-recognised as the largest department store in the world, with an ice rink, cinema, golf range and Spa Land inside",
 "Daily **10:30–20:00** (Fri–Sun until 20:30)",
 "**FREE** entry; Spa Land from **₩20,000**",
 "[department.shinsegae.com](https://department.shinsegae.com)",
 "Line 2 Centum City Station, directly connected. One stop from BEXCO — the standard G-STAR rest stop."),

("🛍️","Lotte Premium Outlets Dongbusan & Osiria Tourism Complex","🔁 daily",
 "The large outlet mall on the Gijang coast, at the centre of the Osiria complex with the science museum, Lotte World Adventure Busan and the coast",
 "Daily **10:30–21:00**",
 "**FREE** entry",
 "[store.lotteshopping.com](https://store.lotteshopping.com)",
 "Donghae Line Osiria Station. Combine outlets + science museum + Haedong Yonggungsa in one Gijang day."),

("🎢","Lotte World Adventure Busan (롯데월드 어드벤처 부산)","🔁 daily",
 "Busan's outdoor theme park on the Osiria coast, opened 2022 — a Giant Digger dive coaster and a hillside setting looking at the East Sea",
 "Daily roughly **10:00–19:00** (Nov, shorter than summer; check daily calendar)",
 "1-day pass adult **₩47,000**; after-4pm pass cheaper",
 "[adventurebusan.lotteworld.com](https://adventurebusan.lotteworld.com)",
 "Donghae Line Osiria Station + shuttle. **November hours vary a lot** — always check the operating calendar the day before."),

("⚓","Busan Port Bridge & Yeongdo Bridge Lift (영도대교 도개)","🔁 daily (FREE)",
 "Korea's only remaining **lifting bascule bridge** — Yeongdodaegyo raises its deck once a day at 14:00, a ritual dating to 1934",
 "Bridge lift **daily at 14:00** (~15 min)",
 "**FREE**",
 "[english.visitbusan.net](https://english.visitbusan.net) · [Yeongdo-gu](https://www.yeongdo.go.kr)",
 "Line 1 Nampo Station Exit 6. Be on the Nampo side by 13:50. Free, brief, and genuinely charming."),

("🚢","Busan Port International Passenger Terminal Observatory","🔁 daily (FREE)",
 "Free observation deck above Korea's biggest passenger port, watching the Japan ferries and container traffic in the world's 7th-busiest container port",
 "Roughly **09:00–18:00**",
 "**FREE**",
 "[busanpa.com](https://www.busanpa.com)",
 "Line 1 Choryang/Busan Station + 10-min walk. A quiet, free, air-conditioned view of the port at work."),

("🌁","Busan X the Sky Observatory (부산엑스더스카이)","🔁 daily",
 "Korea's second-tallest building at Haeundae — a 100th-floor observation deck 411 m over the beach, with a glass-floor ledge and the highest Starbucks in Korea",
 "Daily **10:00–21:00** (last entry 20:30)",
 "Adult **₩27,000**",
 "[busanxthesky.com](https://www.busanxthesky.com)",
 "Line 2 Jung-dong Station Exit 1 or Haeundae Exit 3. Go about an hour before sunset (~17:20 in November) to get daylight, sunset and night in one ticket."),

("🎡","Haeundae Cheongsapo Daritdol Observatory (청사포 다릿돌전망대)","🔁 daily (FREE)",
 "A 72 m glass-floored sea observatory shaped like a cobalt-blue sea dragon, out over the water at the Cheongsapo fishing village",
 "Daily **09:00–18:00** (Nov)",
 "**FREE**",
 "[english.visitbusan.net](https://english.visitbusan.net) · [Haeundae-gu](https://www.haeundae.go.kr)",
 "The Blueline Park beach train stops at Cheongsapo. Free, and the grilled-clam restaurants around it are excellent."),

# --- Sport & active ---
("⚽","K League — Busan IPark home fixtures (부산아이파크)","👀 WATCH — season ending",
 "Busan's professional football club at Gudeok Stadium. **The K League season finishes in late November**, so a final home fixture may fall in your window",
 "Kick-off typically **14:00/16:00** on weekends in November",
 "Tickets typically **₩10,000–₩20,000**",
 "[busanipark.com](https://www.busanipark.com) · [kleague.com](https://www.kleague.com)",
 "Line 1 Dongdaesin Station. Fixtures for the final rounds are confirmed only weeks ahead — check kleague.com in late October."),

("🏀","KBL Basketball — Busan KCC Egis (부산 KCC 이지스)","✅ CONFIRMED — season running",
 "Korean Basketball League. **The KBL season is in full swing in November**, so there will be home games at Sajik Arena during your trip",
 "Tip-off typically **19:00** weekdays, **14:00/16:00** weekends",
 "Tickets typically **₩8,000–₩30,000**",
 "[kbl.or.kr](https://www.kbl.or.kr) · [KCC Egis](https://www.kccegis.com)",
 "Line 3 Sports Complex (Sajik) Station. Cheap, indoor, loud, and a reliable rainy-evening option — one of the safest sporting bets of your trip."),

("🏐","V-League Volleyball — Busan matches (V리그)","✅ CONFIRMED — season running",
 "Korea's professional volleyball league runs **October to April**, so November matches are guaranteed somewhere in the region",
 "Typically **19:00** weekdays, **14:00** weekends",
 "Tickets typically **₩8,000–₩20,000**",
 "[kovo.co.kr](https://www.kovo.co.kr)",
 "Check the KOVO fixture list for Busan-area home games. Korean volleyball crowds are excellent value entertainment."),

("🏃","Busan Running & Cycling — Suyeong River Trail","🔁 daily (FREE)",
 "The riverside path from Suyeong Bay up the Suyeong River — flat, separated, and the local runners' and cyclists' route, linking Gwangalli to Centum City",
 "Always open",
 "**FREE**",
 "[english.visitbusan.net](https://english.visitbusan.net)",
 "Access at Gwangan or Centum City Station. November is ideal running weather in Busan — typically 10–17 °C."),

("🧗","Busan Surfing — Songjeong Beach (송정해수욕장)","🔁 daily",
 "Korea's most consistent surf beach, with year-round schools. **November means 4/3 mm wetsuits and clean autumn swell** with almost no crowd",
 "Schools roughly **09:00–17:00**",
 "Board + wetsuit rental from **₩30,000**; lessons from ₩60,000",
 "[english.visitbusan.net](https://english.visitbusan.net) · [Haeundae-gu](https://www.haeundae.go.kr)",
 "Donghae Line Songjeong Station. Water is around 17–19 °C in November — cold but very surfable in a full suit."),

# --- Day trips & practical ---
("🚄","Day trip: Gyeongju by KTX from Busan","🔁 daily",
 "Silla's thousand-year capital is **~30 minutes** from Busan by KTX — the easiest world-heritage day trip in Korea",
 "KTX Busan → Singyeongju roughly hourly, **05:30–22:00**",
 "KTX one way **~₩11,000**",
 "[letskorail.com](https://www.letskorail.com) · [gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "Singyeongju Station is out of town — bus 700 or a taxi gets you to the historic area in ~20 min. See our `gyeongju.md` file for the full list."),

("🚢","Day trip: Geoje & Oedo Botania by ferry/bus","🔁 daily",
 "The big island west of Busan — Windy Hill, the POW camp historic park, and the Oedo island garden reached by ferry",
 "Buses from Busan's Sasang terminal roughly **06:00–21:00**; ferries seasonal",
 "Bus ~**₩12,000** one way; Oedo ferry + entry ~**₩30,000**",
 "[geoje.go.kr](https://www.geoje.go.kr) · [english.visitkorea.or.kr](https://english.visitkorea.or.kr)",
 "Check ferry operation in November — services reduce sharply out of season and cancel in wind."),

("🚤","Day trip: Tongyeong cable car & Dongpirang Village","🔁 daily",
 "The 'Naples of Korea' two hours west — Korea's longest cable car up Mireuksan, a mural village above the harbour, and the Dongpirang murals",
 "Cable car daily roughly **09:30–17:00** (Nov)",
 "Cable car round trip **₩17,000**; bus from Busan ~₩14,000",
 "[ttdc.kr](https://www.ttdc.kr) · [tongyeong.go.kr](https://www.tongyeong.go.kr)",
 "Buses from Busan Seobu (Sasang) terminal, ~1 h 40 m. The cable car closes in high wind — check before you commit to the trip."),

("🛳️","Busan–Fukuoka Ferry (부산–후쿠오카 페리)","🔁 daily",
 "The international ferries to Japan from Busan Port — a genuinely viable overnight or 3-hour hydrofoil side trip",
 "Multiple daily sailings; crossing **3 h** (hydrofoil) to **overnight**",
 "From roughly **₩90,000** one way",
 "[Busan Port Authority](https://www.busanpa.com) · [koreaferry.kr](http://www.koreaferry.kr)",
 "Passport required and a Japan visa/visa-waiver applies. Listed for completeness — most travellers won't, but it's an unusual option."),

("🗺️","Busan City Tour Bus (부산시티투어버스)","🔁 daily",
 "The official hop-on-hop-off bus with four routes — Red (Haeundae), Blue (Taejongdae), Green (Gijang) and a night route",
 "Roughly **09:30–17:30**, departures every 30–60 min; night tour separate",
 "1-day pass adult **₩15,000**; night tour ₩10,000",
 "[citytourbusan.com](https://www.citytourbusan.com)",
 "Starts at Busan Station. For a first day in a hilly, spread-out city it's genuinely the efficient option."),

("💳","Busan Visit Pass (부산방문패스)","🔁 daily",
 "The official Busan tourist pass — free entry to 30+ attractions on a 24/48/72-hour clock, including X the Sky, the cable car and Blueline Park",
 "Activates on first use",
 "**₩49,000 / ₩69,000 / ₩89,000** (24 / 48 / 72 h)",
 "[visitbusanpass.com](https://www.visitbusanpass.com)",
 "Worth it if you'll do X the Sky + cable car + Sky Capsule, which alone come to about ₩70,000."),

("🚇","Busan Metro & Donghae Line day passes","🔁 daily",
 "Busan's subway plus the **Donghae Line**, which runs along the coast to Osiria and Gijang and is the cheapest way up the eastern shore",
 "Roughly **05:00–24:00**",
 "1-day pass **₩6,000**; single fares from ₩1,500",
 "[humetro.busan.kr](https://www.humetro.busan.kr) · [letskorail.com](https://www.letskorail.com)",
 "T-money and Cashbee both work. The Donghae Line is a normal Korail line — it takes transit cards but runs less often than the subway."),
]

append("/home/user/KoreaFun/busan.md", E, 104, 2,
       "\n---\n\n## 🔁 Always-on Busan fall favorites", "Busan")
