# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "/home/user/KoreaFun/.build")
from addlib import append

E = [
("🏛️","Dongnae-eupseong Fortress & History Museum (동래읍성)","🔁 daily (FREE)",
 "The old walled town of Dongnae — the fortress that fell in the first battle of the 1592 Japanese invasion, with a restored north gate and a history hall",
 "Fortress trail always open; history museum Tue–Sun **09:00–18:00**",
 "**FREE**",
 "[dongnae.go.kr](https://www.dongnae.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "Line 1/4 Dongnae or Line 4 Suan Station. The Battle of Dongnae excavation site at Suan Station — inside the subway station — is free and remarkable."),

("⚔️","Chungnyeolsa Shrine (충렬사)","🔁 Tue–Sun (FREE)",
 "Shrine to the 1592 defenders of Dongnae, including magistrate Song Sang-hyeon who refused to surrender — set in a formal pine and maple garden",
 "Tue–Sun **09:00–18:00** (closed Mondays)",
 "**FREE**",
 "[busan.go.kr](https://www.busan.go.kr) · [Dongnae-gu](https://www.dongnae.go.kr)",
 "Line 1 Chungnyeolsa Station Exit 1. The maples here turn in mid-November and it's usually deserted."),

("🎭","Busan Cultural Center (부산문화회관)","🔁 by performance",
 "The city's main classical performing arts complex in Nam-gu — home of the Busan Philharmonic and the Busan Metropolitan Traditional Music Orchestra",
 "Performances typically **19:30**; box office daily",
 "**₩10,000–₩70,000**; many city-orchestra concerts under ₩30,000",
 "[bscc.or.kr](https://www.bscc.or.kr)",
 "Line 2 Daeyeon Station + bus. City-run orchestras in Korea are heavily subsidised — world-class playing at cinema-ticket prices."),

("🎼","Busan Concert Hall & Busan Opera House district","👀 WATCH",
 "The Busan Concert Hall in the Cultural Center complex, plus the new Busan Opera House on the North Port waterfront (under construction)",
 "By performance",
 "Varies",
 "[bscc.or.kr](https://www.bscc.or.kr) · [busan.go.kr](https://www.busan.go.kr)",
 "The Opera House is not open yet — but the North Port redevelopment area around it is already a good waterfront walk."),

("📖","Bosu-dong Book Alley (보수동 책방골목)","🔁 Mon–Sat",
 "Korea's most famous second-hand book street — a narrow alley of stacked bookshops that began as refugee stalls in 1950",
 "Most shops **09:00–19:00** (many closed Sunday)",
 "**FREE** to browse",
 "[bosubook.com](http://www.bosubook.com) · [Jung-gu](https://www.bsjunggu.go.kr)",
 "Line 1 Jagalchi Station Exit 3. A handful of shops keep English and Japanese sections; several sell vintage Korean film posters."),

("☕","Jeonpo Cafe Street (전포카페거리)","🔁 daily",
 "The old tool-and-machine-parts district behind Seomyeon, now Busan's densest independent coffee neighbourhood — named by the *New York Times* as a place to visit",
 "Most cafes **11:00–22:00**",
 "Coffee **₩4,500–₩8,000**",
 "[english.visitbusan.net](https://english.visitbusan.net) · [Busanjin-gu](https://www.busanjin.go.kr)",
 "Line 2 Jeonpo Station Exit 7. Machine shops on the ground floor, roasteries above them — the mix is the whole charm."),

("🍺","Busan Craft Beer & Gwangalli Brewery Row","🔁 daily",
 "Busan's craft brewing scene — Galmegi Brewing (the city's original), Praha 993 at F1963 and the Gwangalli taproom strip facing the bridge",
 "Most taprooms **17:00–01:00**; weekends from midday",
 "Pints **₩7,000–₩10,000**",
 "[english.visitbusan.net](https://english.visitbusan.net)",
 "Line 2 Gwangan Station. Korean craft beer is genuinely good now, and Busan was where it started."),

("🐙","Cheongsapo Grilled Clam Village (청사포 조개구이)","🔁 daily",
 "A row of tented restaurants at the Cheongsapo fishing harbour grilling shellfish over charcoal at your table, with the lighthouse pair outside",
 "Roughly **12:00–24:00**",
 "Shellfish sets from **₩40,000** (2 people)",
 "[english.visitbusan.net](https://english.visitbusan.net)",
 "Blueline Park beach train to Cheongsapo, or bus from Haeundae. The red and white lighthouse pair is a classic Busan photo."),

("🦑","Gijang Anchovy & Seaweed Coast (기장 멸치·미역)","🔁 daily",
 "The Gijang coast supplies most of Korea's premium seaweed and anchovies — harbour markets at Daebyeon and Ilgwang sell direct",
 "Harbour markets roughly **07:00–19:00**",
 "**FREE** to browse",
 "[gijang.go.kr](https://www.gijang.go.kr) · [english.visitbusan.net](https://english.visitbusan.net)",
 "Donghae Line Gijang or Ilgwang Station. Dried seaweed and anchovies are light, cheap and legal to take home."),

("🏞️","Hoedong Reservoir & Suh Byung-soo Forest Trail","🔁 daily (FREE)",
 "The reservoir in Busan's north-east with a lakeside forest trail and Sujeongsa temple — a genuine escape from the city with autumn colour",
 "Always open",
 "**FREE**",
 "[parks.busan.go.kr](https://parks.busan.go.kr)",
 "Line 1 Nopo + bus, or taxi from Beomeosa. Pairs with Beomeosa Temple on the same northern day."),

("🌳","Busan Citizens Park (부산시민공원)","🔁 daily (FREE)",
 "A former Japanese racecourse, then a US army base, now a 47-hectare city park with a history museum on the base years",
 "Park **05:00–24:00**; history museum Tue–Sun **10:00–18:00**",
 "**FREE**",
 "[citizenpark.busan.go.kr](https://citizenpark.busan.go.kr)",
 "Line 1 Bujeon Station or Line 2 Bujeon. Ten minutes from Seomyeon and almost nobody visits — excellent for a foliage walk."),

("🎋","Busan Children's Grand Park & Seongjigok Reservoir","🔁 daily (FREE)",
 "Large forest park in a valley behind Busanjin with a reservoir walk, a students' science hall and easy hiking to Baekyangsan",
 "Park always open; facilities **09:00–18:00**",
 "Park **FREE**",
 "[parks.busan.go.kr](https://parks.busan.go.kr)",
 "Line 2 Gaya Station + bus. Deep forest 15 minutes from Seomyeon."),

("🏔️","Jangsan Mountain & Waterfall Trail (장산)","🔁 daily (FREE)",
 "Haeundae's own 634 m mountain — a waterfall trail from the residential streets to a summit view over the whole eastern coast",
 "Always open; ~3 h round trip",
 "**FREE**",
 "[haeundae.go.kr](https://www.haeundae.go.kr) · [parks.busan.go.kr](https://parks.busan.go.kr)",
 "Line 2 Jangsan Station Exit 12. The upper section is a military area with restricted hours — signposted in English at the gate."),

("🦌","Seunghaksan & Yunsan Ridge (승학산 억새)","🔁 daily (FREE)",
 "The silver-grass ridge above Saha-gu — a field of *eoksae* grass with views over the Nakdong estuary, at its best **October to November**",
 "Always open; ~2 h round trip",
 "**FREE**",
 "[parks.busan.go.kr](https://parks.busan.go.kr) · [Saha-gu](https://www.saha.go.kr)",
 "Line 1 Hadan Station + bus. **November is exactly the right month** — the grass is silver-white and the estuary sunset behind it is superb."),

("🌉","Yeongdo Bongnaesan Observatory & Sky Park (봉래산)","🔁 daily (FREE)",
 "The peak in the middle of Yeongdo island with a 360° deck over the port, the bridges and Taejongdae",
 "Always open; deck lit at night",
 "**FREE**",
 "[yeongdo.go.kr](https://www.yeongdo.go.kr)",
 "Bus from Nampo across Yeongdo Bridge. The best free port panorama in Busan."),

("🚠","Songdo Sky Park & Yonggung Cloud Trails","🔁 daily (FREE)",
 "The upper cable-car station on Amnam mountain has a free sky park, a dinosaur trail and a viewing platform over Songdo Bay",
 "Roughly **09:00–20:00**",
 "Sky park **FREE** (cable car ticket separate)",
 "[busanaircruise.co.kr](http://busanaircruise.co.kr)",
 "You can also walk up from Amnam Park and use the sky park without a cable-car ticket."),

("🐧","Busan Aquarium Behind-the-Scenes & Feeding Times","🔁 daily",
 "SEA LIFE Busan runs scheduled feeding sessions and diver shows in the ocean tunnel through the day — included with entry",
 "Feeding/diver sessions several times daily between **11:00–17:00**",
 "Included with the **₩31,000** entry",
 "[visitsealife.com/busan](https://www.visitsealife.com/busan)",
 "Check the day's schedule board at the entrance — the shows are the best part and easy to miss."),

("🏛️","Busan Museum of Contemporary Art — MOCA Busan (부산현대미술관)","🔁 Tue–Sun (FREE)",
 "The city's contemporary art museum on Eulsukdo island at the Nakdong estuary, its facade grown over with living plants",
 "Tue–Sun **10:00–18:00** (closed Mondays)",
 "**FREE**",
 "[moca.busan.go.kr](https://moca.busan.go.kr)",
 "Line 1 Hadan Station + bus 58. Combine with the Nakdong Estuary Eco Center — they're on the same island."),

("🖌️","Busan Art Museum Lee Ufan Space (이우환공간)","🔁 Tue–Sun (FREE)",
 "A separate building beside the Busan Museum of Art holding only Lee Ufan's paintings, sculptures and stone-and-steel installations",
 "Tue–Sun **10:00–18:00** (closed Mondays)",
 "**FREE**",
 "[art.busan.go.kr](https://art.busan.go.kr)",
 "Line 2 Busan Museum of Art Station Exit 5. Twenty quiet minutes; one of the calmest rooms in Korea."),

("🎨","Openspace Bae & Busan Alternative Art Spaces","🔁 Tue–Sun (FREE)",
 "Busan's independent art scene — Openspace Bae on the Gijang hillside, Space Heem and the artist-run spaces around Choryang and Nampo",
 "Generally Tue–Sun **11:00–18:00**",
 "Mostly **FREE**",
 "[openspacebae.com](http://www.openspacebae.com)",
 "Small, volunteer-run and sometimes closed between shows — check the site before travelling out."),

("⚓","Korea Maritime Museum (국립해양박물관)","🔁 Tue–Sun (FREE)",
 "Korea's national maritime museum on an artificial island off Yeongdo — a full-size sailing ship indoors, an aquarium, and the history of Korean seafaring",
 "Tue–Sun **09:00–18:00** (closed Mondays)",
 "**FREE**",
 "[knmm.or.kr](https://www.knmm.or.kr)",
 "Bus 66/186 from Nampo to Yeongdo. Free, huge, and a very good rainy-day option."),

("🚢","Busan National Maritime Fisheries & Cruise Terminal Walk","🔁 daily (FREE)",
 "The North Port redevelopment waterfront — a new public park, the cruise terminal and a promenade with the port cranes as backdrop",
 "Always open",
 "**FREE**",
 "[busanpa.com](https://www.busanpa.com) · [busan.go.kr](https://www.busan.go.kr)",
 "Line 1 Choryang or Busan Station. Newly opened public space that most guidebooks haven't caught up with."),

("🍚","Busan Milmyeon — cold wheat noodles (밀면)","🔁 daily",
 "Busan's other refugee dish: wheat noodles in cold broth, invented when North Korean refugees couldn't get buckwheat. Eaten year-round, including in November",
 "Specialist shops roughly **10:30–21:00**",
 "**₩8,000–₩10,000**",
 "[english.visitbusan.net](https://english.visitbusan.net)",
 "Order it *mul* (soup) or *bibim* (spicy dry). Standard practice is to add vinegar and mustard from the table."),

("🐟","Songjeong & Gijang Seafood Ramen Coast Cafes","🔁 daily",
 "The coastal cafe strip north of Haeundae — glass-fronted cafes on the rocks at Songjeong and Daebyeon, an established Busan weekend ritual",
 "Most **10:00–22:00**",
 "Coffee **₩6,000–₩9,000**",
 "[english.visitbusan.net](https://english.visitbusan.net)",
 "Donghae Line Songjeong Station. In November you get storm-watching weather and empty window seats."),

("🎪","Busan International Film Festival venues — off-season screenings","🔁 daily",
 "Even outside BIFF, the Cinema Center and the Nampo BIFF-district cinemas run arthouse and Korean-classic programmes",
 "Screenings roughly **11:00–22:00**",
 "**₩7,000–₩10,000**",
 "[dureraum.org](https://www.dureraum.org) · [biff.kr](https://www.biff.kr)",
 "Look for the Korean Film Archive's Busan programme — subtitled screenings appear regularly."),

("🎳","Seomyeon Underground Shopping Town & Nightlife (서면지하상가)","🔁 daily",
 "Busan's busiest district — a huge underground arcade, the Seomyeon Medical Street, and the city's densest bar and karaoke area above it",
 "Arcade **10:00–22:00**; bars until late",
 "**FREE** to browse",
 "[english.visitbusan.net](https://english.visitbusan.net) · [Busanjin-gu](https://www.busanjin.go.kr)",
 "Line 1/2 Seomyeon Station. Also where the **Seomyeon Light Festival** runs from November — one trip, two things."),

("💊","Seomyeon Medical Street (서면메디컬스트리트)","🔁 Mon–Sat",
 "A concentrated strip of dermatology, dentistry and cosmetic clinics with foreign-patient services and tax-refund support",
 "Most clinics Mon–Fri **10:00–19:00**, Sat mornings",
 "Varies; consultations often **₩10,000–₩30,000**",
 "[english.visitbusan.net](https://english.visitbusan.net) · [Korea Health Industry Development Institute](https://www.medicalkorea.or.kr)",
 "Medical tourism is officially promoted here. Use the Medical Korea portal to find clinics registered for foreign patients."),

("🛒","Bujeon Market (부전시장)","🔁 daily",
 "Busan's biggest traditional market by area — a sprawling produce, herb and seafood market next to Seomyeon that locals actually shop in",
 "Roughly **05:00–20:00**",
 "**FREE** to browse",
 "[english.visitbusan.net](https://english.visitbusan.net)",
 "Line 1 Bujeon Station Exit 1. Rawer and less touristed than Jagalchi or Gukje."),

("🍢","Nampo-dong Gwangbok-ro Fashion Street","🔁 daily",
 "The pedestrianised shopping spine of old Busan — street food carts, cosmetics, a musical fountain and the December tree festival route",
 "Shops roughly **11:00–22:00**",
 "**FREE** to walk",
 "[english.visitbusan.net](https://english.visitbusan.net) · [Jung-gu](https://www.bsjunggu.go.kr)",
 "Line 1 Nampo Station Exit 7. Watch for the Christmas tree installation going up in **late November**."),

("🚡","Busan Air Cruise night crossing (송도해상케이블카 야간)","🔁 daily",
 "The Songdo cable car after dark — the towers and cabins are lit, and the bay reflects them the whole way across",
 "Last cabins roughly **20:30–21:00**",
 "Round trip **₩17,000** (Air) / **₩22,000** (Crystal glass floor)",
 "[busanaircruise.co.kr](http://busanaircruise.co.kr)",
 "Going after dark costs the same as daytime and is considerably better. Suspends in high wind."),

("🌙","Busan Night Tour Bus (부산 야경투어버스)","🔁 nightly",
 "The night route of the official city tour bus — Gwangan Bridge, Haeundae, the port and the bridge lighting from an open-top deck",
 "Departures typically **19:30** and **20:00**",
 "Adult **₩10,000**",
 "[citytourbusan.com](https://www.citytourbusan.com)",
 "Departs Busan Station. Cheap, warm-ish, and it covers the bridges you'd otherwise need three taxis to see."),

("🛶","Suyeong Bay Yachting & Marina (수영만요트경기장)","🔁 daily",
 "The 1988 Olympic yachting venue at Haeundae — sunset yacht cruises out past Gwangan Bridge run year-round",
 "Cruises typically **11:00–21:00**, ~70–90 min",
 "From **₩30,000–₩60,000** per person",
 "[english.visitbusan.net](https://english.visitbusan.net)",
 "Line 2 Dongbaek Station. A sunset sailing under Gwangan Bridge in November is cold but spectacular — bring a jacket."),

("🎣","Songdo & Yeongdo Sea Fishing Piers","🔁 daily",
 "Public fishing piers and rocky platforms around Songdo, Yeongdo and Cheongsapo — autumn is prime season for rockfish and mackerel",
 "Always open; boat charters from **05:00**",
 "Pier fishing **FREE**; boat charters from **₩50,000**",
 "[english.visitbusan.net](https://english.visitbusan.net)",
 "Tackle shops near the piers rent rods by the hour. Check tide tables — the pier platforms flood on high spring tides."),

("🏝️","Yeongdo Jeoryeong Coastal Walk (절영해안산책로)","🔁 daily (FREE)",
 "A sea-level boardwalk along Yeongdo's western cliffs from Huinnyeoul to Jungni — waves under the deck, tunnels through the rock",
 "Always open; ~1 h one way",
 "**FREE**",
 "[yeongdo.go.kr](https://www.yeongdo.go.kr) · [english.visitbusan.net](https://english.visitbusan.net)",
 "Starts below Huinnyeoul Culture Village. Closed in storms — check the weather before descending."),

("🌊","Haeundae Beach Sunrise (해운대 일출)","🔁 daily (FREE)",
 "Sunrise over the East Sea straight down the length of Haeundae Beach — **November sunrise in Busan is around 07:00–07:15**, a very civilised hour",
 "Sunrise ~**07:00–07:15** in November",
 "**FREE**",
 "[english.visitbusan.net](https://english.visitbusan.net) · [Korea Meteorological Administration](https://www.weather.go.kr)",
 "Line 2 Haeundae Station Exit 3/5. Unlike summer, you don't need a 04:30 alarm — just walk down before breakfast."),

("🕌","Busan Al-Fatah Mosque & Halal Restaurant Street","🔁 daily (FREE)",
 "Korea's second-oldest mosque, near Pusan National University, with a small cluster of halal restaurants around it",
 "Prayer times daily; visitors welcome outside prayers",
 "**FREE**",
 "[english.visitbusan.net](https://english.visitbusan.net)",
 "Line 1 Busan National University Station. Useful practical information for halal-observant travellers in Busan."),

("🎓","Pusan National University Front Gate District (부산대 앞)","🔁 daily",
 "Busan's main student neighbourhood — cheap food, live-music bars, indie shops and a weekend street-performance zone",
 "Shops and bars **11:00–02:00**",
 "**FREE** to walk; meals from ₩6,000",
 "[english.visitbusan.net](https://english.visitbusan.net)",
 "Line 1 Busan National University Station Exit 3. The cheapest good eating in Busan, and the busking is genuinely decent."),

("🧧","Busan Chinatown & Texas Street (차이나타운)","🔁 daily",
 "The old foreign quarter opposite Busan Station — Korea's original Chinatown alongside the Russian shopfronts of 'Texas Street'",
 "Restaurants roughly **11:00–22:00**",
 "**FREE** to walk",
 "[english.visitbusan.net](https://english.visitbusan.net) · [Dong-gu](https://www.bsdonggu.go.kr)",
 "Line 1 Busan Station Exit 1/3. Small but genuinely multi-layered — Chinese, Russian and Central Asian signage in three blocks."),

("🚊","Donghae Line coastal rail to Ulsan","🔁 daily",
 "The Donghae Line runs from Busan up the coast all the way to Ulsan — a cheap, scenic local train that hugs the shore for much of the route",
 "Roughly hourly, **05:30–23:00**; Busan → Ulsan ~1 h 20 m",
 "**₩3,000–₩5,000** one way; transit cards accepted",
 "[letskorail.com](https://www.letskorail.com) · [humetro.busan.kr](https://www.humetro.busan.kr)",
 "Sit on the right-hand side heading north for sea views. See our `ulsan.md` file for what to do at the other end."),

("🚌","Day trip: Yangsan Tongdosa Temple — UNESCO","🔁 daily",
 "One of Korea's Three Jewel Temples and a UNESCO World Heritage 'Sansa' mountain monastery, 40 minutes north of Busan",
 "Daily roughly **08:30–17:30**",
 "**FREE** entry (parking charged)",
 "[tongdosa.or.kr](http://www.tongdosa.or.kr) · [UNESCO Sansa](https://whc.unesco.org/en/list/1562)",
 "Busan Line 2 to Yangsan + bus, or intercity bus from Nopo. **The 1 km pine approach avenue in November foliage is the reason to go.**"),

("🏞️","Day trip: Miryang Yeongnamnu & Ice Valley","🔁 daily",
 "The riverside pavilion town an hour north — Yeongnamnu is one of Korea's three great pavilions, and Eoreumgol 'ice valley' is a natural curiosity",
 "Pavilion daily **09:00–18:00**",
 "Pavilion **FREE**",
 "[miryang.go.kr](https://www.miryang.go.kr)",
 "KTX or Mugunghwa from Busan Station, ~40–60 min. A quiet, very Korean day out that almost no foreign visitors make."),
]

append("/home/user/KoreaFun/busan.md", E, 163, 2,
       "\n---\n\n## 🔁 Always-on Busan fall favorites", "Busan",
       intro="*Second expansion batch — neighbourhoods, coast walks, museums, food districts and day trips, all with official city, district or venue sources.*")
