# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "/home/user/KoreaFun/.build")
from addlib import append

E = [
("🏯","Ungcheon Japanese Castle & Jinhae Fortress Sites","🔁 daily (FREE)",
 "The remains of a 1593 Japanese *wajo* fortress above Jinhae bay, built during the Imjin War and still showing its sloping stone walls",
 "Always open",
 "**FREE**",
 "[Korea Heritage Service](https://www.khs.go.kr) · [changwon.go.kr](https://www.changwon.go.kr)",
 "**One of the best-preserved Japanese castles in Korea.** A 20-minute climb from the road."),

("🪖","Anmin Pass & Jinhae Panorama Road (안민고개)","🔁 daily (FREE)",
 "The mountain pass road between Jinhae and Changwon, with a ridge walk and a full panorama over the naval port",
 "Always open",
 "**FREE**",
 "[changwon.go.kr](https://www.changwon.go.kr)",
 "**The best free view of the naval base and the bay.** Taxi up from Jinhae, about ₩10,000."),

("🌾","Junam Reservoir Migratory Bird Sanctuary (주남저수지)","✅ CONFIRMED — Nov peak",
 "A major wintering wetland where **tens of thousands of migratory birds arrive from November**, including hooded cranes, swans and geese",
 "Observatory **09:00–18:00** (Nov: to 17:00)",
 "**FREE**",
 "[junam.changwon.go.kr](https://junam.changwon.go.kr) · [changwon.go.kr](https://www.changwon.go.kr)",
 "**November is exactly when the birds arrive** — this is Changwon's best seasonal attraction in your window. Bring binoculars."),

("🦢","Junam Eco Study Center & Lotus Fields","🔁 Tue–Sun (FREE)",
 "The interpretation centre at Junam Reservoir, with telescopes, exhibits on the migration routes and a lotus-field boardwalk",
 "Tue–Sun **09:00–18:00** (closed Mon)",
 "**FREE**",
 "[junam.changwon.go.kr](https://junam.changwon.go.kr)",
 "**Go at dawn or dusk** — the flights in and out are the spectacle."),

("🏛️","Dahoe-ri Bronze Age Site & Changwon Archaeology","🔁 daily (FREE)",
 "The Dahori site near Changwon produced one of Korea's richest Iron Age tomb assemblages, including lacquerware and Chinese mirrors",
 "Site always open; finds in museums",
 "**FREE**",
 "[Korea Heritage Service](https://www.khs.go.kr) · [museum.go.kr](https://www.museum.go.kr)",
 "**The finds are held at the National Museum of Korea** — the site itself is for completists."),

("🛕","Seongjusa Temple (성주사)","🔁 daily (FREE)",
 "A 9th-century temple on the slopes of Bulmosan above Changwon, known locally as the 'pig temple' after a founding legend",
 "Daily **06:00–19:00**",
 "**FREE**",
 "[changwon.go.kr](https://www.changwon.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "**Good autumn colour and almost no visitors.** Bus from Changwon then a short walk."),

("⛰️","Bulmosan Provincial Park (불모산)","🔁 daily (FREE)",
 "The 802 m mountain between Changwon and Jinhae, with a summit road, ridge trails and views over both cities and the sea",
 "Always open",
 "**FREE**",
 "[changwon.go.kr](https://www.changwon.go.kr) · [Korea Forest Service](https://www.forest.go.kr)",
 "**The highest point in Changwon** — you can see Busan on a clear day."),

("🌲","Daearim & Changwon Arboretums","🔁 Tue–Sun",
 "Changwon's public arboretums and botanical gardens, with themed planting and greenhouse collections",
 "Tue–Sun **09:00–18:00** (Nov: to 17:00)",
 "**FREE**–₩2,000",
 "[changwon.go.kr](https://www.changwon.go.kr) · [Korea Forest Service](https://www.forest.go.kr)",
 "A calm hour if the weather turns."),

("🏛️","Changwon Science Center & Planetarium","🔁 Tue–Sun",
 "A municipal science centre with hands-on exhibits and a planetarium, reflecting Changwon's engineering identity",
 "Tue–Sun **09:30–17:30** (closed Mon)",
 "Adult **₩2,000**; planetarium extra",
 "[changwon.go.kr](https://www.changwon.go.kr)",
 "Cheap, indoors and good with children."),

("🎨","Changwon Public Art & Sculpture Trail","🔁 daily (FREE)",
 "Changwon has installed public sculpture along its boulevards and lake park since the sculpture biennale began",
 "Always open",
 "**FREE**",
 "[changwon.go.kr](https://www.changwon.go.kr)",
 "Concentrated around Yongji Lake and Seongsan Art Hall."),

("📚","Changwon Public Libraries & Study Cafes","🔁 Tue–Sun (FREE)",
 "Modern municipal libraries with reading rooms, free wifi and warm space, open to visitors",
 "Tue–Sun **09:00–21:00**",
 "**FREE**",
 "[changwon.go.kr](https://www.changwon.go.kr)",
 "A practical free refuge between sights on a cold day."),

("🎪","Changwon Festival Calendar & November Events","👀 WATCH",
 "Changwon's official calendar covers Gunhangje, the Masan Chrysanthemum Festival and the Changwon Festival — **the chrysanthemum show typically falls in late October–early November**",
 "By event",
 "Many **FREE**",
 "[changwon.go.kr](https://www.changwon.go.kr)",
 "**The Masan Gagopa Chrysanthemum Festival is the one to check** — it has historically run into early November at the Masan waterfront."),

("🌼","Masan Gagopa Chrysanthemum Festival","👀 WATCH — late Oct–early Nov",
 "One of Korea's largest chrysanthemum shows, staged on the Masan waterfront with large-scale floral sculptures",
 "Typically **late October–early November**",
 "**FREE** or low entry",
 "[changwon.go.kr](https://www.changwon.go.kr)",
 "**This may overlap the very start of your window** — confirm 2026 dates on the city site in October."),

("🎄","Changwon & Jinhae Winter Illumination","👀 WATCH (from late Nov)",
 "Yongji Lake, the Masan waterfront and Jinhae's old town are lit for winter, typically switching on in late November",
 "Evenings once lit",
 "**FREE**",
 "[changwon.go.kr](https://www.changwon.go.kr)",
 "**Switch-on may land at the end of your window.**"),

("🚢","Jinhae Port & Ferry Connections","🔁 daily",
 "Jinhae's civil port and the nearby Masan passenger terminal serve small island routes along the south coast",
 "Sailings roughly **07:00–17:00**",
 "**₩5,000–₩20,000**",
 "[changwon.go.kr](https://www.changwon.go.kr) · [Korea Maritime Safety](https://www.komsa.or.kr)",
 "Limited routes and weather-dependent in November."),

("🏝️","Geoje Island — day trip from Changwon","🔁 daily",
 "**Korea's second-largest island**, an hour from Changwon, with the Windy Hill headland, Oedo botanical island and the POW camp museum",
 "Attractions **09:00–18:00**",
 "**₩5,000–₩20,000** per site",
 "[geoje.go.kr](https://www.geoje.go.kr)",
 "**The Geoje POW Camp museum** covers the 170,000 Korean War prisoners held here — genuinely worth the trip."),

("🏛️","Geoje POW Camp Historic Park","🔁 daily",
 "The site of the UN prisoner-of-war camp that held up to 170,000 North Korean and Chinese prisoners from 1951, including the 1952 riots",
 "Daily **09:00–18:00** (Nov: to 17:00)",
 "Adult **₩7,000**",
 "[geoje.go.kr](https://www.geoje.go.kr)",
 "**A serious and well-presented Korean War site.** About 90 minutes from Changwon."),

("🌊","Tongyeong — day trip from Changwon","🔁 daily",
 "The 'Naples of Korea', an hour away, with the Mireuksan cable car, Dongpirang mural village and Yi Sun-sin's Sambodo naval headquarters",
 "Attractions **09:00–18:00**",
 "Cable car **₩17,000**",
 "[tongyeong.go.kr](https://www.tongyeong.go.kr)",
 "**Tongyeong's honey bread and chungmu gimbap** are national-famous. Easy bus from Changwon."),

("🏛️","Gimhae — Gaya Kingdom day trip","🔁 daily (FREE)",
 "Gimhae was the capital of Geumgwan Gaya; its royal tombs form part of the **Gaya Tumuli inscribed by UNESCO in 2023**",
 "Museum Tue–Sun **09:00–18:00**",
 "**FREE**",
 "[UNESCO ref 1666](https://whc.unesco.org/en/list/1666) · [gimhae.go.kr](https://www.gimhae.go.kr)",
 "**A World Heritage site 40 minutes from Changwon** — and on the way to Gimhae Airport."),

("🍚","Jinhae & Changwon Breakfast Options","🔁 daily",
 "Early-opening options: market *gukbap* houses in Masan, bakery chains near the stations and hotel breakfasts",
 "From **06:00**",
 "**₩7,000–₩12,000**",
 "[changwon.go.kr](https://www.changwon.go.kr)",
 "**Masan Fish Market's soup houses open at dawn** — the best early meal in the city."),

("🚑","Changwon Emergency & Medical Services","🔁 24 h",
 "Samsung Changwon Hospital and Changwon Fatima Hospital run 24-hour emergency departments",
 "Emergency **24 h**",
 "Consultation from **₩20,000** for visitors",
 "[1339 Medical Hotline](https://www.kdca.go.kr) · [changwon.go.kr](https://www.changwon.go.kr)",
 "**119 for ambulance, 1339 for English medical advice.**"),

("💰","Changwon on a budget — free things to do","🔁 daily (FREE)",
 "Junam Reservoir, Jinhae's old town, the post office, Anmin Pass, Yongji Lake, Muhaksan and the March 15th cemetery are all free",
 "Various",
 "**FREE**",
 "[changwon.go.kr](https://www.changwon.go.kr)",
 "**Changwon is one of the cheapest cities in this guide** — very little here charges admission."),

("🌏","Changwon for foreign visitors — language notes","🔁 daily",
 "Changwon and Jinhae see few foreign tourists; English signage is limited outside the main sites",
 "N/A",
 "N/A",
 "[1330 Hotline](https://english.visitkorea.or.kr) · [changwon.go.kr](https://www.changwon.go.kr)",
 "**Have your destination written in Korean for taxis.** 1330 gives free 24-hour interpretation."),

("📸","Changwon & Jinhae Photo Spots","🔁 daily (FREE)",
 "The naval port from Anmin Pass, Jinhae Tower over the bay, Gyeonghwa Station's empty track, Junam's dawn bird flights and Yongji Lake's fountain",
 "Best at dawn and dusk",
 "**FREE**",
 "[changwon.go.kr](https://www.changwon.go.kr)",
 "**Junam Reservoir at sunrise in November** is the picture worth setting an alarm for."),

("🗺️","Changwon as a base for the south coast","🔁 planning",
 "Busan, Gimhae, Tongyeong, Geoje and Jinju are all within 90 minutes, making Changwon a cheap alternative base",
 "N/A",
 "Buses **₩5,000–₩12,000**",
 "[changwon.go.kr](https://www.changwon.go.kr) · [kobus.co.kr](https://www.kobus.co.kr)",
 "**Hotels here cost roughly half what Busan charges** for the same standard."),
]

append("/home/user/KoreaFun/changwon-jinhae.md", E, 186, 3,
       "\n---\n\n## 🧭 Beginner-friendly essentials", "Changwon & Jinhae")
