# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "/home/user/KoreaFun/.build")
from addlib import append

E = [
("🌉","Jinhae Naval Base & Korean Navy Headquarters","👀 WATCH — open days only",
 "Jinhae is **the home port of the Republic of Korea Navy**; the base opens to the public during the Gunhangje festival and on scheduled open days",
 "Base closed except on announced open days",
 "**FREE** when open",
 "[navy.mil.kr](https://www.navy.mil.kr) · [changwon.go.kr](https://www.changwon.go.kr)",
 "**Normally closed to visitors.** Check the Navy site for any autumn open-day announcement."),

("⚓","Jinhae Naval Academy & Turtle Ship Replica","👀 WATCH — booking required",
 "The Korean Naval Academy grounds hold a museum and a full-scale turtle ship replica, open to pre-booked visitors",
 "By reservation; typically weekdays",
 "**FREE**",
 "[navy.mil.kr](https://www.navy.mil.kr) · [changwon.go.kr](https://www.changwon.go.kr)",
 "**Advance booking and ID are required** — this is an active military installation."),

("🗼","Jinhae Tower & Jehwang-san Park (진해탑)","🔁 daily",
 "A nine-storey tower shaped like a turtle ship on Jehwangsan, reached by 365 steps or a monorail, with views over the naval port",
 "Daily **09:00–18:00** (Nov: to 17:00)",
 "Tower **₩2,000**; monorail ₩3,000 return",
 "[changwon.go.kr](https://www.changwon.go.kr)",
 "**Take the monorail up and the 365 steps down.** The view over the naval base is the best in Jinhae."),

("🌸","Yeojwacheon Stream & Romance Bridge (여좌천)","🔁 daily (FREE)",
 "The cherry-lined stream made famous by the drama *Romance*; bare in November but lit at night and quiet enough to actually walk",
 "Always open; lit after dark",
 "**FREE**",
 "[changwon.go.kr](https://www.changwon.go.kr)",
 "**Nothing like the April crowds** — in November you get the bridge to yourself."),

("🚉","Gyeonghwa Station Cherry Tunnel (경화역)","🔁 daily (FREE)",
 "A disused railway station whose 800 m track runs through a cherry tunnel — Korea's single most photographed cherry-blossom spot",
 "Always open",
 "**FREE**",
 "[changwon.go.kr](https://www.changwon.go.kr) · [Korea Rail Network](https://www.kr.or.kr)",
 "Out of season, but the old rolling stock and the empty track are still worth thirty minutes."),

("🌸","Jinhae Gunhangje Festival — why the city is famous","⏳ TBA — spring event",
 "**Korea's largest cherry blossom festival**, held each late March–early April around the naval port with roughly 360,000 cherry trees",
 "Typically **late March–early April**",
 "**FREE**",
 "[changwon.go.kr](https://www.changwon.go.kr)",
 "**Not in your window** — listed so you know what Jinhae's infrastructure was built for."),

("🏛️","Jinhae Modern Cultural Space & Japanese Colonial Streets","🔁 Tue–Sun (FREE)",
 "Jinhae was laid out by the Japanese Navy from 1912 on a radial European plan; the old post office, bank and wooden houses survive",
 "Tue–Sun **09:00–18:00**",
 "**FREE**",
 "[changwon.go.kr](https://www.changwon.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "**Jinhae's street grid radiates from Jungwon Rotary** — the only city in Korea planned this way."),

("🏤","Jinhae Post Office — Registered Cultural Heritage","🔁 daily (FREE)",
 "A 1912 Russian-influenced brick post office, one of the oldest surviving modern buildings in Korea, designated Registered Cultural Heritage No. 291",
 "Exterior always; interior **09:00–18:00**",
 "**FREE**",
 "[Korea Heritage Service](https://www.khs.go.kr) · [changwon.go.kr](https://www.changwon.go.kr)",
 "On Jungwon Rotary, so you'll pass it anyway."),

("🎬","Jungwon Rotary & Jinhae Old Town Walk","🔁 daily (FREE)",
 "The eight-spoked colonial-era roundabout at the heart of Jinhae, surrounded by 1910s–30s buildings and old shopfronts",
 "Always open",
 "**FREE**",
 "[changwon.go.kr](https://www.changwon.go.kr)",
 "**Walk one spoke out and back** — each street has a different period character."),

("🏛️","Changwon City Museum & Masan History","🔁 Tue–Sun (FREE)",
 "Changwon's municipal museums cover the Masan uprising of 1960, the Bronze Age settlement finds and the city's industrial planning",
 "Tue–Sun **09:00–18:00** (closed Mon)",
 "**FREE**",
 "[changwon.go.kr](https://www.changwon.go.kr)",
 "**Masan's March 1960 protest triggered the April Revolution** that ended Syngman Rhee's presidency."),

("🕊️","March 15th Memorial Cemetery & Democracy Sites","🔁 daily (FREE)",
 "The national cemetery in Masan for those killed in the **15 March 1960 uprising**, the spark of the April Revolution",
 "Daily **09:00–18:00**",
 "**FREE**",
 "[mpva.go.kr](https://www.mpva.go.kr) · [changwon.go.kr](https://www.changwon.go.kr)",
 "**Kim Ju-yul's body washing ashore in Masan harbour** is the moment usually credited with starting the revolution."),

("🌊","Masan Fish Market & Agu-jjim Street (마산어시장)","🔁 daily",
 "One of the south coast's largest fish markets, and the birthplace of ***agu-jjim*** — braised monkfish with bean sprouts in chilli sauce",
 "Market **05:00–20:00**; restaurants to 22:00",
 "Agu-jjim **₩30,000–₩50,000** for two",
 "[changwon.go.kr](https://www.changwon.go.kr)",
 "**Agu-jjim was invented on this street.** Order it for at least two people."),

("🍲","Masan Agu-jjim & Fresh Monkfish Season","🔁 daily",
 "Masan's signature dish, in two forms: dried monkfish the traditional way, or fresh — **and winter is the fresh monkfish season**",
 "Roughly **11:00–22:00**",
 "**₩35,000–₩60,000**",
 "[changwon.go.kr](https://www.changwon.go.kr) · [visitkorea.or.kr](https://english.visitkorea.or.kr)",
 "**Ask for *saeng*-agu (fresh) rather than *geon*-agu (dried)** in November — it's the better version in season."),

("🐟","Masan Odong-dong Agu-jjim Alley","🔁 daily",
 "The dedicated restaurant alley in Odong-dong where the dish originated, with a dozen long-established specialists",
 "Roughly **11:00–22:00**",
 "**₩35,000** and up",
 "[changwon.go.kr](https://www.changwon.go.kr)",
 "**The oldest shops advertise their founding year** on the sign — a reliable guide."),

("🌉","Masan Gagopa Waterfront & Marine Park","🔁 daily (FREE)",
 "Masan's redeveloped harbourfront, with a promenade, a musical fountain and a view across the reclaimed bay",
 "Always open",
 "**FREE**",
 "[changwon.go.kr](https://www.changwon.go.kr)",
 "Named after the poem *Gagopa*, written about Masan and known to every Korean."),

("🎡","Masan Robot Land (마산로봇랜드)","🔁 Tue–Sun",
 "A robot-themed park and museum on the Masan coast, combining a theme park with a robotics research complex",
 "Tue–Sun **10:00–18:00** (Nov: to 17:00)",
 "Adult **₩20,000** combined",
 "[robot-land.co.kr](https://www.robot-land.co.kr) · [changwon.go.kr](https://www.changwon.go.kr)",
 "**A public robotics project as much as a theme park.** Good on a wet day with children."),

("🏭","Changwon National Industrial Complex & Machinery Heritage","🔁 daily (FREE)",
 "Korea's planned machinery city, built from 1974; the wide grid, the industrial belt and the boulevards are a deliberate 1970s design",
 "Always open",
 "**FREE**",
 "[changwon.go.kr](https://www.changwon.go.kr)",
 "**Changwon was Korea's first planned city** — the 12-lane Changwon-daero is the axis it was built around."),

("🌳","Yongji Lake Park & Changwon Night Fountain (용지호수)","🔁 daily (FREE)",
 "Changwon's central lake park, with a lakeside loop, a lit musical fountain and the city hall district around it",
 "Always open; fountain evenings",
 "**FREE**",
 "[changwon.go.kr](https://www.changwon.go.kr)",
 "**The 2 km loop is Changwon's default evening walk.** Fountain shows run after dark."),

("🚡","Jinhae Solpo & Changwon Marine Solo Way Cable Car","🔁 daily (weather-dependent)",
 "The coastal cable car linking Jinhae's waterfront to the hillside, with harbour and island views",
 "Daily **10:00–18:00**",
 "Return from **₩15,000**",
 "[changwon.go.kr](https://www.changwon.go.kr)",
 "**Closes in strong wind** — common on this coast in November."),

("🌊","Jinhae Solo-gil Coastal Road & Uldolmok","🔁 daily (FREE)",
 "The coastal road east from Jinhae past small ports and headlands toward Busan's western edge",
 "Always open",
 "**FREE**",
 "[changwon.go.kr](https://www.changwon.go.kr)",
 "Better by car or taxi than by bus — services are sparse."),

("⛰️","Muhaksan Mountain & Masan Views (무학산)","🔁 daily (FREE)",
 "Masan's 761 m guardian mountain, with ridge trails, autumn silver grass and a view over the whole bay",
 "Always open",
 "**FREE**",
 "[changwon.go.kr](https://www.changwon.go.kr) · [Korea Forest Service](https://www.forest.go.kr)",
 "Three to four hours return. **The silver-grass ridge peaks in October–November.**"),

("⛰️","Jangboksan & Cheonjasan Hiking","🔁 daily (FREE)",
 "Jinhae's cherry-covered hill with a sculpture park, and Cheonjasan's ridge route above the naval port",
 "Always open",
 "**FREE**",
 "[changwon.go.kr](https://www.changwon.go.kr) · [Korea Forest Service](https://www.forest.go.kr)",
 "Jangboksan has an easy paved path suitable for a short walk."),

("🌲","Jinhae Naeqsan & Changwon Forest Trails","🔁 daily (FREE)",
 "The forested ridges ringing Changwon, threaded by the **Changwon Dulle-gil** circuit path with mapped, graded sections",
 "Always open",
 "**FREE**",
 "[changwon.go.kr](https://www.changwon.go.kr) · [durunubi.kr](https://www.durunubi.kr)",
 "Maps at the city site. Sections range from 2 to 12 km."),

("🏛️","Changwon Sculpture Biennale & Moonshin Art Museum","🔁 Tue–Sun",
 "The museum of sculptor Moonshin, built on the Masan hillside to his own design, plus the city's sculpture park",
 "Tue–Sun **09:00–18:00** (closed Mon)",
 "Adult **₩1,000**",
 "[changwon.go.kr](https://www.changwon.go.kr)",
 "**Moonshin worked in Paris for two decades** before returning to build this. The building itself is the main exhibit."),

("🎭","Seongsan Art Hall & Changwon Performances","👀 WATCH — check programme",
 "Changwon's main concert and theatre complex, hosting the city philharmonic, touring productions and the autumn arts season",
 "Box office **09:00–18:00**",
 "Tickets **₩10,000–₩60,000**",
 "[changwon.go.kr](https://www.changwon.go.kr) · [culture.go.kr](https://www.culture.go.kr)",
 "**Check the November programme** — the autumn season is the busiest of the year."),

("🏟️","Changwon LG Sakers — KBL basketball","✅ CONFIRMED — season runs",
 "The KBL basketball club plays at Changwon Gymnasium; **the 2026–27 season is under way through November**",
 "Tip-off typically **19:00** weekdays, **14:00/16:00** weekends",
 "Tickets from **₩8,000**",
 "[kbl.or.kr](https://www.kbl.or.kr) · [lgsakers.com](https://www.lgsakers.com)",
 "**A reliable indoor evening in your window** — check the KBL fixture list for home dates."),

("⚾","NC Dinos & Changwon NC Park","👀 WATCH — season ends October",
 "**One of Korea's best modern ballparks**, opened 2019, home to the NC Dinos; the KBO regular season finishes before November",
 "Season roughly **March–October**",
 "Tickets from **₩10,000**",
 "[ncdinos.com](https://www.ncdinos.com) · [koreabaseball.com](https://www.koreabaseball.com)",
 "**The season will be over during your trip**, but stadium tours are sometimes available — check the club site."),

("⚽","Gyeongnam FC & Changwon Football Center","👀 WATCH — season ending",
 "The K League 2 club plays at Changwon Football Center, a dedicated football ground",
 "Kick-off typically **14:00/16:00**",
 "Tickets from **₩8,000**",
 "[kleague.com](https://www.kleague.com) · [gyeongnamfc.com](https://www.gyeongnamfc.com)",
 "**Check for a home fixture in early November** before the season closes."),

("🏛️","Changwon Sports Parks & Public Facilities","🔁 daily",
 "Changwon's public sports complexes offer swimming, skating and courts at low municipal rates",
 "Roughly **06:00–22:00**",
 "**₩3,000–₩8,000**",
 "[changwon.go.kr](https://www.changwon.go.kr)",
 "Bring your own lock and indoor shoes."),

("🚴","Changwon Nubija Public Bike Share","🔁 daily",
 "**Korea's first city-wide public bike scheme**, launched 2008, with several hundred stations across Changwon",
 "**24 hours**",
 "Day pass around **₩1,000**",
 "[nubija.changwon.go.kr](https://nubija.changwon.go.kr)",
 "**Changwon's flat grid makes it genuinely cyclable** — better here than in most Korean cities."),

("🏝️","Jeodo Island & Colour Island (저도 연륙교)","🔁 daily (FREE)",
 "A small island off Masan linked by the **Colour Bridge**, whose deck includes a glass-floor sea walk, plus a coastal loop trail",
 "Always open; glass walk **09:00–18:00**",
 "**FREE**",
 "[changwon.go.kr](https://www.changwon.go.kr)",
 "**The glass-floor bridge is free** and the island loop takes about an hour."),

("🌊","Gujora & Changwon Coastal Villages","🔁 daily (FREE)",
 "The fishing villages along the Changwon coast, with small harbours, drying racks and seafood restaurants",
 "Always open",
 "**FREE**",
 "[changwon.go.kr](https://www.changwon.go.kr)",
 "Quieter and cheaper than Busan's equivalents."),

("🦪","Changwon & Jinhae Oyster Season","✅ CONFIRMED — Nov peak",
 "**Gyeongsangnam-do produces most of Korea's oysters**, and November is the start of peak season along this coast",
 "Restaurants roughly **11:00–22:00**",
 "Oyster meals **₩15,000–₩30,000**",
 "[changwon.go.kr](https://www.changwon.go.kr) · [mof.go.kr](https://www.mof.go.kr)",
 "**Your window is exactly right for oysters here.** Try *gul-guk* soup or a raw oyster platter."),

("🍜","Jinhae Food — naval port dishes & seafood","🔁 daily",
 "Jinhae's own specialities: *chungmu gimbap* variants, fresh sashimi from the port, and navy-town pork cutlet shops",
 "Roughly **11:00–22:00**",
 "**₩8,000–₩25,000**",
 "[changwon.go.kr](https://www.changwon.go.kr)",
 "**The pork cutlet shops near the base are a real Jinhae tradition** — huge portions at low prices."),

("🛍️","Changwon Shopping — Sangnam & Department Stores","🔁 daily",
 "The Sangnam-dong commercial district with its street market, plus Shinsegae and Lotte department stores",
 "Roughly **10:30–20:00**; market Fri–Sat",
 "**FREE** entry",
 "[changwon.go.kr](https://www.changwon.go.kr) · [shinsegae.com](https://www.shinsegae.com)",
 "**The Sangnam street market runs on Friday and Saturday evenings** and is the liveliest thing in Changwon."),

("🌃","Sangnam-dong Nightlife & Changwon Evenings","🔁 nightly",
 "Changwon's main entertainment district, with bars, barbecue houses and late-night food around Sangnam",
 "Roughly **17:00–03:00**",
 "**₩20,000–₩40,000** per person",
 "[changwon.go.kr](https://www.changwon.go.kr)",
 "**Busiest on Friday** when the street market and the bars overlap."),

("☕","Changwon & Jinhae Cafe Streets","🔁 daily",
 "Cafes around Yongji Lake, in Jinhae's old town and along the Masan waterfront",
 "Roughly **10:00–22:00**",
 "Coffee **₩5,000–₩7,000**",
 "[changwon.go.kr](https://www.changwon.go.kr)",
 "**Jinhae's converted colonial houses** make the most atmospheric cafes in the city."),

("🚄","Getting to Changwon & Jinhae — KTX and buses","🔁 daily",
 "KTX serves **Changwon Jungang Station** from Seoul in about 3 hours; Jinhae is 30 minutes further by bus or local train",
 "Trains roughly **05:30–21:30**",
 "KTX from Seoul **₩53,000**",
 "[letskorail.com](https://www.letskorail.com) · [changwon.go.kr](https://www.changwon.go.kr)",
 "**Changwon Jungang is the useful station** — Masan Station is a separate stop further west."),

("🚌","Changwon BRT & City Buses","🔁 daily",
 "Changwon runs a bus rapid transit corridor along Changwon-daero plus a dense city bus network; **there is no subway**",
 "Roughly **05:30–23:00**",
 "**₩1,500**",
 "[changwon.go.kr](https://www.changwon.go.kr)",
 "**No metro in Changwon** — buses and the BRT are how the city moves. T-money works."),

("🚌","Changwon ↔ Busan & Gimhae connections","🔁 daily",
 "Frequent buses link Changwon and Masan with Busan Sasang in about an hour, and Gimhae Airport in about 50 minutes",
 "Roughly **06:00–22:00**",
 "**₩5,000–₩8,000**",
 "[kobus.co.kr](https://www.kobus.co.kr) · [changwon.go.kr](https://www.changwon.go.kr)",
 "**Gimhae Airport is the nearest airport** and the bus is direct."),

("🧭","Changwon & Jinhae Tourist Information","🔁 daily (FREE)",
 "Information centres at Changwon Jungang Station, Jinhae's Jungwon Rotary and Masan Fish Market",
 "Daily **09:00–18:00**",
 "**FREE**",
 "[changwon.go.kr](https://www.changwon.go.kr) · [1330 Hotline](https://english.visitkorea.or.kr)",
 "**Very few foreign tourists come here off-season** — 1330 phone interpretation is the reliable fallback."),

("🏨","Changwon & Jinhae Accommodation","🔁 planning",
 "Business hotels around Changwon Jungang and Sangnam, cheaper options in Masan, and small guesthouses in Jinhae",
 "Check-in typically **15:00**",
 "From **₩45,000** per night",
 "[changwon.go.kr](https://www.changwon.go.kr) · [visitkorea.or.kr](https://english.visitkorea.or.kr)",
 "**Stay near Sangnam** for food and buses. Jinhae is quiet after dark outside blossom season."),

("🌡️","Changwon November Weather","🔁 planning",
 "One of Korea's mildest climates: November highs around **16°C**, lows near 6°C, with low rainfall and clear skies",
 "N/A",
 "N/A",
 "[weather.go.kr](https://www.weather.go.kr) · [changwon.go.kr](https://www.changwon.go.kr)",
 "**Good hiking and walking weather.** Sea wind on the Jinhae coast is the main discomfort."),

("🍁","Changwon Autumn Foliage — early November","✅ CONFIRMED — seasonal",
 "Muhaksan, Jangboksan and the Changwon Dulle-gil peak for foliage in **the first half of November** on this southern coast",
 "Daylight hours",
 "**FREE**",
 "[Korea Forest Service](https://www.forest.go.kr) · [changwon.go.kr](https://www.changwon.go.kr)",
 "**Muhaksan's silver grass plus maples** is the combination worth a morning."),

("🗺️","Changwon–Jinhae two-day model route","🔁 planning",
 "Day 1: Masan Fish Market → agu-jjim lunch → Moonshin Museum → Yongji Lake → Sangnam evening. Day 2: Jinhae old town → post office → Jinhae Tower → Yeojwacheon → Gyeonghwa Station → oysters",
 "Two days",
 "About **₩60,000** plus meals",
 "[changwon.go.kr](https://www.changwon.go.kr)",
 "**Jinhae and Masan are the two halves of Changwon worth your time** — the new city in between is mainly residential."),
]

append("/home/user/KoreaFun/changwon-jinhae.md", E, 141, 3,
       "\n---\n\n## 🧭 Beginner-friendly essentials", "Changwon & Jinhae",
       intro="**Verified expansion set** — the naval port and colonial old town of Jinhae, Masan's fish market and democracy history, Changwon's planned-city landmarks, oyster and monkfish season, sport, hiking and transit.")
