# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "/home/user/KoreaFun/.build")
from addlib import append

E = [
("🧺","Seomun Market & Night Market (서문시장)","🔁 daily",
 "Daegu's 400-year-old great market, one of the three largest in Joseon Korea — 4,000+ stalls over six districts, with a famous **night market from 19:30**",
 "Day market **09:00–19:00** (closed 1st & 3rd Sunday); night market **19:30–24:00**",
 "**FREE** to browse; street food ₩2,000–₩6,000",
 "[daegu.go.kr](https://www.daegu.go.kr) · [Jung-gu Daegu](https://www.jung.daegu.kr)",
 "Daegu Line 3 Seomun Market Station. **The night market is the single best evening in Daegu** — go hungry, and try the *napjak mandu* flat dumplings."),

("🥟","Daegu Napjak-mandu & Ten Signature Foods (대구 십미)","🔁 daily",
 "Daegu officially designates **ten signature dishes** — flat dumplings, *makchang* grilled intestine, *ttaro gukbap*, muntier noodles, spicy braised catfish and more",
 "Restaurants roughly **11:00–23:00**",
 "Most dishes **₩7,000–₩15,000**",
 "[daegu.go.kr](https://www.daegu.go.kr)",
 "The city tourism site lists designated restaurants for each dish. **Makchang with soju is the definitive Daegu night out.**"),

("🌃","Kim Kwang-seok Memorial Street (김광석 다시그리기길)","🔁 daily (FREE)",
 "A 350 m alley beside Bangcheon Market covered in murals to **Kim Kwang-seok (1964–96)**, Korea's most beloved folk singer-songwriter, who grew up here",
 "Always open; cafes roughly **11:00–22:00**",
 "**FREE**",
 "[daegu.go.kr](https://www.daegu.go.kr) · [Jung-gu Daegu](https://www.jung.daegu.kr)",
 "Daegu Line 2 Kyungpook Univ. Hospital Station Exit 3. His songs play from speakers along the whole street — genuinely moving even if you don't know him."),

("🏛️","Daegu National Museum (국립대구박물관)","🔁 Tue–Sun (FREE)",
 "The regional national museum covering the Yeongnam area — Gaya and Silla archaeology, Confucian scholarly culture and Daegu's textile industry",
 "Tue–Sun **10:00–18:00** (Sat to 21:00; closed Mondays)",
 "**FREE**",
 "[daegu.museum.go.kr](https://daegu.museum.go.kr)",
 "Daegu Line 2 Manchon Station + short bus. Free, and the textile gallery explains why Daegu was Korea's fashion capital."),

("🎨","Daegu Art Museum (대구미술관)","🔁 Tue–Sun",
 "The city's major contemporary art museum next to the stadium — strong holdings of Korean modern art and a well-known **Lee Inseong** collection",
 "Tue–Sun **10:00–19:00** (closed Mondays)",
 "Adult **₩1,000**; special exhibitions extra",
 "[daeguartmuseum.or.kr](https://artmuseum.daegu.go.kr)",
 "Daegu Line 2 Daegongwon Station + bus. ₩1,000 for a full-scale art museum."),

("🚶","Daegu Modern Culture Alley — 5 free walking courses (근대골목)","🔁 daily (FREE)",
 "Daegu's flagship heritage walk — **five numbered courses** through missionary houses, the 1919 March 1st Movement stairs, Gyesan Cathedral and Jingolmok alley",
 "Always open; free guided walks by reservation",
 "**FREE**",
 "[daegu.go.kr](https://www.daegu.go.kr) · [Jung-gu Daegu](https://www.jung.daegu.kr)",
 "Course 2 is the classic (about 2 hours). **Free English guided walks can be booked through the Jung-gu office** — highly recommended."),

("⛪","Gyesan Catholic Cathedral (계산성당)","🔁 daily (FREE)",
 "Daegu's 1902 Gothic red-brick cathedral, the oldest Western building in the city and the third oldest church in Korea",
 "Daily roughly **09:00–17:00** outside services",
 "**FREE**",
 "[Jung-gu Daegu](https://www.jung.daegu.kr) · [Catholic Archdiocese of Daegu](https://www.daegu-archdiocese.or.kr)",
 "On Modern Alley Course 2. The painter Lee Inseong sketched here as a boy — his tree is still in the churchyard."),

("🪜","3·1 Movement Road & Cheongna Hill Missionary Houses","🔁 daily (FREE)",
 "The 90 stone steps students climbed in secret to join the **March 1st Movement in 1919**, leading up to three 1910 American missionary houses, now small museums",
 "Steps always open; house museums Tue–Sun **09:30–17:30**",
 "**FREE**",
 "[Jung-gu Daegu](https://www.jung.daegu.kr) · [daegu.go.kr](https://www.daegu.go.kr)",
 "Near Dongsan Hospital. **Autumn foliage on the steps is excellent in early November.**"),

("🌿","Yangnyeongsi Oriental Medicine Museum & Herb Market (약령시)","🔁 Tue–Sun (FREE)",
 "**Korea's oldest herbal medicine market**, established 1658 — a working street of 350+ herb shops and clinics, with a free museum and tea tasting",
 "Museum Tue–Sun **10:00–18:00**; market shops **09:00–18:00**",
 "Museum **FREE**; foot bath and tea free",
 "[daegu.go.kr](https://www.daegu.go.kr) · [Jung-gu Daegu](https://www.jung.daegu.kr)",
 "Daegu Line 1 Banwoldang Station Exit 18. **Free herbal foot bath and free medicinal tea** in the museum — a great cold-weather stop."),

("🏛️","Gyeongsang-gamyeong Park & Provincial Office Site (경상감영공원)","🔁 daily (FREE)",
 "The site of the Joseon provincial government of Gyeongsang, with two surviving 1601 halls in a public park in the middle of downtown",
 "Always open",
 "**FREE**",
 "[Jung-gu Daegu](https://www.jung.daegu.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "Daegu Line 1 Jungangno Station. A quiet green square surrounded by department stores."),

("🕊️","Gukchaebosang Memorial Park (국채보상운동기념공원)","🔁 daily (FREE)",
 "A park commemorating the **1907 National Debt Repayment Movement**, when Daegu citizens gave up tobacco to pay off Korea's debt to Japan — a UNESCO Memory of the World record",
 "Always open",
 "**FREE**",
 "[daegu.go.kr](https://www.daegu.go.kr) · [UNESCO Memory of the World](https://www.unesco.org)",
 "Daegu Line 1 Jungangno Station. The movement's archives were UNESCO-inscribed in 2017 — it started in this city."),

("🛍️","Dongseongno Shopping Street (동성로)","🔁 daily (FREE)",
 "Daegu's main pedestrian shopping and nightlife street — Korea's largest downtown commercial district outside Seoul, with 2 km of shops and street performers",
 "Shops **11:00–22:00**; bars later",
 "**FREE** to walk",
 "[daegu.go.kr](https://www.daegu.go.kr) · [Jung-gu Daegu](https://www.jung.daegu.kr)",
 "Daegu Line 1 Jungangno Station. Busking every weekend evening; Daegu has a real live-music culture."),

("👞","Hyangchon-dong Shoe Alley & Modern History Museum","🔁 Tue–Sun (FREE)",
 "The old handmade-shoe street beside the free Hyangchon Cultural Center, which recreates 1950s–60s Daegu — a music cafe, a barbershop, a photo studio",
 "Museum Tue–Sun **09:00–19:00** (closed Mondays)",
 "**FREE**",
 "[Jung-gu Daegu](https://www.jung.daegu.kr)",
 "Daegu Line 1 Jungangno Station. The basement recreation of a 1960s classical music cafe is charming and free."),

("🗼","Daegu 83 Tower & E-World (83타워·이월드)","🔁 daily",
 "The 202 m observation tower on Duryu Mountain and the amusement park below it — with an all-year **evening illumination** across the park",
 "Park roughly **10:00–21:00**; tower to 22:00 (Nov)",
 "Tower **₩10,000**; park + tower ₩45,000",
 "[eworld.kr](https://www.eworld.kr)",
 "Daegu Line 2 Duryu Station Exit 15. **The night illumination and the tower view together are the best-value evening in Daegu.**"),

("🌳","Duryu Park & Daegu Culture & Arts Center (두류공원)","🔁 daily (FREE)",
 "Daegu's biggest city park around 83 Tower — forest paths, a large plaza, the culture and arts centre and Duryu Baseball Park",
 "Always open",
 "**FREE**",
 "[daegu.go.kr](https://www.daegu.go.kr)",
 "Daegu Line 2 Duryu Station. **Foliage peaks in early-to-mid November** and the whole park is free."),

("⛰️","Apsan Park & Cable Car (앞산공원·앞산케이블카)","🔁 daily",
 "The forested mountain park on Daegu's southern edge, with a cable car to an observatory that gives **the best panorama of the entire Daegu basin**",
 "Park always open; cable car **10:30–18:00** (Nov)",
 "Park **FREE**; cable car return **₩12,000**",
 "[daegu.go.kr](https://www.daegu.go.kr) · [Nam-gu Daegu](https://www.nam.daegu.kr)",
 "Bus 401/southbound from downtown. **Go up before sunset (~17:25 in November) and come down after dark** for the city lights."),

("🎖️","Nakdong River Victory Memorial Hall (낙동강승전기념관)","🔁 Tue–Sun (FREE)",
 "The museum of the 1950 **Battle of the Nakdong Bulge**, the last defensive line that saved South Korea — at Apsan, with outdoor military hardware",
 "Tue–Sun **09:00–18:00** (closed Mondays)",
 "**FREE**",
 "[daegu.go.kr](https://www.daegu.go.kr)",
 "In Apsan Park. Daegu was inside the Pusan Perimeter and never fell — this explains why that mattered."),

("🛕","Donghwasa Temple, Palgongsan (동화사)","🔁 daily",
 "Founded 493, the head temple of the Jogye Order's 9th district — with a **33 m stone Medicine Buddha** built in 1992 as a prayer for reunification",
 "Daily **08:00–18:00** (Nov: to 17:30)",
 "Adult **₩2,500**",
 "[donghwasa.net](https://www.donghwasa.net) · [templestay.com](https://www.templestay.com)",
 "Bus Express 1 from downtown (~50 min). **The Palgongsan approach road in early November foliage is one of the best drives in Korea.**"),

("🗿","Gatbawi Stone Buddha, Palgongsan (갓바위)","🔁 daily",
 "A 4 m 9th-century seated Buddha wearing a flat stone 'hat' on a 850 m summit — Korea's most famous wish-granting site, especially before exams",
 "Always open; ~50 min climb from the car park",
 "Entry **₩1,500** (Seonbonsa)",
 "[daegu.go.kr](https://www.daegu.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "Bus 401 to Gatbawi. **It is said to grant one wish to everyone who climbs to it** — hence thousands of parents each November before the CSAT exam."),

("🚡","Palgongsan Cable Car (팔공산 케이블카)","🔁 daily",
 "A 1.2 km cable car up Palgongsan to an observatory deck and a ridge cafe, with views over the whole massif",
 "Daily **09:30–17:30** (Nov)",
 "Return adult **₩12,000**",
 "[palgongsan.co.kr](https://www.palgongsan.co.kr)",
 "Next to Donghwasa. **Foliage on Palgongsan peaks roughly late October to early November.**"),

("🏞️","Palgongsan National Park (팔공산국립공원)","🔁 daily (FREE)",
 "Upgraded to **Korea's 23rd national park in 2023** — the 1,193 m Birobong ridge, a chain of temples and hermitages, and a serious full-day traverse",
 "Always open",
 "**FREE**",
 "[knps.or.kr](https://www.knps.or.kr) · [english.knps.or.kr](https://english.knps.or.kr)",
 "Trailheads at Donghwasa and Sutasa. Check the Korea National Park Service site for the November trail closure schedule."),

("🌲","Daegu Arboretum (대구수목원)","🔁 Tue–Sun (FREE)",
 "Built on a former landfill and now one of Korea's best free arboretums — 1,800 species, a cactus greenhouse and a large **chrysanthemum display in autumn**",
 "Tue–Sun **09:00–18:00** (Nov: to 17:00; closed Mondays)",
 "**FREE**",
 "[daegu.go.kr](https://www.daegu.go.kr)",
 "Daegu Line 1 Daegok Station + short walk. **The autumn chrysanthemum exhibition typically runs into early November** — free and very large."),

("🌊","Suseong Lake & Night Fountain (수성못)","🔁 daily (FREE)",
 "A 1925 irrigation reservoir turned into Daegu's favourite evening promenade — a 2 km lit loop, swan boats, a music fountain and a cafe strip",
 "Always open; fountain shows evenings",
 "**FREE**; swan boat ₩15,000/30 min",
 "[Suseong-gu](https://www.suseong.kr) · [daegu.go.kr](https://www.daegu.go.kr)",
 "Daegu Line 3 Suseongmot Station. **The single most pleasant free evening in Daegu.** Sunset ~17:25 in November."),

("🌉","The ARC & Nakdong River Culture Center (디아크)","🔁 Tue–Sun (FREE)",
 "A striking fish-shaped river culture centre at the Nakdong–Geumho confluence, with a free exhibition hall and a riverside park",
 "Tue–Sun **10:00–18:00** (closed Mondays)",
 "**FREE**",
 "[daegu.go.kr](https://www.daegu.go.kr) · [K-water](https://www.kwater.or.kr)",
 "Bus from Dasa Station (Daegu Line 2). Free, architecturally impressive and lit at night."),

("🏺","Bullo-dong Ancient Tomb Park (불로동고분군)","🔁 daily (FREE)",
 "A hillside of 200+ grass-covered **Three Kingdoms-period tombs** near the airport, a Gyeongju-like landscape with no entry fee and no crowds",
 "Always open",
 "**FREE**",
 "[daegu.go.kr](https://www.daegu.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "Bus from Ayanggyo Station. **Sunset over the mounds is superb** and you will likely have it to yourself."),

("🎨","Mabijeong Mural Village (마비정 벽화마을)","🔁 daily (FREE)",
 "A remote farming hamlet in the hills south-west of Daegu, painted end to end with rural-life murals — plus a 400-year-old zelkova and a spring",
 "Always open",
 "**FREE**",
 "[daegu.go.kr](https://www.daegu.go.kr) · [Dalseo-gu](https://www.dalseo.daegu.kr)",
 "Bus 성서3 from Daegok Station. Remote and rural — check the return bus timetable before you go."),

("🏫","Dodongseowon — UNESCO (도동서원)","🔁 daily (FREE)",
 "One of the nine **UNESCO-listed Korean seowon**, honouring the scholar Kim Goeng-pil — with an extraordinary 1607 stone-and-mud wall that is a National Treasure",
 "Daily **09:00–18:00** (Nov: to 17:00)",
 "**FREE**",
 "[UNESCO](https://whc.unesco.org/en/list/1498) · [Dalseong-gun](https://www.dalseong.daegu.kr)",
 "Bus 달성5 from Hyeonpung. **The 400-year-old ginkgo at the gate is spectacular in early-to-mid November.**"),

("📚","Nokdong Seowon & Dalseong Confucian Sites","🔁 daily (FREE)",
 "The academy honouring **Kim Chung-seon**, the Japanese general Sayaka who defected to Korea in 1592 and fought for his adopted country — a genuinely remarkable story",
 "Daily **09:00–18:00** (Nov: to 17:00)",
 "**FREE**",
 "[Dalseong-gun](https://www.dalseong.daegu.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "In Dalseong-gun. His Korean descendants still live in the village below."),

("⛰️","Biseulsan Recreational Forest (비슬산)","🔁 daily",
 "A 1,084 m mountain south of Daegu famous for its azaleas and its **rock river** — a 2 km field of boulders left by the last ice age",
 "Always open; observation shuttle to 17:00",
 "Parking ₩3,000; shuttle **₩6,000**",
 "[Dalseong-gun](https://www.dalseong.daegu.kr) · [Korea Forest Service](https://www.forest.go.kr)",
 "Bus from Hyeonpung. Autumn colour peaks late October to early November; the boulder field is worth seeing in any season."),

("🥣","Bangjja Yugi Brassware Museum (방짜유기박물관)","🔁 Tue–Sun (FREE)",
 "Korea's only museum of hand-hammered bronze tableware, a craft designated Important Intangible Cultural Heritage — with a workshop reconstruction",
 "Tue–Sun **10:00–19:00** (closed Mondays)",
 "**FREE**",
 "[daegu.go.kr](https://www.daegu.go.kr)",
 "Near Donghwasa on the Palgongsan road. Combine with the temple. Free and unexpectedly absorbing."),

("🔬","National Daegu Science Museum (국립대구과학관)","🔁 Tue–Sun",
 "The regional national science museum in Dalseong — hands-on engineering, a planetarium and an industrial technology hall reflecting Daegu's manufacturing base",
 "Tue–Sun **09:30–17:30** (closed Mondays)",
 "Adult **₩3,000**; planetarium extra",
 "[dnsm.or.kr](https://www.dnsm.or.kr)",
 "Daegu Line 1 Daesil Station + bus. Very good with children and cheap."),

("🐠","Alive Aquarium & Daegu Sparkland","🔁 daily",
 "The indoor aquarium and the rooftop amusement complex at Sparkland in Suseong — warm indoor options right by Suseong Lake",
 "Roughly **10:00–20:00**",
 "Aquarium **₩20,000**; Sparkland rides individually priced",
 "[daegu.go.kr](https://www.daegu.go.kr)",
 "Daegu Line 3 Suseongmot Station. A practical wet-weather pairing with the lake walk."),

("🎢","Daegu Dongchon Recreation Area & Rail Bike (동촌유원지)","🔁 daily",
 "A riverside recreation park on the Geumho with paddle boats, a suspension bridge and a small vintage amusement area — Daegu's old-fashioned day out",
 "Always open; rides roughly **10:00–18:00**",
 "Park **FREE**; boats from ₩10,000",
 "[daegu.go.kr](https://www.daegu.go.kr) · [Dong-gu Daegu](https://www.dong.daegu.kr)",
 "Daegu Line 1 Donggu Office Station. Faded and charming rather than slick."),

("🎭","Daegu Opera House (대구오페라하우스)","🔁 by event",
 "**Korea's first purpose-built opera house** (2003), with a full autumn season and the annual Daegu International Opera Festival",
 "Performances typically **19:30**; matinees weekends",
 "**₩10,000–₩120,000**",
 "[daeguoperahouse.org](https://www.daeguoperahouse.org)",
 "Daegu Line 1 Chilseong Market Station. **Check the November programme in October** — Daegu is genuinely Korea's opera city."),

("🎵","Daegu Concert House & Daegu Symphony Orchestra","🔁 by event",
 "The city's main classical concert hall, home of the Daegu Symphony Orchestra, with a full November subscription season",
 "Concerts typically **19:30**",
 "**₩10,000–₩50,000**",
 "[dgconcerthouse.or.kr](https://www.dgconcerthouse.or.kr)",
 "Daegu Line 1 Daegu Station. Cheaper than Seoul for equivalent programming."),

("🎬","Daegu Art Factory & Suchang Cheongnyeon Manseon","🔁 Tue–Sun (FREE)",
 "Two converted industrial buildings downtown — a former beer factory and a former tobacco warehouse, now free contemporary art and maker spaces",
 "Tue–Sun **10:00–19:00** (closed Mondays)",
 "**FREE**",
 "[daegu.go.kr](https://www.daegu.go.kr) · [Jung-gu Daegu](https://www.jung.daegu.kr)",
 "Both near Banwoldang. Free, central and a good pair with the Modern Alley walk."),

("⚽","K League 1 — Daegu FC at DGB Daegu Bank Park","👀 WATCH — season ending",
 "Daegu FC play at **Korea's best football-specific stadium**, a 12,000-seat ground where the stands are 7 m from the touchline. **The season ends in late November**",
 "Kick-off typically **14:00/16:00** at weekends",
 "Tickets **₩12,000–₩30,000**",
 "[daegufc.co.kr](https://www.daegufc.co.kr) · [kleague.com](https://www.kleague.com)",
 "Daegu Line 3 Bukbu Bus Terminal Station. **If you see one K League game in Korea, make it this one** — the atmosphere is exceptional."),

("🏀","KBL — Daegu KOGAS Pegasus","✅ CONFIRMED — season running",
 "Professional basketball at Daegu Gymnasium; **the KBL season runs right through November**, so home games are close to guaranteed",
 "Tip-off typically **19:00** weekdays, **14:00/16:00** weekends",
 "Tickets **₩8,000–₩25,000**",
 "[kbl.or.kr](https://www.kbl.or.kr)",
 "Daegu Line 2 Daegongwon Station. Indoor, warm and cheap — a reliable November evening."),

("⚾","Daegu Samsung Lions Park (대구삼성라이온즈파크)","👀 WATCH — off-season",
 "One of Korea's best ballparks, home of the eight-time champion Samsung Lions. **The KBO season ends in October**, so November is off-season",
 "By event",
 "Stadium tours when scheduled",
 "[samsunglions.com](https://www.samsunglions.com) · [koreabaseball.com](https://www.koreabaseball.com)",
 "Daegu Line 2 Daegongwon Station. Check for off-season open days and the team shop."),

("🏟️","Daegu Stadium & EXCO Convention Center","🔁 by event",
 "The 2011 World Athletics Championships stadium, and EXCO, Daegu's convention centre, which hosts major expos through the autumn",
 "By event",
 "Varies; some expos free",
 "[exco.co.kr](https://www.exco.co.kr) · [daegu.go.kr](https://www.daegu.go.kr)",
 "Daegu Line 3 EXCO Station. **Check the EXCO November calendar in October** — there are usually several large weekend fairs."),

("♨️","Daegu Spa Valley & Public Jjimjilbang","🔁 daily",
 "Daegu's hot-spring and sauna facilities, including the large Spa Valley complex in Palgongsan with outdoor thermal pools",
 "Roughly **09:00–20:00**; jjimjilbang often 24 h",
 "Spa Valley from **₩20,000**; local jjimjilbang ₩10,000–₩15,000",
 "[daegu.go.kr](https://www.daegu.go.kr)",
 "Outdoor hot pools on Palgongsan in November air are excellent after a day's hiking."),

("🍶","Anjirang Gopchang Alley & Makchang Streets (안지랑곱창골목)","🔁 daily",
 "A 500 m street of 60+ grilled-intestine restaurants, all charging roughly the same, all packed every night — one of Korea's great food alleys",
 "Roughly **16:00–02:00**",
 "Per person **₩12,000–₩18,000**",
 "[daegu.go.kr](https://www.daegu.go.kr) · [Nam-gu Daegu](https://www.nam.daegu.kr)",
 "Daegu Line 1 Anjirang Station Exit 3. **This is the Daegu experience.** Order *makchang* and a bottle of soju and copy your neighbours."),

("🍜","Bangcheon Market & Daegu Ttaro Gukbap","🔁 daily",
 "The market beside Kim Kwang-seok Street, and Daegu's signature *ttaro gukbap* — spicy beef soup served with the rice separate",
 "Market roughly **08:00–20:00**",
 "Gukbap **₩9,000–₩11,000**",
 "[daegu.go.kr](https://www.daegu.go.kr)",
 "Daegu Line 2 Kyungpook Univ. Hospital Station. 'Ttaro' means 'separately' — the rice comes in its own bowl, which is the whole innovation."),

("☕","Daegu Cafe Culture — Kyungpook & Bongsan-dong","🔁 daily",
 "Daegu's cafe and gallery districts — Bongsan Culture Street for art galleries, and the Kyungpook National University quarter for cheap student cafes",
 "Most **11:00–23:00**",
 "Coffee **₩4,500–₩7,000**",
 "[daegu.go.kr](https://www.daegu.go.kr) · [Jung-gu Daegu](https://www.jung.daegu.kr)",
 "Bongsan-dong has over 30 commercial galleries in a few blocks, nearly all free to enter."),

("🚄","Daegu via Dongdaegu KTX Station","🔁 daily",
 "**Seoul → Dongdaegu by KTX is about 1 h 45**, and Busan → Dongdaegu about 50 minutes — Daegu is the natural midpoint of the country",
 "Trains roughly **05:15–23:00**",
 "Seoul→Dongdaegu from **₩43,500**",
 "[letskorail.com](https://www.letskorail.com) · [srail.co.kr](https://www.srail.co.kr)",
 "Dongdaegu Station is on Daegu Line 1 and has a large shopping complex attached. SRT from Suseo is often cheaper."),

("🚇","Daegu Metro Lines 1–3 & the Monorail View","🔁 daily",
 "Daegu's Line 3 is an **elevated monorail** running above the streets — effectively a free sightseeing ride across the whole city for the price of a fare",
 "Roughly **05:30–24:00**",
 "Single fare **₩1,500**; T-money accepted",
 "[dtro.or.kr](https://www.dtro.or.kr) · [daegu.go.kr](https://www.daegu.go.kr)",
 "**Ride Line 3 end to end at dusk** — it passes above Suseong Lake and the downtown. One of the best-value things in this file."),

("🗺️","Daegu City Tour Bus & Free Guided Walks","🔁 Tue–Sun",
 "The official city tour bus with themed routes, plus **free volunteer-guided walks** of the Modern Alley courses in English",
 "Bus departures roughly **09:30–17:00**",
 "Bus day pass **₩5,000–₩10,000**; guided walks FREE",
 "[daegu.go.kr](https://www.daegu.go.kr) · [Jung-gu Daegu](https://www.jung.daegu.kr)",
 "Departs Dongdaegu Station. Book English guided walks through the Jung-gu office a few days ahead."),

("🍂","Daegu Autumn Foliage — Palgongsan, Apsan, Dodongseowon","✅ CONFIRMED — peak late Oct–mid Nov",
 "Daegu's foliage runs **Palgongsan first (late October), then Apsan and the city parks in early November, with the Dodongseowon ginkgo around Nov 5–15**",
 "Daylight hours",
 "**FREE** except cable cars",
 "[Korea Forest Service](https://www.forest.go.kr) · [daegu.go.kr](https://www.daegu.go.kr)",
 "Daegu sits in a basin and is warmer than Seoul, so its colour arrives a little later — good for the first half of the trip window."),

("🌡️","Daegu November Weather & the 'Daegu basin' effect","✅ CONFIRMED",
 "Daegu is Korea's hottest city in summer and mild in November — roughly **4–16 °C**, dry and often sunny, with big day-night swings",
 "n/a",
 "n/a",
 "[Korea Meteorological Administration](https://www.weather.go.kr)",
 "Warmer daytime than Seoul, colder nights than Busan. Layers, and a proper jacket for Palgongsan."),

("🎪","Daegu Autumn Festivals & City Event Calendar","👀 WATCH",
 "Daegu's city calendar carries chrysanthemum shows, the Colorful Daegu programme and district festivals through the autumn — **2026 November dates unconfirmed**",
 "TBA",
 "Most city events **FREE**",
 "[daegu.go.kr](https://www.daegu.go.kr) · [Daegu Tourism](https://www.daegu.go.kr/tour)",
 "Re-check the official Daegu city and tourism calendars in **September–October 2026** for confirmed November dates."),
]

append("/home/user/KoreaFun/daegu.md", E, 140, 3,
       "\n---\n\n## 🧭 Beginner-friendly essentials", "Daegu")
