# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "/home/user/KoreaFun/.build")
from addlib import append

E = [
("🛕","Pagyesa Temple & Palgongsan Hermitages (파계사)","🔁 daily",
 "A 9th-century temple on the north-west of Palgongsan, famous for the Wontong-jeon hall and a wooden Gwanseeum statue that yielded a royal robe in 1979",
 "Daily **08:00–18:00** (Nov: to 17:30)",
 "Adult **₩2,500**",
 "[daegu.go.kr](https://www.daegu.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "Bus 파계1 from Dongdaegu. Far quieter than Donghwasa with the same mountain scenery."),

("🍁","Palgongsan Sunhwan-doro Scenic Drive & Bus (팔공산순환도로)","🔁 daily (FREE)",
 "The circular road around Palgongsan, lined with maples, cafes and temple turn-offs — **one of Korea's designated 100 most beautiful roads**",
 "Always open",
 "**FREE**; bus fare ₩1,500",
 "[daegu.go.kr](https://www.daegu.go.kr) · [Korea Forest Service](https://www.forest.go.kr)",
 "Bus Express 1 covers much of it. **Peak colour is late October to the first week of November.**"),

("🧗","Palgongsan Birobong & Gatbawi Ridge Traverse","🔁 daily (FREE)",
 "The full ridge walk across Palgongsan from Donghwasa to Gatbawi — 6–7 hours, with the Silla-era hermitages strung along the way",
 "Always open; start before 09:00",
 "**FREE**",
 "[knps.or.kr](https://www.knps.or.kr) · [english.knps.or.kr](https://english.knps.or.kr)",
 "**A serious full-day hike.** Check National Park Service closure notices; some sections shut in winter fire season from mid-November."),

("🏛️","Daegu Bangjja & Otgol Village Traditional Houses (옻골마을)","🔁 daily (FREE)",
 "A 17th-century Gyeongju Choi clan village in eastern Daegu, with a 350-year-old head house and a protective zelkova grove — a complete Joseon village inside a modern city",
 "Daylight hours",
 "**FREE**",
 "[Dong-gu Daegu](https://www.dong.daegu.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "Bus from Ayanggyo. Twenty minutes from downtown and almost unknown to visitors."),

("🎋","Daegu Hyanggyo & Confucian Ceremonies (대구향교)","🔁 daily (FREE)",
 "Daegu's Confucian school, founded 1398 — with public *seokjeon* rites, tea ceremony programmes and free hanbok-wearing sessions",
 "Daily **09:00–18:00**",
 "**FREE**",
 "[daegu.go.kr](https://www.daegu.go.kr) · [Jung-gu Daegu](https://www.jung.daegu.kr)",
 "Daegu Line 1 Banwoldang Station. Free traditional-culture programmes run most weekends — check the district site."),

("📿","Yeongnam Jeilgwan & Dalseong Park (달성공원)","🔁 daily (FREE)",
 "**Daegu's oldest park**, on a 1,500-year-old earthen fortress mound, with a small zoo, the restored Yeongnam Jeilgwan gate and old trees",
 "Daily **05:00–21:00**",
 "**FREE**",
 "[daegu.go.kr](https://www.daegu.go.kr) · [Jung-gu Daegu](https://www.jung.daegu.kr)",
 "Daegu Line 3 Dalseong Park Station. Free entry including the zoo — old-fashioned, but a genuine piece of local life."),

("🚉","Chilseong Night Market & Daegu Wholesale Markets","🔁 daily",
 "Chilseong Market, Daegu's big wholesale complex near the station, with a flower market, a dawn produce auction and a night food section",
 "Wholesale from **03:00**; retail **08:00–20:00**",
 "**FREE** to browse",
 "[daegu.go.kr](https://www.daegu.go.kr)",
 "Daegu Line 1 Chilseong Market Station. The 04:00 flower market is a genuine spectacle if you're up."),

("🌸","Daegu Chrysanthemum & Autumn Flower Exhibitions","👀 WATCH (late Oct–early Nov)",
 "Daegu's arboretum, Duryu Park and district offices mount large chrysanthemum displays each autumn, typically running into the first week of November",
 "Daylight hours once open",
 "**FREE**",
 "[daegu.go.kr](https://www.daegu.go.kr)",
 "The Daegu Arboretum display is the largest. Dates are published on the city site in October."),

("🎤","Daegu Live Music, Busking & Rock Festival Scene","🔁 weekends (FREE)",
 "Daegu has one of Korea's strongest live-music cultures — free busking on Dongseongno, small live clubs in Bongsan-dong, and the city-run busking programme",
 "Weekend evenings roughly **18:00–22:00**",
 "Busking **FREE**; club entry ₩10,000–₩20,000",
 "[daegu.go.kr](https://www.daegu.go.kr) · [Jung-gu Daegu](https://www.jung.daegu.kr)",
 "Kim Kwang-seok came out of this scene. Dongseongno on a Saturday evening is free and consistently good."),

("🎨","Bongsan Culture Street Galleries (봉산문화거리)","🔁 Tue–Sun (FREE)",
 "Over 30 commercial art galleries along one downtown street, nearly all free to enter — Korea's densest gallery cluster outside Seoul",
 "Tue–Sun roughly **10:30–18:30** (closed Mondays)",
 "**FREE**",
 "[daegu.go.kr](https://www.daegu.go.kr) · [Jung-gu Daegu](https://www.jung.daegu.kr)",
 "Daegu Line 2 Banwoldang Station. Just walk in — commercial galleries in Korea expect browsers."),

("🧵","Daegu Textile Complex & Fashion Industry Heritage","🔁 by event",
 "Daegu was Korea's textile capital, and the industry's museums, the Daegu Textile Complex and the annual Daegu Fashion Fair still reflect it",
 "By event; DTC museum Tue–Sun **10:00–18:00**",
 "Mostly **FREE**",
 "[daegu.go.kr](https://www.daegu.go.kr) · [exco.co.kr](https://www.exco.co.kr)",
 "The Daegu National Museum's textile gallery is the best free introduction to this history."),

("🏞️","Geumho River Cycle Path & Nakdong Confluence","🔁 daily (FREE)",
 "The riverside cycle route along the Geumho to its confluence with the Nakdong — part of Korea's national bike-certification network",
 "Always open",
 "**FREE**; bike hire from ₩10,000/day",
 "[riverguide.go.kr](https://www.riverguide.go.kr) · [daegu.go.kr](https://www.daegu.go.kr)",
 "Certification stamp booths along the route. Flat, separated and good in cool November weather."),

("🌾","Sagunjin & Hwawon Recreation Area Nakdong Cliffs","🔁 daily (FREE)",
 "The riverside cliffs and pavilion at Hwawon overlooking the Nakdong — a Joseon-era scenic spot with a modern observation deck and cafe",
 "Always open",
 "**FREE**",
 "[Dalseong-gun](https://www.dalseong.daegu.kr) · [daegu.go.kr](https://www.daegu.go.kr)",
 "Bus from Daegok Station. **Sunset over the Nakdong from the deck is the best free view in western Daegu.**"),

("🕌","Daegu Islamic Center & Multicultural Districts","🔁 daily (FREE)",
 "Daegu's mosque and the multicultural food streets around Kyungpook National University serving Central Asian, Uzbek and Pakistani food",
 "Mosque prayer times; restaurants **11:00–22:00**",
 "**FREE** to visit",
 "[daegu.go.kr](https://www.daegu.go.kr)",
 "Near Kyungpook National University. Halal options in Daegu are concentrated here."),

("🏥","Daegu Medical Tourism & Oriental Medicine Experience","🔁 weekdays",
 "Daegu markets itself as a medical tourism city; the Yangnyeongsi district offers short traditional-medicine consultations and herbal experience programmes",
 "Weekdays roughly **09:00–18:00**",
 "Experience programmes from **₩10,000**",
 "[daegu.go.kr](https://www.daegu.go.kr) · [Korea Health Industry Development Institute](https://www.khidi.or.kr)",
 "Book through the Yangnyeongsi museum. Making your own herbal sachet is a good hour."),

("🛌","Daegu Hanok Stay & Guesthouse Districts","🔁 daily",
 "Restored hanok guesthouses in the Modern Alley and Otgol areas, plus a large cheap guesthouse cluster near Dongdaegu Station",
 "Check-in typically **15:00**",
 "From **₩40,000** per night",
 "[daegu.go.kr](https://www.daegu.go.kr) · [visitkorea.or.kr](https://english.visitkorea.or.kr)",
 "Daegu is markedly cheaper than Seoul or Busan for accommodation."),

("🛍️","Daegu Department Stores — Shinsegae & Hyundai","🔁 daily",
 "Shinsegae Daegu at Dongdaegu Station includes an aquarium, a rooftop theme park and a cinema — one of Korea's largest department stores",
 "Daily **10:30–20:00** (food halls later)",
 "**FREE** entry",
 "[shinsegae.com](https://www.shinsegae.com) · [ehyundai.com](https://www.ehyundai.com)",
 "Directly attached to Dongdaegu KTX Station — a good place to spend a couple of hours before a train."),

("🧊","Daegu Winter Illumination & Seasonal Ice Rinks","👀 WATCH (from mid-Nov)",
 "E-World, Suseong Lake and Dongseongno typically switch on winter lighting **from mid-to-late November**, with outdoor rinks opening around the same time",
 "Lighting roughly **17:30–23:00** once lit",
 "Street lighting **FREE**; rinks ₩1,000–₩5,000",
 "[daegu.go.kr](https://www.daegu.go.kr) · [eworld.kr](https://www.eworld.kr)",
 "**E-World's illumination runs year-round**, so it's the reliable option regardless of switch-on dates."),

("🎿","Daegu-area Ski & Winter Sports Access","👀 WATCH — opens late Nov/Dec",
 "The nearest ski resorts to Daegu (Eden Valley near Yangsan, and the Gyeongbuk resorts) typically open **from late November or December**",
 "Season-dependent",
 "Lift passes from **₩50,000**",
 "[visitkorea.or.kr](https://english.visitkorea.or.kr) · [daegu.go.kr](https://www.daegu.go.kr)",
 "**Probably just outside your Nov 22 window** — check resort sites in early November if you're hoping for snow."),

("🚌","Daegu Intercity Bus & Regional Day Trips","🔁 daily",
 "Daegu is within an hour of Gyeongju, Andong, Pohang and Gimcheon by bus or train — the best base for the northern Yeongnam region",
 "Roughly **06:00–22:00**",
 "Gyeongju **₩6,500**; Andong ₩9,000",
 "[kobus.co.kr](https://www.kobus.co.kr) · [txbus.t-money.co.kr](https://txbus.t-money.co.kr)",
 "Dongdaegu and Seobu terminals. **Andong (Hahoe Village, UNESCO) is 1 h 30 and makes an excellent day trip.**"),

("🏘️","Andong Hahoe Folk Village day trip — UNESCO (하회마을)","🔁 daily",
 "The most famous **UNESCO-listed** Korean clan village, on a river bend north of Daegu — with the Hahoe mask dance performed on weekends",
 "Daily **09:00–18:00** (Nov: to 17:00); mask dance typically **14:00** weekends",
 "Adult **₩5,000**",
 "[UNESCO](https://whc.unesco.org/en/list/1324) · [andong.go.kr](https://www.andong.go.kr)",
 "Bus Daegu → Andong (1 h 30), then local bus 246. **Check the mask dance schedule** — it's the highlight and it isn't daily in November."),

("📚","Byeongsan Seowon, Andong — UNESCO day trip (병산서원)","🔁 daily (FREE)",
 "Widely considered **the most beautiful of the nine UNESCO Korean seowon** — a 1613 academy whose Mandaeru pavilion frames the cliff and river opposite",
 "Daily **09:00–18:00** (Nov: to 17:00)",
 "**FREE**",
 "[UNESCO](https://whc.unesco.org/en/list/1498) · [andong.go.kr](https://www.andong.go.kr)",
 "Near Hahoe Village — combine the two. The view from the Mandaeru floor is the single best piece of Confucian architecture in Korea."),

("🍗","Andong Jjimdak & Regional Food day trip","🔁 daily",
 "Andong's braised soy-sauce chicken, invented in its old market in the 1980s and now sold nationwide — plus salted mackerel and Andong soju",
 "Most **11:00–21:00**",
 "Jjimdak for 2–3 people **₩35,000–₩45,000**",
 "[andong.go.kr](https://www.andong.go.kr)",
 "Andong Jjimdak Alley in the old market. Combine with Hahoe Village on the same day trip from Daegu."),

("🏛️","Gimcheon, Gumi & Nakdong Valley day trips","🔁 daily",
 "The Nakdong valley towns north of Daegu — Gimcheon's Jikjisa temple and Gumi's Geumosan provincial park, both under an hour away",
 "Temples roughly **08:00–18:00**",
 "Jikjisa **₩3,000**",
 "[jikjisa.or.kr](https://www.jikjisa.or.kr) · [gimcheon.go.kr](https://www.gimcheon.go.kr)",
 "Train or bus from Daegu. Jikjisa's approach avenue is a well-known autumn foliage walk."),

("🧭","Daegu Tourist Information & Discount Passes","🔁 daily (FREE)",
 "Staffed information centres at Dongdaegu Station, the airport and Dongseongno, with free maps, English help and discount coupon booklets",
 "Roughly **09:00–18:00**",
 "**FREE**",
 "[daegu.go.kr](https://www.daegu.go.kr) · [visitkorea.or.kr](https://english.visitkorea.or.kr)",
 "Pick up the Modern Alley map and the Daegu Ten Foods guide — both free and genuinely useful."),

("♿","Daegu Barrier-Free Access & Senior Discounts","🔁 daily",
 "Daegu's metro is fully lift-accessible, and most municipal museums and parks are free or discounted for seniors and visitors with disabilities",
 "Facility hours",
 "Many **FREE**",
 "[daegu.go.kr](https://www.daegu.go.kr) · [dtro.or.kr](https://www.dtro.or.kr)",
 "Line 3 monorail stations all have lifts. The city publishes a barrier-free tourism map."),

("🌙","Daegu Night Views — 83 Tower, Apsan, Suseong Lake","🔁 nightly",
 "Daegu's three classic night viewpoints, all reachable in an evening: 83 Tower, the Apsan cable-car observatory and Suseong Lake's lit promenade",
 "Roughly **17:30–22:00** in November",
 "Suseong Lake **FREE**; towers ₩10,000–₩12,000",
 "[eworld.kr](https://www.eworld.kr) · [daegu.go.kr](https://www.daegu.go.kr)",
 "**Sunset is around 17:25 in November** — an early blue hour means you can do two of the three in one evening."),

("🥘","Daegu Muntier Noodles & Jjiga-galbi Specialities","🔁 daily",
 "Two more of Daegu's ten designated dishes — cold *nurungji-guksu* wheat noodles, and **Dongin-dong jjigalbi**, braised short ribs served in a brass bowl",
 "Most **11:00–22:00**",
 "Jjigalbi **₩20,000–₩30,000** per person",
 "[daegu.go.kr](https://www.daegu.go.kr)",
 "The Dongin-dong jjigalbi street near Gukchaebosang Park has a dozen specialists side by side."),

("🎓","Kyungpook National University Campus & Autumn Ginkgo","🔁 daily (FREE)",
 "One of Korea's major national universities, with an open campus, a free museum and a **ginkgo avenue that is a local November landmark**",
 "Campus always open; museum weekdays **09:00–18:00**",
 "**FREE**",
 "[knu.ac.kr](https://www.knu.ac.kr)",
 "Daegu Line 1 Sincheon Station + bus. Cheap student cafeterias are open to visitors."),

("🎡","Daegu Suseong Land & Family Amusement Options","🔁 daily",
 "The small lakeside amusement park at Suseong, plus the family attractions at Sparkland — modest, cheap and convenient",
 "Roughly **10:00–20:00**",
 "Rides **₩5,000–₩8,000** each",
 "[Suseong-gu](https://www.suseong.kr) · [daegu.go.kr](https://www.daegu.go.kr)",
 "Daegu Line 3 Suseongmot Station. Combine with the lake walk and the fountain show."),
]

append("/home/user/KoreaFun/daegu.md", E, 190, 3,
       "\n---\n\n## 🧭 Beginner-friendly essentials", "Daegu",
       intro="**Second expansion batch** — Palgongsan depth, Andong UNESCO day trips, Confucian and industrial heritage, night views and practical services.")
