# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "/home/user/KoreaFun/.build")
from addlib import append

E = [
# --- Daejeon science ---
("🔬","National Science Museum of Korea (국립중앙과학관)","🔁 Tue–Sun (FREE)",
 "Korea's national science museum in Daedeok Science Town — permanent halls on natural history, technology and space, plus a planetarium and an outdoor rocket park",
 "Tue–Sun **09:30–17:50** (closed Mondays)",
 "Permanent halls **FREE**; planetarium ₩2,000; special exhibitions extra",
 "[science.go.kr](https://www.science.go.kr)",
 "Bus from Daejeon Station (~30 min). Free entry to the main halls makes this the single best-value day in Daejeon."),

("🚀","National Science Museum Planetarium & Astronomy Hall","🔁 Tue–Sun",
 "The museum's dome theatre and astronomical observatory, with public star-viewing nights on clear evenings",
 "Shows Tue–Sun, several daily; night observation typically **19:00–21:00** on scheduled evenings",
 "Planetarium **₩2,000**; night observation FREE with reservation",
 "[science.go.kr](https://www.science.go.kr)",
 "Reserve night observation sessions online — they fill up and are cancelled if it's cloudy."),

("🧪","Daedeok Innopolis Research Campus Walk (대덕연구개발특구)","🔁 daily (FREE)",
 "Korea's national research cluster — 40+ government institutes including KAIST, the Institute for Basic Science and the nuclear research institute, in a green campus district",
 "Streets always open; institute museums vary",
 "**FREE** to walk",
 "[innopolis.or.kr](https://www.innopolis.or.kr) · [daejeon.go.kr](https://www.daejeon.go.kr)",
 "This is why Daejeon is called Korea's science city. Several institutes run free public exhibition halls — check individually."),

("🎓","KAIST Campus & Bridge of Wisdom (카이스트)","🔁 daily (FREE)",
 "Korea's top science and engineering university — an open campus with the duck pond, the sculpture walk and the distinctive KI building",
 "Always open",
 "**FREE**",
 "[kaist.ac.kr](https://www.kaist.ac.kr)",
 "Bus from Yuseong. **Peak foliage around the duck pond is early-to-mid November.** Cafeterias are open to visitors and very cheap."),

("💰","Korea Minting & Security Printing Currency Museum (화폐박물관)","🔁 Tue–Sun (FREE)",
 "Korea's official mint museum — the history of Korean money from Goryeo coins to modern banknotes, plus counterfeiting-prevention technology",
 "Tue–Sun **10:00–17:00** (closed Mondays)",
 "**FREE**",
 "[komsco.com](https://www.komsco.com)",
 "In Daedeok Science Town. You can buy commemorative medal strikes in the shop — a genuinely unusual souvenir."),

("🌍","Geological Museum, KIGAM (지질박물관)","🔁 Tue–Sun (FREE)",
 "The national geology museum — dinosaur skeletons, a large mineral collection and Korean plate tectonics, run by the state geoscience institute",
 "Tue–Sun **10:00–17:00** (closed Mondays)",
 "**FREE**",
 "[museum.kigam.re.kr](https://museum.kigam.re.kr)",
 "In Daedeok Innopolis, near the science museum. Free, small and excellent for children."),

("🛰️","Korea Aerospace Research Institute Exhibition Hall (항공우주연구원)","🔁 weekdays (FREE)",
 "KARI's public exhibition hall — the Nuri (KSLV-II) launch vehicle programme, Korean satellites and lunar orbiter models",
 "Weekdays, by advance reservation",
 "**FREE**",
 "[kari.re.kr](https://www.kari.re.kr)",
 "**Reservation required** through the KARI site — it's a working research institute, not a walk-in museum."),

("⚛️","Korea Atomic Energy Research Institute Public Hall","🔁 weekdays (FREE)",
 "The public exhibition hall of Korea's nuclear research institute, covering reactor technology and radiation science",
 "Weekdays by reservation",
 "**FREE**",
 "[kaeri.re.kr](https://www.kaeri.re.kr)",
 "Reservation required. Of interest if you want to understand how Korea became a nuclear-reactor exporter."),

("🌐","Expo Science Park & Hanbit Tower (엑스포과학공원·한빛탑)","🔁 daily (FREE)",
 "The site of the **1993 Daejeon Expo**, still the city's landmark — the 93 m Hanbit Tower observatory, the Expo Bridge and the riverside plaza",
 "Park always open; tower observatory roughly **10:00–18:00**",
 "Park **FREE**; observatory FREE",
 "[daejeon.go.kr](https://www.daejeon.go.kr)",
 "Daejeon Line 1 Government Complex Station + bus. **The Expo Bridge is lit at night** and the tower view over the Gapcheon is free."),

("🎡","Daejeon Sky Road & Expo Bridge Night Lighting","🔁 nightly (FREE)",
 "The Expo Bridge and Hanbit Tower are illuminated after dark, and the Gapcheon riverside path connects them into an easy night walk",
 "Lighting roughly **sunset–23:00**",
 "**FREE**",
 "[daejeon.go.kr](https://www.daejeon.go.kr)",
 "Combine with Sungsimdang for the classic Daejeon evening. The riverside path is flat, lit and safe."),

# --- Daejeon culture ---
("🖼️","Daejeon Museum of Art (대전시립미술관)","🔁 Tue–Sun",
 "The city's main contemporary art museum, next to the Expo park — strong on media art, reflecting the science-city identity",
 "Tue–Sun **10:00–18:00** (closed Mondays)",
 "Adult **₩1,000**; often free for special city programmes",
 "[dma.daejeon.go.kr](https://dma.daejeon.go.kr)",
 "Daejeon Line 1 Government Complex Station. ₩1,000 for a full municipal art museum is close to free."),

("🖌️","Lee Ungno Museum (이응노미술관)","🔁 Tue–Sun",
 "A museum dedicated to **Lee Ungno (1904–89)**, the Korean ink painter who reinvented calligraphy as abstract art in Paris — in a building by Laurent Beaudouin",
 "Tue–Sun **10:00–18:00** (closed Mondays)",
 "Adult **₩500**",
 "[leeungnomuseum.or.kr](https://www.leeungnomuseum.or.kr)",
 "Next to the Museum of Art. One of the best single-artist museums in Korea, and it costs ₩500."),

("🏛️","Daejeon Museum of History (대전시립박물관)","🔁 Tue–Sun (FREE)",
 "The city history museum — Daejeon from Baekje-era settlement to railway town to planned science capital",
 "Tue–Sun **09:00–18:00** (closed Mondays)",
 "**FREE**",
 "[museum.daejeon.go.kr](https://museum.daejeon.go.kr)",
 "In Yuseong-gu. Daejeon barely existed before the railway arrived in 1905 — this explains the whole city."),

("🏺","Daejeon Sunsa Archaeological Museum & Dunsan Prehistoric Site","🔁 Tue–Sun (FREE)",
 "A Palaeolithic and Neolithic site preserved in the middle of the Dunsan new town, with an on-site museum",
 "Tue–Sun **09:00–18:00** (closed Mondays)",
 "**FREE**",
 "[daejeon.go.kr](https://www.daejeon.go.kr)",
 "Daejeon Line 1 Government Complex Station. A 12,000-year-old site surrounded by apartment blocks — an odd and good half hour."),

("🎭","Daejeon Arts Center (대전예술의전당)","🔁 by event",
 "Daejeon's flagship performing arts complex — home of the **Daejeon Philharmonic Orchestra** and a full autumn opera, ballet and concert season",
 "Box office **09:00–20:00**; performances usually **19:30**",
 "**₩10,000–₩70,000**",
 "[djac.or.kr](https://www.djac.or.kr) · [dpo.or.kr](https://www.dpo.or.kr)",
 "Daejeon Line 1 Government Complex Station. **Check the November calendar in October** — the season is busy and tickets are far cheaper than Seoul."),

("🎻","Daejeon Philharmonic Orchestra — November concerts","👀 WATCH",
 "One of Korea's leading regional orchestras, with monthly subscription concerts at the Daejeon Arts Center",
 "Typically Friday **19:30**",
 "**₩10,000–₩50,000**",
 "[dpo.or.kr](https://www.dpo.or.kr)",
 "November programme published on the orchestra site. Student and same-day discounts are common."),

("🎪","Daejeon Yesulga's House & Daejeon Culture & Arts Complex","🔁 Tue–Sun (FREE)",
 "The city's arts complex next to the Arts Center, with free galleries, an artists' studio building and a small theatre",
 "Tue–Sun **10:00–18:00** (closed Mondays)",
 "Mostly **FREE**",
 "[dcac.or.kr](https://www.dcac.or.kr) · [daejeon.go.kr](https://www.daejeon.go.kr)",
 "In the Dunsan cultural cluster — the art museum, Lee Ungno museum, arts centre and this are all within a 10-minute walk."),

("📚","Daejeon Hanbat Library & Book Street","🔁 Tue–Sun (FREE)",
 "The city's main library plus the Eunhaeng-dong secondhand book street, a survivor of the old downtown",
 "Library Tue–Sun **09:00–20:00**",
 "**FREE**",
 "[hbl.daejeon.go.kr](https://hbl.daejeon.go.kr) · [daejeon.go.kr](https://www.daejeon.go.kr)",
 "Daejeon Line 1 Jungangno Station for the book street. A quiet rainy-day option in the old centre."),

# --- Daejeon nature ---
("🌳","Hanbat Arboretum (한밭수목원)","🔁 Tue–Sun (FREE)",
 "**Korea's largest inner-city artificial arboretum** — east and west gardens either side of the Expo park, with 1,700+ species and a tropical greenhouse",
 "Tue–Sun **09:00–18:00** (Nov; closed Mondays)",
 "**FREE**",
 "[daejeon.go.kr](https://www.daejeon.go.kr)",
 "Daejeon Line 1 Government Complex Station. Free, huge, and **peak foliage is the first half of November**."),

("🍁","Gyejoksan Red Clay Barefoot Trail (계족산 황톳길)","🔁 daily (FREE)",
 "A 14.5 km mountain ridge trail surfaced with **soft red clay for barefoot walking** — Daejeon's most distinctive attraction, and free",
 "Always open; best in daylight",
 "**FREE**; foot-wash stations provided",
 "[daejeon.go.kr](https://www.daejeon.go.kr) · [Daedeok-gu](https://www.daedeok.go.kr)",
 "Bus to Jangdong. **November clay is cold** — most people do a shorter barefoot stretch and wear shoes for the rest. Bring a towel."),

("⛰️","Bomunsan Mountain & Observatory (보문산)","🔁 daily (FREE)",
 "The wooded 457 m mountain on Daejeon's southern edge with an observation tower, a sculpture park and easy family trails",
 "Always open",
 "**FREE**",
 "[daejeon.go.kr](https://www.daejeon.go.kr) · [Jung-gu Daejeon](https://www.djjunggu.go.kr)",
 "Bus from Daejeon Station. An hour up for the full city panorama; autumn colour peaks early November."),

("🏞️","Daecheong Lake & Daecheongho Osolgil Trail (대청호 오솔길)","🔁 daily (FREE)",
 "Korea's third-largest reservoir, on Daejeon's eastern edge — a network of lakeside walking courses, plus the Daecheong Dam observation deck",
 "Always open",
 "**FREE**",
 "[daejeon.go.kr](https://www.daejeon.go.kr) · [K-water](https://www.kwater.or.kr)",
 "Bus from Daejeon Station. **Autumn mist over the lake in the early morning is the reason to come.** Course 4 is the popular one."),

("🌲","Jangtaesan Recreational Forest (장태산자연휴양림)","🔁 daily",
 "Korea's best **metasequoia** forest — a canopy skywalk 20 m up through the redwoods, spectacular when the needles turn rust-orange in November",
 "Daily **09:00–18:00** (Nov)",
 "Adult **₩2,000**; parking ₩3,000",
 "[daejeon.go.kr](https://www.daejeon.go.kr)",
 "Bus 22 from Daejeon Station (~50 min). **Metasequoia colour peaks in early-to-mid November** — this is the single most photogenic thing near Daejeon in your window."),

("🦌","Daejeon O-World & Zooland (대전오월드)","🔁 daily",
 "The city's combined zoo, amusement park and flower garden on the slopes of Bomunsan",
 "Daily roughly **09:30–18:00** (Nov)",
 "Combined ticket adult **₩17,000**; zoo only ₩12,000",
 "[oworld.kr](https://www.oworld.kr)",
 "Bus from Daejeon Station. The seasonal **Light Festival typically runs from late autumn** — check the site for 2026 dates."),

("🌸","Ppuri Park & Korean Clan Origins (뿌리공원)","🔁 daily (FREE)",
 "A park of 240+ sculptures, one for each Korean family clan and its origin story — a genuinely unique idea, plus the Family Name Museum",
 "Park always open; museum Tue–Sun **09:00–18:00**",
 "**FREE**",
 "[daejeon.go.kr](https://www.daejeon.go.kr) · [Jung-gu Daejeon](https://www.djjunggu.go.kr)",
 "Bus from Daejeon Station. If you know any Korean's surname and clan seat, you can find their stone here."),

("🌊","Gapcheon Riverside Path & Autumn Reeds (갑천)","🔁 daily (FREE)",
 "The river running through central Daejeon — a flat cycling and walking corridor with reed beds, and the Expo Bridge at its centre",
 "Always open",
 "**FREE**; Tashu bike share from ₩1,000",
 "[daejeon.go.kr](https://www.daejeon.go.kr) · [Tashu bike share](https://www.tashu.or.kr)",
 "The reed beds around Wolpyeong are at their best in November. Tashu public bikes are the easy way to do the whole length."),

("♨️","Yuseong Hot Springs & Foot Bath Park (유성온천)","🔁 daily (FREE foot bath)",
 "Korea's best-known alkaline hot-spring district, in use for over 600 years — with a **free public outdoor foot bath** in the town centre",
 "Foot bath daily roughly **09:00–18:00**; bathhouses vary",
 "Foot bath **FREE**; bathhouse entry ₩8,000–₩15,000",
 "[daejeon.go.kr](https://www.daejeon.go.kr) · [Yuseong-gu](https://www.yuseong.go.kr)",
 "Daejeon Line 1 Yuseong Spa Station. **A free hot foot bath on a cold November afternoon** is one of the best things in this file."),

("⛰️","Gyeryongsan National Park — Donghaksa & Gapsa (계룡산국립공원)","🔁 daily",
 "One of Korea's most sacred mountains, straddling Daejeon and Gongju — with the historic nun temple **Donghaksa** and the ancient **Gapsa**",
 "Park always open; temples roughly **08:00–18:00**",
 "Park **FREE**; temple entry ~₩3,000",
 "[knps.or.kr](https://www.knps.or.kr) · [Korea National Park Service](https://english.knps.or.kr)",
 "Bus 107 from Yuseong to Donghaksa. **The Donghaksa valley is one of the top autumn-foliage walks in central Korea**, peaking late October to early November."),

("🧘","Gapsa Temple & Templestay, Gyeryongsan (갑사)","🔁 daily",
 "A 5th-century temple on the western slope of Gyeryongsan, reached through a famous maple-lined approach path — with an English templestay programme",
 "Daily **08:00–18:00**",
 "Entry **₩3,000**; templestay from ₩70,000",
 "[templestay.com](https://www.templestay.com) · [knps.or.kr](https://www.knps.or.kr)",
 "The Gapsa approach road in autumn colour is a national classic. Book templestay in advance online."),

# --- Daejeon food & city life ---
("🥐","Sungsimdang Main Bakery & Twigim Soboro (성심당)","🔁 daily",
 "Korea's most famous regional bakery, founded 1956 — the fried *twigim soboro* bun and the chive bread are national institutions, and the queues are real",
 "Daily roughly **08:00–22:00**",
 "Breads **₩2,000–₩5,000**",
 "[sungsimdang.co.kr](https://www.sungsimdang.co.kr)",
 "Daejeon Line 1 Jungangno Station Exit 3. **Sungsimdang only sells in Daejeon** — that's the whole point. Expect a 20-minute queue at weekends."),

("🍜","Daejeon Kalguksu — the city's official dish (대전 칼국수)","🔁 daily",
 "Daejeon designates itself Korea's **kalguksu capital**; the city publishes a list of designated noodle houses, several running for 50+ years",
 "Most **10:00–21:00**",
 "A bowl **₩7,000–₩10,000**",
 "[daejeon.go.kr](https://www.daejeon.go.kr)",
 "The city tourism site lists the designated shops. A hot bowl of hand-cut noodles is the correct November lunch."),

("🍖","Daejeon Dujeong-dong & Jungang Market Food Alleys","🔁 daily",
 "Daejeon's traditional market complex near the station — the largest in Chungcheong, with a food alley, a fabric market and a herbal medicine street",
 "Roughly **08:00–20:00**",
 "**FREE** to browse; meals ₩7,000–₩12,000",
 "[daejeon.go.kr](https://www.daejeon.go.kr) · [Dong-gu Daejeon](https://www.donggu.go.kr)",
 "Walkable from Daejeon Station. Much less touristed than Seoul's markets and correspondingly cheaper."),

("🍢","Daejeon Eunhaeng-dong & Sky Road Downtown","🔁 daily (FREE)",
 "The old downtown pedestrian district, roofed with a 214 m **LED media canopy** that runs light shows over the street after dark",
 "Shows roughly **18:00–22:00**",
 "**FREE**",
 "[daejeon.go.kr](https://www.daejeon.go.kr) · [Jung-gu Daejeon](https://www.djjunggu.go.kr)",
 "Daejeon Line 1 Jungangno Station. Sungsimdang is at one end — do the bakery, then the light canopy."),

("🚉","Daejeon Station Food Court & Hodugwaja Platform Culture","🔁 daily",
 "Daejeon Station is the KTX midpoint of Korea, and its platform snack culture — walnut cakes, kalguksu, Sungsimdang outlet — is a travel tradition",
 "Roughly **06:00–23:00**",
 "Snacks **₩3,000–₩8,000**",
 "[letskorail.com](https://www.letskorail.com)",
 "**Seoul → Daejeon KTX is about 1 hour.** Daejeon is the easiest day trip from Seoul in this whole guide."),

("☕","Daejeon Daeheung-dong & Cafe Districts","🔁 daily",
 "The university-adjacent cafe and independent-shop districts around Daeheung-dong and Bongmyeong-dong",
 "Most **11:00–23:00**",
 "Coffee **₩4,500–₩7,000**",
 "[daejeon.go.kr](https://www.daejeon.go.kr)",
 "Daejeon Line 1 Jung-gu Office Station. Cheaper and calmer than the Seoul equivalents."),

# --- Daejeon sport ---
("⚽","K League 1 — Daejeon Hana Citizen (대전하나시티즌)","👀 WATCH — season ending",
 "Daejeon's top-flight football club at the Daejeon World Cup Stadium (Purple Arena), one of the 2002 World Cup venues. **The season ends in late November**",
 "Kick-off typically **14:00/16:00** at weekends",
 "Tickets **₩12,000–₩30,000**",
 "[daejeonhana.com](https://www.daejeonhana.com) · [kleague.com](https://www.kleague.com)",
 "Daejeon Line 1 World Cup Stadium Station. Final-round fixtures are set only weeks ahead — check kleague.com in late October."),

("⚾","Daejeon Hanwha Life Ballpark (한화생명볼파크)","👀 WATCH — off-season",
 "The Hanwha Eagles' brand-new 2025 stadium. **The KBO season ends in October**, so November is off-season, but stadium tours and events may run",
 "By event",
 "Tours when scheduled",
 "[hanwhaeagles.co.kr](https://www.hanwhaeagles.co.kr) · [koreabaseball.com](https://www.koreabaseball.com)",
 "Daejeon Line 1 Jung-gu Office Station + bus. Worth checking for off-season open days if you're a baseball fan."),

("🎮","Daejeon Esports Arena (대전 e스포츠경기장)","🔁 by event",
 "A dedicated municipal esports stadium in Dongseo-daero — Korea takes competitive gaming seriously enough to build public arenas for it",
 "By event; typically evenings and weekends",
 "Many events **FREE** to attend",
 "[daejeon.go.kr](https://www.daejeon.go.kr)",
 "Check the schedule ahead. Free entry to many amateur and semi-pro events."),

("🏊","Daejeon Public Sports Facilities & Ice Rink","🔁 daily",
 "The city's municipal sports centres — cheap public swimming, skating and gym sessions across the districts",
 "Roughly **06:00–21:00**",
 "**₩3,000–₩6,000** per session",
 "[daejeon.go.kr](https://www.daejeon.go.kr)",
 "Bring a swim cap. Useful as a rainy-day option."),

# --- Cheonan / Asan ---
("🇰🇷","Independence Hall of Korea (독립기념관)","🔁 Tue–Sun (FREE)",
 "Korea's **national museum of the independence movement** against Japanese colonial rule — seven vast exhibition halls, a Grand Hall of the Nation and a monumental plaza",
 "Tue–Sun **09:30–18:00** (Nov: to 17:00; closed Mondays)",
 "**FREE**; parking ₩4,000",
 "[i815.or.kr](https://www.i815.or.kr)",
 "Bus 400 from Cheonan Station (~30 min). **Free, enormous, and the single most important historical site in Chungcheong.** Allow at least 3 hours."),

("🍁","Independence Hall Maple Avenue & Danpung Trail","✅ CONFIRMED — Nov peak",
 "The 3 km maple-lined approach avenue at the Independence Hall — one of the best and least-known foliage walks in Korea, peaking in early November",
 "Tue–Sun **09:30–17:00** (closed Mondays)",
 "**FREE**",
 "[i815.or.kr](https://www.i815.or.kr)",
 "The avenue alone is worth the trip. **Peak colour is roughly Nov 1–10** — perfectly timed for the start of the trip window."),

("🥜","Cheonan Hodu-gwaja (Walnut Cake) Origin Shops (천안 호두과자)","🔁 daily",
 "The walnut-shaped red-bean cake was invented in Cheonan in 1934 and is now sold at every Korean rest stop — the original shops are still here",
 "Roughly **08:00–21:00**",
 "A box of 10 **₩6,000–₩10,000**",
 "[cheonan.go.kr](https://www.cheonan.go.kr)",
 "At Cheonan Station and along the old highway. Eat them warm — completely different from the rest-stop version."),

("🍲","Byeongcheon Sundae Street (병천순대거리)","🔁 daily",
 "Korea's most famous *sundae* (blood sausage) town — a street of specialist restaurants serving Byeongcheon-style sundae and sundae-gukbap",
 "Most **09:00–21:00**",
 "Sundae-gukbap **₩9,000–₩12,000**",
 "[cheonan.go.kr](https://www.cheonan.go.kr)",
 "Bus from Cheonan Station (~40 min). Byeongcheon sundae is thin-skinned and vegetable-heavy — the benchmark version of the dish."),

("🛕","Gakwonsa Temple & Great Bronze Buddha (각원사)","🔁 daily (FREE)",
 "A 15 m, 60-tonne seated bronze Buddha on the slope of Taejosan — one of the largest in East Asia, reached up 203 steps",
 "Always open",
 "**FREE**",
 "[cheonan.go.kr](https://www.cheonan.go.kr)",
 "Bus from Cheonan Station. Built in 1977 as a prayer for reunification. The view back over Cheonan from the top is excellent."),

("🖼️","Arario Museum & Arario Gallery Cheonan (아라리오)","🔁 Tue–Sun",
 "Cheonan's internationally known contemporary art complex at the bus terminal — with major outdoor sculptures by Damien Hirst, Keith Haring and Arman on the public plaza",
 "Gallery Tue–Sun **11:00–19:00** (closed Mondays); plaza always open",
 "Plaza sculptures **FREE**; gallery from ₩5,000",
 "[arariogallery.com](https://www.arariogallery.com)",
 "At Cheonan Bus Terminal — you can see world-class sculpture for free while waiting for a bus, which is a very Cheonan thing."),

("🏛️","Cheonan Museum & Cheonan City Hall Sky Lounge","🔁 Tue–Sun (FREE)",
 "The city museum, plus the free 47th-floor observatory in the Cheonan city hall tower with a panorama over the Chungcheong plain",
 "Both Tue–Sun **09:00–18:00** (closed Mondays)",
 "**FREE**",
 "[cheonan.go.kr](https://www.cheonan.go.kr)",
 "The sky lounge is genuinely free and almost empty. Best on a clear November morning."),

("✉️","Postal Museum of Korea (우정박물관)","🔁 Tue–Sun (FREE)",
 "Korea's national postal museum, at the Korea National Information Society Agency campus in Cheonan — stamps, mail history and telecommunications",
 "Tue–Sun **09:00–18:00** (closed Mondays)",
 "**FREE**",
 "[postmuseum.go.kr](https://www.postmuseum.go.kr)",
 "Bus from Cheonan Station. Small, free, and a good stop if you're already at Independence Hall."),

("🌳","Taejosan Country Park & Cheonan Foliage (태조산공원)","🔁 daily (FREE)",
 "Cheonan's main city park on Taejosan, with forest trails, a cable-free ridge walk and the Cheonan Bell of Unity",
 "Always open",
 "**FREE**",
 "[cheonan.go.kr](https://www.cheonan.go.kr)",
 "Bus from Cheonan Station. Combine with Gakwonsa — they're on the same mountain."),

("🚉","Cheonan-Asan KTX & Suseo High Speed Rail Access","🔁 daily",
 "Cheonan-Asan is the first KTX stop south of Seoul — **34 minutes from Seoul Station** — making the whole Cheonan/Asan area a viable half-day trip",
 "Trains roughly **05:30–23:00**",
 "KTX Seoul→Cheonan-Asan from **₩14,100**",
 "[letskorail.com](https://www.letskorail.com) · [srail.co.kr](https://www.srail.co.kr)",
 "SRT from Suseo is often cheaper. Local Line 1 also runs to Cheonan but takes about 90 minutes."),

("🏯","Oeam Folk Village, Asan (외암민속마을)","🔁 daily",
 "A **living** Joseon-era village of 60+ thatched and tiled houses with the original stone walls — nationally designated as a Folklore Cultural Heritage, and still inhabited",
 "Daily **09:00–18:00** (Nov: to 17:00)",
 "Adult **₩2,000**",
 "[oeam.co.kr](https://www.oeam.co.kr) · [asan.go.kr](https://www.asan.go.kr)",
 "Bus from Onyang Oncheon Station. **Quieter and more authentic than Jeonju Hanok Village** — people actually live and farm here."),

("🗡️","Hyeonchungsa Shrine, Asan (현충사)","🔁 Tue–Sun (FREE)",
 "The national shrine to **Admiral Yi Sun-sin**, Korea's greatest naval commander, on the estate where he grew up — with his family home, an archery field and a museum",
 "Tue–Sun **09:00–18:00** (Nov: to 17:00; closed Mondays)",
 "**FREE**",
 "[hcs.khs.go.kr](https://hcs.khs.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "Bus from Onyang Oncheon Station. Free, beautifully landscaped, and **the grounds are outstanding in November colour**."),

("♨️","Onyang Hot Springs, Asan (온양온천)","🔁 daily",
 "**Korea's oldest recorded hot spring**, used by Joseon kings for over 600 years — public bathhouses and a free foot bath in the town centre",
 "Bathhouses roughly **05:00–20:00**",
 "Bathhouse **₩8,000–₩12,000**; foot bath FREE",
 "[asan.go.kr](https://www.asan.go.kr)",
 "Line 1 / Janghang Line Onyang Oncheon Station. King Sejong came here for his eye condition — the tradition is documented back to 1441."),

("💦","Asan Spavis & Paradise Spa Dogo","🔁 daily",
 "Large hot-spring water parks in the Asan spa belt — indoor and outdoor thermal pools, open through winter",
 "Roughly **09:00–19:00**",
 "Day ticket **₩25,000–₩40,000**",
 "[spavis.co.kr](https://www.spavis.co.kr) · [asan.go.kr](https://www.asan.go.kr)",
 "Outdoor hot pools in November air are the reason to go. Bring your own towel or pay for rental."),

("🌊","Sapgyoho Tourist Area & Asan Bay Sunset","🔁 daily (FREE)",
 "The estuary lake and sea-wall park on Asan Bay — a sculpture park, a security museum with a decommissioned aircraft, and a wide west-coast sunset",
 "Always open",
 "**FREE**",
 "[asan.go.kr](https://www.asan.go.kr)",
 "Bus from Onyang. **Sunset around 17:20 in November** over the bay — cold, wide and empty."),

("🌾","Gongju — Gongsanseong Fortress, UNESCO Baekje (공산성)","🔁 daily",
 "The hilltop Baekje royal fortress at Gongju, part of the **UNESCO Baekje Historic Areas** — a 2.6 km rampart walk above the Geum River",
 "Daily **09:00–18:00** (Nov: to 17:00)",
 "Adult **₩1,200**",
 "[UNESCO](https://whc.unesco.org/en/list/1477) · [gongju.go.kr](https://www.gongju.go.kr)",
 "Bus from Daejeon (~50 min). The rampart circuit takes about an hour and the river view is excellent in autumn."),

("👑","Gongju — Tomb of King Muryeong & Songsan-ri Tombs","🔁 Tue–Sun",
 "The **only Baekje royal tomb ever found intact** (discovered 1971), with its 4,600 grave goods — part of the UNESCO Baekje listing, next to the national museum",
 "Tue–Sun **09:00–18:00** (closed Mondays)",
 "Adult **₩1,500**",
 "[UNESCO](https://whc.unesco.org/en/list/1477) · [gongju.museum.go.kr](https://gongju.museum.go.kr)",
 "The tomb itself is sealed; you view a full-scale replica, and the real gold crown ornaments are in the free national museum next door."),

("🏛️","Gongju National Museum (국립공주박물관)","🔁 Tue–Sun (FREE)",
 "Home of the **King Muryeong tomb treasures** — the gold crown ornaments, the stone guardian animal and the epitaph tablets that dated the tomb exactly",
 "Tue–Sun **09:00–18:00** (closed Mondays)",
 "**FREE**",
 "[gongju.museum.go.kr](https://gongju.museum.go.kr)",
 "Next to the tombs. National-treasure-grade Baekje gold, free, an hour from Daejeon."),

("🏯","Buyeo — Busosanseong & Baekje Historic Areas","🔁 daily",
 "The last Baekje capital — the Busosanseong fortress, the Nakhwaam cliff, Goransa temple and a boat on the Baengma River, all UNESCO-listed",
 "Daily **09:00–18:00** (Nov: to 17:00)",
 "Adult **₩2,000**; river boat ₩7,000",
 "[UNESCO](https://whc.unesco.org/en/list/1477) · [buyeo.go.kr](https://www.buyeo.go.kr)",
 "Bus from Daejeon (~1 h 20). The legend of the 3,000 court ladies leaping from Nakhwaam is Korea's most famous tragic story."),

("🏛️","Buyeo National Museum & Jeongnimsa Pagoda","🔁 Tue–Sun (FREE)",
 "The Baekje Gilt-bronze Incense Burner — **National Treasure No. 287 and arguably the finest object in Korean archaeology** — plus the 7th-century Jeongnimsa stone pagoda",
 "Museum Tue–Sun **09:00–18:00** (closed Mondays); pagoda site daily",
 "Museum **FREE**; Jeongnimsa site ₩1,500",
 "[buyeo.museum.go.kr](https://buyeo.museum.go.kr) · [UNESCO](https://whc.unesco.org/en/list/1477)",
 "The incense burner alone justifies the trip from Daejeon. Free entry."),
]

append("/home/user/KoreaFun/daejeon-cheonan.md", E, 81, 2,
       "\n---\n\n## 🧭 If you have one extra day — official picks", "Daejeon & Cheonan")
