# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "/home/user/KoreaFun/.build")
from addlib import append

E = [
("🏛️","Sejong City — Government Complex Rooftop Park (정부세종청사 옥상정원)","🔁 weekdays",
 "The world's **longest rooftop garden** (3.6 km) linking the buildings of Korea's administrative capital, open to the public by reservation",
 "Weekdays, guided sessions roughly **10:00–17:00**",
 "**FREE** with advance reservation",
 "[sejong.go.kr](https://www.sejong.go.kr) · [mois.go.kr](https://www.mois.go.kr)",
 "40 min by bus from Daejeon. **Reservation required** — apply online a few days ahead. A Guinness-record garden, free."),

("📖","Sejong National Library & Presidential Archives","🔁 Tue–Sun (FREE)",
 "The dramatic wave-roofed national library branch in Sejong, plus the Presidential Archives museum on Korea's post-1948 presidencies",
 "Tue–Sun **09:00–18:00** (closed Mondays)",
 "**FREE**",
 "[sejong.nl.go.kr](https://sejong.nl.go.kr) · [pa.go.kr](https://www.pa.go.kr)",
 "Bus from Daejeon or Osong KTX. Striking architecture and a free, serious archive museum."),

("🌾","Sejong Lake Park & Geumgang Reed Fields","🔁 daily (FREE)",
 "Korea's largest artificial lake park, with a floating stage, a 4.8 km loop and extensive Geum River reed beds that turn silver in November",
 "Always open",
 "**FREE**",
 "[sejong.go.kr](https://www.sejong.go.kr)",
 "Bus from Daejeon (~40 min). Flat, wide and good for cycling; bike hire on site."),

("🌉","Sejong Geumgang Bridges & Ihaseung Night Lighting","🔁 nightly (FREE)",
 "The Geum River bridges in Sejong — including the double-deck pedestrian **Ipo Bridge** — are lit after dark over the water",
 "Lighting roughly **sunset–23:00**",
 "**FREE**",
 "[sejong.go.kr](https://www.sejong.go.kr)",
 "The pedestrian deck below the road deck is a genuinely good night walk."),

("🌿","National Sejong Arboretum (국립세종수목원)","🔁 Tue–Sun",
 "Korea's first urban national arboretum — with a large glass conservatory containing Mediterranean and tropical zones, plus a Korean traditional garden",
 "Tue–Sun **09:00–18:00** (Nov: to 17:00; closed Mondays)",
 "Adult **₩5,000**",
 "[sjna.or.kr](https://www.sjna.or.kr)",
 "Bus from Daejeon. The glasshouse makes this a good bad-weather option; the traditional garden peaks in November colour."),

("🚄","Osong KTX Junction & Cheongju Access","🔁 daily",
 "Osong is where Korea's KTX network splits toward Busan and Gwangju — the gateway station for Cheongju and the Sejong area",
 "Trains roughly **05:30–23:00**",
 "Seoul→Osong KTX from **₩18,500**",
 "[letskorail.com](https://www.letskorail.com)",
 "Useful if you want to reach Sejong or Cheongju fast from Seoul without going via Daejeon."),

("🏛️","Cheongju Early Printing Museum & Jikji (청주고인쇄박물관)","🔁 Tue–Sun (FREE)",
 "The site of Heungdeoksa temple, where **Jikji — the world's oldest surviving book printed with movable metal type (1377)** — was made, 78 years before Gutenberg",
 "Tue–Sun **09:00–18:00** (closed Mondays)",
 "**FREE**",
 "[jikjiworld.cheongju.go.kr](https://jikjiworld.cheongju.go.kr) · [UNESCO Memory of the World](https://www.unesco.org)",
 "Bus from Cheongju or Osong. The original Jikji is in Paris, but this is where it was printed — a UNESCO Memory of the World item."),

("🎨","Cheongju Museum of Art & Culture Factory (청주시립미술관)","🔁 Tue–Sun (FREE)",
 "Cheongju's art museum plus the **Cultural Factory**, a former tobacco plant converted into a huge contemporary art and craft complex",
 "Tue–Sun **10:00–19:00** (closed Mondays)",
 "**FREE**",
 "[cmoa.cheongju.go.kr](https://cmoa.cheongju.go.kr) · [cheongju.go.kr](https://www.cheongju.go.kr)",
 "Cheongju is 40 min from Daejeon. The Culture Factory is one of Korea's better industrial-conversion art spaces."),

("🏯","Sangdangsanseong Fortress, Cheongju (상당산성)","🔁 daily (FREE)",
 "A 4.2 km Joseon mountain fortress wall above Cheongju — a complete circuit walk with gates, a reservoir and city views",
 "Always open",
 "**FREE**",
 "[cheongju.go.kr](https://www.cheongju.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "Bus from Cheongju. About two hours for the full wall circuit; the restaurants at the main gate do good country food."),

("🌳","Cheongnamdae Presidential Villa (청남대)","🔁 Tue–Sun",
 "The former **presidential summer retreat** on Daecheong Lake, secret until 2003 and now a public park — the residence, a presidential path and lake gardens",
 "Tue–Sun **09:00–18:00** (Nov: to 17:00; closed Mondays)",
 "Adult **₩5,000**",
 "[chnam.chungbuk.go.kr](https://chnam.chungbuk.go.kr)",
 "Shuttle bus from Cheongju — **private cars are not allowed in**, so you must use the official shuttle. Autumn colour on the lake is superb."),

("⛰️","Songnisan National Park & Beopjusa (속리산·법주사)","🔁 daily",
 "One of Korea's great mountain temples — **Beopjusa** holds a 33 m gilt-bronze Maitreya and Korea's only surviving five-storey wooden pagoda, a UNESCO Sansa site",
 "Park always open; temple **08:00–18:00**",
 "Temple entry **₩4,000**",
 "[knps.or.kr](https://www.knps.or.kr) · [UNESCO Sansa listing](https://whc.unesco.org/en/list/1562)",
 "Bus from Daejeon (~1 h 40). The Palsangjeon wooden pagoda (1626) is a National Treasure and the only one of its kind left in Korea."),

("🥾","Daejeon Dulle-gil Trail Network (대전둘레산길)","🔁 daily (FREE)",
 "A 133 km waymarked circuit of the mountains ringing Daejeon, in 12 numbered sections — the city's answer to the Seoul Dulle-gil",
 "Always open",
 "**FREE**",
 "[daejeon.go.kr](https://www.daejeon.go.kr)",
 "Section maps on the city site. Sections 2 and 3 (Bomunsan, Gyejoksan) are the most scenic in autumn."),

("🦇","Donggwangdong & Daejeon Traditional Herbal Medicine Market","🔁 daily",
 "The herbal medicine street near Daejeon Station — dried roots, ginseng, deer antler and traditional pharmacies, with the smell to match",
 "Roughly **09:00–19:00** (many closed Sundays)",
 "**FREE** to browse",
 "[daejeon.go.kr](https://www.daejeon.go.kr) · [Dong-gu Daejeon](https://www.donggu.go.kr)",
 "Walkable from Daejeon Station. A sensory experience even if you buy nothing."),

("🌌","Daejeon Sunset & Night View from Sikjangsan (식장산)","🔁 daily (FREE)",
 "Daejeon's highest peak (598 m) with a road almost to the top — the best night panorama of the city, popular with local drivers and photographers",
 "Always open",
 "**FREE**",
 "[daejeon.go.kr](https://www.daejeon.go.kr) · [Dong-gu Daejeon](https://www.donggu.go.kr)",
 "Taxi or car; limited bus service. There's a small cafe near the top open in the evening."),

("🕯️","Daejeon Winter Illumination & Sky Road Christmas","👀 WATCH (from mid-Nov)",
 "Daejeon's downtown Sky Road, Expo Bridge and O-World typically light up for the winter season **from mid-to-late November**",
 "Roughly **17:30–23:00** once lit",
 "Street lighting **FREE**; O-World light festival with park ticket",
 "[daejeon.go.kr](https://www.daejeon.go.kr) · [oworld.kr](https://www.oworld.kr)",
 "Switch-on dates announced in early November on the city site — check if you're visiting in the last week of the window."),

("🎪","Daejeon Convention Center (DCC) & Autumn Expos","🔁 by event",
 "Daejeon's convention centre next to the Expo park, hosting science, technology and consumer expos through the autumn",
 "By event; typically **10:00–18:00**",
 "Varies; many trade expos free with registration",
 "[dcc.or.kr](https://www.dcc.or.kr)",
 "**Check the November calendar in October** — Daejeon's expos skew scientific and are often free to enter."),

("🎨","Daejeon Sculpture Biennale & Public Art Trail","👀 WATCH (FREE)",
 "Daejeon's public art programme scatters sculpture through the Dunsan district, the Expo park and the Gapcheon riverside",
 "Always open",
 "**FREE**",
 "[dma.daejeon.go.kr](https://dma.daejeon.go.kr) · [daejeon.go.kr](https://www.daejeon.go.kr)",
 "A self-guided map is available from the city art museum. Free, and it makes a good excuse for a Dunsan walk."),

("🐟","Daecheongho Freshwater Fish & Chueotang Restaurants","🔁 daily",
 "The restaurants around Daecheong Lake specialising in freshwater fish — *maeuntang* spicy stew and *chueotang* loach soup, a Chungcheong speciality",
 "Most **11:00–20:00**",
 "A meal **₩12,000–₩20,000**",
 "[daejeon.go.kr](https://www.daejeon.go.kr)",
 "Combine with a Daecheongho Osolgil walk. Chueotang is a serious cold-weather dish."),

("🏨","Yuseong Spa Hotels & Overnight Onsen Stay","🔁 daily",
 "Yuseong's hot-spring hotels pipe thermal water directly into the rooms — an in-room hot spring bath after a cold day's walking",
 "Check-in typically **15:00**",
 "Rooms from **₩70,000–₩150,000**",
 "[daejeon.go.kr](https://www.daejeon.go.kr) · [Yuseong-gu](https://www.yuseong.go.kr)",
 "Daejeon Line 1 Yuseong Spa Station. Cheaper than equivalent Japanese onsen towns and 1 hour from Seoul by KTX."),

("🗺️","Daejeon City Tour Bus & Tourist Information","🔁 Tue–Sun",
 "The official city tour bus with themed science, history and night routes, plus staffed information centres at Daejeon Station and Yuseong",
 "Tue–Sun, departures roughly **09:30–17:00**",
 "Day pass **₩5,000–₩10,000**",
 "[daejeon.go.kr](https://www.daejeon.go.kr) · [daejeontour.co.kr](https://www.daejeontour.co.kr)",
 "Departs Daejeon Station. The science route reaches the Daedeok institutes that are awkward by public bus."),

("🚲","Tashu Public Bike Share, Daejeon (타슈)","🔁 daily",
 "Daejeon's public bike-share system, with stations across the city and the flat Gapcheon riverside as its natural route",
 "**24 h**",
 "First hour often **FREE**; day pass ~₩1,000",
 "[tashu.or.kr](https://www.tashu.or.kr)",
 "App registration needed; a foreign card sometimes fails, so try registering before you arrive."),

("🍁","Chungcheong Autumn Foliage — regional peak timing","✅ CONFIRMED — early-to-mid Nov",
 "Chungcheong's foliage peaks **roughly Nov 1–12**: Gyeryongsan and Songnisan first, then the Independence Hall avenue, Jangtaesan and the city parks",
 "Daylight hours",
 "**FREE** except park entries",
 "[Korea Forest Service](https://www.forest.go.kr) · [knps.or.kr](https://www.knps.or.kr)",
 "The Korea Forest Service publishes a national peak-foliage map each October — use it to sequence these in the first two weeks of the trip."),

("🎓","Cheonan University District — Dujeong-dong & Sinbu-dong","🔁 daily",
 "Cheonan hosts a dozen universities, and Dujeong-dong and Sinbu-dong are the resulting cheap-food and nightlife districts",
 "Most **11:00–02:00**",
 "Meals **₩7,000–₩12,000**",
 "[cheonan.go.kr](https://www.cheonan.go.kr)",
 "Walkable from Cheonan Bus Terminal. Very cheap, very young, and no tourists at all."),

("🏟️","Cheonan Sports Complex & Yu Gwan-sun Gymnasium","🔁 by event",
 "Cheonan's municipal sports complex, including an ice rink, a swimming pool and the gymnasium named after independence martyr **Yu Gwan-sun**",
 "Roughly **06:00–21:00**; events vary",
 "Public sessions **₩3,000–₩6,000**",
 "[cheonan.go.kr](https://www.cheonan.go.kr)",
 "Yu Gwan-sun, who led the 1919 Cheonan demonstrations at 16 and died in prison, is from here — her memorial hall is nearby."),

("🇰🇷","Yu Gwan-sun Memorial Hall & Aunae Market (유관순열사기념관)","🔁 Tue–Sun (FREE)",
 "The memorial hall at Yu Gwan-sun's birthplace beside Aunae Market, where she led the March 1st Movement demonstration of 1919",
 "Tue–Sun **09:00–18:00** (closed Mondays)",
 "**FREE**",
 "[cheonan.go.kr](https://www.cheonan.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "Bus from Cheonan, near Byeongcheon — combine with the sundae street, which is 5 minutes away."),

("🌊","Asan Gongseri Catholic Church & Martyrs' Shrine (공세리성당)","🔁 daily (FREE)",
 "A 1922 red-brick church on a wooded hill in Asan, on the site of a Joseon-era tax granary — regularly named one of Korea's most beautiful churches",
 "Grounds always open; church roughly **09:00–17:00**",
 "**FREE**",
 "[asan.go.kr](https://www.asan.go.kr)",
 "Bus from Onyang. **The 300-year-old zelkova trees on the grounds are exceptional in November colour** — a frequent film location."),

("🏞️","Asan Gokgyocheon Ecological Park & Sinjeongho Lake","🔁 daily (FREE)",
 "Asan's riverside ecological park and the lakeside path at Sinjeongho — quiet flat walking with reed beds and waterbirds",
 "Always open",
 "**FREE**",
 "[asan.go.kr](https://www.asan.go.kr)",
 "Near Onyang Oncheon Station. A calm hour before or after the hot springs."),

("🚂","Janghang Line Local Train & Chungcheong Rail Day Trip","🔁 daily",
 "The scenic local line running from Cheonan through Onyang, Asan and down the west coast to Iksan — slow, cheap and full of rural Korea",
 "Several services daily",
 "Fares from **₩3,000–₩10,000**",
 "[letskorail.com](https://www.letskorail.com)",
 "A Mugunghwa local train is the cheapest way to see the Chungcheong countryside. No reservation needed off-peak."),

("🛍️","Cheonan Shinbu-dong & Galleria / Yawoori Malls","🔁 daily",
 "Cheonan's department stores and shopping district around the terminal — including the Galleria Centercity by UNStudio",
 "Daily **10:30–20:00**",
 "**FREE** entry",
 "[cheonan.go.kr](https://www.cheonan.go.kr)",
 "The Galleria Centercity facade, by the Dutch firm UNStudio, is a genuine piece of architecture in an unlikely place."),

("🧭","Chungcheong Regional Tourist Passes & Bus Network","🔁 daily",
 "Intercity buses connect Daejeon, Sejong, Cheongju, Cheonan, Gongju and Buyeo cheaply and frequently — the practical spine for everything in this file",
 "Roughly **06:00–22:00**",
 "Intercity fares **₩3,000–₩8,000**",
 "[txbus.t-money.co.kr](https://txbus.t-money.co.kr) · [kobus.co.kr](https://www.kobus.co.kr)",
 "T-money works on local buses throughout Chungcheong. Book intercity buses on the apps above, or just turn up — they run every 20–30 minutes."),
]

append("/home/user/KoreaFun/daejeon-cheonan.md", E, 140, 2,
       "\n---\n\n## 🧭 If you have one extra day — official picks", "Daejeon & Cheonan",
       intro="**Second expansion batch** — Sejong, Cheongju, Gongju/Buyeo UNESCO Baekje day trips, Asan hot springs, trails and practical regional transport.")
