# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "/home/user/KoreaFun/.build")
from addlib import append

E = [
("🛕","Girimsa Temple (기림사)","🔁 daily",
 "A large, quiet temple founded in 643 in the Hamwolsan valley east of Gyeongju — five hall complexes, a 500-arhat hall and almost no visitors",
 "Daily **08:00–18:00** (Nov: to 17:00)",
 "Adult **₩3,000**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "Bus 100/150 toward Gampo. Bigger and older than most famous temples, with a fraction of the crowd."),

("🌊","Yongyeon Waterfall & Gyeongju Hamwolsan Valley","🔁 daily (FREE)",
 "The waterfall on the road to Girimsa where, in legend, King Sinmun received the magic flute *Manpasikjeok* that could calm all troubles",
 "Always open",
 "**FREE**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "On the bus 150 route. A short stop, but a good one, and the valley is beautiful in autumn."),

("🏯","Gyeongju Yangdong Village Seobaekdang & Hyangdan Houses","🔁 daily",
 "The two most important houses in UNESCO Yangdong — the 1454 **Seobaekdang** clan head house and the unusual H-plan **Hyangdan**, both National Treasures or Treasures",
 "Daily **09:00–18:00** (Nov: to 17:00)",
 "Included in Yangdong entry **₩4,000**",
 "[yangdong.invil.org](http://yangdong.invil.org) · [UNESCO](https://whc.unesco.org/en/list/1324)",
 "Some houses are private homes — only enter those marked open. The hilltop pavilion view over the whole village is the best photo."),

("📚","Oksan Seowon — UNESCO (옥산서원)","🔁 daily (FREE)",
 "A 1573 Confucian academy honouring the scholar Yi Eon-jeok — one of the nine **UNESCO-listed Korean seowon**, in a stream valley near Yangdong",
 "Daily **09:00–18:00** (Nov: to 17:00)",
 "**FREE**",
 "[UNESCO](https://whc.unesco.org/en/list/1498) · [gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "Bus 203 from Gyeongju. The Dongnakdang villa next door, where Yi Eon-jeok lived in retirement, is equally good and equally empty."),

("🏞️","Dongnakdang House & Jasan Seodang, Oksan","🔁 daily (FREE)",
 "The 1532 retirement villa of Yi Eon-jeok beside the Oksan stream — a masterpiece of Joseon scholar-house design, with pavilions over the water",
 "Daylight hours",
 "**FREE**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "Next to Oksan Seowon. The stream-side pavilion in November colour is one of the quietest good things in this guide."),

("⛰️","Danseoksan & Sinseonsa Hermitage (단석산 신선사)","🔁 daily (FREE)",
 "Gyeongju's highest peak, with a natural rock cleft containing 10 large **6th-century Buddhist relief carvings** — the oldest in the region, and a National Treasure",
 "Always open; ~2 h round trip",
 "**FREE**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr) · [knps.or.kr](https://www.knps.or.kr)",
 "Bus from Gyeongju toward Geoncheon. The carvings are inside a U-shaped rock enclosure — utterly unlike anything else in Korea."),

("🗿","Gulbulsa Site Four-Buddha Stone (굴불사지 사면석불)","🔁 daily (FREE)",
 "A single boulder carved with Buddhas on all four faces (8th century), standing alone below Sogeumgangsan on the way to Baengnyulsa",
 "Always open",
 "**FREE**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "North of the centre, reachable by bike. Free, unfenced, and 1,300 years old."),

("🛕","Baengnyulsa Temple & Sogeumgangsan (백률사·소금강산)","🔁 daily (FREE)",
 "The temple marking where **Ichadon was martyred in 527**, the event that made Buddhism the Silla state religion — on a small hill with a city view",
 "Always open",
 "**FREE**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "A 20-minute climb from the Gulbulsa boulder. The whole northern hill is a free open-air heritage walk."),

("🏛️","Gyeongju Silla History Science Museum (신라역사과학관)","🔁 Tue–Sun",
 "A private museum devoted to the **engineering** of Silla — how Seokguram's dome, the Divine Bell and the pagodas were actually built, with cutaway models",
 "Tue–Sun **09:00–18:00** (closed Mondays)",
 "Adult **₩6,000**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "Near Bulguksa. If you found Seokguram impressive, this explains why it should not be structurally possible."),

("🖼️","Gyeongju Arte Museum & Media Art (아르떼뮤지엄 경주)","🔁 daily",
 "A large immersive digital-art space at Bomun — room-scale projection installations, indoor and warm, from the team behind the Jeju original",
 "Daily **10:00–20:00**",
 "Adult **₩17,000**",
 "[artemuseum.com](https://www.artemuseum.com)",
 "At Bomun Lake. A good option for a cold or wet November afternoon, and popular with families."),

("🌌","Gyeongju Stargazing at Bomun & Namsan","🔁 daily (FREE)",
 "Gyeongju's low-rise skyline and the ban on tall buildings in the heritage zone make it one of the darkest mid-sized cities in Korea for stargazing",
 "After dark; **new moon is best**",
 "**FREE**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr) · [Korea Astronomy and Space Science Institute](https://www.kasi.re.kr)",
 "The Namsan foothills and the far side of Bomun Lake are the darkest accessible spots. November skies are clear and cold."),

("🚶","Gyeongju Silla Sculpture Path & Wolseong Loop Walk","🔁 daily (FREE)",
 "A flat, signposted 5 km circuit linking Cheomseongdae, Gyerim, Wolseong, Woljeonggyo and Gyochon — **the single best free walk in the city**",
 "Always open",
 "**FREE**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr) · [UNESCO](https://whc.unesco.org/en/list/976)",
 "Start at Daereungwon. About two hours at a slow pace, all of it UNESCO-listed, none of it ticketed."),

("🚌","Gyeongju City Tour Bus (경주시티투어)","🔁 Tue–Sun",
 "The official day tour bus with routes covering Bulguksa/Seokguram, the east coast (Daewangam, Gameunsa, Jusangjeolli) and Yangdong",
 "Departures roughly **09:00–10:00**, returning **17:00–18:00**",
 "**₩20,000–₩30,000** plus site entries",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr) · [visitkorea.or.kr](https://english.visitkorea.or.kr)",
 "**The east-coast route is the one worth taking** — Daewangam, Gameunsa and Jusangjeolli are awkward and slow by public bus."),

("🥘","Gyeongju Chalborippang & Gyeongju Bread Culture","🔁 daily",
 "Beyond Hwangnam-ppang, Gyeongju has a whole regional bread culture — barley cakes, walnut breads and the *ssarippang* rice buns sold along Hwangnidan-gil",
 "Roughly **09:00–21:00**",
 "**₩1,000–₩2,000** each",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "Buy a mixed box. They keep about two days and make good train food."),

("🍲","Gyeongju Haejangguk & Local Beef Restaurants","🔁 daily",
 "Gyeongju's inland food traditions — *hanwoo* beef from the surrounding hills and hangover soup houses that open before dawn near Seongdong Market",
 "Some open **05:00**; most **10:00–21:00**",
 "Soup **₩9,000**; hanwoo from ₩30,000",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "The early-opening soup houses by the market are how you handle a 07:00 sunrise trip to Daewangam."),

("🌙","Donggung & Wolji Pond — November night photography","✅ CONFIRMED — nightly",
 "The definitive Gyeongju photograph. **In November sunset is around 17:20**, so the blue-hour reflection window is roughly 17:30–18:15 — much earlier and less crowded than summer",
 "Daily **09:00–22:00**; blue hour ~**17:30–18:15**",
 "Adult **₩3,000**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "Bring a small tripod; the paths are wide enough. Weekday evenings are dramatically quieter than weekends."),

("🎏","Gyeongju Hanbok Night Walk & Heritage Lighting Combo","🔁 nightly",
 "Hanbok rental shops on Hwangnidan-gil stay open into the evening, and the lit monuments — Woljeonggyo, Cheomseongdae, Daereungwon — are free",
 "Rentals to roughly **19:00**; lighting to 23:00",
 "Rental from **₩15,000**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "Wear thermals underneath. The lit Woljeonggyo is the best backdrop and costs nothing."),

("🧗","Toham-san Ridge Hike — Bulguksa to Seokguram on foot","🔁 daily (FREE)",
 "The historic 3.2 km pilgrim path up from Bulguksa to Seokguram — about 90 minutes each way through pine and maple forest",
 "Always open; allow 3 h round trip",
 "**FREE** (site entries separate)",
 "[knps.or.kr](https://www.knps.or.kr) · [gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "Start early and take the bus back down. **November is the best month for this** — the summer version is unpleasantly humid."),

("🏕️","Bomun Lake Camping & Caravan Sites","🔁 daily",
 "Municipal and private camping grounds around Bomun Lake, open through the autumn with heated caravan options",
 "Check-in typically **14:00**",
 "Pitches from **₩20,000**; caravans from ₩80,000",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "November nights drop near freezing inland — take a proper sleeping bag or book a heated caravan."),

("🎣","Gyeongju Deokdong Lake & Reservoir Walks","🔁 daily (FREE)",
 "The reservoirs ringing Gyeongju — Deokdong, Bomun and Sanae — with quiet perimeter paths, waterbirds and morning mist",
 "Always open",
 "**FREE**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr) · [K-water](https://www.kwater.or.kr)",
 "Deokdong is on the road to Bulguksa. Almost nobody walks these, which is the point."),

("🏛️","Gyeongju Bunhwangsa & Hwangnyongsa Combined Heritage Walk","🔁 daily (FREE)",
 "The eastern heritage cluster — Bunhwangsa, the Hwangnyongsa platform, the Guhwang-dong pagoda site and the National Museum, all within 2 km",
 "Sites daylight hours; museum Tue–Sun",
 "Mostly **FREE**; Bunhwangsa ₩1,300",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr) · [gyeongju.museum.go.kr](https://gyeongju.museum.go.kr)",
 "A good half-day on foot or by bike from the town centre, ending at the free national museum."),

("🕯️","Gyeongju Lotus Lantern & Temple Ceremonies","👀 WATCH",
 "Bulguksa, Golgulsa and Girimsa hold public Buddhist ceremonies through the year; the temples publish their own calendars",
 "Ceremony times vary; dawn services typically **04:00**",
 "**FREE** to attend",
 "[bulguksa.or.kr](https://www.bulguksa.or.kr) · [golgulsa.com](https://www.golgulsa.com)",
 "Visitors may attend respectfully. Check each temple's site for November dates."),

("🛍️","Gyeongju Souvenir Crafts & Silla Replica Goldwork","🔁 daily",
 "Licensed reproductions of the Silla gold crown, the *gogok* jade pendants and Cheonmachong metalwork, sold at the museum shop and craft village",
 "Roughly **09:00–18:00**",
 "From **₩10,000**",
 "[gyeongju.museum.go.kr](https://gyeongju.museum.go.kr) · [gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "The National Museum shop is the best-quality and most reasonably priced option."),

("🚏","Gyeongju Intercity & Express Bus Terminal Connections","🔁 daily",
 "Frequent buses to Busan (1 h), Daegu (1 h), Pohang (40 min) and Ulsan (50 min) — Gyeongju is the natural hub of the southeast",
 "Roughly **06:00–22:00**",
 "Busan **₩5,800**; Daegu ₩6,500; Pohang ₩4,500",
 "[kobus.co.kr](https://www.kobus.co.kr) · [txbus.t-money.co.kr](https://txbus.t-money.co.kr)",
 "**Gyeongju–Pohang and Gyeongju–Busan are both under an hour** — you can combine city files in a single day."),

("🌤️","Gyeongju November Weather & What to Wear","✅ CONFIRMED",
 "Inland Gyeongju in November runs roughly **3–15 °C**, colder than Busan and drier than Seoul, with big day-night swings and excellent visibility",
 "n/a",
 "n/a",
 "[Korea Meteorological Administration](https://www.weather.go.kr) · [gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "Layers plus a windproof shell. Mornings at Daewangam and on Namsan are genuinely cold; afternoons can be mild and sunny."),

("♻️","Gyeongju Heritage Site Combined Ticket & Discounts","🔁 daily",
 "Gyeongju sells integrated tickets covering several ticketed sites, and holders of a Korea Rail Pass or hanbok often get further discounts",
 "Ticket offices roughly **09:00–17:00**",
 "Combined tickets from **₩10,000**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "Ask at the first site you visit. Note that **most of the best sites here are free anyway.**"),

("👨‍👩‍👧","Gyeongju Family Programmes & Children's Museum","🔁 Tue–Sun (FREE)",
 "The National Museum's children's wing runs free hands-on Silla archaeology programmes, bookable online",
 "Tue–Sun, sessions through the day",
 "**FREE** with reservation",
 "[gyeongju.museum.go.kr](https://gyeongju.museum.go.kr)",
 "Reserve online — walk-in places are limited. Conducted in Korean, but largely hands-on."),

("📸","Gyeongju Cheomseongdae Flower Field & Seasonal Planting","🔁 daily (FREE)",
 "The city plants the meadow around Cheomseongdae seasonally — **pink muhly grass and cosmos run into early November** before the winter clearance",
 "Always open",
 "**FREE**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "Pink muhly is usually at its best late September to mid-October and fades through early November — go in the first week for the tail of it."),

("🏛️","Gyeongju Silla Wolseong Excavation Public Viewing","🔁 daily (FREE)",
 "The Wolseong palace dig is one of Korea's largest active archaeological projects, with a public viewing platform and interpretive panels",
 "Daylight hours",
 "**FREE**",
 "[Korea Heritage Service](https://www.khs.go.kr) · [gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "Between Cheomseongdae and Woljeonggyo. Human sacrificial burials were found here in 2017 — the panels explain the finds."),

("🌏","Gyeongju as a UNESCO triple site — orientation","🔁 daily (FREE)",
 "Gyeongju holds **three separate UNESCO World Heritage inscriptions**: Bulguksa/Seokguram, the Gyeongju Historic Areas, and Yangdong Village — plus Oksan Seowon in the seowon listing",
 "n/a",
 "n/a",
 "[UNESCO Korea listings](https://whc.unesco.org/en/statesparties/kr) · [gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "Four World Heritage inscriptions in one small city is unmatched in Korea. Two full days is the realistic minimum."),
]

append("/home/user/KoreaFun/gyeongju.md", E, 202, 3,
       "\n---\n\n## 🧭 Beginner-friendly essentials", "Gyeongju",
       intro="**Second expansion batch** — outlying UNESCO sites, free stone heritage, hikes, night photography timing and practical November logistics.")
