# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "/home/user/KoreaFun/.build")
from addlib import append

E = [
# --- UNESCO core ---
("🛕","Bulguksa Temple — UNESCO (불국사)","🔁 daily",
 "The masterpiece of Silla Buddhist architecture, founded 528 and rebuilt 751 — the Dabotap and Seokgatap pagodas, the Blue Cloud Bridge, and **UNESCO World Heritage since 1995**",
 "Daily **09:00–17:00** (Nov; last entry 16:30)",
 "Adult **₩6,000**; youth ₩4,000; child ₩3,000",
 "[bulguksa.or.kr](https://www.bulguksa.or.kr) · [UNESCO](https://whc.unesco.org/en/list/736)",
 "Bus 10/11 from Gyeongju Station (~40 min). Go at opening — by 10:30 it fills with school groups. **Foliage on the approach peaks in early November.**"),

("🗿","Seokguram Grotto — UNESCO (석굴암)","🔁 daily",
 "The granite grotto shrine above Bulguksa (774 AD) — a 3.5 m seated Buddha under a corbelled dome, facing the sunrise over the East Sea. **UNESCO World Heritage**",
 "Daily **09:00–17:00** (Nov)",
 "Adult **₩6,000**",
 "[UNESCO](https://whc.unesco.org/en/list/736) · [gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "Bus 12 up from Bulguksa, roughly hourly. The Buddha is behind glass for conservation. The 20-minute forest walk in from the car park is part of the experience."),

("🌙","Donggung Palace & Wolji Pond (동궁과 월지)","🔁 daily",
 "The Silla crown prince's palace and its artificial pond, built 674 — **the single most photographed night view in Korea**, with the pavilions mirrored in black water",
 "Daily **09:00–22:00** (last entry 21:30)",
 "Adult **₩3,000**; youth ₩2,000",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "**Go after dark — that is the whole point.** In November the lights come on around 17:30, so 18:00–19:00 is ideal and less crowded than summer."),

("⛰️","Daereungwon Tomb Complex & Cheonmachong (대릉원·천마총)","🔁 daily",
 "Twenty-three grass-covered Silla royal burial mounds in a city-centre park — and **Cheonmachong**, the one you can walk inside, with its gold crown and painted heavenly horse",
 "Daily **09:00–22:00** (Nov)",
 "Adult **₩3,000**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "In the town centre, walkable. **Open until 22:00 and lit at night** — the mounds after dark are extraordinary and almost empty."),

("🔭","Cheomseongdae Observatory (첨성대)","🔁 daily (FREE)",
 "Built around 634 under Queen Seondeok — **the oldest surviving astronomical observatory in East Asia**, 362 stones for the days of a lunar year",
 "Always open; illuminated at night",
 "**FREE** to view",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "Next to Daereungwon. Free, floodlit at night, and the surrounding meadow is planted with seasonal flowers."),

("🌉","Woljeonggyo Bridge (월정교)","🔁 daily (FREE)",
 "A full reconstruction of the Silla royal bridge over the Namcheon, completed 2018 after decades of research — a covered wooden bridge, **spectacularly lit at night**",
 "Bridge always open; interior exhibition **09:00–18:00**",
 "**FREE**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "Walkable from Gyochon Village. Do Woljeonggyo and Wolji Pond in the same evening — they're 15 minutes apart."),

("🏛️","Gyeongju National Museum (국립경주박물관)","🔁 Tue–Sun (FREE)",
 "The definitive collection of Silla civilisation — gold crowns, the **Divine Bell of King Seongdeok** (771, Korea's largest bell), and the Wolji Pond finds",
 "Tue–Sun **10:00–18:00** (Sat to 21:00; closed Mondays)",
 "**FREE**",
 "[gyeongju.museum.go.kr](https://gyeongju.museum.go.kr)",
 "Walkable from Wolji Pond. **Free entry to one of the great museums of Asia.** Allow at least two hours; the outdoor bell pavilion is free even when halls close."),

("🏘️","Yangdong Folk Village — UNESCO (양동마을)","🔁 daily",
 "A 15th-century **living** yangban clan village of 160 tiled and thatched houses on a wooded hillside — UNESCO World Heritage, and still farmed and inhabited",
 "Daily **09:00–18:00** (Nov: to 17:00)",
 "Adult **₩4,000**",
 "[yangdong.invil.org](http://yangdong.invil.org) · [UNESCO](https://whc.unesco.org/en/list/1324)",
 "Bus 203 from Gyeongju (~50 min), roughly hourly. **Check the return bus time before you set off** — services are sparse."),

("🏯","Gyochon Traditional Village & Choi Clan House (교촌마을)","🔁 daily (FREE)",
 "The village of the **Gyeongju Choi family**, Korea's most famous 'twelve-generation rich' household, known for its Confucian code of charity — plus the Gyeongju Hyanggyo",
 "Village always open; house **10:00–18:00**",
 "**FREE**; craft experiences from ₩5,000",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "Next to Woljeonggyo. The Choi house rule that 'no one within 100 li should go hungry' is a genuine part of Korean moral folklore."),

("🍶","Gyochon Gyeongju Beopju & Traditional Liquor (경주교동법주)","🔁 daily",
 "The Choi family's **Intangible Cultural Heritage** rice liquor, brewed by the same household for 400 years — tastings and sales in Gyochon Village",
 "Roughly **10:00–17:00**",
 "Tasting free; bottles from **₩30,000**",
 "[Korea Heritage Service](https://www.khs.go.kr) · [gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "A nationally designated Important Intangible Cultural Property (No. 86-3). Production is tiny — buy at source."),

# --- Tombs, sites, temples ---
("👑","Tomb of King Muyeol & Seoak Tombs (무열왕릉)","🔁 daily",
 "The tomb of **Kim Chun-chu, King Muyeol (r. 654–661)**, who unified the Three Kingdoms — with the only Silla tombstone base whose inscription confirms the occupant",
 "Daily **09:00–18:00** (Nov: to 17:00)",
 "Adult **₩2,000**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "Bus from the centre. The turtle-and-dragon stele base is one of the finest Silla stone carvings anywhere."),

("👸","Tomb of Queen Seondeok & Neungji Tower (선덕여왕릉)","🔁 daily (FREE)",
 "The hilltop tomb of **Korea's first reigning queen (r. 632–647)**, who commissioned Cheomseongdae — reached by a quiet pine-forest path on Nangsan",
 "Always open",
 "**FREE**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "Bus toward Bulguksa, then a 15-minute walk uphill. Free, empty and one of the most atmospheric spots in Gyeongju."),

("🌲","Oreung Royal Tombs (오릉)","🔁 daily",
 "Five mounds traditionally held to contain **Bak Hyeokgeose, the founding king of Silla (57 BC)**, and his queen — in a walled pine and zelkova grove",
 "Daily **09:00–18:00** (Nov: to 17:00)",
 "Adult **₩2,000**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "South of the centre, walkable or a short bus. The grove in November colour is quiet and beautiful."),

("🌳","Gyerim Forest (계림)","🔁 daily (FREE)",
 "The ancient zelkova and willow grove where, by legend, the **Kim clan's founder was found in a golden box** in 65 AD — beside the Wolseong palace site",
 "Always open",
 "**FREE**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "Between Cheomseongdae and Woljeonggyo. **Golden foliage here in early November** is one of Gyeongju's best free sights."),

("🏰","Wolseong Palace Site & Seokbinggo Ice Store (월성·석빙고)","🔁 daily (FREE)",
 "The earthwork ramparts of the Silla royal palace, under long-running excavation — plus the 1738 **Seokbinggo**, a stone ice house still standing in the bank",
 "Always open; excavation viewing platform daylight hours",
 "**FREE**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "Walkable from Cheomseongdae. You can watch active archaeology from the public platform."),

("🗻","Namsan Mountain Buddhist Trails (남산)","🔁 daily (FREE)",
 "An entire mountain designated **UNESCO World Heritage** — over 100 temple sites, 80 stone Buddhas and 60 pagodas scattered across the slopes of the Silla holy mountain",
 "Always open; allow 3–5 h for a full crossing",
 "**FREE**",
 "[UNESCO](https://whc.unesco.org/en/list/976) · [gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "Bus to Samneung for the classic Samneung → Sangseonam → Yongjangsa route. **November is the ideal hiking month** — cool, clear and no insects."),

("🪨","Samneung Valley & Buddha Carvings, Namsan","🔁 daily (FREE)",
 "The most rewarding single section of Namsan — a pine-forest valley strung with 7th–9th-century rock-carved Buddhas, several of them headless and all of them free",
 "Always open",
 "**FREE**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr) · [UNESCO](https://whc.unesco.org/en/list/976)",
 "Bus 500 series to Samneung. About 90 minutes up to the seated Buddha; the morning mist through the pines is famous among photographers."),

("🛕","Bunhwangsa Temple & Stone Pagoda (분황사)","🔁 daily",
 "Founded 634 under Queen Seondeok — its **stone-brick pagoda is the oldest datable pagoda in Silla**, and the temple is still active",
 "Daily **09:00–18:00** (Nov: to 17:00)",
 "Adult **₩1,300**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "Next to the Hwangnyongsa site. National Treasure No. 30, and rarely crowded."),

("🏛️","Hwangnyongsa Temple Site & History Culture Hall (황룡사지)","🔁 Tue–Sun",
 "The empty platform of what was **the largest wooden building in East Asia** — a 9-storey, 80 m pagoda burned by the Mongols in 1238, now reconstructed at 1:10 scale in the adjacent hall",
 "Site always open; exhibition hall Tue–Sun **09:00–18:00**",
 "Site **FREE**; hall ₩3,000",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "The scale model in the hall makes the lost pagoda comprehensible. The empty field itself is oddly moving."),

("🥋","Golgulsa Temple & Sunmudo (골굴사)","🔁 daily",
 "A cave temple carved into a limestone cliff, home of **Sunmudo**, the Korean Buddhist martial art — with public demonstrations and a well-known templestay",
 "Daily **08:00–18:00**; demonstrations typically **15:30**",
 "Entry **₩3,000**; templestay from ₩70,000",
 "[golgulsa.com](https://www.golgulsa.com) · [templestay.com](https://www.templestay.com)",
 "Bus 100/150 toward Gampo. The cliff Buddha relief is 9th-century; the martial-art demonstration is genuinely impressive."),

("🌊","Underwater Tomb of King Munmu, Daewangam (문무대왕릉)","🔁 daily (FREE)",
 "The rock islet 200 m offshore where King Munmu was buried in 681, having asked to become a **sea dragon guarding Silla from Japanese pirates** — the world's only known underwater royal tomb",
 "Always open; sunrise is the traditional time",
 "**FREE**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "Bus 150 from Gyeongju (~1 h). Shamans still hold rituals on the beach at dawn — a living, not museum, tradition."),

("🛕","Gameunsa Temple Site & Twin Pagodas (감은사지)","🔁 daily (FREE)",
 "Two 13 m granite pagodas (682) standing alone in a field near the coast — built by King Sinmun for his father Munmu, with a channel under the hall for the sea dragon to enter",
 "Always open",
 "**FREE**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "On the bus 150 route to Daewangam. Free, unstaffed, and among the most powerful sights in Korea at dawn or dusk."),

("🪨","Yangnam Jusangjeolli Columnar Joints (양남 주상절리)","🔁 daily (FREE)",
 "A rare **fan-shaped radial basalt column formation** on the Gyeongju coast, formed 20 million years ago — with a coastal boardwalk and observation deck",
 "Always open; boardwalk lit until 22:00",
 "**FREE**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "Bus 150 toward Gampo. The fan-shaped cluster is geologically unusual worldwide — most columnar basalt is vertical."),

("🏖️","Bonggil & Najeong Beach, Gyeongju Coast","🔁 daily (FREE)",
 "Gyeongju's East Sea beaches — pine-backed, quiet in November, and the sunrise coast for Daewangam",
 "Always open; **sunrise ~07:05 in November**",
 "**FREE**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "Bus 150. Najeong has a cafe strip; Bonggil has the fish market and the boats to nowhere."),

("🐋","Gampo Port & East Sea Fish Market","🔁 daily",
 "The working fishing port on Gyeongju's coast — a morning auction, a raw fish market and snow crab in season",
 "Market roughly **06:00–19:00**",
 "**FREE** to browse",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "Bus 150 terminus. Combine with Daewangam and Gameunsa in one coastal day trip."),

# --- Parks, nature, lake ---
("🌅","Bomun Lake Resort & Lakeside Path (보문관광단지)","🔁 daily (FREE)",
 "Gyeongju's purpose-built resort district around a 1.65 km² lake — a flat 8 km lakeside walking and cycling loop, hotels, a musical fountain and the Gyeongju Tower",
 "Always open",
 "**FREE**; bike hire from ₩5,000/h",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "Bus 10/100 from the centre. **The lakeside foliage peaks in early-to-mid November**; the loop is the best easy walk in Gyeongju."),

("🗼","Gyeongju Tower & Expo Park (경주타워·경주엑스포대공원)","🔁 daily",
 "A 82 m tower whose facade is a **negative silhouette of the lost Hwangnyongsa nine-storey pagoda** — plus the Expo park's exhibition halls and media shows",
 "Daily **09:00–22:00** (Nov)",
 "Park + tower **₩12,000**; night media show included",
 "[gyeongjuexpo.com](https://www.gyeongjuexpo.com)",
 "At Bomun Lake. The evening projection-mapping show on the tower is the reason to come after dark."),

("🎠","Silla Millennium Park (신라밀레니엄파크)","🔁 daily",
 "A historical theme park recreating Silla-era streets, with costumed performances, craft workshops and the **Queen Seondeok** drama sets",
 "Daily roughly **10:00–18:00** (Nov)",
 "Adult **₩22,000**",
 "[silla.co.kr](https://www.silla.co.kr)",
 "At Bomun Lake. Commercial, but the martial-arts and court performances are well done and good with children."),

("🎢","Gyeongju World & California Beach (경주월드)","🔁 daily",
 "The region's main amusement park at Bomun, with the **Draken** and **Phaethon** roller coasters, among Korea's most intense",
 "Daily roughly **10:00–19:00** (Nov; shorter weekdays)",
 "Freepass adult **₩56,000**",
 "[gyeongjuworld.com](https://www.gyeongjuworld.com)",
 "Bus 10 from the centre. Check the winter operating calendar — some rides close in November."),

("🌳","Gyeongju National Park — Toham & Danseoksan sections","🔁 daily (FREE)",
 "Korea's **only national park designated for its cultural heritage rather than its landscape** — eight separate districts covering Namsan, Toham, Danseok and the coast",
 "Always open",
 "**FREE**",
 "[knps.or.kr](https://www.knps.or.kr) · [english.knps.or.kr](https://english.knps.or.kr)",
 "Trailhead information at each district. Toham-san behind Bulguksa is the classic ridge walk to Seokguram on foot."),

("🍁","Gyeongju Autumn Foliage — Bomun, Bulguksa, Gyerim","✅ CONFIRMED — peak early-to-mid Nov",
 "Gyeongju's ginkgo and maple peak **roughly Nov 1–12** — the Bulguksa approach, Gyerim Forest, Bomun lakeside and the Oreung grove are the four best sites",
 "Daylight hours",
 "**FREE** except site entries",
 "[Korea Forest Service](https://www.forest.go.kr) · [gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "Gyeongju in early November is arguably the best-timed city in this entire guide. Book accommodation early — Koreans know this too."),

("🌾","Gyeongju Samneung Pine Forest & Morning Mist","🔁 daily (FREE)",
 "The pine grove around the three royal tombs at the foot of Namsan — famous among Korean landscape photographers for the light through the mist at dawn",
 "Always open",
 "**FREE**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "Bus 500 series. **Be there at sunrise (~07:05 in November)** for the mist; by 09:00 it's an ordinary pine wood."),

("🌿","Gyeongju Hwangseong Park & Citizen Forest","🔁 daily (FREE)",
 "The city's main recreation park with sports fields, a 3 km jogging loop and a large tree-lined avenue — where Gyeongju residents actually go",
 "Always open",
 "**FREE**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "North of the centre, walkable. Useful if you want a run or a quiet hour away from the heritage sites."),

# --- Museums & modern culture ---
("🎨","Woljeong Gyo & Gyeongju Solgeo Art Museum","🔁 Tue–Sun",
 "The Expo park's art museum, named after the legendary Silla painter Solgeo — with a large collection of modern Korean ink painting",
 "Tue–Sun **09:00–18:00** (closed Mondays)",
 "Included in Expo park ticket",
 "[gyeongjuexpo.com](https://www.gyeongjuexpo.com)",
 "At Bomun. A calm indoor option if the weather turns."),

("🖼️","Wooyang Museum of Contemporary Art (우양미술관)","🔁 Tue–Sun",
 "A serious contemporary art museum at Bomun in a Kim Swoo-geun building — Korean and international modern art, an unexpected find in a heritage city",
 "Tue–Sun **10:30–18:00** (closed Mondays)",
 "Adult **₩8,000**",
 "[wooyangmuseum.org](https://www.wooyangmuseum.org)",
 "At Bomun Lake, next to the Hilton. Kim Swoo-geun is Korea's most important modern architect — the building is part of the exhibit."),

("🧸","Gyeongju Teddy Bear Museum & Bird Park","🔁 daily",
 "Two family attractions at Bomun — teddy bear dioramas of Silla history, and a walk-through aviary and botanical garden",
 "Daily **09:00–19:00**",
 "Each roughly **₩10,000–₩18,000**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "At Bomun Lake. Tourist-trap territory, but genuinely good with small children on a cold day."),

("🛷","Gyeongju Luge World (경주루지월드)","🔁 daily",
 "A 1.5 km gravity luge track down a hillside at Bomun, with karts you steer yourself — no engine, just brakes and nerve",
 "Daily roughly **10:00–18:00** (Nov)",
 "2 rides **₩25,000**; combo with gondola from ₩33,000",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "At Bomun. Dress warmly — it's open air and fast."),

("🏛️","Gyeongju Historic Areas — UNESCO overview walk","🔁 daily (FREE)",
 "The **Gyeongju Historic Areas** UNESCO listing covers five zones — Namsan, Wolseong, Daereungwon, Hwangnyongsa and Sanseong — most of which are free and walkable",
 "Always open",
 "Mostly **FREE**",
 "[UNESCO](https://whc.unesco.org/en/list/976) · [gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "The Wolseong belt from Cheomseongdae through Gyerim to Woljeonggyo is a flat 3 km and entirely free. Start here on day one."),

("🚲","Gyeongju Bicycle Loop & Rental (경주 자전거)","🔁 daily",
 "Gyeongju is flat and compact, and the standard local way to see it is by bicycle — rental shops cluster around the station and Bomun",
 "Rentals roughly **09:00–18:00**",
 "**₩10,000–₩15,000** per day",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "**The single best way to see Gyeongju.** The central heritage belt is entirely bikeable and November weather is ideal for it."),

# --- Food, markets, town ---
("🍜","Hwangnidan-gil Cafe & Restaurant Street (황리단길)","🔁 daily",
 "Gyeongju's converted old-town street of hanok cafes, craft shops and restaurants, next to Daereungwon — the city's social centre",
 "Most **11:00–22:00**",
 "Coffee **₩5,000–₩7,000**; meals ₩10,000–₩20,000",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "Directly beside the tomb park. Busy at weekends; hanbok rental shops here serve the Daereungwon photo trade."),

("🥮","Gyeongju Hwangnam-ppang & Chalborideok (황남빵)","🔁 daily",
 "The red-bean pastry invented in Gyeongju in 1939, sold from the original shop near Daereungwon — plus the barley-cake *chalborideok* variant",
 "Roughly **08:00–22:00**",
 "A box of 10 **₩13,000**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "There's a queue at the original Hwangnam-ppang shop most afternoons. They're best eaten the same day."),

("🍲","Gyeongju Ssambap & Korean Set Meal Restaurants (경주 쌈밥)",  "🔁 daily",
 "Gyeongju's signature meal — a table of 20+ side dishes with leaves for wrapping, served at the restaurant row near Daereungwon and Bulguksa",
 "Most **10:00–21:00**",
 "Per person **₩15,000–₩22,000**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "A ssambap spread is the classic Gyeongju lunch. Minimum two people at most restaurants."),

("🧺","Seongdong Market (성동시장)","🔁 daily",
 "Gyeongju's main traditional market beside the old station — a large food alley, dried goods and a famously cheap set-menu hall",
 "Roughly **07:00–20:00** (closed some Sundays)",
 "Meals **₩6,000–₩10,000**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "Walkable from the town centre. The upstairs food court does full Korean meals for under ₩10,000."),

("🍢","Gyeongju Jungang Market & Night Food Alley","🔁 daily",
 "The older covered market in the town centre, with a night-time street-food section and local specialities",
 "Roughly **08:00–22:00**",
 "Snacks **₩2,000–₩6,000**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "Less polished than Seongdong and correspondingly cheaper. Good for an evening wander."),

("🍶","Gyeongju Beopju & Local Craft Brewery Tastings","🔁 daily",
 "Beyond the Choi family's Beopju, Gyeongju has a growing craft brewing scene using local rice and barley",
 "Roughly **12:00–22:00**",
 "Tasting flights from **₩10,000**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "Several are on Hwangnidan-gil. Ask for *makgeolli* made with Gyeongju rice."),

("👘","Gyeongju Hanbok Rental & Free Site Entry","🔁 daily",
 "Wearing hanbok gives **free or discounted entry to several Gyeongju heritage sites**, and the rental shops cluster on Hwangnidan-gil",
 "Shops roughly **09:00–18:00**",
 "Rental **₩15,000–₩30,000** for 2–4 hours",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "Bring a warm layer to wear underneath in November — hanbok is thin. Ask each shop which sites the discount applies to."),

("🏨","Gyeongju Hanok Guesthouse Stay (경주 한옥스테이)","🔁 daily",
 "Gyeongju has one of Korea's densest concentrations of hanok guesthouses, many in the Hwangnam and Gyochon districts",
 "Check-in typically **15:00**",
 "From **₩60,000–₩150,000** per night",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr) · [visitkorea.or.kr](https://english.visitkorea.or.kr)",
 "Ondol underfloor heating makes a hanok comfortable even in November. Book ahead for the foliage weeks."),

("🧘","Gyeongju Templestay — Golgulsa & Bulguksa","🔁 daily",
 "Overnight temple programmes in Gyeongju — Golgulsa's Sunmudo martial arts programme is the best known in Korea",
 "Check-in typically **15:00**",
 "From **₩70,000** per night",
 "[templestay.com](https://www.templestay.com) · [golgulsa.com](https://www.golgulsa.com)",
 "English programmes must be booked via templestay.com. The 04:00 morning service is not optional."),

# --- Practical / events ---
("🚄","Gyeongju via Singyeongju KTX Station","🔁 daily",
 "**Seoul → Singyeongju by KTX is about 2 hours**, and Busan → Singyeongju about 30 minutes — making Gyeongju an easy day trip from either",
 "Trains roughly **05:30–22:30**",
 "Seoul→Singyeongju from **₩49,300**; Busan→Singyeongju from ₩11,000",
 "[letskorail.com](https://www.letskorail.com)",
 "**Singyeongju is 8 km outside town** — take bus 700/701 or a taxi (~₩12,000) into the centre. Don't plan to walk it."),

("🚌","Gyeongju City Bus Network & Day Passes","🔁 daily",
 "Buses 10, 11, 100, 150, 203 and 500 reach every site in this file from the town centre; T-money works throughout",
 "Roughly **06:00–22:00**",
 "Single fare **₩1,500**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "Buses 10 and 11 run the Bulguksa loop in opposite directions. **Rural routes like 203 to Yangdong run roughly hourly** — check times."),

("🗺️","Gyeongju Tourist Information & Free Guided Tours","🔁 daily (FREE)",
 "Information centres at Singyeongju station, the bus terminal and Daereungwon, several offering **free volunteer-guided heritage walks**",
 "Roughly **09:00–18:00**",
 "**FREE**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr) · [visitkorea.or.kr](https://english.visitkorea.or.kr)",
 "Book English guided walks a few days ahead. The free Daereungwon and Wolseong walks are genuinely good."),

("🎭","Gyeongju Arts Center & Silla Cultural Performances","🔁 by event",
 "The municipal arts centre and the Expo park stage regular traditional-music and dance performances through the autumn",
 "By event; typically **19:30** or weekend afternoons",
 "**FREE** to ₩30,000",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr) · [gyeongjuexpo.com](https://www.gyeongjuexpo.com)",
 "Check the November calendar in October. Several city-funded performances are free."),

("🌃","Gyeongju Night Heritage Lighting Tour","🔁 nightly (FREE)",
 "Gyeongju floodlights its major monuments after dark — Cheomseongdae, Woljeonggyo, Donggung, Daereungwon and the Expo tower",
 "Lighting roughly **17:30–23:00** in November",
 "Mostly **FREE** (Donggung ₩3,000)",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "**The night version of Gyeongju is better than the day version and far less crowded.** Sunset is around 17:20 in November — you get a long evening."),

("🏃","Gyeongju International Marathon & Autumn Races","👀 WATCH (October–November)",
 "Gyeongju hosts one of Korea's best-known road races through the heritage areas each autumn — 2026 dates to be announced",
 "Race day typically a Sunday morning",
 "Entry fees apply; spectating **FREE**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr) · [Korea Athletics Federation](https://www.kaaf.or.kr)",
 "Check the city site in September for confirmed 2026 dates. Even as a spectator it's a good morning."),

("🎆","Silla Cultural Festival & Gyeongju city events","👀 WATCH",
 "Gyeongju's flagship heritage festival and its associated events are scheduled annually by the city — **2026 dates unconfirmed at the time of writing**",
 "TBA",
 "Most events **FREE**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr) · [visitkorea.or.kr](https://english.visitkorea.or.kr)",
 "Re-check the official Gyeongju city calendar in September 2026 — festival dates are published about two months ahead."),

("♨️","Gyeongju Bomun Spa & Hot Spring Hotels","🔁 daily",
 "The Bomun resort hotels operate public spa and sauna facilities, several with outdoor pools looking over the lake",
 "Roughly **06:00–21:00**",
 "Day entry **₩10,000–₩25,000**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr)",
 "A hot bath after a day on Namsan is the correct sequence. Non-guests are admitted at most of them."),

("🏛️","Gyeongju Silla Arts & Crafts Village (신라공예촌)","🔁 Tue–Sun",
 "Workshops of designated master craftspeople reproducing Silla metalwork, pottery and jewellery — with hands-on classes",
 "Tue–Sun **09:00–18:00** (closed Mondays)",
 "**FREE** to browse; workshops from ₩15,000",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "Near Bulguksa. Making a small gold-crown replica is a better souvenir than buying one."),

("📜","Gyeongju Poseokjeong & Royal Banquet Site (포석정)","🔁 daily",
 "The stone water channel where Silla kings floated wine cups at poetry banquets — and where the last king was surprised and killed in 927",
 "Daily **09:00–18:00** (Nov: to 17:00)",
 "Adult **₩2,000**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "At the foot of Namsan, bus 500 series. Small, but the story of the dynasty ending at a drinking party is hard to beat."),

("🗿","Gyeongju Seoak-dong Three-storey Pagoda & Stone Buddhas","🔁 daily (FREE)",
 "Free, unstaffed Silla stone monuments scattered across the western suburbs — pagodas, Buddha triads and tomb stelae, usually with nobody there",
 "Always open",
 "**FREE**",
 "[gyeongju.go.kr](https://www.gyeongju.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "Gyeongju has hundreds of these. Renting a bike and finding them yourself is the connoisseur's version of the city."),
]

append("/home/user/KoreaFun/gyeongju.md", E, 143, 3,
       "\n---\n\n## 🧭 Beginner-friendly essentials", "Gyeongju")
