# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "/home/user/KoreaFun/.build")
from addlib import append

E = [
("🏛️","Incheon Metropolitan Museum of Art / Incheon Culture & Arts Centre (인천문화예술회관)","🔁 by event",
 "Incheon's main concert hall and exhibition complex — the home stage of the **Incheon Philharmonic Orchestra**, with a full autumn concert season",
 "Box office **09:00–18:00**; performances usually **19:30**",
 "Concerts **₩10,000–₩50,000**; exhibitions often FREE",
 "[iacc.or.kr](https://www.iacc.or.kr) · [incheon.go.kr](https://www.incheon.go.kr)",
 "Incheon Line 1 Arts Center Station. The city orchestra plays here most months — cheaper than equivalent Seoul tickets."),

("🎻","Incheon Philharmonic Orchestra — November season","👀 WATCH",
 "The city's professional symphony orchestra, with regular subscription concerts at the Culture & Arts Centre through the autumn",
 "Typically Friday **19:30**",
 "**₩10,000–₩40,000**",
 "[iacc.or.kr](https://www.iacc.or.kr)",
 "The November programme is published on the venue site about six weeks ahead. Student/senior discounts available."),

("🏛️","Incheon City Hall & Michuhol Tower Observatory","🔁 weekdays (FREE)",
 "The city government complex in Guwol-dong with a free public observation floor over central Incheon",
 "Weekdays **09:00–18:00**",
 "**FREE**",
 "[incheon.go.kr](https://www.incheon.go.kr)",
 "Incheon Line 1 Incheon City Hall Station. Weekdays only, and quiet — a free alternative if G-Tower is closed."),

("🛍️","Guwol-dong Rodeo Street (구월동 로데오거리)","🔁 daily",
 "Incheon's main downtown shopping and eating district around the city hall — the local equivalent of Gangnam station, with a young crowd",
 "Shops **11:00–22:00**; bars later",
 "**FREE** to walk",
 "[Namdong-gu](https://www.namdong.go.kr)",
 "Incheon Line 1 Incheon City Hall Station Exit 4. Where Incheon residents actually go out, rather than Chinatown."),

("🍲","Sinpo Market Fried Chicken vs Bupyeong Fried Chicken","🔁 daily",
 "Incheon's two rival fried-chicken traditions — Sinpo's sweet-garlic *dakgangjeong* and Bupyeong's newer alley shops",
 "Roughly **11:00–22:00**",
 "A whole chicken **₩12,000–₩20,000**",
 "[Incheon Jung-gu tourism](https://www.icjg.go.kr) · [icbp.go.kr](https://www.icbp.go.kr)",
 "Dakgangjeong travels well cold — buy a box for the train back to Seoul."),

("🐄","Incheon Sinpo Dak-gangjeong & Hwadojin Park Waterfront","🔁 daily (FREE)",
 "The restored waterfront park at Hwadojin, site of an 1879 coastal battery, now a walking park facing the inner harbour",
 "Always open",
 "**FREE**",
 "[Incheon Dong-gu](https://www.icdonggu.go.kr)",
 "Line 1 Dongincheon Station. A quiet 20-minute walk that most visitors never find."),

("🚢","Incheon Port 1st & 8th Wharf Redevelopment Walk","🔁 daily (FREE)",
 "The opened-up sections of Incheon's inner port — grain silos turned into the world's largest mural, warehouses turned into public space",
 "Always open",
 "**FREE**",
 "[Incheon Port Authority](https://www.icpa.or.kr) · [incheon.go.kr](https://www.incheon.go.kr)",
 "Near Incheon Station. The **Guinness-recognised silo mural** (about 22 storeys tall) is genuinely startling in person."),

("⛴️","Incheon Coastal Ferry Terminal — West Sea islands","🔁 daily",
 "Departures to Deokjeokdo, Jawoldo, Yeongheungdo and the far Baengnyeongdo — Korea's Yellow Sea island network starts here",
 "Sailings roughly **08:00–17:00**, weather-dependent",
 "Deokjeokdo return from **₩45,000**",
 "[Incheon Port Authority](https://www.icpa.or.kr)",
 "**Foreign passengers need their passport** to board domestic ferries. November seas can cancel sailings — check the morning of."),

("🏝️","Yeongheungdo & Seonjaedo Islands (영흥도·선재도)","🔁 daily (FREE)",
 "Two islands reachable **by road bridge** from the mainland — pine-backed beaches, mudflat clam digging and the tidal 'Mopil' island road",
 "Always open",
 "**FREE**; parking charges apply",
 "[Ongjin-gun](https://www.ongjin.go.kr) · [incheon.go.kr](https://www.incheon.go.kr)",
 "Bus 790 from Oido Station. No ferry needed — the easiest 'island' day trip from the metro area."),

("🏝️","Deokjeokdo Island (덕적도)","🔁 daily",
 "The largest of Incheon's outer islands — Seopori Beach, a pine forest ridge walk and near-total quiet in the off season",
 "Ferry ~1 h 10 min by fast boat",
 "Return ferry from **₩45,000**",
 "[Ongjin-gun](https://www.ongjin.go.kr) · [Incheon Port Authority](https://www.icpa.or.kr)",
 "Overnight is better than a day trip. **Passport required** to board. November is cold but empty and beautiful."),

("🌊","Incheon Mudflat (Getbol) Walk — UNESCO listed coast","🔁 tide-dependent (FREE)",
 "Korea's Yellow Sea tidal flats are a **UNESCO World Heritage site**; the Incheon coast has accessible sections at Sorae, Yeongjong and Seonjaedo",
 "Low tide only — check tide tables",
 "**FREE**; guided programmes from ₩5,000",
 "[UNESCO Getbol listing](https://whc.unesco.org/en/list/1591) · [khoa.go.kr tide tables](https://www.khoa.go.kr)",
 "Wear boots you can hose down. **Always check the tide table and never walk out on a rising tide.**"),

("🦆","Ganghwa Estuary Bird Watching — winter migrants","✅ CONFIRMED — Nov arrival season",
 "The Han estuary is a major East Asian flyway stopover; **November is when the swans, geese and cranes arrive** from Siberia",
 "Daylight hours",
 "**FREE**",
 "[Ganghwa-gun](https://www.ganghwa.go.kr) · [National Institute of Biological Resources](https://www.nibr.go.kr)",
 "Best from the Ganghwa Peace Observatory area and Donggeom-do. Bring binoculars — nothing is rented on site."),

("🏯","Ganghwa Goryeo Palace Site & Ganghwa Anglican Church","🔁 daily",
 "The site of the exile capital where the Goryeo court held out against the Mongols (1232–70), plus Korea's oldest Anglican church (1900), built as a **hanok**",
 "Roughly **09:00–18:00**",
 "Palace site **₩900**; church FREE",
 "[Ganghwa-gun](https://www.ganghwa.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "In Ganghwa town, walkable from the bus terminal. A Christian church built as a Confucian-style hanok is a genuine oddity."),

("📖","Ganghwa Tripitaka Koreana Connection & History Museum","🔁 Tue–Sun",
 "The **original Tripitaka Koreana woodblocks were carved on Ganghwa** during the Mongol invasions; the island's history museum tells that story",
 "Tue–Sun **09:00–18:00** (closed Mondays)",
 "Adult **₩3,000**",
 "[Ganghwa-gun](https://www.ganghwa.go.kr)",
 "Next to the UNESCO dolmen site. The blocks themselves are now at Haeinsa, but this is where they were made."),

("🥾","Ganghwa Nadeul-gil Trail (강화나들길)","🔁 daily (FREE)",
 "A 310 km network of 20 waymarked walking courses around Ganghwa Island — coastline, dyke paths, fortresses and rice fields",
 "Always open",
 "**FREE**",
 "[Ganghwa-gun](https://www.ganghwa.go.kr) · [Korea Trails](https://www.koreatrails.or.kr)",
 "Course 1 (Simdo History Trail, 18 km) from Ganghwa terminal is the classic. Maps at the tourist information centre."),

("♨️","Ganghwa Seokmodo Mineral Hot Spring (석모도미네랄온천)","🔁 daily",
 "An open-air seawater mineral hot spring on Seokmodo, **facing the Yellow Sea sunset** — outdoor pools right at the shoreline",
 "Daily roughly **07:00–19:00**",
 "Adult **₩9,000**",
 "[Ganghwa-gun](https://www.ganghwa.go.kr)",
 "Over the Seokmodo bridge. Sitting in a hot outdoor pool in cold November air watching the sun set into the sea is the whole point."),

("🍚","Ganghwa Jeondeungsa Temple Food & Templestay","🔁 daily",
 "Temple cuisine and overnight templestay at Jeondeungsa, inside the Samnangseong fortress walls — meditation, a 04:00 service and forest walking",
 "Templestay check-in typically **15:00**",
 "Templestay from **₩70,000** per night",
 "[templestay.com](https://www.templestay.com) · [jeondeungsa.org](http://www.jeondeungsa.org)",
 "English-language programmes must be booked through templestay.com in advance. An hour and a half from Seoul."),

("🍜","Incheon Chinatown Gonggalppang & Bakery Row","🔁 daily",
 "The hollow *gonggalppang* bread, walnut cakes, moon cakes and hand-pulled candy of the Chinatown bakeries",
 "Roughly **10:00–20:00**",
 "**₩3,000–₩8,000** a bag",
 "[Incheon Jung-gu tourism](https://www.icjg.go.kr)",
 "Buy gonggalppang hot — it's a hollow crisp shell and goes soft within an hour."),

("🎋","Incheon Chinese Cultural Centre & Confucius Statue","🔁 Tue–Sun (FREE)",
 "The cultural centre in Chinatown with calligraphy, tea ceremony and Chinese-Korean history exhibits, plus the Confucius statue on the main gate street",
 "Tue–Sun **09:00–18:00** (closed Mondays)",
 "**FREE**",
 "[Incheon Jung-gu tourism](https://www.icjg.go.kr)",
 "Free tea tasting is often running. The 140-year Chinese-Korean community story is unique in Korea."),

("🏫","Incheon Uhyeondang & Former Japanese Consulate Buildings","🔁 daily (FREE)",
 "The surviving Japanese, Chinese and Western consulate and merchant buildings of the 1883 treaty port, along the 'Modern Architecture Street'",
 "Exteriors always open; interiors Tue–Sun **09:00–18:00**",
 "Exteriors **FREE**",
 "[Incheon Jung-gu tourism](https://www.icjg.go.kr)",
 "The stone steps dividing the old Chinese and Japanese settlements are still there — Korea's clearest surviving colonial-era street plan."),

("🎨","Incheon Art Platform November Exhibitions & Open Studios","👀 WATCH (FREE)",
 "The Art Platform's resident artists open their studios and mount group shows in the autumn — check the exhibition calendar",
 "Tue–Sun **11:00–18:00**",
 "**FREE**",
 "[inartplatform.kr](https://www.inartplatform.kr)",
 "Programme published a month ahead. Free, and the warehouses themselves are worth the visit regardless."),

("🎭","Incheon Traditional Performance at Jemulpo Gurakbu","🔁 Tue–Sun (FREE)",
 "The 1901 **Jemulpo Club**, Korea's first Western social club, restored as a museum with period costume and occasional live performances",
 "Tue–Sun **09:00–18:00** (closed Mondays)",
 "**FREE**",
 "[Incheon Jung-gu tourism](https://www.icjg.go.kr)",
 "On the Jayu Park slope. Korea's first billiard table was installed here — it's still on display."),

("🚉","Incheon Station & Korea's First Railway (경인선)","🔁 daily (FREE)",
 "Korea's **first railway line** opened Noryangjin–Jemulpo in 1899; Incheon Station is its terminus, with a monument and displays",
 "Always open",
 "**FREE**; Line 1 fares from ₩1,400",
 "[letskorail.com](https://www.letskorail.com) · [Incheon Jung-gu tourism](https://www.icjg.go.kr)",
 "Line 1 terminus. Everything in Chinatown is at Exit 1 — the station itself is the historical marker."),

("🏞️","Cheongna Lake Park & Cheongna Canal (청라호수공원)","🔁 daily (FREE)",
 "The new-town lake park in Cheongna with a **musical fountain**, a 4 km canal walk and lit night promenades",
 "Park always open; fountain shows evenings",
 "**FREE**",
 "[IFEZ](https://www.ifez.go.kr) · [incheon.go.kr](https://www.incheon.go.kr)",
 "Incheon Line 2 + bus, or the airport rail to Cheongna International City Station. Quiet, well-designed and free."),

("🌸","Incheon Wolmi Traditional Garden (월미전통정원)","🔁 daily (FREE)",
 "A free reconstruction of Korean royal, aristocratic and folk gardens inside Wolmi Park — pavilions, ponds and a Joseon-style vegetable plot",
 "Daily **09:00–18:00** (Nov)",
 "**FREE**",
 "[Incheon Jung-gu tourism](https://www.icjg.go.kr)",
 "Beautiful in autumn colour and almost empty. Five minutes uphill from the Wolmido seafront crowds."),

("🍢","Yeonan Pier Crab & Shrimp Season Dining","✅ CONFIRMED — Nov peak",
 "**November is peak Yellow Sea season** for *daeha* prawns, blue crab and *jeoneo* gizzard shad — bought live at the market and cooked in the upstairs restaurants",
 "Market **05:00–20:00**; restaurants to **22:00**",
 "Salt-grilled prawns from **₩30,000** per kg",
 "[incheon.go.kr](https://www.incheon.go.kr) · [Incheon Port Authority](https://www.icpa.or.kr)",
 "Buy downstairs, pay a small cooking fee upstairs. This is the cheapest good seafood within an hour of Seoul."),

("🧊","Incheon Winter Illumination & Christmas Markets","👀 WATCH (mid-Nov onwards)",
 "Songdo Triple Street, Cheongna Lake Park and Bupyeong typically switch on their winter lighting from **mid-to-late November**",
 "Roughly **17:30–23:00** once lit",
 "**FREE**",
 "[incheon.go.kr](https://www.incheon.go.kr) · [triplestreet.co.kr](https://www.triplestreet.co.kr)",
 "Switch-on dates are announced in early November. Worth a check if you're here in the last week of the trip."),

("🎿","Incheon Airport Ice Rink & Seasonal Rinks","👀 WATCH (opens late Nov/Dec)",
 "Outdoor seasonal rinks open across Incheon each winter, including at Songdo and Bupyeong — **most open from late November or December**",
 "Typically **10:00–21:00** once open",
 "Around **₩1,000–₩5,000** per session including skates",
 "[incheon.go.kr](https://www.incheon.go.kr)",
 "Opening dates depend on temperature. Check the city site in mid-November if you want one before Nov 22."),

("🏊","Incheon Munhak & Public Sports Centres","🔁 daily",
 "Incheon's municipal sports centres offer cheap public swimming, gym and badminton sessions — a practical option on a rainy day",
 "Roughly **06:00–21:00**",
 "Swim session **₩4,000–₩6,000**",
 "[insiseol.or.kr](https://www.insiseol.or.kr)",
 "Bring your own cap — Korean pools require them and won't let you in without."),

("🗺️","Incheon Tourist Information Centres & Free Guided Walks","🔁 daily (FREE)",
 "Staffed information centres at Incheon Station, the airport and Songdo, several offering **free volunteer-guided walking tours** of the Open Port district",
 "Roughly **09:00–18:00**",
 "**FREE**; guided walks free with advance booking",
 "[itourtv.com](https://www.itourtv.com) · [incheon.go.kr](https://www.incheon.go.kr)",
 "Book English-language guided walks a few days ahead through the Incheon Tourism Organization site."),
]

append("/home/user/KoreaFun/incheon.md", E, 213, 3,
       "\n---\n\n## 🧭 Beginner-friendly essentials", "Incheon",
       intro="**Second expansion batch** — islands, Ganghwa heritage, new-town Songdo/Cheongna, seasonal November food and practical services.")
