# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "/home/user/KoreaFun/.build")
from addlib import append

E = [
# --- Chinatown & Open Port historic district ---
("🧧","Incheon Chinatown Paeru Gates & Samgukji Mural Street (인천 차이나타운)","🔁 daily (FREE)",
 "Korea's only official Chinatown, established 1884 — three ceremonial *paeru* gates, and a 150 m mural wall telling the whole Romance of the Three Kingdoms in 160 panels",
 "Streets always open; restaurants roughly **10:00–21:00**",
 "**FREE** to walk",
 "[Incheon Jung-gu tourism](https://www.icjg.go.kr) · [incheon.go.kr](https://www.incheon.go.kr)",
 "Line 1 Incheon Station Exit 1 — the first gate is directly across the road. Start here and walk uphill; everything in this list is within 15 minutes."),

("🍜","Jjajangmyeon Museum (짜장면박물관)","🔁 Tue–Sun",
 "The birthplace of Korea's national comfort dish — the former Gonghwachun restaurant (1905), now a museum on how Shandong dockworkers' noodles became Korean",
 "Tue–Sun **09:00–18:00** (closed Mondays)",
 "Adult **₩1,000**; youth ₩700; child ₩500",
 "[Incheon Jung-gu museums](https://www.icjg.go.kr)",
 "In the middle of Chinatown. ₩1,000 for a genuinely well-made museum, then eat jjajangmyeon 30 seconds away."),

("🏮","Gonghwachun & Chinatown Jjajangmyeon Restaurants","🔁 daily",
 "The Chinatown restaurant row where jjajangmyeon was invented — plus *jjamppong*, *tangsuyuk* and the yellow-boxed *gonggalppang* pastry",
 "Most restaurants **10:00–21:00**",
 "Jjajangmyeon **₩7,000–₩9,000**; tangsuyuk from ₩18,000",
 "[Incheon Jung-gu tourism](https://www.icjg.go.kr)",
 "Expect a queue at the famous ones on weekends. The white *baek-jjajang* version is the local speciality worth trying."),

("🧚","Songwol-dong Fairytale Village (송월동 동화마을)","🔁 daily (FREE)",
 "A declining 1900s residential quarter repainted in 2013 with murals and sculptures of Western fairy tales — an entire neighbourhood of Snow White, Peter Pan and Dorothy",
 "Always open; shops roughly **10:00–18:00**",
 "**FREE**",
 "[Incheon Jung-gu tourism](https://www.icjg.go.kr)",
 "Directly behind Chinatown, uphill. People live here — the murals are on their front walls, so keep it quiet."),

("🌳","Jayu Park (자유공원)","🔁 daily (FREE)",
 "**Korea's first Western-style public park**, opened 1888 — on the hill above the old foreign settlements, with the MacArthur statue and a harbour view",
 "Always open",
 "**FREE**",
 "[Incheon Jung-gu tourism](https://www.icjg.go.kr)",
 "Between Chinatown and the Open Port district. **Autumn foliage here is excellent in mid-November** and the harbour view is the best free one in Incheon."),

("🏛️","Incheon Open Port Modern Architecture Museum (인천개항장 근대건축전시관)","🔁 Tue–Sun",
 "Housed in the 1888 Japanese No. 18 Bank building — a museum of the treaty-port architecture that still stands in the streets outside",
 "Tue–Sun **09:00–18:00** (closed Mondays)",
 "Adult **₩500**; combined Open Port ticket **₩3,400** for four museums",
 "[Incheon Jung-gu museums](https://www.icjg.go.kr)",
 "**Buy the ₩3,400 combined ticket** — it covers this, the Open Port Museum, the Art Platform annexe and Jjajangmyeon Museum."),

("🏦","Incheon Open Port Museum (인천개항박물관)","🔁 Tue–Sun",
 "In the 1899 Japanese First Bank building — the story of Korea's first railway, first telegraph, first lighthouse and first modern port, all of which started here",
 "Tue–Sun **09:00–18:00** (closed Mondays)",
 "Adult **₩500** (or the ₩3,400 combined ticket)",
 "[Incheon Jung-gu museums](https://www.icjg.go.kr)",
 "Line 1 Incheon Station Exit 1, 8-min walk. Incheon is where modern Korea was physically plugged in — this museum makes that concrete."),

("⛪","Dapdong Cathedral (답동성당)","🔁 daily (FREE)",
 "Korea's oldest surviving Catholic church building outside Seoul (1897), a red-brick Romanesque basilica and National Historic Site No. 287",
 "Daily roughly **09:00–17:00** outside services",
 "**FREE**",
 "[Incheon Jung-gu tourism](https://www.icjg.go.kr) · [Catholic Diocese of Incheon](https://www.caincheon.or.kr)",
 "Line 1 Dongincheon Station Exit 2, 8-min walk uphill. The interior stained glass is worth the climb."),

("⛪","Incheon Naeri Methodist Church (내리교회)","🔁 daily (FREE)",
 "Founded 1885 by Henry Appenzeller — **the first Methodist church in Korea**, with a small museum on the arrival of Protestantism",
 "Daily roughly **10:00–17:00**",
 "**FREE**",
 "[Incheon Jung-gu tourism](https://www.icjg.go.kr)",
 "Near Jayu Park. The Appenzeller landing site marker down at the port is part of the same story."),

("🎨","Incheon Art Platform (인천아트플랫폼)","🔁 Tue–Sun (FREE)",
 "A block of 1930s–40s warehouses and offices converted into artist studios, galleries and performance spaces — Incheon's contemporary art hub",
 "Tue–Sun **11:00–18:00** (closed Mondays)",
 "**FREE**",
 "[inartplatform.kr](https://www.inartplatform.kr)",
 "Line 1 Incheon Station Exit 1, 5-min walk. Free, atmospheric, and the courtyard cafe is a good pause between museums."),

("🏠","Sudoguksan Museum of Housing and Living (수도국산달동네박물관)","🔁 Tue–Sun",
 "A full-scale reconstruction of a 1960s–70s Incheon hillside shantytown — the barbershop, the briquette shop, the shared toilet, the one-room homes",
 "Tue–Sun **09:00–18:00** (closed Mondays)",
 "Adult **₩1,000**",
 "[Incheon Dong-gu](https://www.icdonggu.go.kr)",
 "Line 1 Dongincheon Station + short bus. Genuinely one of the best small museums in Korea — it shows the poverty modern Korea came out of."),

("🚢","Museum of Korean Emigration History (한국이민사박물관)","🔁 Tue–Sun (FREE)",
 "Korea's national emigration museum, at Wolmido — because the first organised Korean emigrants sailed from Incheon to Hawaii in 1902",
 "Tue–Sun **09:00–18:00** (closed Mondays)",
 "**FREE**",
 "[Incheon Jung-gu museums](https://www.icjg.go.kr) · [incheon.go.kr](https://www.incheon.go.kr)",
 "Bus from Incheon Station to Wolmido. Free, well-designed, and it explains the Korean diaspora better than anything else in the country."),

("🎖️","Memorial Hall for Incheon Landing Operation (인천상륙작전기념관)","🔁 Tue–Sun (FREE)",
 "Museum of MacArthur's September 1950 amphibious landing, the operation that reversed the Korean War — with outdoor tanks, aircraft and landing craft",
 "Tue–Sun **09:00–18:00** (closed Mondays)",
 "**FREE**",
 "[incheon.go.kr](https://www.incheon.go.kr)",
 "Bus from Line 1 Dongincheon or Incheon Station. The outdoor hardware park is free and open even when the halls are closed."),

("🖼️","Incheon Metropolitan City Museum (인천광역시립박물관)","🔁 Tue–Sun (FREE)",
 "**Korea's first public municipal museum**, founded 1946 — Incheon's history from prehistory through the treaty port to the present",
 "Tue–Sun **09:00–18:00** (closed Mondays)",
 "**FREE**",
 "[icmuseum.incheon.go.kr](https://www.incheon.go.kr/museum)",
 "Next to the Incheon Landing memorial — do both in one trip. Free, air-conditioned and rarely busy."),

("💰","Incheon Metropolitan City Museum Coin Gallery & Compass Hall","🔁 Tue–Sun (FREE)",
 "The city museum's specialist wings — Korean currency history and a maritime navigation gallery, reflecting Incheon's port trade",
 "Tue–Sun **09:00–18:00** (closed Mondays)",
 "**FREE**",
 "[incheon.go.kr](https://www.incheon.go.kr)",
 "Included in the free city museum entry. Twenty extra minutes and worth it."),

# --- Wolmido ---
("🎡","Wolmi Theme Park (월미테마파크)","🔁 daily",
 "The old-school seafront amusement park at Wolmido — the Viking ship, the disco pang-pang and a Ferris wheel over the harbour",
 "Daily roughly **10:00–21:00** (weekday hours shorter in November)",
 "Individual rides **₩5,000–₩8,000**; freepass ~**₩25,000**",
 "[Incheon Jung-gu tourism](https://www.icjg.go.kr)",
 "Bus 2/10/45 from Incheon Station. The 'disco pang-pang' with its shouting DJ is a Korean institution — deeply silly and very fun."),

("🚋","Wolmi Sea Train (월미바다열차)","🔁 Tue–Sun",
 "Korea's longest urban tourist monorail — a 6.1 km elevated loop 7–18 m above Wolmido with four stations and views over the port and the old town",
 "Tue–Sun **10:00–18:00** (closed Mondays; last boarding 17:00)",
 "Adult **₩8,000**; youth ₩6,000; child ₩5,000",
 "[wolmiseatrain.or.kr](https://www.wolmiseatrain.or.kr)",
 "Boards at Wolmi Sea Train Station, next to Incheon Station. Forty minutes for the full loop; you can hop off at all four stops."),

("🌊","Wolmido Culture Street & Raw Fish Restaurants (월미문화의거리)","🔁 daily",
 "The seafront promenade at Wolmido — buskers, clam-grill tents, a *hoe* restaurant row and the ferry pier for Yeongjong",
 "Promenade always open; restaurants roughly **11:00–23:00**",
 "**FREE** to walk",
 "[Incheon Jung-gu tourism](https://www.icjg.go.kr)",
 "The sunset over the port here is the classic Incheon view. Grilled clams and soju at a plastic table is the correct order."),

("⛰️","Wolmi Park & Wolmi Observatory (월미공원·월미전망대)","🔁 daily (FREE)",
 "The wooded hill behind Wolmido, off-limits as a military zone until 2001 — a traditional garden, a forest walk and a free observatory over the Yellow Sea",
 "Park **05:00–23:00**; observatory roughly **09:00–18:00**",
 "**FREE**",
 "[Incheon Jung-gu tourism](https://www.icjg.go.kr) · [incheon.go.kr](https://www.incheon.go.kr)",
 "Behind the amusement park. Free observatory, free traditional garden, and almost nobody goes up."),

("⛵","Wolmido → Yeongjongdo Ferry (월미도–영종도 여객선)","🔁 daily",
 "The short car-and-passenger ferry across to Yeongjong Island — 10 minutes, with gulls following the boat for shrimp crackers",
 "Roughly every 30–40 min, **07:00–21:00**",
 "Passenger **₩3,000–₩4,000** one way",
 "[Incheon Port Authority](https://www.icpa.or.kr)",
 "The seagulls-and-shrimp-crackers ritual is a genuine Korean ferry tradition. Buy the crackers at the terminal."),

# --- Songdo ---
("🏙️","Songdo Central Park & Water Taxi (송도센트럴파크)","🔁 daily (FREE)",
 "The 41-hectare centrepiece of Songdo International Business City — a 1.8 km **seawater canal** through the skyscrapers, with boats, a deer park and a hanok village",
 "Park always open; boats roughly **10:00–21:00**",
 "Park **FREE**; water taxi **₩4,000**; kayak/canoe from ₩6,000",
 "[insiseol.or.kr](https://www.insiseol.or.kr) · [incheon.go.kr](https://www.incheon.go.kr)",
 "Incheon Line 1 Central Park Station Exit 3/4. The canal is filled with seawater, not fresh — unusual and it's why there are no mosquitoes."),

("🔭","G-Tower Observatory (G타워 전망대)","🔁 weekdays (FREE)",
 "The free 29th-floor observation deck in Songdo's government tower — the definitive view over Central Park, the Incheon Bridge and the reclaimed grid",
 "Weekdays roughly **09:00–18:00** (closed weekends and holidays)",
 "**FREE**",
 "[Incheon Free Economic Zone (IFEZ)](https://www.ifez.go.kr)",
 "Incheon Line 1 Central Park Station. **Weekdays only** — a lot of visitors turn up on Saturday and find it shut."),

("🏯","Songdo Hanok Village (송도한옥마을)","🔁 daily (FREE)",
 "A newly built traditional hanok quarter inside Central Park, with restaurants and tea houses — hanok roofs framed against glass towers",
 "Grounds always open; restaurants roughly **11:00–22:00**",
 "**FREE** to walk",
 "[incheon.go.kr](https://www.incheon.go.kr) · [IFEZ](https://www.ifez.go.kr)",
 "In Central Park. Architecturally artificial, photographically excellent — the hanok-and-skyscraper shot is the Songdo cliché for a reason."),

("🏢","Songdo Convensia (송도컨벤시아)","🔁 by event",
 "Incheon's international convention centre in Songdo, host of major expos, K-pop concerts and international conferences year-round",
 "By event; typically **10:00–18:00** for expos",
 "Varies by event",
 "[songdoconvensia.com](https://www.songdoconvensia.com)",
 "Incheon Line 1 Campus Town or Central Park Station. **Check the November event calendar in October** — Convensia regularly hosts large weekend expos."),

("🎨","Tri-bowl (트라이볼)","🔁 Tue–Sun (FREE)",
 "An upside-down-bowl concert and exhibition hall floating on a water plaza in Songdo — one of Korea's more striking pieces of public architecture",
 "Tue–Sun **10:00–18:00**; performances in the evening",
 "Exhibitions **FREE**; concerts ticketed",
 "[incheon.go.kr](https://www.incheon.go.kr) · [insiseol.or.kr](https://www.insiseol.or.kr)",
 "Incheon Line 1 Central Park Station Exit 3. Lit at night, and free to walk around."),

("🛍️","Triple Street Songdo (트리플스트리트)","🔁 daily",
 "A four-block open-air shopping street in Songdo — Korea's take on a European high street, with a large food hall and seasonal illumination",
 "Daily **10:30–22:00**",
 "**FREE** entry",
 "[triplestreet.co.kr](https://www.triplestreet.co.kr)",
 "Incheon Line 1 Technopark Station. **Winter illumination typically switches on in November** — worth checking."),

("🏬","Hyundai Premium Outlet Songdo (현대프리미엄아울렛 송도)","🔁 daily",
 "Large premium outlet mall in Songdo with a rooftop garden and a Songdo skyline view",
 "Daily **10:30–21:00**",
 "**FREE** entry",
 "[ehyundai.com](https://www.ehyundai.com)",
 "Incheon Line 1 Technopark Station + short walk. Practical if you want winter clothing at Korean outlet prices."),

("📚","Songdo Michuhol Library & Park (송도미추홀도서관)","🔁 Tue–Sun (FREE)",
 "Incheon's flagship public library with a lakeside reading room — a warm, quiet, free place to sit for an hour in Songdo",
 "Tue–Sun **09:00–18:00** (closed Mondays)",
 "**FREE**",
 "[library.incheon.go.kr](https://www.library.incheon.go.kr)",
 "Incheon Line 1 Central Park Station. Wi-Fi, power sockets and a view — an underrated rainy-day option."),

("🌉","Incheon Bridge Observation Point (인천대교 전망)","🔁 daily (FREE)",
 "Korea's longest bridge (21.4 km) linking Songdo to the airport island — viewable from the Songdo waterfront and the Incheon Bridge Memorial Hall",
 "Viewpoints always open",
 "**FREE** to view; toll applies if driving across",
 "[incheonbridge.com](https://www.incheonbridge.com)",
 "Best at sunset from the Songdo Waterfront Park side. Crossing it on the airport bus is free entertainment in itself."),

# --- Markets & city districts ---
("🍗","Sinpo International Market & Dakgangjeong (신포국제시장)","🔁 daily",
 "Incheon's historic market, open since the 1890s foreign settlement — and the birthplace of **dakgangjeong**, Korea's sweet-and-spicy fried chicken",
 "Roughly **09:00–20:00** (some stalls closed 2nd & 4th Sunday)",
 "Dakgangjeong from **₩12,000**; most snacks under ₩5,000",
 "[Incheon Jung-gu tourism](https://www.icjg.go.kr)",
 "Line 1 Dongincheon Station Exit 3. The dakgangjeong queue is long and worth it; also try the *gonggalppang* hollow bread."),

("🏪","Bupyeong Underground Shopping Mall (부평지하상가)","🔁 daily",
 "**Guinness-recognised as the world's largest underground shopping centre by number of shops** — 1,400+ stores in a subterranean grid under Bupyeong",
 "Daily roughly **10:30–21:30**",
 "**FREE** to browse",
 "[Bupyeong-gu](https://www.icbp.go.kr) · [incheon.go.kr](https://www.incheon.go.kr)",
 "Line 1/Incheon Line 1 Bupyeong Station. Genuinely disorienting — download the map. Cheapest clothing and accessories in the metro area."),

("🎪","Bupyeong Culture Street & Live Music (부평문화의거리)","🔁 daily",
 "The pedestrian street above the underground mall — Incheon's busiest nightlife and busking district, with a jazz heritage from the US base years",
 "Shops **11:00–22:00**; bars later",
 "**FREE** to walk",
 "[icbp.go.kr](https://www.icbp.go.kr)",
 "Line 1 Bupyeong Station Exit 3. Incheon has a real jazz history — the American bases here created Korea's first jazz scene."),

("🐟","Yeonan Pier Fish Market (연안부두 종합어시장)","🔁 daily",
 "Incheon's big working fish market at the coastal ferry terminal — Yellow Sea blue crab, shrimp and flatfish, cheaper than Seoul by a wide margin",
 "Roughly **05:00–20:00**",
 "**FREE** to browse",
 "[incheon.go.kr](https://www.incheon.go.kr) · [Incheon Port Authority](https://www.icpa.or.kr)",
 "Bus from Line 1 Dongincheon. **November is blue-crab and shrimp season** on the Yellow Sea — this is the place to eat them."),

("🦐","Sorae Pogu Fish Market (소래포구 종합어시장)","🔁 daily",
 "The most atmospheric fish market in the metro area — a former salt-trade harbour with an old rail bridge, mudflats and tanks of live crab and shrimp",
 "Roughly **06:00–21:00**",
 "**FREE** to browse; grilling fee ~₩5,000 pp",
 "[Namdong-gu](https://www.namdong.go.kr) · [incheon.go.kr](https://www.incheon.go.kr)",
 "Suin-Bundang Line Soraepogu Station Exit 2. **Autumn is peak season for *daeha* prawns** — buy them live and have them salt-grilled on the spot."),

("🌾","Sorae Ecology Park & Salt Farm (소래습지생태공원)","🔁 Tue–Sun (FREE)",
 "A restored salt farm and tidal wetland with wooden windmills, salt pans and a bird observatory — **November brings the migratory waders and the red *sea blite* flats**",
 "Tue–Sun **09:00–18:00** (closed Mondays)",
 "**FREE**",
 "[Namdong-gu](https://www.namdong.go.kr)",
 "Suin-Bundang Line Soraepogu Station. Walk the park, then eat at the fish market — that's the standard local Sunday."),

("🌳","Incheon Grand Park (인천대공원)","🔁 daily (FREE)",
 "Incheon's biggest park at the foot of Gwanmosan — a botanical garden, a zoo, a cycling loop and one of the metro area's best maple avenues",
 "Park **05:00–23:00**; zoo **09:00–18:00**",
 "Park **FREE**; zoo small charge; bike hire from ₩3,000/h",
 "[grandpark.incheon.go.kr](https://www.incheon.go.kr/grandpark)",
 "Incheon Line 2 Incheon Grand Park Station. **The maple avenue peaks in early-to-mid November** — one of the best foliage walks in the metro area."),

("🌲","Incheon Arboretum & Gwanmosan Trail","🔁 Tue–Sun (FREE)",
 "The arboretum inside Incheon Grand Park, plus the hiking trail up 216 m Gwanmosan for a view over the city and the sea",
 "Arboretum Tue–Sun **09:00–18:00**; trail always open",
 "**FREE**",
 "[incheon.go.kr](https://www.incheon.go.kr)",
 "Same station as Incheon Grand Park. An easy hour up and back with a genuine payoff view."),

("🎠","Wolmi Culture Village & Incheon Chinatown Night Lighting","🔁 nightly (FREE)",
 "The Chinatown gates, mural street and Jayu Park steps are lit after dark — a much quieter and prettier version of the daytime crowd",
 "Lighting roughly **sunset–23:00**",
 "**FREE**",
 "[Incheon Jung-gu tourism](https://www.icjg.go.kr)",
 "Line 1 Incheon Station. Most day-trippers leave by 18:00 — the evening is the good version."),

("🖌️","Korea Manhwa Museum (한국만화박물관)","🔁 Tue–Sun",
 "Korea's national comics museum (in neighbouring Bucheon, on the Incheon line) — the history of *manhwa* and *webtoon*, plus a 30,000-volume open reading library",
 "Tue–Sun **10:00–18:00** (closed Mondays)",
 "Adult **₩5,000**; youth ₩3,000",
 "[komacon.kr](https://www.komacon.kr)",
 "Line 7 Sanggok Station or Bucheon. Korea invented the vertical-scroll webtoon — this is where that story is told."),

("🎨","Paradise Art Space (파라다이스 아트 스페이스)","🔁 daily (FREE)",
 "The free contemporary art gallery inside Paradise City near the airport — Damien Hirst, Yayoi Kusama, Jeff Koons and Alessandro Mendini works on public display",
 "Daily roughly **10:00–19:00**",
 "**FREE**",
 "[p-city.com](https://www.p-city.com)",
 "Maglev from Incheon Airport T1 to Paradise City Station. A genuinely serious art collection, free, next to an airport — a brilliant layover option."),

("🚝","Incheon Airport Maglev Line (인천공항 자기부상철도)","🔁 daily (FREE)",
 "Korea's only urban maglev — a free 6.1 km magnetically levitated train from Terminal 1 to Yongyu, serving Paradise City and the water park",
 "Roughly **09:00–18:00**, every 15 min",
 "**FREE**",
 "[airport.kr](https://www.airport.kr)",
 "Board at Incheon Airport T1, level B1. A free maglev ride is a curiosity worth 20 minutes on a layover."),

("🏖️","Eurwangni Beach (을왕리해수욕장)","🔁 daily (FREE)",
 "The best-known beach on Yeongjong Island, 15 minutes from the airport — a west-coast beach whose whole point is the **sunset over the Yellow Sea**",
 "Always open; **sunset ~17:20 in November**",
 "**FREE**",
 "[Incheon Jung-gu tourism](https://www.icjg.go.kr)",
 "Bus 302/306 from the airport. The classic Korean move is a late-afternoon layover trip out here for the sunset and grilled clams."),

("🏝️","Wangsan & Masian Beach, Yeongjongdo","🔁 daily (FREE)",
 "The two quieter beaches next to Eurwangni — Wangsan has a marina, Masian has the widest mudflat at low tide",
 "Always open",
 "**FREE**",
 "[Incheon Jung-gu tourism](https://www.icjg.go.kr)",
 "Bus from the airport or Unseo Station. **Check the tide table** — at low tide the water is 1 km away, which is its own attraction."),

("🚲","Yeongjong Sea Side Rail Bike (영종씨사이드 레일바이크)","🔁 daily",
 "A 5.6 km pedal-powered rail bike along the Yeongjong coast with sea views the whole way",
 "Daily roughly **09:00–17:00** (Nov)",
 "2-seater **₩30,000**; 4-seater **₩40,000**",
 "[Incheon Jung-gu tourism](https://www.icjg.go.kr)",
 "Bus from Unseo Station. Book ahead on weekends. Cold and windy in November — dress for it."),

("🏝️","Muuido Island & Hanagae Beach (무의도)","🔁 daily",
 "The island south of the airport, now reachable by road bridge — Hanagae Beach, the Silmido causeway and a coastal ridge trail",
 "Always open; ferry to Silmido tide-dependent",
 "Beach entry small charge in season; **FREE** in November",
 "[Incheon Jung-gu tourism](https://www.icjg.go.kr)",
 "Bus 2-1 from Incheon Airport T1. The Silmido causeway only appears at low tide — check the tide table before going."),

("🌊","Silmido Island (실미도)","🔁 tide-dependent (FREE)",
 "The island of the notorious 1968 Unit 684 training camp and the film it inspired — reachable **on foot across a sand causeway at low tide only**",
 "Accessible around low tide; check tide tables",
 "**FREE**",
 "[Incheon Jung-gu tourism](https://www.icjg.go.kr) · [Korea Hydrographic and Oceanographic Agency](https://www.khoa.go.kr)",
 "From Muuido. **Getting the tide wrong strands you for six hours** — check khoa.go.kr, and turn back when the water starts returning."),

# --- Ganghwa Island ---
("🏯","Ganghwado Jeondeungsa Temple (전등사)","🔁 daily",
 "Korea's oldest continuously operating temple site, inside the walls of the legendary Samnangseong fortress — founded in 381 AD",
 "Daily roughly **08:00–18:00**",
 "Adult **₩4,000**",
 "[jeondeungsa.org](http://www.jeondeungsa.org) · [Ganghwa-gun](https://www.ganghwa.go.kr)",
 "Bus 3000 from Sinchon or Ganghwa terminal. **Mid-November foliage inside the fortress walls is excellent.** Templestay available."),

("🛡️","Gwangseongbo Fortress (광성보)","🔁 daily",
 "The riverside fort where Korean troops fought the 1871 American expedition to the last man — restored gun batteries along the Yeomha channel",
 "Daily **09:00–18:00** (Nov: last entry 17:00)",
 "Adult **₩1,100**",
 "[Ganghwa-gun](https://www.ganghwa.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "Bus from Ganghwa terminal. One of a chain of forts along the channel — Chojijin and Deokjinjin are on the same road."),

("🔭","Ganghwa Peace Observatory (강화평화전망대)","🔁 Tue–Sun",
 "An observatory 2.3 km from **North Korea** across the Han estuary — telescopes onto North Korean villages and fields, with a unification exhibition",
 "Tue–Sun **09:00–18:00** (closed Mondays; last entry 17:00)",
 "Adult **₩2,500**",
 "[Ganghwa-gun](https://www.ganghwa.go.kr)",
 "Bus from Ganghwa terminal. **Bring your passport** — there's a military checkpoint on the approach road. Closer to the North than Imjingak."),

("🧘","Bomunsa Temple, Seongmodo (보문사)","🔁 daily",
 "One of Korea's three great Buddhist prayer sites, on Seongmodo island — a 10 m Buddha carved into the cliff, up 419 steps, facing the Yellow Sea sunset",
 "Daily roughly **07:00–18:30**",
 "Adult **₩2,000**",
 "[bomunsa.or.kr](http://www.bomunsa.or.kr) · [Ganghwa-gun](https://www.ganghwa.go.kr)",
 "Bus to Oepo-ri, then the Seongmodo bridge bus. The 419 steps are real, but the cliff Buddha and sea view justify them."),

("🪨","Ganghwa Dolmen Site — UNESCO (강화 고인돌)","🔁 daily (FREE)",
 "UNESCO World Heritage prehistoric dolmens — including the enormous Bugeun-ri table dolmen, one of the largest in the world, next to the history museum",
 "Site always open; Ganghwa History Museum Tue–Sun **09:00–18:00**",
 "Dolmen site **FREE**; museum ₩3,000",
 "[UNESCO](https://whc.unesco.org/en/list/977) · [Ganghwa-gun](https://www.ganghwa.go.kr)",
 "Bus from Ganghwa terminal. Korea has roughly **40% of all the dolmens on Earth** — this is the flagship site."),

("🧵","Ganghwa Hwamunseok & Textile Museum (강화화문석·소창체험관)","🔁 Tue–Sun",
 "Ganghwa's two craft traditions — *hwamunseok* patterned sedge mats (a royal tribute good) and the cotton mills that clothed post-war Korea",
 "Tue–Sun **09:00–18:00** (closed Mondays)",
 "**FREE** to ₩2,000; workshops extra",
 "[Ganghwa-gun](https://www.ganghwa.go.kr)",
 "In Ganghwa town. The cotton-mill experience hall is in a working former mill and does hands-on weaving."),

("🌾","Ganghwa Ssuk (Mugwort) & Local Market","🔁 daily",
 "Ganghwa's five-day market and its famous mugwort, ginseng and *sunmu* turnip — a proper rural Korean market an hour from Seoul",
 "Permanent market daily; **five-day market on dates ending 2 and 7**",
 "**FREE** to browse",
 "[Ganghwa-gun](https://www.ganghwa.go.kr)",
 "Ganghwa bus terminal. Time your visit for a 2 or 7 date and you get the full five-day market."),

# --- Practical, sport, seasonal ---
("✈️","Incheon Airport Cultural Programmes & Transit Tours","🔁 daily (FREE)",
 "ICN runs free traditional performances, a Korean Cultural Street, museums airside and **free transit tours** for passengers with 5+ hour layovers",
 "Cultural performances several times daily; transit tours **07:00–17:00** departures",
 "**FREE**",
 "[airport.kr](https://www.airport.kr)",
 "Sign up at the Transit Tour desk in the transit area. The 1-hour Chinatown and 5-hour Seoul city tours are genuinely free — you just pay for food."),

("🛏️","Incheon Airport Free Spa, Nap Zones & Sky Deck","🔁 24 h (FREE)",
 "ICN's free passenger facilities — shower rooms, nap zones, a free spa area, a rooftop sky deck, a library and an indoor garden",
 "**24 h**",
 "Most facilities **FREE**; premium spa lounges charged",
 "[airport.kr](https://www.airport.kr)",
 "Consistently voted the world's best airport for a reason. Useful for an early departure on Nov 22."),

("🎢","Paradise City Wonderbox & Cimer Spa","🔁 daily",
 "The indoor European-carnival theme park and the Cimer thermal spa inside Paradise City, both open to non-hotel guests",
 "Wonderbox roughly **11:00–20:00**; Cimer **10:00–21:00**",
 "Wonderbox from **₩35,000**; Cimer from **₩50,000**",
 "[p-city.com](https://www.p-city.com) · [cimer.kr](https://www.cimer.kr)",
 "Free maglev from Terminal 1. Cimer's outdoor heated pools in cold November air are the correct move."),

("⚽","K League — Incheon United home fixtures (인천유나이티드)","👀 WATCH — season ending",
 "Incheon United at Sungui Arena Park, one of Korea's few purpose-built football-only stadiums with steep, close stands. **The K League season ends in late November**",
 "Kick-off typically **14:00/16:00** at weekends in November",
 "Tickets **₩12,000–₩25,000**",
 "[incheonutd.com](https://www.incheonutd.com) · [kleague.com](https://www.kleague.com)",
 "Line 1 Dowon Station, 5-min walk. Final-round fixtures are confirmed only a few weeks ahead — check kleague.com in late October."),

("🏟️","Incheon Munhak Stadium & Landers Field (인천문학경기장)","🔁 by event",
 "The 2002 World Cup stadium and the adjacent SSG Landers baseball park. **KBO baseball finishes before November**, but the complex hosts concerts and events",
 "By event",
 "Varies",
 "[ssglanders.com](https://www.ssglanders.com) · [incheon.go.kr](https://www.incheon.go.kr)",
 "Incheon Line 1 Munhak Sportscomplex Station. Check for November concerts — the stadium is a regular large-scale venue."),

("🏀","KBL Basketball — Incheon-area home games","✅ CONFIRMED — season running",
 "The Korean Basketball League runs through the winter, so there are **guaranteed November games** in the Seoul–Incheon metro area",
 "Tip-off typically **19:00** weekdays, **14:00/16:00** weekends",
 "Tickets **₩8,000–₩30,000**",
 "[kbl.or.kr](https://www.kbl.or.kr)",
 "Check the KBL fixture list for the nearest home game. Indoor, cheap and reliable in cold weather."),

("🚴","Ara Waterway Cycle Path (아라뱃길 자전거길)","🔁 daily (FREE)",
 "The 21 km canal cycle path from the Yellow Sea at Jeongseojin to the Han River — flat, separated and part of Korea's national bike-certification route",
 "Always open",
 "**FREE**; bike hire from ₩10,000/day",
 "[Korea Water Resources Corporation](https://www.kwater.or.kr) · [Bike Korea passport](https://www.riverguide.go.kr)",
 "Start at Incheon Line 2 Geomdan Oryu Station. You can get a stamp in the national bicycle passport at the certification booths."),

("🌅","Jeongseojin Sunset & Ara Sea Lock (정서진)","🔁 daily (FREE)",
 "The westernmost point on the same latitude as Seoul's Gwanghwamun — a designated sunset landmark with a lighthouse-shaped monument at the canal mouth",
 "Always open; **sunset ~17:20 in November**",
 "**FREE**",
 "[incheon.go.kr](https://www.incheon.go.kr) · [Seo-gu](https://www.seo.incheon.kr)",
 "Incheon Line 2 Geomdan Oryu + bus. Korea has Jeongdongjin for sunrise on the east coast; **Jeongseojin is its sunset counterpart**."),

("🧂","Incheon Salt Museum & Sorae Salt Farm History","🔁 Tue–Sun (FREE)",
 "A small museum in the old Sorae salt works on how Korea's west-coast solar salt was made — the industry that built this coastline",
 "Tue–Sun **09:00–18:00** (closed Mondays)",
 "**FREE**",
 "[Namdong-gu](https://www.namdong.go.kr)",
 "In Sorae Ecology Park. Korean *cheonilyeom* solar salt is a premium export product — this explains why."),

("🚋","Incheon Subway Line 2 & the Wolmi Loop day pass","🔁 daily",
 "Incheon's driverless Line 2 crosses the whole city; combined with Line 1 and the Suin-Bundang Line it reaches every attraction in this file",
 "Roughly **05:30–24:00**",
 "Single fares from **₩1,400**; T-money accepted",
 "[ictr.or.kr](https://www.ictr.or.kr) · [incheon.go.kr](https://www.incheon.go.kr)",
 "Seoul's T-money works throughout. Line 2 trains are unstaffed — sit at the front window for the driver's view."),

("🍚","Incheon Hwadojin & Sinpo Chicken, Coast Cafes","🔁 daily",
 "The coastal cafe and restaurant strip along the Incheon shoreline — sea-view cafes at Yeongjong and the Songdo waterfront",
 "Most **10:00–22:00**",
 "Coffee **₩5,000–₩8,000**",
 "[incheon.go.kr](https://www.incheon.go.kr)",
 "The Yeongjong-side cafes look straight at the Incheon Bridge and the airport approach path — good plane-spotting."),

("🛫","Incheon Airport Sky72 & Aviation Viewpoints","🔁 daily (FREE)",
 "Public viewpoints around the airport perimeter for watching landings over the Yellow Sea — plus the airport's own observation decks",
 "Always open; terminal decks roughly **07:00–21:00**",
 "**FREE**",
 "[airport.kr](https://www.airport.kr)",
 "One of the world's busiest airports, and free to watch. The T1 4th-floor deck is the easiest access."),

("🎏","Incheon City Tour Bus (인천시티투어)","🔁 Tue–Sun",
 "The official hop-on-hop-off city tour with themed routes covering Chinatown, the Open Port, Songdo, Wolmido and the Ganghwa heritage sites",
 "Tue–Sun, roughly **09:30–17:30**",
 "1-day pass adult **₩10,000–₩15,000** depending on route",
 "[itourtv.com](https://www.itourtv.com) · [incheon.go.kr](https://www.incheon.go.kr)",
 "Departs Incheon Station. The Ganghwa route is the one that's genuinely hard to replicate on public transport."),

("🌃","Incheon Songdo Night Skyline & Northeast Asia Trade Tower","🔁 daily",
 "Korea's 5th-tallest building (305 m) anchoring the Songdo skyline, with an observation deck and sky restaurants",
 "Observation deck roughly **10:00–20:00**",
 "Deck **₩10,000–₩15,000**; the Central Park view is free",
 "[incheon.go.kr](https://www.incheon.go.kr) · [IFEZ](https://www.ifez.go.kr)",
 "Incheon Line 1 International Business District Station. The free view from Central Park at night is arguably the better photograph."),

("🎇","Incheon Pentaport & Songdo festival grounds — off-season","👀 WATCH",
 "Songdo's Moonlight Festival Park and the Pentaport grounds host outdoor events through the year; the big rock festival itself is summer",
 "By event",
 "Varies; many city events **FREE**",
 "[incheon.go.kr](https://www.incheon.go.kr) · [pentaportrock.com](https://www.pentaportrock.com)",
 "Check the Incheon city event calendar in October for November weekend programmes at the Songdo festival grounds."),

("🧗","Gyeyangsan Mountain & Paragliding (계양산)","🔁 daily (FREE)",
 "Incheon's highest peak at 395 m — an easy 90-minute climb with a view over the whole city to the sea, and a paragliding launch site",
 "Always open",
 "Hiking **FREE**; tandem paragliding from ₩100,000",
 "[Gyeyang-gu](https://www.gyeyang.go.kr) · [incheon.go.kr](https://www.incheon.go.kr)",
 "Incheon Line 1 Gyeyang Station + bus. The best cheap panorama of Incheon, and busy with local hikers at weekends."),

("🍂","Incheon Autumn Foliage — Jayu Park & Grand Park peak week","✅ CONFIRMED — peak early-to-mid Nov",
 "Incheon's foliage peaks slightly **later than Seoul** because of the maritime climate — Jayu Park, Incheon Grand Park and Jeondeungsa are the three best sites",
 "Daylight hours; peak typically **Nov 5–15**",
 "**FREE**",
 "[Korea Forest Service foliage forecast](https://www.forest.go.kr) · [incheon.go.kr](https://www.incheon.go.kr)",
 "The Korea Forest Service publishes a national foliage-peak map each autumn — check it in late October to time this precisely."),
]

append("/home/user/KoreaFun/incheon.md", E, 143, 3,
       "\n---\n\n## 🧭 Beginner-friendly essentials", "Incheon")
