# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "/home/user/KoreaFun/.build")
from addlib import append

E = [
("🏰","Gochang Eupseong Walled Town day trip (고창읍성)","🔁 daily",
 "A complete 1453 Joseon fortress wall of 1.7 km that you can walk in full, with a local tradition of circling it with a stone on your head",
 "Daily **09:00–18:00** (Nov: to 17:00)",
 "Adult **₩3,000**",
 "[gochang.go.kr](https://www.gochang.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "Beside Gochang bus terminal. Combine with the UNESCO dolmen site the same day."),

("🌿","Seonunsa Temple & Camellia Forest, Gochang (선운사)","🔁 daily",
 "A 577 CE temple with a **natural camellia forest designated a Natural Monument** and one of Jeolla's best autumn valleys",
 "Daily **06:00–19:00** (Nov: to 18:00)",
 "Adult **₩4,000**",
 "[seonunsa.org](http://www.seonunsa.org) · [gochang.go.kr](https://www.gochang.go.kr)",
 "**Late-November maples along the temple stream are the reason to come in your window.**"),

("🐚","Gochang Getbol Tidal Flat — UNESCO (고창갯벌)","🔁 daily (FREE)",
 "Part of the **UNESCO-listed Getbol, Korean Tidal Flats**, with a boardwalk over the mud and huge migratory bird numbers in November",
 "Always open; go at low tide",
 "**FREE**",
 "[UNESCO](https://whc.unesco.org/en/list/1591) · [gochang.go.kr](https://www.gochang.go.kr)",
 "**Check the tide table before going** — at high tide there is nothing to see."),

("🏝️","Byeonsanbando National Park day trip (변산반도)","🔁 daily (FREE)",
 "**Korea's only national park combining coast and mountains**, an hour west of Jeonju, with sea cliffs, Naesosa temple and the Chaeseokgang rock strata",
 "Always open",
 "Park **FREE**; Naesosa ₩4,000",
 "[knps.or.kr](https://www.knps.or.kr) · [buan.go.kr](https://www.buan.go.kr)",
 "**Chaeseokgang's layered cliffs are only accessible at low tide** — check tides first."),

("🛕","Naesosa Temple, Buan (내소사)","🔁 daily",
 "A 633 CE temple approached through a 600-metre fir avenue, famous for its unpainted, hand-carved lattice flower doors",
 "Daily **07:00–18:00** (Nov: to 17:00)",
 "Adult **₩4,000**",
 "[naesosa.org](http://www.naesosa.org) · [knps.or.kr](https://www.knps.or.kr)",
 "The fir avenue alone is worth the trip. Bus from Buan or Jeonju."),

("🧂","Gomso Salt Farm & Jeolla Sea Salt (곰소염전)","🔁 daily (FREE to view)",
 "Traditional evaporation salt pans on the Byeonsan coast producing Korea's prized *cheonilyeom* sun-dried salt, with a market alongside",
 "Daylight hours",
 "**FREE** to view",
 "[buan.go.kr](https://www.buan.go.kr)",
 "Harvest season is over by November but the pans, the market and the salted-fish stalls are open."),

("🍲","Buan & Byeonsan Seafood — bajirak & jeotgal","🔁 daily",
 "The Jeolla west coast's clam bibimbap, salted seafood and raw fish, at Gyeokpo port and along the Byeonsan road",
 "Most **10:00–21:00**",
 "Clam bibimbap **₩12,000–₩15,000**",
 "[buan.go.kr](https://www.buan.go.kr)",
 "Gyeokpo port has a purpose-built seafood market building. Cash is still handy at the smaller stalls."),

("🌊","Saemangeum Seawall & Gunsan day trip (새만금방조제)","🔁 daily (FREE)",
 "**The world's longest man-made sea dyke at 33.9 km**, drivable end to end, with observation decks over reclaimed tidal land",
 "Always open",
 "**FREE**",
 "[saemangeum.go.kr](https://www.saemangeum.go.kr) · [gunsan.go.kr](https://www.gunsan.go.kr)",
 "A Guinness-recognised record. Best by car; buses run to the Sinsi-do midpoint."),

("🏯","Gunsan Modern History Museum & Japanese Quarter (군산근대역사박물관)","🔁 Tue–Sun",
 "Gunsan preserves **Korea's largest concentration of colonial-era Japanese buildings**, including a 1930s temple, a bank and a merchant's house",
 "Tue–Sun **09:00–18:00** (closed Mon)",
 "Adult **₩2,000**; combined ticket ₩3,000",
 "[museum.gunsan.go.kr](https://museum.gunsan.go.kr) · [gunsan.go.kr](https://www.gunsan.go.kr)",
 "Bus Jeonju → Gunsan, 1 hour. The walking loop of colonial buildings takes about three hours."),

("🥖","Gunsan Lee Sung Dang Bakery (이성당)","🔁 daily",
 "**Korea's oldest surviving bakery, opened 1945**, famous nationwide for its red-bean bread and vegetable bread — with a permanent queue",
 "Daily **08:00–22:00**",
 "Buns **₩2,000–₩3,000**",
 "[leesungdang1945.com](http://www.leesungdang1945.com) · [gunsan.go.kr](https://www.gunsan.go.kr)",
 "**Fresh batches come out roughly hourly** — ask when the next one is due rather than buying cold stock."),

("🚢","Gunsan Port, Sinheung-dong & Film Locations","🔁 daily (FREE)",
 "The old Sinheung-dong quarter and Gunsan port area used as a location for dozens of Korean period films, preserved as a heritage district",
 "Always open",
 "**FREE**",
 "[gunsan.go.kr](https://www.gunsan.go.kr)",
 "The Hiroetsu House and the old customs building anchor the walk. Free and easy to self-guide."),

("🏞️","Wanju Daedunsan Provincial Park & Cloud Bridge (대둔산)","🔁 daily",
 "A rock-spire mountain 40 minutes from Jeonju, crossed by a **50-metre suspension cloud bridge and a 127-step steel staircase** between peaks",
 "Cable car daily **09:00–17:00**",
 "Cable car **₩11,000** return; bridge ₩1,000",
 "[wanju.go.kr](https://www.wanju.go.kr) · [Korea Forest Service](https://www.forest.go.kr)",
 "**Spectacular and genuinely vertiginous.** Bus from Jeonju to Daedunsan, about 50 minutes."),

("🍂","Wanju Songgwangsa & Wibongsa Temples (송광사·위봉사)","🔁 daily",
 "Two Wanju county temples near Jeonju — Songgwangsa with its cherry avenue and Wibongsa inside a Joseon mountain fortress",
 "Daily **08:00–18:00**",
 "**FREE** / ₩2,000",
 "[wanju.go.kr](https://www.wanju.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "Not to be confused with the larger Songgwangsa in Suncheon. Both are quiet and close to Jeonju."),

("💧","Wibong Waterfall & Wanju Sanseong Trails (위봉폭포)","🔁 daily (FREE)",
 "A 60-metre two-tier waterfall in Wanju, one of the eight scenic views of old Wansan, with short trails to the fortress walls above",
 "Always open",
 "**FREE**",
 "[wanju.go.kr](https://www.wanju.go.kr)",
 "Twenty minutes from Jeonju by car. Easy, short and rarely visited."),

("🌳","Wanju Aegi Bongsan & Sangkwan Maple Road (상관 편백숲)","🔁 daily (FREE)",
 "A planted cypress forest just south of Jeonju used for forest bathing, with soft paths and a nationally known maple drive nearby",
 "Daylight hours",
 "**FREE**",
 "[wanju.go.kr](https://www.wanju.go.kr) · [Korea Forest Service](https://www.forest.go.kr)",
 "Twenty minutes by bus from Jeonju. The cypress air is the point — go slow."),

("🏛️","Iksan Mireuksa Temple Site — UNESCO (익산 미륵사지)","🔁 daily (FREE)",
 "Part of the **UNESCO Baekje Historic Areas**: the ruins of what was Korea's largest ancient temple, with the restored 7th-century stone pagoda",
 "Always open; museum Tue–Sun **09:00–18:00**",
 "**FREE**",
 "[UNESCO](https://whc.unesco.org/en/list/1477) · [iksan.go.kr](https://www.iksan.go.kr)",
 "Train Jeonju → Iksan (30 min) then bus. **The reassembled Mireuksa pagoda is the oldest and largest stone pagoda in Korea.**"),

("👑","Iksan Wanggung-ri Historic Site — UNESCO (왕궁리 유적)","🔁 Tue–Sun (FREE)",
 "The **UNESCO-listed** Baekje royal palace site at Iksan, with a five-storey stone pagoda and an excellent free museum of excavated gold work",
 "Site always open; museum Tue–Sun **09:00–18:00**",
 "**FREE**",
 "[UNESCO](https://whc.unesco.org/en/list/1477) · [iksan.go.kr](https://www.iksan.go.kr)",
 "Combine with Mireuksa on one Iksan day trip. Both are free."),

("💎","Iksan Jewelry Museum & Baekje Culture (익산보석박물관)","🔁 Tue–Sun",
 "Iksan has been Korea's jewellery-processing centre since the 1970s; the museum shows gemstones, fossils and Baekje gold reproductions",
 "Tue–Sun **10:00–18:00** (closed Mon)",
 "Adult **₩3,000**",
 "[jewelmuseum.go.kr](https://www.jewelmuseum.go.kr) · [iksan.go.kr](https://www.iksan.go.kr)",
 "Unusual, cheap and good with children. Near the Wanggung-ri site."),

("🌾","Gimje Byeokgolje Reservoir & Horizon Festival site (벽골제)","🔁 Tue–Sun",
 "The remains of **Korea's oldest reservoir, built in 330 CE**, on the country's only true horizon-to-horizon plain, with an agricultural museum",
 "Tue–Sun **09:00–18:00** (closed Mon)",
 "Adult **₩3,000**",
 "[gimje.go.kr](https://www.gimje.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "The Gimje Horizon Festival is in early October; in November the site is quiet but open."),

("🛤️","Jeonju Hanok Village Night Walk & Illumination","🔁 nightly (FREE)",
 "The village lights its main gates, Gyeonggijeon walls, Jeondong Cathedral and Cheongyeonru after dark — a completely different and much emptier experience",
 "Lighting roughly **18:00–23:00**",
 "**FREE**",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "**Sunset is around 17:20 in November.** The day-trip crowds leave by 18:00 — this is the best time to be here."),

("🌡️","Jeonju Hanok Village Ondol & Cold-Weather Tips","🔁 seasonal",
 "November nights in Jeonju drop to 3–5 °C; hanok rooms rely on heated floors, and many village cafes and shops are only partly heated",
 "N/A",
 "**FREE** advice",
 "[weather.go.kr](https://www.weather.go.kr) · [tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "**Bring layers and thick socks** — you will be sitting on floors, and shoes come off constantly."),

("🎒","Jeonju Luggage Storage & Station Lockers","🔁 daily",
 "Coin lockers at Jeonju Station and the express bus terminal, plus paid storage at the hanok village information centre",
 "Roughly **06:00–23:00**",
 "**₩2,000–₩5,000** per day",
 "[letskorail.com](https://www.letskorail.com) · [tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "**The village storage desk is the useful one** if you're doing Jeonju as a day trip between trains."),

("💳","Jeonju Payments, ATMs & Market Cash","🔁 daily",
 "Cards work almost everywhere, but Nambu Market stalls, the night market and small makgeolli houses are often cash-only",
 "ATMs **24 h**",
 "N/A",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "**Carry ₩50,000 in cash for market nights.** Global-card ATMs are in the CU and GS25 near Pungnammun."),

("🧳","Jeonju as a base vs a day trip","🔁 planning",
 "Jeonju rewards an overnight — the village empties after 18:00 and the makgeolli alleys and night market only happen in the evening",
 "N/A",
 "N/A",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "**Recommendation: one night minimum.** Arrive early afternoon, do the village at dusk, eat at the night market."),

("🕌","Jeonju Halal, Vegetarian & Temple Food Options","🔁 daily",
 "Bibimbap is easily made vegetarian on request, several hanok-village restaurants serve Buddhist temple cuisine, and halal options exist near the universities",
 "Most **11:00–21:00**",
 "Temple set from **₩15,000**",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr) · [visitkorea.or.kr](https://english.visitkorea.or.kr)",
 "Ask for bibimbap **without gochujang-with-beef and without the raw beef** — most places manage it easily."),

("🎎","Jeonju Traditional Culture Center & Nori Madang (전주전통문화관)","🔁 Tue–Sun (FREE)",
 "A city-run centre in the hanok village running free traditional performances, tea ceremony and craft classes on a published monthly schedule",
 "Tue–Sun **10:00–18:00** (closed Mon)",
 "Many programmes **FREE**",
 "[jjcc.or.kr](http://www.jjcc.or.kr) · [tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "**Check the monthly programme board on arrival** — the free weekend performances are genuinely good."),

("🏵️","Jeonju Hyanggyo Autumn Rite & Cultural Events","👀 WATCH",
 "The Confucian school and Gyeonggijeon hold seasonal rites and re-enactments; the hyanggyo also runs free hanbok and etiquette programmes",
 "By event, usually weekends",
 "**FREE**",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "Dates are announced locally with little notice — ask at the village information centre."),

("📷","Jeonju Photo Spots — the definitive list","🔁 daily (FREE)",
 "Omokdae rooftop panorama, the Jeonjucheon stepping stones, Jeonjuhyanggyo ginkgos, Jeondong Cathedral's facade and the Eunhaeng-ro alleys",
 "Best **07:30–09:00** and after dark",
 "**FREE**",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "**Before 09:00 you can photograph the main street essentially empty.** After 11:00 you cannot."),

("🧴","Jeonju Hanji Products & Souvenir Shopping","🔁 daily",
 "Hanji lamps, notebooks, fans and dolls made locally, sold at the Crafts Exhibition Hall, the Hanji Museum shop and village stores",
 "Roughly **10:00–19:00**",
 "**₩5,000–₩50,000**",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "**Buy at the Crafts Exhibition Hall** — same makers, better prices and no tourist markup."),

("🥘","Jeonju Hanjeongsik Full-Table Banquet (한정식)","🔁 daily",
 "The Jeolla full-course meal — twenty to thirty side dishes arriving at once — the regional cuisine at its most complete",
 "Lunch **12:00–14:30**; dinner **17:30–21:00**",
 "**₩25,000–₩60,000** per person",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr) · [UNESCO Creative Cities](https://www.unesco.org/en/creative-cities)",
 "**Reserve a day ahead** and go hungry. Minimum two people at nearly every restaurant."),

("🍢","Jeonju Piyanggi & Grilled Offal Alley (피순대)","🔁 daily",
 "Jeonju's blood sausage — thicker and offal-rich compared to the national version — sold at Nambu Market and a dedicated alley nearby",
 "Roughly **10:00–22:00**",
 "**₩10,000–₩14,000**",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "*Sundae-guk* soup is the gentler entry point if the sausage plate looks daunting."),

("🍵","Jeonju Tea Houses & Traditional Sweets","🔁 daily",
 "Hanok tea houses in the village serving *omija*, *ssanghwa* medicinal tea and *hangwa* sweets — the warm-up stop on a cold November afternoon",
 "Roughly **10:00–21:00**",
 "Tea **₩6,000–₩9,000**",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "**Ssanghwa-cha with pine nuts and jujube is the November drink** — it's a herbal tonic served hot."),

("🐦","Jeonjucheon Stream Birdwatching & Ecology (전주천)","🔁 daily (FREE)",
 "The restored city stream now supports otters, herons and **overwintering ducks that arrive in November** — a signature Korean urban-restoration success",
 "Always open",
 "**FREE**",
 "[jeonju.go.kr](https://www.jeonju.go.kr) · [me.go.kr](https://www.me.go.kr)",
 "The stretch below Hanbyeokdang is the richest. Early morning is best."),

("🏃","Jeonju Running & Walking Routes","🔁 daily (FREE)",
 "The Jeonjucheon and Samcheon stream paths give a flat, continuous, traffic-free loop of about 12 km through the city",
 "Always open",
 "**FREE**",
 "[jeonju.go.kr](https://www.jeonju.go.kr)",
 "Lit at night. **Cool, dry November mornings are ideal running conditions here.**"),

("🏛️","Jeonju City Hall Observatory & Free Viewpoints","🔁 weekdays (FREE)",
 "Free public viewing floors at Jeonju City Hall and the Jeollabuk-do provincial building give city-wide views without paying for a tower",
 "Weekdays roughly **09:00–18:00**",
 "**FREE**",
 "[jeonju.go.kr](https://www.jeonju.go.kr)",
 "Ask at the lobby desk. A quirky free alternative to Omokdae if the weather is clear."),

("🎨","Jeonju Modern Art & Palbok Art Factory (팔복예술공장)","🔁 Tue–Sun (FREE)",
 "A disused cassette-tape factory converted into a contemporary art centre with studios, exhibitions and a cafe",
 "Tue–Sun **10:00–18:00** (closed Mon)",
 "**FREE**",
 "[palbokart.kr](http://www.palbokart.kr) · [jeonju.go.kr](https://www.jeonju.go.kr)",
 "In the industrial north of the city. The best contemporary counterweight to the hanok village."),

("🎠","Jeonju Ohn Culture Center & Family Programmes","🔁 Tue–Sun",
 "City-run family and children's culture facilities with indoor play, craft workshops and a children's library — useful on a cold or wet day",
 "Tue–Sun **10:00–18:00**",
 "**FREE** to ₩3,000",
 "[jeonju.go.kr](https://www.jeonju.go.kr)",
 "Book online for weekend slots; weekdays are usually walk-in."),

("🌏","Jeonju International Community & Language Exchange","🔁 weekly (FREE)",
 "The Jeonju Global Center runs free Korean classes, language exchanges and a foreigner help line in English",
 "Weekdays **09:00–18:00**",
 "**FREE**",
 "[jeonju.go.kr](https://www.jeonju.go.kr) · [1330 Tourist Hotline](https://english.visitkorea.or.kr)",
 "**Dial 1330 for 24-hour English tourist help anywhere in Korea** — free from any phone."),

("🚑","Jeonju Emergency, Pharmacy & Medical Info","🔁 24 h",
 "Jeonju has two large university hospitals with 24-hour emergency departments, and pharmacies signed 약국 across the centre",
 "Emergency **24 h**; pharmacies roughly **09:00–20:00**",
 "Consultation from **₩20,000** for visitors",
 "[Jeonbuk National University Hospital](https://www.jbuh.co.kr) · [1339 Medical Hotline](https://www.kdca.go.kr)",
 "**119 for ambulance, 1339 for medical advice in English.** Travel insurance strongly recommended."),

("📋","Jeonju One-Day and Two-Day Model Routes","🔁 planning",
 "Day 1: Gyeonggijeon → Cathedral → Taejo-ro → Omokdae → Jaman → dusk lighting → makgeolli alley. Day 2: Nambu Market → Hanji Museum → Deokjin Park → Palbok Art Factory",
 "N/A",
 "N/A",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "**Add a third day for Naejangsan or Maisan** if your window allows — both are outstanding in November."),
]

append("/home/user/KoreaFun/jeonju.md", E, 187, 3,
       "\n---\n\n## 🧭 Beginner-friendly essentials", "Jeonju")
