# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "/home/user/KoreaFun/.build")
from addlib import append

E = [
("🏘️","Jeonju Hanok Village — the full 800-house district (전주한옥마을)","🔁 daily (FREE)",
 "**Korea's largest surviving hanok district** — over 800 traditional houses in Pungnam-dong and Gyo-dong, built from the 1930s as a Korean quarter in a Japanese-administered city",
 "Streets always open; individual houses roughly **09:00–18:00**",
 "Streets **FREE**",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr) · [visitkorea.or.kr](https://english.visitkorea.or.kr)",
 "Bus 79/119 from Jeonju Station (20 min). **Go early — by 11:00 in autumn it is genuinely crowded.**"),

("👑","Gyeonggijeon Shrine & Royal Portrait Museum (경기전)","🔁 Tue–Sun",
 "The 1410 shrine holding the **portrait of King Taejo**, founder of the Joseon dynasty, whose Yi clan originated in Jeonju — plus the adjoining royal portrait museum",
 "Daily **09:00–19:00** (Nov: to 18:00)",
 "Adult **₩3,000**; youth ₩2,000; child ₩1,000",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "The bamboo grove behind the shrine is the quietest corner of the whole village."),

("⛪","Jeondong Catholic Cathedral (전동성당)","🔁 daily (FREE)",
 "A 1908–1914 Romanesque-Byzantine church built on the site where **Korea's first Catholic martyrs were executed in 1791** — National Treasure-grade architecture in red brick",
 "Daily **09:00–17:00** (no entry during Mass)",
 "**FREE**",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr) · [Catholic Diocese of Jeonju](https://www.jcatholic.or.kr)",
 "Directly opposite Gyeonggijeon. **Quiet please — it is an active parish church.**"),

("🎓","Jeonjuhyanggyo Confucian School & Ginkgo Trees (전주향교)","🔁 daily (FREE)",
 "The 1354 Confucian school, with **six ginkgo trees over 400 years old** whose late-autumn yellow is one of Jeonju's signature sights",
 "Daily **09:00–18:00**",
 "**FREE**",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "**Peak ginkgo colour is typically the first ten days of November** — perfect timing for this trip."),

("🏯","Pungnammun Gate (풍남문) — Treasure No. 308","🔁 daily (FREE)",
 "The last surviving gate of Jeonju's city wall, rebuilt in 1768 — a two-storey wooden gatehouse now marooned on a roundabout beside the market",
 "Always visible; interior closed",
 "**FREE**",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "Lit at night and photogenic. Nambu Market is immediately south of it."),

("🌄","Omokdae & Imokdae Pavilions (오목대·이목대)","🔁 daily (FREE)",
 "The hilltop pavilion where **General Yi Seong-gye celebrated his 1380 victory** before founding the Joseon dynasty — and the best free overlook of the hanok roofs",
 "Always open",
 "**FREE**",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "Five minutes uphill from the main street. **The classic Jeonju photo of tiled roofs is taken here.**"),

("🎨","Jaman Mural Village (자만벽화마을)","🔁 daily (FREE)",
 "A hillside village of small painted houses above the hanok district, reached by a footbridge over the road from Omokdae",
 "Always open",
 "**FREE**",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "Residential — keep noise down. Several small cafes with hanok-roof views."),

("🍜","Nambu Market & Youth Mall (남부시장)","🔁 daily",
 "A 200-year-old market beside Pungnammun, with a **Youth Mall of young-run shops on the second floor** and a famous kongnamul-gukbap alley",
 "Daily **07:00–20:00**; closed 1st & 3rd Sunday",
 "**FREE** to browse; gukbap **₩8,000**",
 "[namsijang.co.kr](http://www.namsijang.co.kr) · [tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "**Nambu Night Market runs Friday and Saturday evenings, roughly 18:00–24:00** — one of Korea's best."),

("🌃","Nambu Market Night Market — Fri & Sat (남부야시장)","✅ CONFIRMED — Fri & Sat",
 "Around 40 food carts filling the market aisles on weekend nights, run by the merchants' association since 2014",
 "**Fri & Sat 18:00–24:00** (roughly)",
 "Dishes **₩3,000–₩8,000**",
 "[namsijang.co.kr](http://www.namsijang.co.kr) · [tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "**Your trip includes several Fri/Sat nights — this is the single best cheap-eats evening in Jeonju.**"),

("🍚","Jeonju Bibimbap — the original (전주비빔밥)","🔁 daily",
 "Jeonju is the home of bibimbap, served here with beef tartare, yellow bean sprouts and rice cooked in beef broth, in a brass bowl",
 "Most restaurants **10:00–21:00**",
 "**₩13,000–₩20,000**",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr) · [UNESCO Creative Cities](https://www.unesco.org/en/creative-cities)",
 "Hankookjib and Gogung are the two long-established names. **Jeonju is a UNESCO City of Gastronomy.**"),

("🥣","Jeonju Kongnamul-gukbap (콩나물국밥) — bean-sprout soup rice","🔁 daily / 24 h",
 "Jeonju's hangover soup: bean sprouts, rice and broth, with a raw egg on the side — many of the classic shops open 24 hours",
 "Several open **24 hours**",
 "**₩8,000–₩10,000**",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "Two schools: Namguensa-style (egg stirred in) and Wangyeong-style (egg on the side). Both around Nambu Market."),

("🍫","PNB Poong-nyeon Bakery Choco Pie (풍년제과)","🔁 daily",
 "A 1951 bakery whose handmade choco pie became a national souvenir — still baked in Jeonju and queued for daily",
 "Daily **08:00–22:00**",
 "Box of 5 **₩12,000**",
 "[pnb.co.kr](http://www.pnb.co.kr) · [tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "Main branch on Gyeonggijeon-gil. Buy a single one first — they're rich."),

("🍶","Jeonju Traditional Wine Museum (전주전통술박물관)","🔁 Tue–Sun (FREE)",
 "A working museum of Korean rice wine with brewing demonstrations, a *makgeolli* tasting bar and short classes in making your own",
 "Tue–Sun **09:00–18:00** (closed Mon)",
 "Entry **FREE**; classes from ₩20,000",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "Inside the hanok village. Book the brewing class a day ahead if you want it."),

("🍻","Jeonju Makgeolli Alley (막걸리골목)","🔁 nightly",
 "A Jeonju institution: order a kettle of makgeolli and a **table of free side dishes arrives** — more arrive with each additional kettle",
 "Roughly **17:00–24:00**",
 "Kettle **₩15,000–₩20,000** (anju included)",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "Samcheon-dong and Seosin-dong alleys. **Two kettles between two people is a full dinner** — don't eat beforehand."),

("📜","Jeonju Hanji Museum & Papermaking (전주한지박물관)","🔁 Mon–Sat (FREE)",
 "Jeonju has made Korea's finest mulberry paper for a thousand years; the museum shows the process and runs hands-on papermaking",
 "Mon–Sat **10:00–17:00** (closed Sun)",
 "**FREE**; workshop ₩5,000",
 "[hanjimuseum.co.kr](http://www.hanjimuseum.co.kr) · [tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "Run by a paper company outside the centre — take a taxi. Making a sheet takes 20 minutes."),

("🎋","Jeonju Traditional Crafts Exhibition Hall (전주공예품전시관)","🔁 daily (FREE)",
 "Hanji, fans, brassware and lacquer by Jeollabuk-do master artisans, with a shop selling directly from the makers",
 "Daily **10:00–18:00**",
 "**FREE**",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "Inside the hanok village. Better-quality souvenirs than the street stalls, at fair prices."),

("🪭","Jeonju Fan Culture Center (전주부채문화관)","🔁 Tue–Sun (FREE)",
 "Jeonju's *hapjukseon* folding fans were a royal tribute item; the centre exhibits them and runs fan-painting sessions",
 "Tue–Sun **10:00–18:00** (closed Mon)",
 "**FREE**; painting ₩10,000",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "Small and quick — 30 minutes, and a good rainy-hour option."),

("🖌️","Gangam Calligraphy Museum (강암서예관)","🔁 Tue–Sun (FREE)",
 "**Korea's only public museum dedicated to calligraphy**, holding the work of Song Seong-yong (Gangam) and Chinese and Korean masters",
 "Tue–Sun **09:00–18:00** (closed Mon)",
 "**FREE**",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "On the riverbank below Omokdae. Genuinely worth 40 minutes even if calligraphy isn't your thing."),

("🏠","Hakindang House (학인당)","🔁 daily",
 "A 1908 upper-class hanok built with royal-palace techniques, used as a private performance hall for pansori — and still a hanok stay",
 "Daily **10:00–17:00**",
 "Tour **₩3,000**; stay from ₩150,000",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "One of the very few hanok in the village that is genuinely old rather than 1930s or reconstructed."),

("🎭","Jeonju Pansori & Traditional Performance (전주소리문화관)","🔁 weekends",
 "Jeonju is the heartland of *pansori* epic story-singing — **a UNESCO Intangible Cultural Heritage** — with free weekend performances in the hanok village",
 "Weekend afternoons, typically **14:00–16:00**",
 "Many **FREE**",
 "[UNESCO ICH](https://ich.unesco.org/en/RL/pansori-epic-chant-00070) · [tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "Check the village information centre board on arrival for the weekend schedule."),

("🎼","Sori Arts Center of Jeollabuk-do (한국소리문화의전당)","🔁 by programme",
 "Jeonju's main concert complex, home to the Jeollabuk-do Provincial Orchestra and a full autumn season of classical and gugak",
 "Box office **09:00–18:00**; evening shows **19:30**",
 "**₩10,000–₩50,000**",
 "[sori21.co.kr](https://www.sori21.co.kr)",
 "North of the centre near the arboretum. Check the November calendar when you book."),

("🎬","Jeonju Film Street & Cinema Complex (영화의거리)","🔁 daily (FREE)",
 "The downtown street built around the **Jeonju International Film Festival**, with the Jeonju Cinema Complex screening arthouse films year-round",
 "Street always open; cinema **11:00–23:00**",
 "Street **FREE**; tickets ₩8,000",
 "[jiff.or.kr](https://www.jiff.or.kr) · [tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "The festival itself is in spring, but the street and the arthouse cinema run all year."),

("🏛️","Jeonju National Museum (국립전주박물관)","🔁 Tue–Sun (FREE)",
 "The regional national museum covering Jeolla's Baekje-era, Confucian and craft history, with an excellent hanji and calligraphy gallery",
 "Tue–Sun **10:00–18:00** (closed Mon)",
 "**FREE** (permanent galleries)",
 "[jeonju.museum.go.kr](https://jeonju.museum.go.kr)",
 "In the south-west of the city — bus or taxi. Free, air-conditioned and rarely busy."),

("🏞️","Deokjin Park & Lotus Pond (덕진공원)","🔁 daily (FREE)",
 "A large city park built around a lotus pond, with an arched wooden bridge and a musical fountain — Jeonju's main local green space",
 "Always open",
 "**FREE**",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "Bus from downtown. The lotuses are gone by November but the pond, bridge and maples are the reason to come then."),

("🌲","Jeonju Arboretum & Chunggyeongsa (전주수목원)","🔁 Mon–Sat (FREE)",
 "A 60-hectare arboretum run by the Korea Expressway Corporation, with 3,000 plant species and a strong autumn maple display",
 "Mon–Sat **10:00–18:00** (closed Sun & holidays)",
 "**FREE**",
 "[Korea Expressway Corporation](https://www.ex.co.kr)",
 "**Closed Sundays** — a common trip-planning trap. Free parking and free entry."),

("🦁","Jeonju Zoo (전주동물원)","🔁 daily",
 "A municipal zoo beside Deokjin Park, in the middle of a well-publicised conversion toward larger naturalistic enclosures",
 "Daily **09:00–19:00** (Nov: to 18:00)",
 "Adult **₩3,000**; child ₩1,000",
 "[zoo.jeonju.go.kr](https://zoo.jeonju.go.kr)",
 "Cheap and pleasant for families; the botanical section is included."),

("🌉","Hanbyeokdang Pavilion & Jeonjucheon Riverside (한벽당)","🔁 daily (FREE)",
 "A 1404 cliff-side pavilion where the Jeonjucheon stream meets the rock face — with a riverside path back into the hanok village",
 "Always open",
 "**FREE**",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "Ten minutes' walk east of the village along the stream. Popular for autumn photos."),

("🏛️","Jeolla Gamyeong Provincial Government Office (전라감영)","🔁 daily (FREE)",
 "The reconstructed Joseon provincial capital complex, reopened in 2020 on its original downtown site after decades under a government building",
 "Daily **09:00–18:00**",
 "**FREE**",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "Ten minutes from Pungnammun. Free evening lighting makes it worth a second pass after dark."),

("👘","Hanbok Rental in the Hanok Village (한복대여)","🔁 daily",
 "Dozens of rental shops around Gyeonggijeon; wearing hanbok gets you **free entry to Gyeonggijeon and other paid sites**",
 "Roughly **09:00–19:00**",
 "**₩15,000–₩30,000** for 2–4 hours",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "**The free-admission perk applies at several Jeonju sites** — worth it if you were going to pay anyway. November is cold: rent a cloak too."),

("🚶","Taejo-ro & Eunhaeng-ro Main Streets (태조로·은행로)","🔁 daily (FREE)",
 "The two main hanok-village streets — Taejo-ro for street food and shops, Eunhaeng-ro for the 600-year-old ginkgo tree and quieter cafes",
 "Shops roughly **10:00–21:00**",
 "**FREE** to walk",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "Street-food skewers, hanji shops and croquettes. **Weekday mornings are dramatically calmer.**"),

("🥟","Jeonju Street Food — the hanok village circuit","🔁 daily",
 "The village's specific street snacks: baguette-buns, *munjjigi* octopus skewers, PNB pies, hanok-shaped waffles and cheese-filled fish cakes",
 "Roughly **10:00–21:00**",
 "**₩3,000–₩8,000** each",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "**Grazing your way down Taejo-ro is a legitimate way to have dinner here.**"),

("☕","Gaeksa & Gaengnidan-gil Modern Cafe District (객리단길)","🔁 daily",
 "Jeonju's independent cafe and bar quarter around the old Gaeksa guesthouse site, in converted 1970s shopfronts",
 "Cafes **11:00–22:00**; bars later",
 "Coffee **₩5,000**",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "A 15-minute walk from the hanok village. **This is where young Jeonju actually goes at night.**"),

("🖼️","Seohakdong Art Village (서학동예술마을)","🔁 Tue–Sun (FREE)",
 "A quiet artists' quarter across the river from the hanok village, with converted-house galleries, studios and a photography space",
 "Galleries roughly Tue–Sun **11:00–18:00**",
 "**FREE**",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "Cross the footbridge from Hanbyeokdang. Almost no tour groups come here."),

("🚂","Jeonju Gyeongam-dong Railroad Village (경암동철길마을)","🔁 daily (FREE)",
 "Disused railway tracks running between houses, now a nostalgic retro strip of 1970s-themed shops and photo spots",
 "Always open; shops **10:00–18:00**",
 "**FREE**",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "Small and quick, but photogenic. Combine with the zoo or Deokjin Park."),

("⛩️","Jeonju Chiname & Cheongyeonru Pavilion (청연루)","🔁 daily (FREE)",
 "A modern pavilion on the Jeonjucheon at the entrance to the hanok village, lit at night and framing the stream and stepping stones",
 "Always open",
 "**FREE**",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "The stepping stones across the stream here are a favourite local photo. Illuminated from dusk."),

("🇨🇳","Jeonju China Street (차이나거리)","🔁 daily",
 "A small Chinese quarter near the old town serving jjajangmyeon and hand-pulled noodles, dating to Jeonju's early-20th-century Chinese community",
 "Most **11:00–21:00**",
 "Noodles **₩7,000–₩12,000**",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "Much smaller than Incheon's Chinatown but cheap and authentic."),

("🍢","Jeonju Ten Tastes & Local Specialities","🔁 daily",
 "Beyond bibimbap: *hanjeongsik* full-table meals, *piyanggi* grilled offal, Jeonju kalguksu, *moju* spiced rice wine and Jeonju bibim-jjajang",
 "Varies",
 "Hanjeongsik from **₩25,000** per person",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr) · [UNESCO Creative Cities](https://www.unesco.org/en/creative-cities)",
 "**A Jeonju hanjeongsik is 20+ dishes** and the most complete Korean meal you can buy — order it for two minimum."),

("🏨","Jeonju Hanok Stay (한옥스테이)","🔁 daily",
 "Sleeping on ondol floors inside the hanok village — dozens of certified hanok guesthouses, from budget rooms to restored gentry houses",
 "Check-in typically **15:00**",
 "**₩60,000–₩250,000** per night",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr) · [visitkorea.or.kr](https://english.visitkorea.or.kr)",
 "**Book ahead for November weekends.** Ondol floor heating is warm; the rooms themselves can be chilly."),

("🚄","Getting to Jeonju — KTX & express bus","🔁 daily",
 "Jeonju is on the Jeolla KTX line from Seoul Yongsan (about 1 h 40), with frequent express buses from Seoul, Daejeon and Gwangju",
 "Trains roughly **05:30–22:00**",
 "KTX from Yongsan **₩34,400**; bus ₩17,000",
 "[letskorail.com](https://www.letskorail.com) · [kobus.co.kr](https://www.kobus.co.kr)",
 "**Jeonju Station is 5 km from the hanok village** — take bus 79/119 or a ₩7,000 taxi."),

("🚌","Jeonju City Bus & Hanok Village Access","🔁 daily",
 "Flat-fare city buses serve the hanok village from the station and the express bus terminal; T-money and Cashbee both work",
 "Roughly **05:30–23:00**",
 "**₩1,500** cash / ₩1,450 card",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "**Jeonju has no metro.** Buses 79, 119, 508 and 542 all reach the village."),

("🚲","Jeonju Bicycle & Electric Cart Rental","🔁 daily",
 "Bike, tandem and electric-cart rental at the hanok village edge for exploring the stream path and Deokjin Park",
 "Roughly **09:00–18:00**",
 "Bike **₩5,000/hr**; electric cart ₩20,000/hr",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "The Jeonjucheon path is flat and traffic-free — the best use of a rental bike here."),

("🧭","Jeonju Tourist Information & Free Guided Walks","🔁 daily (FREE)",
 "Staffed information centres at the hanok village, Pungnammun and Jeonju Station, offering free English-language walking guides on request",
 "Daily **09:00–18:00**",
 "**FREE**",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr) · [visitkorea.or.kr](https://english.visitkorea.or.kr)",
 "**Book free guides at least a day in advance** through the tourism site."),

("🍁","Jeonju Autumn Foliage & November Weather","🔁 seasonal",
 "Jeonju's foliage peaks in **early-to-mid November**, later than the mountains — the hyanggyo ginkgos and Deokjin Park maples are the highlights",
 "Daylight hours",
 "**FREE**",
 "[weather.go.kr](https://www.weather.go.kr) · [tour.jeonju.go.kr](https://tour.jeonju.go.kr)",
 "Expect **4–15 °C in November** with clear dry days. **Excellent timing for this trip.**"),

("🎪","Jeonju November Festivals & Events Calendar","👀 WATCH",
 "Jeonju's autumn programme includes the Jeonju Bibimbap Festival, Daesaseupnori pansori competition and hanok-village night events; 2026 dates are published by the city",
 "By event",
 "Many **FREE**",
 "[tour.jeonju.go.kr](https://tour.jeonju.go.kr) · [jeonju.go.kr](https://www.jeonju.go.kr)",
 "**Check the city calendar in October 2026** — festival dates shift year to year."),

("⚽","Jeonbuk Hyundai Motors — K League 1 (전북현대)","👀 WATCH — season ends Nov/Dec",
 "**Korea's most successful modern football club**, playing at Jeonju World Cup Stadium; the K League 1 season runs into late November",
 "Kick-off typically **14:00** or **19:00**",
 "Tickets from **₩12,000**",
 "[hyundai-motorsfc.com](https://www.hyundai-motorsfc.com) · [kleague.com](https://www.kleague.com)",
 "**Check the K League fixture list for November 2026** — the final rounds usually fall in your window."),

("🏟️","Jeonju World Cup Stadium (전주월드컵경기장)","🔁 daily (FREE outside matches)",
 "A 2002 World Cup venue whose roof is designed after a Korean traditional fan and hapjukseon — worth seeing even without a match",
 "Grounds always open; tours by arrangement",
 "**FREE** to view",
 "[hyundai-motorsfc.com](https://www.hyundai-motorsfc.com) · [jeonju.go.kr](https://www.jeonju.go.kr)",
 "Bus from downtown, 25 minutes. The architecture is genuinely good."),

("🏔️","Maisan Provincial Park & Tapsa day trip (마이산 탑사)","🔁 daily",
 "Two horse-ear peaks an hour east of Jeonju, with **Tapsa temple's 80 hand-stacked stone pagodas** built by one hermit between 1885 and 1915",
 "Daily **08:00–18:00** (Nov: to 17:00)",
 "Park **₩3,000**",
 "[jinan.go.kr](https://www.jinan.go.kr) · [Korea Forest Service](https://www.forest.go.kr)",
 "Bus Jeonju → Jinan (1 h). **The most striking day trip from Jeonju, and superb in November.**"),

("🌊","Naejangsan National Park day trip (내장산)","🔁 daily",
 "**Korea's most famous autumn-foliage mountain**, an hour south of Jeonju, with a maple tunnel approach, a cable car and Naejangsa temple",
 "Daily **06:00–18:00**",
 "Park **FREE**; cable car ₩11,000 return",
 "[knps.or.kr](https://www.knps.or.kr/park/main.do?parkId=naejangsan) · [english.knps.or.kr](https://english.knps.or.kr)",
 "**Peak colour is usually early November** — expect heavy crowds and go on a weekday. Bus from Jeonju to Jeongeup then local bus."),

("🛕","Geumsansa Temple, Gimje day trip (금산사)","🔁 daily",
 "A 599 CE temple on Moaksan with **Mireukjeon, Korea's only three-storey wooden Buddhist hall** and a National Treasure",
 "Daily **08:00–18:00** (Nov: to 17:00)",
 "Adult **₩3,000**",
 "[geumsansa.org](http://www.geumsansa.org) · [gimje.go.kr](https://www.gimje.go.kr)",
 "Bus 79 from Jeonju, about 50 minutes. Far quieter than the famous temples and architecturally more important."),

("🌾","Gochang Dolmen Site — UNESCO day trip (고창 고인돌)","🔁 Tue–Sun",
 "**UNESCO World Heritage**: over 440 Bronze Age dolmens in one valley, the densest concentration on earth, with a museum and a walking trail",
 "Tue–Sun **09:00–18:00** (Nov: to 17:00; closed Mon)",
 "Adult **₩3,000**",
 "[UNESCO](https://whc.unesco.org/en/list/977) · [gochang.go.kr](https://www.gochang.go.kr)",
 "Bus Jeonju → Gochang (1 h 20). Combine with Gochang Eupseong walled town and Seonunsa temple."),
]

append("/home/user/KoreaFun/jeonju.md", E, 137, 3,
       "\n---\n\n## 🧭 Beginner-friendly essentials", "Jeonju",
       intro="**Verified expansion set** — the full hanok-village inventory, UNESCO gastronomy and pansori heritage, craft museums, the night market, transit, and day trips to Maisan, Naejangsan and the Gochang dolmens.")
