# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "/home/user/KoreaFun/.build")
from addlib import append

E = [
("🏯","Deoksugung Palace (덕수궁) — 12 min walk","🔁 Tue–Sun",
 "The palace where **Emperor Gojong proclaimed the Korean Empire in 1897**, uniquely mixing Joseon halls with Western neoclassical buildings",
 "Tue–Sun **09:00–21:00** (last entry 20:00); closed Mon",
 "Adult **₩1,000**; free in hanbok",
 "[Royal Palaces (KHS)](https://royal.khs.go.kr) · Exit 2, City Hall Stn",
 "**Open until 21:00 — the only palace with regular night opening.** A 12-minute walk from Myeongdong."),

("💂","Deoksugung Royal Guard Changing Ceremony","🔁 Tue–Sun (FREE)",
 "The reconstructed Joseon royal guard ceremony at Daehanmun gate, performed three times daily with period uniforms and drums",
 "**11:00, 14:00, 15:30**; closed Mon",
 "**FREE** to watch",
 "[Royal Palaces (KHS)](https://royal.khs.go.kr) · [visitseoul.net](https://english.visitseoul.net)",
 "**Free and outside the gate** — you don't need a palace ticket. Cancelled in heavy rain."),

("🏛️","Seokjojeon Hall & Korean Empire History Museum","🔁 Tue–Sun (booking)",
 "The 1910 neoclassical stone hall inside Deoksugung, restored to its Korean Empire interiors and shown by guided tour only",
 "Tue–Sun by reserved timed tour",
 "**FREE** with palace admission; booking required",
 "[Royal Palaces (KHS)](https://royal.khs.go.kr)",
 "**Reservation-only and books out weeks ahead** — check the palace site as soon as your dates are fixed."),

("🚶","Deoksugung Doldam-gil Stone Wall Road (돌담길)","🔁 daily (FREE)",
 "The stone-walled lane around Deoksugung, one of Seoul's best-known autumn walks, running into the Jeong-dong diplomatic quarter",
 "Always open; lit at night",
 "**FREE**",
 "[visitseoul.net](https://english.visitseoul.net) · Exit 1, City Hall Stn",
 "**Peak ginkgo colour here is late October into early November** — right at the start of your window."),

("⛪","Jeong-dong Quarter & Chungdong First Methodist Church","🔁 daily (FREE)",
 "Seoul's original diplomatic and missionary quarter, with **Korea's oldest Protestant church building (1897)** and the former Russian legation tower",
 "Streets always open; church **10:00–17:00**",
 "**FREE**",
 "[jung.go.kr](https://www.junggu.seoul.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "**A 15-minute walk from Myeongdong** and the most concentrated late-19th-century streetscape in Seoul."),

("🏛️","Seoul Museum of Art (SeMA) main branch","🔁 Tue–Sun (FREE)",
 "The city art museum in the former Supreme Court building of 1928, with a preserved facade and free rotating exhibitions",
 "Tue–Fri **10:00–20:00**; weekends to 19:00; closed Mon",
 "**FREE** (special shows charged)",
 "[sema.seoul.go.kr](https://sema.seoul.go.kr) · Exit 1, City Hall Stn",
 "**Free, major and 12 minutes from Myeongdong.** Check the November exhibition programme."),

("🏛️","Seoul Museum of History (서울역사박물관)","🔁 Tue–Sun (FREE)",
 "The city's own history museum, covering Hanyang's founding through colonial Seoul to the present, with a large scale model of the city",
 "Tue–Sun **09:00–18:00**; closed Mon",
 "**FREE**",
 "[museum.seoul.go.kr](https://museum.seoul.go.kr) · Exit 7, Seodaemun Stn",
 "**Free and genuinely excellent** — the best single explanation of how Seoul became this shape."),

("🏛️","Seoul City Hall & Citizens' Hall","🔁 daily (FREE)",
 "The 2012 glass city hall wrapping the 1926 colonial building, with a public library inside the old hall and the underground Citizens' Hall",
 "Daily **09:00–21:00**; library Tue–Sun",
 "**FREE**",
 "[seoul.go.kr](https://english.seoul.go.kr) · Exit 5, City Hall Stn",
 "**The vertical garden in the lobby is the largest indoor green wall in Korea.** Free exhibitions downstairs."),

("⛸️","Seoul Plaza Ice Rink","👀 WATCH — opens December",
 "The city's outdoor ice rink on Seoul Plaza, traditionally opening in mid-December after the Christmas lighting",
 "Season typically **mid-December–February**",
 "**₩1,000** per hour including skates",
 "[seoul.go.kr](https://english.seoul.go.kr) · Exit 5, City Hall Stn",
 "**Opens after your window closes** — noted so you don't plan around it."),

("🎄","Seoul Plaza & Cheonggye Christmas Lighting","👀 WATCH — late Nov",
 "Seoul's central Christmas trees and light installations on Seoul Plaza and along Cheonggyecheon typically switch on in **late November**",
 "Evenings once lit",
 "**FREE**",
 "[seoul.go.kr](https://english.seoul.go.kr) · [visitseoul.net](https://english.visitseoul.net)",
 "**The switch-on may fall inside the last week of your trip** — check the city site in November."),

("🌊","Cheonggyecheon Stream — full 11 km walk","🔁 daily (FREE)",
 "The restored stream running east from Gwanghwamun, opened 2005 after the elevated expressway above it was demolished",
 "Always open; lit at night",
 "**FREE**",
 "[seoul.go.kr](https://english.seoul.go.kr) · Exit 5, Euljiro 1-ga Stn",
 "**Enter at Euljiro 1-ga, five minutes from Myeongdong.** Walking east to Dongdaemun takes about 90 minutes."),

("🏛️","Cheonggyecheon Museum & Gwangtonggyo Bridge","🔁 Tue–Sun (FREE)",
 "The museum of the stream's history plus **Gwangtonggyo, a 1410 stone bridge** re-exposed during the restoration",
 "Tue–Sun **09:00–19:00**; closed Mon",
 "**FREE**",
 "[museum.seoul.go.kr](https://museum.seoul.go.kr)",
 "The bridge is right at the Euljiro entrance — most people walk past without noticing it's 600 years old."),

("🏛️","Bosingak Belfry & the Seoul bell (보신각)","🔁 daily (FREE)",
 "The pavilion holding Seoul's city bell, historically rung to open and close the capital's gates; a public bell-striking ceremony runs at midday",
 "Ceremony **Tue–Sun 12:00**",
 "**FREE**",
 "[jung.go.kr](https://www.junggu.seoul.kr) · Exit 4, Jonggak Stn",
 "**The midday striking is free and takes ten minutes.** Ten minutes' walk from Myeongdong."),

("🏛️","Jongmyo Shrine — UNESCO World Heritage","🔁 Wed–Mon (guided)",
 "The Confucian royal ancestral shrine of the Joseon dynasty, **inscribed by UNESCO in 1995** and still holding the world's oldest continuous royal ritual",
 "Wed–Mon by guided tour; free-walk Saturdays; closed Tue",
 "Adult **₩1,000**",
 "[UNESCO ref 738](https://whc.unesco.org/en/list/738) · [Royal Palaces (KHS)](https://royal.khs.go.kr)",
 "**Guided tour only except Saturdays.** English tours at 10:00, 12:00, 14:00, 16:00 — reserve online."),

("🏯","Changdeokgung Palace & Secret Garden — UNESCO","🔁 Tue–Sun",
 "The 1405 palace **inscribed by UNESCO in 1997**, with the Huwon 'Secret Garden' shown only on timed guided tours",
 "Tue–Sun **09:00–18:00** (Nov: to 17:30); closed Mon",
 "Palace **₩3,000**; Secret Garden **₩5,000** extra",
 "[UNESCO ref 816](https://whc.unesco.org/en/list/816) · [Royal Palaces (KHS)](https://royal.khs.go.kr)",
 "**Book the Secret Garden tour online in advance** — daily numbers are capped and it sells out. Peak foliage in early November."),

("🏯","Gyeongbokgung Palace & National Palace Museum","🔁 Wed–Mon",
 "The main Joseon palace of 1395, with the throne hall, the Gyeonghoeru pavilion pond and the National Palace Museum on site",
 "Wed–Mon **09:00–18:00** (Nov: to 17:00); closed Tue",
 "Adult **₩3,000**; free in hanbok",
 "[Royal Palaces (KHS)](https://royal.khs.go.kr) · Exit 5, Gyeongbokgung Stn",
 "**Free entry if you wear hanbok** — rental shops cluster at the gate. Guard changing at 10:00 and 14:00."),

("🏛️","National Museum of Korean Contemporary History","🔁 Tue–Sun (FREE)",
 "The national museum of Korea's story since 1876, on Gwanghwamun Square, with a rooftop terrace looking at the palace",
 "Tue–Sun **10:00–18:00**; Wed to 21:00; closed Mon",
 "**FREE**",
 "[much.go.kr](https://www.much.go.kr) · Exit 2, Gwanghwamun Stn",
 "**Free, English-labelled, and the rooftop view of Gyeongbokgung is the best free one in Seoul.**"),

("🗿","Gwanghwamun Square, Sejong & Yi Sun-sin statues","🔁 daily (FREE)",
 "Seoul's civic square, remodelled in 2022, with the statues of King Sejong and Admiral Yi and underground exhibition halls beneath them",
 "Square always open; halls **10:30–22:30**",
 "**FREE**",
 "[seoul.go.kr](https://english.seoul.go.kr) · Exit 9, Gwanghwamun Stn",
 "**The exhibition halls under the Sejong statue are free** and almost nobody goes in."),

("🏛️","Sejong Center for the Performing Arts","👀 WATCH — check programme",
 "Seoul's largest municipal arts complex, hosting the Seoul Philharmonic, opera, musicals and free lobby concerts",
 "Box office **09:00–20:00**",
 "**FREE**–₩150,000",
 "[sejongpac.or.kr](https://www.sejongpac.or.kr) · Exit 1, Gwanghwamun Stn",
 "**Check the November programme** — the autumn season is the fullest of the year."),

("🏛️","National Theater of Korea & Namsan venues","👀 WATCH — check programme",
 "The national theatre complex on Namsan, home to the National Changgeuk Company, the National Orchestra and the National Dance Company",
 "Box office **09:00–20:00**",
 "**₩20,000–₩70,000**",
 "[ntok.go.kr](https://www.ntok.go.kr)",
 "**Changgeuk — Korean opera based on pansori — is the distinctive thing to see here.** English surtitles on major productions."),

("🗼","N Seoul Tower & Namsan Cable Car","🔁 daily",
 "The 1971 broadcast tower on Namsan, 236 m tall on a 243 m mountain, reached by cable car, bus or a 40-minute walk",
 "Daily **10:00–23:00**; cable car **10:00–23:00**",
 "Observatory **₩21,000**; cable car return ₩15,000",
 "[seoultower.co.kr](https://www.seoultower.co.kr) · Exit 3, Myeongdong Stn",
 "**The cable car base is a steep 10-minute walk from Myeongdong** — or take the free Namsan lift from Myeongdong Station."),

("🚡","Namsan Orumi Free Elevator from Myeongdong","🔁 daily (FREE)",
 "A free public inclined elevator from Myeongdong up to the Namsan cable car base station, avoiding the steep climb",
 "Daily **09:00–23:00**",
 "**FREE**",
 "[seoul.go.kr](https://english.seoul.go.kr) · Exit 3, Myeongdong Stn",
 "**Free and most visitors don't know it exists** — it saves the worst part of the walk."),

("🚌","Namsan Circular Bus 01 & 02","🔁 daily",
 "Green shuttle buses circling Namsan from Myeongdong, Chungmuro and Seoul Station up to the tower plaza",
 "Roughly **07:00–24:00**, every 8–15 min",
 "**₩1,200** with T-money",
 "[bus.go.kr](https://bus.go.kr) · Exit 3, Chungmuro Stn",
 "**Bus 01 from Chungmuro is the cheapest way to the tower** — a fraction of the cable car fare."),

("🏯","Namsangol Hanok Village (남산골한옥마을)","🔁 Wed–Mon (FREE)",
 "Five relocated Joseon *hanok* houses in a traditional garden at the foot of Namsan, with a **time capsule buried in 1994 to be opened in 2394**",
 "Wed–Mon **09:00–21:00**; closed Tue",
 "**FREE**",
 "[hanokmaeul.or.kr](https://www.hanokmaeul.or.kr) · Exit 3, Chungmuro Stn",
 "**Free, open late and eight minutes' walk from Myeongdong.** Traditional craft workshops run most days."),

("🏔️","Namsan Seoul Fortress Wall Trail (한양도성)","🔁 daily (FREE)",
 "The **18.6 km Joseon city wall of 1396**, on Korea's UNESCO Tentative List; the Namsan section climbs directly from Myeongdong",
 "Always open",
 "**FREE**",
 "[seoulcitywall.seoul.go.kr](https://seoulcitywall.seoul.go.kr) · [UNESCO Tentative List](https://whc.unesco.org)",
 "**The Namsan section from Jangchungdong to the tower takes about 90 minutes** and is the best free walk in central Seoul."),

("🏛️","Seoul City Wall Museum (한양도성박물관)","🔁 Tue–Sun (FREE)",
 "The museum of the Joseon capital's fortifications, at the Heunginjimun section of the wall",
 "Tue–Sun **09:00–18:00**; closed Mon",
 "**FREE**",
 "[museum.seoul.go.kr](https://museum.seoul.go.kr) · Exit 1, Dongdaemun Stn",
 "Pairs with the Dongdaemun wall section and the Heunginjimun gate."),

("🏛️","Sungnyemun / Namdaemun Gate — National Treasure No. 1","🔁 Tue–Sun (FREE)",
 "**Korea's National Treasure No. 1**, the 1398 great south gate of Seoul, rebuilt after the 2008 arson and reopened in 2013",
 "Plaza always open; upper level Tue–Sun **09:00–18:00**",
 "**FREE**",
 "[Korea Heritage Service](https://www.khs.go.kr) · Exit 4, Hoehyeon Stn",
 "**You can go up inside the gate for free** on the guided access slots — most visitors only photograph it from outside."),

("🛍️","Namdaemun Market — Korea's oldest market (남대문시장)","🔁 daily",
 "**Korea's largest and oldest traditional market**, trading since 1414, with over 10,000 stalls across a dense grid of alleys",
 "Most stalls **08:30–18:00**; night wholesale **23:00–04:00**",
 "**FREE** entry",
 "[namdaemunmarket.co.kr](https://www.namdaemunmarket.co.kr) · Exit 5, Hoehyeon Stn",
 "**Ten minutes' walk from Myeongdong.** Sundays are much quieter — many wholesale sections close."),

("🍲","Namdaemun Galchi-jorim Alley (갈치조림골목)","🔁 daily",
 "A market alley of specialists in braised hairtail fish in chilli sauce — a Namdaemun institution",
 "Roughly **10:00–21:00**",
 "**₩12,000–₩15,000** per person",
 "[namdaemunmarket.co.kr](https://www.namdaemunmarket.co.kr)",
 "**One dish, a dozen shops, all doing it well.** Comes with unlimited rice and side dishes."),

("🥟","Namdaemun Kalguksu Alley & market food","🔁 daily",
 "The famously cramped noodle alley where you sit shoulder to shoulder for hand-cut noodle soup, plus the market's *hotteok* and *jokbal* stalls",
 "Roughly **08:00–20:00**",
 "**₩6,000–₩9,000**",
 "[namdaemunmarket.co.kr](https://www.namdaemunmarket.co.kr)",
 "**Cash only in most of the alley.** The bowl comes with a side of noodles and rice to add."),

("👓","Namdaemun Specialist Sections — glasses, cameras, kitchenware","🔁 daily",
 "Namdaemun's alleys are organised by trade: eyewear, imported goods, children's clothes, kitchen supplies and camera equipment",
 "Roughly **09:00–18:00**",
 "Varies",
 "[namdaemunmarket.co.kr](https://www.namdaemunmarket.co.kr)",
 "**Prescription glasses in about an hour at a fraction of Western prices** — the eyewear section is a genuine bargain."),

("🌺","Namdaemun Flower & Import Alley","🔁 daily",
 "The market's flower section and the 'import alley' of foreign foods and goods, historically supplied by US base surplus",
 "Roughly **07:00–18:00**",
 "Varies",
 "[namdaemunmarket.co.kr](https://www.namdaemunmarket.co.kr)",
 "The import alley is a genuinely odd remnant of postwar Seoul."),

("🏢","Euljiro Printing District & Nogari Alley (을지로)","🔁 daily",
 "Euljiro's tool shops, printworks and metal foundries by day, and **Nogari Alley's outdoor beer tables** by night — Seoul's most atmospheric drinking street",
 "Shops **09:00–18:00**; alley **17:00–01:00**",
 "Beer and dried pollack **₩10,000–₩15,000**",
 "[jung.go.kr](https://www.junggu.seoul.kr) · Exit 4, Euljiro 3-ga Stn",
 "**Two stops from Myeongdong on Line 2.** The alley fills the street with plastic stools from about 18:00."),

("🍺","Euljiro Hipster Bars & 'Hip-jiro' rooftops","🔁 nightly",
 "Bars and cafes hidden inside Euljiro's working industrial buildings, usually unmarked and up unlit stairwells",
 "Roughly **18:00–02:00**",
 "Drinks **₩8,000–₩15,000**",
 "[jung.go.kr](https://www.junggu.seoul.kr) · Exit 1, Euljiro 3-ga Stn",
 "**The lack of signage is the point.** Search by name on Naver Map before you set out."),

("🎞️","Chungmuro & Korean Film Heritage (충무로)","🔁 daily (FREE)",
 "The historic centre of the Korean film industry, with the Korean Film Museum nearby and film-related monuments through the district",
 "Streets always open",
 "**FREE**",
 "[koreafilm.or.kr](https://www.koreafilm.or.kr) · Exit 1, Chungmuro Stn",
 "**'Chungmuro' still means 'the film industry' in Korean.** One stop from Myeongdong on Line 4."),

("📷","Chungmuro Camera & Printing Street","🔁 daily",
 "Seoul's concentration of camera shops, film processing labs and print houses, a survival of the analogue film district",
 "Roughly **09:00–19:00**; many closed Sun",
 "Varies",
 "[jung.go.kr](https://www.junggu.seoul.kr) · Exit 1, Chungmuro Stn",
 "**Film development and second-hand cameras** at prices that no longer exist in most cities."),

("🏛️","Bank of Korea Money Museum (한국은행 화폐박물관)","🔁 Tue–Sun (FREE)",
 "The 1912 Bank of Korea headquarters, a Registered Cultural Heritage building, now housing a free museum of Korean currency",
 "Tue–Sun **10:00–17:00**; closed Mon",
 "**FREE**",
 "[bok.or.kr](https://www.bok.or.kr) · Exit 7, Hoehyeon Stn",
 "**Directly across from Shinsegae, five minutes from Myeongdong, and free.** The building alone is worth it."),

("🏬","Shinsegae Main Store & the 1930 Mitsukoshi building","🔁 daily",
 "**Korea's first department store**, opened as Mitsukoshi in 1930; the original building survives beside the modern wing",
 "Daily **10:30–20:00**",
 "**FREE** entry",
 "[shinsegae.com](https://www.shinsegae.com) · Exit 7, Hoehyeon Stn",
 "**The Christmas facade display here is a Seoul institution** — typically switched on in mid-to-late November."),

("🎄","Shinsegae Main Store Christmas Facade Show","👀 WATCH — from mid/late Nov",
 "Shinsegae's animated media facade over the 1930 building draws large evening crowds each winter",
 "Evenings once switched on",
 "**FREE**",
 "[shinsegae.com](https://www.shinsegae.com) · Exit 7, Hoehyeon Stn",
 "**Historically switches on in the second half of November** — likely to fall inside your window. Confirm on the store's site."),

("🏬","Lotte Department Store Main & Lotte Young Plaza","🔁 daily",
 "Lotte's flagship complex at Euljiro 1-ga, with a duty-free floor, a food hall and the Young Plaza youth wing",
 "Daily **10:30–20:00**",
 "**FREE** entry",
 "[lotteshopping.com](https://www.lotteshopping.com) · Exit 7, Euljiro 1-ga Stn",
 "**The duty-free floors need your passport and a departure within 30 days.**"),

("🏛️","Myeongdong Cathedral — Korea's Catholic mother church","🔁 daily (FREE)",
 "The 1898 Gothic Revival cathedral, **Korea's first parish church and a National Historic Site**, and a sanctuary for democracy protesters in the 1970s–80s",
 "Daily **09:00–21:00**; Mass several times daily",
 "**FREE**",
 "[mdsd.or.kr](https://www.mdsd.or.kr) · Exit 8, Myeongdong Stn",
 "**Its role sheltering 1987 democracy protesters** is as important as its architecture. Quiet inside even when the street outside is packed."),

("⛪","Myeongdong Cathedral crypt, 1898 Plaza & shops","🔁 daily (FREE)",
 "The cathedral's underground crypt holding Korean martyrs' remains, plus the 1898 Plaza shopping and dining complex built beneath the hill",
 "Plaza **10:00–22:00**; crypt daytime",
 "**FREE**",
 "[mdsd.or.kr](https://www.mdsd.or.kr)",
 "**The 1898 Plaza is a quiet, warm place to sit** two minutes off the main shopping street."),

("🕌","Seoul Central Mosque & Itaewon Islamic quarter","🔁 daily (FREE)",
 "**Korea's first purpose-built mosque**, opened 1976 in Itaewon, with a surrounding halal food street",
 "Daily **09:00–18:00**; prayer times restricted",
 "**FREE**",
 "[koreaislam.org](http://www.koreaislam.org) · Exit 3, Itaewon Stn",
 "**Two subway stops from Myeongdong.** Dress modestly; visitors welcome outside prayer times."),

("🏛️","National Museum of Korea — Yongsan","🔁 daily (FREE)",
 "**Korea's national museum and one of the largest in the world**, with the Gyeongju gold crowns, the Pensive Bodhisattva hall and 310,000 objects",
 "Mon–Fri **10:00–18:00**; Wed & Sat to 21:00",
 "**FREE** (special shows charged)",
 "[museum.go.kr](https://www.museum.go.kr) · Exit 2, Ichon Stn",
 "**The Room of Quiet Contemplation, with two 7th-century gilt-bronze Pensive Bodhisattvas, is the single greatest room in Korea.** Free."),

("🏛️","War Memorial of Korea (전쟁기념관)","🔁 Tue–Sun (FREE)",
 "A vast museum of Korean military history centred on the Korean War, with outdoor aircraft and armour displays",
 "Tue–Sun **09:30–18:00**; closed Mon",
 "**FREE**",
 "[warmemo.or.kr](https://www.warmemo.or.kr) · Exit 12, Samgakji Stn",
 "**Free, enormous, and three subway stops from Myeongdong.** Allow three hours."),

("🏛️","Seoul Museum of Craft Art (서울공예박물관)","🔁 Tue–Sun (FREE)",
 "Korea's first public craft museum, opened 2021 in a converted girls' school in Bukchon, covering textiles, lacquer and metalwork",
 "Tue–Sun **10:00–18:00**; closed Mon",
 "**FREE**",
 "[craftmuseum.seoul.go.kr](https://craftmuseum.seoul.go.kr) · Exit 1, Anguk Stn",
 "**Free and excellent** — a much better use of an hour than most paid attractions."),

("🏛️","MMCA Seoul — National Museum of Modern & Contemporary Art","🔁 Tue–Sun",
 "The national contemporary art museum's Seoul branch, beside Gyeongbokgung, with free entry on Wednesday evenings",
 "Tue–Sun **10:00–18:00**; Wed & Sat to 21:00",
 "Adult **₩2,000**; **FREE** Wed 18:00–21:00",
 "[mmca.go.kr](https://www.mmca.go.kr) · Exit 1, Anguk Stn",
 "**Free on Wednesday evenings** — and the galleries stay open until 21:00."),

("🏘️","Bukchon Hanok Village & Samcheong-dong","🔁 daily (FREE)",
 "The hillside district of some 900 surviving *hanok* houses between Gyeongbokgung and Changdeokgung, with the Samcheong-dong cafe street below",
 "Streets always open; **quiet hours 17:00–10:00**",
 "**FREE**",
 "[hanok.seoul.go.kr](https://hanok.seoul.go.kr) · Exit 2, Anguk Stn",
 "**People live here — photography restrictions apply on Bukchon-ro 11-gil** and are enforced with fines. Keep your voice down."),

("🎨","Insadong Antique & Craft Street (인사동)","🔁 daily (FREE)",
 "Seoul's traditional arts street, with galleries, brush and paper shops, tea houses and the Ssamziegil spiral mall",
 "Shops roughly **10:00–20:00**",
 "**FREE** to browse",
 "[visitseoul.net](https://english.visitseoul.net) · Exit 6, Anguk Stn",
 "**The main street is pedestrianised at weekends.** Traditional tea houses hidden up the side alleys are the real find."),

("🍵","Insadong Traditional Tea Houses","🔁 daily",
 "Long-established tea houses serving jujube, omija and citron teas in hanok courtyards off the Insadong alleys",
 "Roughly **11:00–22:00**",
 "Tea **₩8,000–₩12,000**",
 "[visitseoul.net](https://english.visitseoul.net) · Exit 6, Anguk Stn",
 "**Worth the price for the setting.** Several have been operating for over forty years."),

("🏛️","Tapgol Park & the March 1st Movement","🔁 daily (FREE)",
 "**Korea's first modern public park**, where the Declaration of Independence was read on 1 March 1919, holding a 15th-century ten-storey pagoda",
 "Daily **09:00–18:00**",
 "**FREE**",
 "[jongno.go.kr](https://www.jongno.go.kr) · Exit 1, Jongno 3-ga Stn",
 "**The pagoda is National Treasure No. 2**, kept under a glass housing."),

("🍢","Gwangjang Market — Korea's oldest daily market (광장시장)","🔁 daily",
 "Opened 1905, famous for its food alley: **mung bean pancakes, mayak gimbap and raw beef tartare**, plus a silk and hanbok section upstairs",
 "Food alley **09:00–23:00**; closed some Sundays",
 "**₩5,000–₩20,000**",
 "[gwangjangmarket.co.kr](https://www.gwangjangmarket.co.kr) · Exit 8, Jongno 5-ga Stn",
 "**Three stops from Myeongdong.** Go before 18:00 or after 20:00 to get a seat at the bindaetteok counters."),

("🛍️","Dongdaemun Design Plaza (DDP)","🔁 daily",
 "**Zaha Hadid's 2014 neofuturist landmark**, built over an excavated section of the Seoul city wall, with exhibition halls and the LED rose garden",
 "Daily **10:00–19:00**; plazas 24 h",
 "Plazas **FREE**; exhibitions charged",
 "[ddp.or.kr](https://www.ddp.or.kr) · Exit 1, Dongdaemun History & Culture Park Stn",
 "**Two stops from Myeongdong on Line 4.** The building is best seen after dark."),

("🏛️","Dongdaemun History Museum & excavated city wall","🔁 Tue–Sun (FREE)",
 "The Joseon-era military camp and city wall foundations uncovered during DDP's construction, preserved on site with a free museum",
 "Tue–Sun **10:00–19:00**; closed Mon",
 "**FREE**",
 "[ddp.or.kr](https://www.ddp.or.kr)",
 "**They found a chunk of the 1396 city wall while digging the foundations** and built the park around it."),

("🛍️","Dongdaemun Night Shopping — Doota, Hyundai Outlet, wholesale","🔁 nightly",
 "Dongdaemun's fashion towers run late into the night, with the wholesale markets trading from about 20:00 until dawn",
 "Retail to **24:00**; wholesale **20:00–06:00**",
 "**FREE** entry",
 "[ddm.go.kr](https://www.ddm.go.kr) · Exit 14, Dongdaemun History & Culture Park Stn",
 "**Korea's largest fashion district trades overnight.** Retail towers close Mondays."),
]

append("/home/user/KoreaFun/myeongdong.md", E, 264, 3,
       "\n---\n\n## 🧭 Beginner-friendly essentials", "Myeongdong & central Seoul",
       intro="**Verified expansion set — everything within walking distance or a few subway stops of Myeongdong.** Central Seoul's palaces and UNESCO sites, the Namsan fortress wall, Namdaemun and Gwangjang markets, Euljiro, the free national museums, and the November seasonal calendar.")
