# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "/home/user/KoreaFun/.build")
from addlib import append

E = [
("🎡","Seoullo 7017 Skygarden","🔁 daily (FREE)",
 "A 1970 highway overpass converted in 2017 into an elevated garden walkway with 24,000 plants, linking Seoul Station to Namdaemun",
 "Always open; lit at night",
 "**FREE**",
 "[seoullo7017.seoul.go.kr](https://seoullo7017.seoul.go.kr) · Exit 2, Seoul Station",
 "**Designed by MVRDV, the same practice behind Rotterdam's Markthal.** Walks straight into Namdaemun Market."),

("🚉","Culture Station Seoul 284 (문화역서울284)","🔁 Tue–Sun (FREE)",
 "The 1925 Seoul Station building, a Historic Site, restored as a free exhibition and performance space",
 "Tue–Sun **11:00–19:00**; closed Mon",
 "**FREE**",
 "[seoul284.org](https://www.seoul284.org) · Exit 2, Seoul Station",
 "**The old station's grand hall and dome are the exhibit.** Free and usually empty."),

("🏛️","Seoul Station & KTX hub","🔁 daily",
 "Korea's principal rail terminal, with KTX services nationwide, the AREX airport line and a large station complex",
 "Trains roughly **05:00–24:00**",
 "Varies by route",
 "[letskorail.com](https://www.letskorail.com) · Seoul Station",
 "**Two subway stops or a 20-minute walk from Myeongdong** — the practical departure point for every city in this guide."),

("✈️","AREX Airport Railroad from Seoul Station","🔁 daily",
 "The direct express to Incheon Airport in **43 minutes**, plus the all-stop line, both from Seoul Station's underground concourse",
 "Roughly **05:20–23:40**",
 "Express **₩11,000**; all-stop ₩4,750",
 "[arex.or.kr](https://www.arex.or.kr) · Seoul Station",
 "**City airport check-in is available at Seoul Station** for some airlines — drop your bags before the train."),

("🚌","Airport limousine buses from Myeongdong hotels","🔁 daily",
 "Limousine coaches stop at Myeongdong's major hotels en route to both Incheon and Gimpo airports",
 "Roughly **05:00–22:30**",
 "Incheon **₩17,000**; Gimpo ₩7,500",
 "[airport.kr](https://www.airport.kr) · [seoul.go.kr](https://english.seoul.go.kr)",
 "**Door-to-door with luggage** — worth the premium over the train if you're carrying bags."),

("🚇","Myeongdong Station & Line 4 connections","🔁 daily",
 "Myeongdong sits on Line 4, one stop from Chungmuro (Line 3) and Hoehyeon (Line 4), with Euljiro 1-ga (Line 2) within walking distance",
 "Roughly **05:30–24:00**",
 "**₩1,400** base with T-money",
 "[seoulmetro.co.kr](https://www.seoulmetro.co.kr) · Myeongdong Stn",
 "**Three different lines are within a ten-minute walk** — Myeongdong is one of the best-connected places to stay in Seoul."),

("🎫","T-money, Climate Card & transit passes","🔁 daily",
 "T-money works nationwide on transit and in convenience stores; Seoul's **Climate Card** offers unlimited city transit for a flat monthly or short-term fee",
 "N/A",
 "T-money card **₩4,000** plus credit; Climate Card from ₩5,000/day",
 "[t-money.co.kr](https://www.t-money.co.kr) · [seoul.go.kr](https://english.seoul.go.kr)",
 "**The Climate Card pays off above about four journeys a day.** Buy either at any station machine."),

("🚌","Seoul City Tour Bus from Gwanghwamun","🔁 daily",
 "Official hop-on-hop-off routes covering the palaces, Namsan, Itaewon and the Han River, with audio guides",
 "Roughly **09:30–17:30**",
 "Day ticket **₩24,000**",
 "[seoulcitybus.com](https://www.seoulcitybus.com) · Exit 6, Gwanghwamun Stn",
 "Useful on a cold day for covering distance between sights."),

("🚶","Free walking tours with Seoul city guides","🔁 daily (FREE)",
 "The city runs free guided walks of the palaces, Bukchon, the city wall and Myeongdong with trained volunteer guides in English",
 "Various daily start times",
 "**FREE**; booking required",
 "[visitseoul.net](https://english.visitseoul.net) · [seoul.go.kr](https://english.seoul.go.kr)",
 "**Genuinely free and led by trained volunteers** — reserve on the Visit Seoul site a few days ahead."),

("🏞️","Han River Parks & Yeouido Hangang Park","🔁 daily (FREE)",
 "Eleven riverside parks along the Han, with cycle paths, ferries and the Banpo Bridge rainbow fountain",
 "Always open",
 "**FREE**",
 "[hangang.seoul.go.kr](https://hangang.seoul.go.kr) · Exit 3, Yeouinaru Stn",
 "**The Banpo fountain show pauses for winter** — typically from late October. Check before travelling for it."),

("🌾","Haneul Park & Seoul silver grass — November","✅ CONFIRMED — Nov",
 "The park built on a capped landfill at World Cup Park, whose **silver grass fields peak from October into November**",
 "Daily **sunrise–sunset**; extended during the festival",
 "**FREE**",
 "[parks.seoul.go.kr](https://parks.seoul.go.kr) · Exit 1, World Cup Stadium Stn",
 "**291 steps to the top.** The silver grass into early November is one of Seoul's best free autumn sights."),

("🍁","Seoul autumn foliage peak — early November","✅ CONFIRMED — seasonal",
 "Seoul's peak foliage typically falls in **the first week or two of November**, with the palaces, Namsan and Deoksugung's stone wall road at their best",
 "Daylight hours",
 "**FREE**",
 "[Korea Forest Service](https://www.forest.go.kr) · [visitseoul.net](https://english.visitseoul.net)",
 "**Your window opens right at peak.** Changdeokgung's Secret Garden and Namsan are the two to prioritise."),

("🏛️","Seoul Metropolitan Library & Seoul Plaza","🔁 Tue–Sun (FREE)",
 "The public library inside the 1926 old city hall, preserving the original council chamber and mayor's office",
 "Tue–Fri **09:00–21:00**; weekends to 18:00",
 "**FREE**",
 "[lib.seoul.go.kr](https://lib.seoul.go.kr) · Exit 5, City Hall Stn",
 "**Free, warm, central and architecturally interesting** — a good place to sit out rain."),

("🏛️","Seoul Hall of Urbanism & Architecture","🔁 Tue–Sun (FREE)",
 "A free museum on how Seoul is planned and built, with a large city model and views over Seoul Plaza",
 "Tue–Sun **09:00–19:00**; closed Mon",
 "**FREE**",
 "[seoulhour.kr](https://seoulhour.kr) · Exit 5, City Hall Stn",
 "The rooftop terrace looks straight at the old and new city halls."),

("🎨","Ihwa Mural Village & Naksan Park","🔁 daily (FREE)",
 "A hillside village painted with murals from 2006, beside a preserved section of the city wall at Naksan Park with a wide Seoul view",
 "Always open; **residential quiet hours after 18:00**",
 "**FREE**",
 "[jongno.go.kr](https://www.jongno.go.kr) · Exit 2, Hyehwa Stn",
 "**Residents have removed some murals over tourist noise** — keep quiet and don't photograph into homes."),

("🎭","Daehangno Theatre District (대학로)","👀 WATCH — check programme",
 "Seoul's live theatre quarter, with over 100 small venues staging plays and musicals nightly",
 "Shows typically **16:00 and 20:00**",
 "**₩20,000–₩60,000**",
 "[jongno.go.kr](https://www.jongno.go.kr) · Exit 2, Hyehwa Stn",
 "**Mostly Korean-language** — the non-verbal shows in Myeongdong are the better bet without Korean."),

("🏛️","Seodaemun Prison History Hall","🔁 Tue–Sun",
 "The 1908 Japanese colonial prison where independence activists were held and executed, preserved as a memorial museum",
 "Tue–Sun **09:30–18:00** (Nov: to 17:00); closed Mon",
 "Adult **₩3,000**",
 "[sscmc.or.kr](https://www.sscmc.or.kr) · Exit 5, Dongnimmun Stn",
 "**Sobering and important.** The execution building and the underground cells are preserved as found."),

("⛪","Yakhyeon Catholic Church & Seosomun Shrine","🔁 daily (FREE)",
 "**Korea's first Western-style church building (1892)** and the nearby Seosomun shrine, the execution site of 100+ Catholic martyrs",
 "Daily **09:00–17:00**",
 "**FREE**",
 "[Korea Heritage Service](https://www.khs.go.kr) · [jung.go.kr](https://www.junggu.seoul.kr)",
 "**Seosomun has more canonised martyrs than any other site in Korea** — 44 of the 103 saints. Ten minutes from Myeongdong."),

("🕯️","Jogyesa Temple & the chrysanthemum display","🔁 daily (FREE)",
 "The head temple of the Jogye Order in central Seoul, with a 500-year-old white pine and a **large autumn chrysanthemum display typically staged in November**",
 "Daily **04:00–21:00**",
 "**FREE**",
 "[jogyesa.kr](http://www.jogyesa.kr) · Exit 6, Jonggak Stn",
 "**The chrysanthemum festival usually runs in November** — check the temple's calendar. Templestay office is on site."),

("🧘","Templestay in central Seoul","🔁 daily (booking)",
 "Overnight and day templestay programmes at Jogyesa, Bongeunsa and Geumsunsa, run under the official national programme",
 "Day programmes from **13:00**; overnight from 15:00",
 "Day **₩50,000**; overnight from ₩70,000",
 "[templestay.com](https://www.templestay.com)",
 "**English-language programmes available** — book at least a week ahead through the official portal."),

("🛕","Bongeunsa Temple, Gangnam","🔁 daily (FREE)",
 "A 794 CE temple opposite COEX, with a 23 m stone Maitreya and a **Thursday English templestay programme**",
 "Daily **03:00–22:00**",
 "**FREE**",
 "[bongeunsa.org](https://www.bongeunsa.org) · Exit 1, Bongeunsa Stn",
 "**The contrast with the COEX towers across the road** is the reason to come."),

("🏙️","COEX Mall & Starfield Library","🔁 daily (FREE)",
 "**Asia's largest underground shopping centre**, with the two-storey Starfield Library and its 13 m bookshelves",
 "Mall **10:30–22:00**; library to 22:00",
 "**FREE**",
 "[starfield.co.kr](https://www.starfield.co.kr) · Exit 5, Samseong Stn",
 "**The library is free and open to all.** COEX also hosts the Seoul International Cafe Show in November."),

("🏢","Lotte World Tower & Seoul Sky","🔁 daily",
 "**Korea's tallest building at 555 m**, with the Seoul Sky observatory on floors 117–123 and a glass-floor skydeck",
 "Daily **10:00–22:00**",
 "Adult **₩29,000**",
 "[seoulsky.lotteworld.com](https://seoulsky.lotteworld.com) · Exit 1, Jamsil Stn",
 "**Book a timed slot online** for a discount and to skip the queue. Sunset slots go first."),

("🎢","Lotte World Adventure","🔁 daily",
 "**The world's largest indoor theme park**, plus the outdoor Magic Island on Seokchon Lake — fully weatherproof",
 "Daily **10:00–21:00**",
 "Adult day pass **₩62,000**",
 "[lotteworld.com](https://www.lotteworld.com) · Exit 4, Jamsil Stn",
 "**The best bad-weather option in Seoul** — the main park is entirely indoors."),

("🌊","Seokchon Lake & autumn walking loop","🔁 daily (FREE)",
 "The 2.5 km loop around the lake beside Lotte World, planted with cherries and maples and lit at night",
 "Always open",
 "**FREE**",
 "[songpa.go.kr](https://www.songpa.go.kr) · Exit 3, Jamsil Stn",
 "**Free, flat and lit** — a good evening walk with the tower reflected in the water."),

("🏛️","Seoul Baekje Museum & Olympic Park","🔁 Tue–Sun (FREE)",
 "The museum of Seoul's Baekje-period origins beside the earthen fortress walls of Pungnaptoseong, inside Olympic Park",
 "Tue–Sun **09:00–18:00**; closed Mon",
 "**FREE**",
 "[baekjemuseum.seoul.go.kr](https://baekjemuseum.seoul.go.kr) · Exit 3, Mongchontoseong Stn",
 "**Seoul was Baekje's capital for nearly 500 years** — the earthworks are still visible in the park."),

("🌳","Olympic Park & the Lone Tree","🔁 daily (FREE)",
 "The 1988 Olympic site, now a large park with sculpture, the Mongchontoseong earthen fortress and Seoul's most photographed single tree",
 "Always open",
 "**FREE**",
 "[olympicpark.co.kr](https://www.olympicpark.co.kr) · Exit 3, Mongchontoseong Stn",
 "**The 1988 Games were Korea's international coming-out** — the park is full of that moment's design."),

("🏛️","Leeum Museum of Art, Hannam","🔁 Tue–Sun",
 "The Samsung foundation's flagship art museum, in buildings by Mario Botta, Jean Nouvel and Rem Koolhaas, holding National Treasures and contemporary art",
 "Tue–Sun **10:00–18:00**; closed Mon",
 "Permanent collection **FREE**; specials charged",
 "[leeum.org](https://www.leeum.org) · Exit 1, Hangangjin Stn",
 "**The permanent collection is now free** — reserve a timed slot online."),

("🌏","Itaewon & Gyeongnidan international quarter","🔁 daily (FREE)",
 "Seoul's most international district, with global restaurants, the Antique Furniture Street and the Gyeongnidan hillside bar strip",
 "Roughly **11:00–02:00**",
 "**FREE** to browse",
 "[yongsan.go.kr](https://www.yongsan.go.kr) · Exit 1, Itaewon Stn",
 "**Three subway stops from Myeongdong** and the easiest place in Seoul to find non-Korean food."),

("🛍️","Hongdae, Yeonnam-dong & the Gyeongui Line Forest Park","🔁 daily (FREE)",
 "The university district's shopping streets, buskers and clubs, plus the linear park built over a buried railway line in Yeonnam-dong",
 "Streets always open; busking evenings",
 "**FREE**",
 "[mapo.go.kr](https://www.mapo.go.kr) · Exit 9, Hongik Univ Stn",
 "**Street busking peaks on Friday and Saturday evenings** around the Hongdae playground."),

("🛍️","Garosu-gil, Apgujeong & Seongsu","🔁 daily (FREE)",
 "Seoul's designer-retail and concept-store districts: the ginkgo-lined Garosu-gil, Apgujeong Rodeo, and Seongsu's converted factories",
 "Shops roughly **11:00–21:00**",
 "**FREE** to browse",
 "[visitseoul.net](https://english.visitseoul.net) · Exit 8, Sinsa Stn",
 "**Garosu-gil's ginkgos turn gold in early November** — the street is named after its trees."),

("🎤","K-pop landmarks — HYBE, SM, JYP & Starfield COEX","🔁 daily",
 "The label headquarters, artist cafes and the COEX K-pop square, plus official merchandise stores across central Seoul",
 "Roughly **10:00–20:00**",
 "**FREE** to visit; merch varies",
 "[visitseoul.net](https://english.visitseoul.net)",
 "**HYBE Insight museum has closed** — the buildings themselves are exterior-only. Official stores are the reliable stop."),

("🎤","K-pop concerts & music show tapings","👀 WATCH — apply ahead",
 "Music show tapings (*M Countdown*, *Music Bank*, *Inkigayo*) admit audiences by advance application, and November is a heavy concert month",
 "Tapings weekday afternoons",
 "**FREE** by application; concerts vary",
 "[interpark.com](https://ticket.interpark.com) · [visitseoul.net](https://english.visitseoul.net)",
 "**Applications open roughly a week before each taping** and require a fanclub or agency route for many shows."),

("🎫","Interpark, Melon & buying tickets as a visitor","🔁 daily",
 "Korea's main ticketing platforms; Interpark Global handles English-language sales for concerts, musicals and sport",
 "N/A",
 "Booking fees **₩1,000–₩2,000**",
 "[globalinterpark.com](https://www.globalinterpark.com) · [ticket.melon.com](https://ticket.melon.com)",
 "**Use Interpark Global** — the Korean site often requires a Korean ID number."),

("🎳","Myeongdong indoor entertainment — arcades, VR, bowling","🔁 daily",
 "Multi-floor arcades, VR centres, screen golf and bowling around Myeongdong and Euljiro, most open late",
 "Roughly **10:00–02:00**",
 "**₩5,000–₩20,000**",
 "[jung.go.kr](https://www.junggu.seoul.kr) · Exit 6, Myeongdong Stn",
 "**Coin karaoke booths from ₩1,000 for a few songs** — the cheapest fun in Myeongdong."),

("🎤","Noraebang karaoke in Myeongdong","🔁 daily",
 "Karaoke rooms throughout Myeongdong, from coin booths to full private rooms with English song catalogues",
 "Roughly **12:00–06:00**",
 "**₩15,000–₩30,000** per hour per room",
 "[jung.go.kr](https://www.junggu.seoul.kr) · Exit 6, Myeongdong Stn",
 "**Cheaper before 18:00.** Most machines have a large English-language catalogue."),

("♨️","Jjimjilbang near Myeongdong — Silloam & Dragon Hill","🔁 24 h",
 "Large 24-hour bathhouse and sauna complexes near Seoul Station and Yongsan, with sleeping halls and food courts",
 "**24 hours**",
 "**₩15,000–₩20,000** overnight",
 "[silloamsauna.com](https://www.silloamsauna.com) · Exit 1, Seoul Station",
 "**A legitimate cheap overnight option** if you have an early flight. Silloam is the closest to Myeongdong."),

("🍲","Myeongdong Kalguksu & the classic Seoul lunch","🔁 daily",
 "The Myeongdong institutions serving hand-cut noodle soup and steamed dumplings — several trading for over fifty years",
 "Roughly **10:30–21:00**",
 "**₩10,000–₩12,000**",
 "[visitseoul.net](https://english.visitseoul.net) · Exit 8, Myeongdong Stn",
 "**Expect a queue at lunch, but it moves fast** — the turnover is deliberate."),

("🍗","Myeongdong late-night food & Euljiro tables","🔁 nightly",
 "Myeongdong's street food carts run until about 23:00; Euljiro and Namdaemun's night eateries carry on past midnight",
 "Roughly **17:00–02:00**",
 "**₩5,000–₩25,000**",
 "[jung.go.kr](https://www.junggu.seoul.kr)",
 "**Street carts are cash-preferred** and prices are posted — no bargaining."),

("💊","Pharmacies, clinics & English medical help near Myeongdong","🔁 daily",
 "Pharmacies throughout Myeongdong, plus international clinics and the 24-hour emergency departments at nearby university hospitals",
 "Pharmacies roughly **09:00–22:00**",
 "Consultation from **₩20,000** for visitors",
 "[1339 Medical Hotline](https://www.kdca.go.kr) · [seoul.go.kr](https://english.seoul.go.kr)",
 "**119 for ambulance, 1339 for English medical advice, 1330 for tourist interpretation.**"),

("🧭","Myeongdong Tourist Information Centre & 1330","🔁 daily (FREE)",
 "Staffed information centres in Myeongdong and at Cheonggyecheon, plus the red-jacketed roving tourist helpers",
 "Daily **09:00–20:00**",
 "**FREE**",
 "[visitseoul.net](https://english.visitseoul.net) · [1330 Hotline](https://english.visitkorea.or.kr)",
 "**1330 is a free 24-hour interpretation line** — they will speak to a taxi driver or shopkeeper for you."),

("💸","Tax refund for visitors in Myeongdong","🔁 daily",
 "Immediate tax refund at participating Myeongdong shops and self-service kiosks, or at the airport on departure",
 "Kiosks roughly **10:00–22:00**",
 "Refund about **7–8%** of purchase price",
 "[customs.go.kr](https://www.customs.go.kr) · Exit 6, Myeongdong Stn",
 "**Immediate refund needs your passport at the till** and works on purchases up to a per-transaction limit."),

("📶","SIM cards, eSIM & wifi in Myeongdong","🔁 daily",
 "Prepaid SIM and eSIM from the airport counters or Myeongdong shops; Seoul also runs extensive free public wifi",
 "Shops roughly **10:00–21:00**",
 "Data SIM from **₩27,000** for 10 days",
 "[seoul.go.kr](https://english.seoul.go.kr) · [airport.kr](https://www.airport.kr)",
 "**'Seoul Wi-Fi' hotspots are free citywide** but a SIM is worth it for maps and Kakao T taxis."),

("📱","Essential Korean apps — Naver Map, Kakao T, Papago","🔁 daily",
 "Google Maps is restricted for driving directions in Korea; **Naver Map or Kakao Map is essential**, with Kakao T for taxis and Papago for translation",
 "N/A",
 "**FREE**",
 "[naver.com](https://map.naver.com) · [kakaocorp.com](https://www.kakaocorp.com)",
 "**Download these before you arrive.** Naver Map has full English and gives accurate transit routing; Google Maps does not."),

("💰","Myeongdong on a budget — free things to do","🔁 daily (FREE)",
 "The cathedral, Namsangol Hanok Village, the city wall walk, the Namsan free elevator, Namdaemun Market, the Bank of Korea museum and the free national museums",
 "Various",
 "**FREE**",
 "[visitseoul.net](https://english.visitseoul.net)",
 "**A full day in central Seoul can cost only transit and food** — most of the best museums here are free."),

("📸","Central Seoul photo spots","🔁 daily (FREE)",
 "Deoksugung's stone wall road in ginkgo, Namsan Tower from Namsangol, the cathedral spire from the shopping street, DDP after dark and the city from Naksan",
 "Best at dusk",
 "**FREE**",
 "[visitseoul.net](https://english.visitseoul.net)",
 "**Blue hour in mid-November is around 17:30** — Namsan and DDP are both best in that window."),

("🗺️","Myeongdong walking-radius day plan","🔁 planning",
 "Namdaemun Market breakfast → Bank of Korea museum → Myeongdong Cathedral → Namsangol Hanok Village → free elevator → Namsan wall walk → tower at sunset → Euljiro nogari alley",
 "One full day, all on foot",
 "Under **₩40,000** including the tower",
 "[visitseoul.net](https://english.visitseoul.net)",
 "**Everything on this route is within 2 km of Myeongdong Station.** No transit needed at all."),

("🗺️","Myeongdong-based three-day Seoul plan","🔁 planning",
 "Day 1 palaces and Bukchon; Day 2 Namsan, Namdaemun and Euljiro; Day 3 National Museum, War Memorial and the Han River — all from a Myeongdong base",
 "Three days",
 "About **₩60,000** in admissions and transit",
 "[visitseoul.net](https://english.visitseoul.net)",
 "**Myeongdong is the best base in Seoul for a first visit** — central, three subway lines, and the airport buses stop at the door."),
]

append("/home/user/KoreaFun/myeongdong.md", E, 319, 3,
       "\n---\n\n## 🧭 Beginner-friendly essentials", "Myeongdong & central Seoul")
