# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "/home/user/KoreaFun/.build")
from addlib import append

E = [
("🌋","Pohang Yongdeok & Janggi Basalt Columns (주상절리)","🔁 daily (FREE)",
 "Hexagonal basalt columns on the Pohang coast, formed by cooling lava and designated a Natural Monument",
 "Always open; best at low tide",
 "**FREE**",
 "[pohang.go.kr](https://www.pohang.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "On the coast road south of Guryongpo. **Check the tide** — high water covers the base of the columns."),

("🐚","Pohang Homigot Coastal Trail (호미반도 해안둘레길)","🔁 daily (FREE)",
 "A 58 km coastal walking route around the Homi peninsula in four sections, including a boardwalk over the rocks at Seonnyeotang",
 "Always open",
 "**FREE**",
 "[pohang.go.kr](https://www.pohang.go.kr) · [durunubi.kr](https://www.durunubi.kr)",
 "**Section 2 with the sea boardwalk is the one to walk** if you only do one — about 3 hours."),

("🪨","Seonnyeotang & Himal Rock Sea Boardwalk (선녀탕)","🔁 daily (FREE)",
 "A steel boardwalk built directly over the tidal rocks on the Homi peninsula trail, passing rock pools and sea caves",
 "Always open; closed in high seas",
 "**FREE**",
 "[pohang.go.kr](https://www.pohang.go.kr)",
 "**Closed when waves are high** — check before making the trip out."),

("🌊","Janggil-ri & Pohang Southern Fishing Villages","🔁 daily (FREE)",
 "The small working ports south of Guryongpo, where gwamegi is dried on racks in the open sea wind from November",
 "Always open",
 "**FREE** to view",
 "[pohang.go.kr](https://www.pohang.go.kr)",
 "**The drying racks appear in November** — the visible start of the season, and a genuinely unusual sight."),

("🏛️","Pohang Cheongha Confucian Sites & Old County Office","🔁 daily (FREE)",
 "The Joseon county seat at Cheongha, with the old office building, a hyanggyo school and a preserved administrative quarter",
 "Daylight hours",
 "**FREE**",
 "[pohang.go.kr](https://www.pohang.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "On the way to Naeyeonsan. Also holds the Yeongil Folk Museum."),

("🌲","Pohang Bo-gyeong Valley Forest Bathing & Trails","🔁 daily (FREE)",
 "The pine and maple forest around Bogyeongsa, with graded forest-bathing paths as well as the waterfall route",
 "Always open",
 "Temple ticket **₩4,000**",
 "[Korea Forest Service](https://www.forest.go.kr) · [pohang.go.kr](https://www.pohang.go.kr)",
 "**You don't need to walk all twelve waterfalls** — the first three are within an hour of the temple."),

("🏔️","Unjesan & Pohang Inland Hiking (운제산)","🔁 daily (FREE)",
 "The mountain behind Oeosa, with ridge trails and views over the Pohang plain and the sea",
 "Always open",
 "**FREE**",
 "[pohang.go.kr](https://www.pohang.go.kr) · [Korea Forest Service](https://www.forest.go.kr)",
 "Three to four hours for the loop from Oeosa. Well signed."),

("🚴","Pohang Coastal Cycle Route & East Sea Path","🔁 daily (FREE)",
 "Pohang sits on the **East Coast Cycling Route**, part of Korea's certified national bike network running from Goseong to Busan",
 "Always open",
 "**FREE**; rental from ₩15,000/day",
 "[riverguide.go.kr](https://www.riverguide.go.kr) · [pohang.go.kr](https://www.pohang.go.kr)",
 "Certification stamp booths at Homigot and Yeongildae. **The Homigot section is the scenic highlight.**"),

("🎡","Pohang Children's & Family Facilities","🔁 Tue–Sun",
 "Pohang's children's museum, the science centre and the Hwanho Park play areas — indoor options for a cold or wet day",
 "Tue–Sun **10:00–18:00**",
 "**FREE**–₩5,000",
 "[pohang.go.kr](https://www.pohang.go.kr)",
 "Space Walk itself has a minimum height requirement — check before promising it to small children."),

("🏛️","Pohang Modern History & POSCO Museum","🔁 weekdays",
 "The story of how a fishing village became a steel city after 1968, told at the POSCO history hall and the city's exhibitions",
 "Weekdays **09:00–17:00**; booking advised",
 "**FREE**",
 "[posco.co.kr](https://www.posco.co.kr) · [pohang.go.kr](https://www.pohang.go.kr)",
 "**Pohang's population went from 50,000 to 500,000 in thirty years** because of this plant."),

("☕","Pohang Cafe Streets — Yeongildae & Hyoja","🔁 daily",
 "Sea-view cafes along Yeongildae Beach and the independent cafe cluster in Hyoja-dong near POSTECH",
 "Roughly **10:00–22:00**",
 "Coffee **₩5,000–₩7,000**",
 "[pohang.go.kr](https://www.pohang.go.kr)",
 "**The Yeongildae seafront cafes look straight at the lit steelworks after dark.**"),

("🍺","Pohang Nightlife & Yukhoe Alley","🔁 nightly",
 "Pohang's evening districts around Jukdo Market and Yukdaemyeong, with raw-beef restaurants, pubs and late seafood",
 "Roughly **17:00–02:00**",
 "**₩15,000–₩30,000** per person",
 "[pohang.go.kr](https://www.pohang.go.kr)",
 "**Jukdo Market's second floor stays open late** for fish and drinks — cheaper than the seafront."),

("🛍️","Pohang Shopping — Jukdo, Lotte & downtown","🔁 daily",
 "Jukdo Market for food and goods, plus a Lotte department store and the downtown Yukgeori shopping district",
 "Market **06:00–21:00**; stores **10:30–20:00**",
 "**FREE** entry",
 "[lotteshopping.com](https://www.lotteshopping.com) · [pohang.go.kr](https://www.pohang.go.kr)",
 "Dried seafood and gwamegi vacuum-packed for travel are the standard Pohang souvenirs."),

("🏨","Pohang Accommodation — beach vs downtown","🔁 planning",
 "Yeongildae Beach for sea views, downtown near Jukdo for food and buses, and Guryongpo for the fishing-village experience",
 "Check-in typically **15:00**",
 "From **₩45,000** per night",
 "[pohang.go.kr](https://www.pohang.go.kr) · [visitkorea.or.kr](https://english.visitkorea.or.kr)",
 "**Yeongildae is the best base** — the beach, the cafes and the bus routes are all there."),

("♨️","Pohang Bathhouses & Seawater Spas","🔁 daily",
 "Jjimjilbang in central Pohang and seawater bathhouses near the beach, useful after a coastal walk in the wind",
 "Many **24 hours**",
 "**₩10,000–₩15,000**",
 "[pohang.go.kr](https://www.pohang.go.kr)",
 "Seawater baths are a local speciality on the east coast."),

("🚑","Pohang Emergency & Medical Services","🔁 24 h",
 "Pohang St Mary's and Pohang Semyeong Christian hospitals run 24-hour emergency departments",
 "Emergency **24 h**",
 "Consultation from **₩20,000** for visitors",
 "[1339 Medical Hotline](https://www.kdca.go.kr) · [pohang.go.kr](https://www.pohang.go.kr)",
 "**119 for ambulance, 1339 for English medical advice.**"),

("🌏","Pohang for foreign visitors — language & payment","🔁 daily",
 "Pohang sees relatively few foreign tourists; English signage exists at major sites but market stalls are cash and Korean only",
 "N/A",
 "N/A",
 "[1330 Hotline](https://english.visitkorea.or.kr) · [ipohang.org](https://www.ipohang.org)",
 "**Carry cash for Jukdo Market.** Dial 1330 for free 24-hour interpretation."),

("🌡️","Pohang Wind, Sea State & Cancellation Risk","🔁 planning",
 "The Space Walk, the harbour cruise, the Ulleungdo ferry and the sea boardwalk all close in strong wind — common on this coast in November",
 "N/A",
 "N/A",
 "[weather.go.kr](https://www.weather.go.kr) · [Korea Maritime Safety](https://www.komsa.or.kr)",
 "**Have an indoor plan.** The steel art museum, the lighthouse museum and Jukdo Market all work in bad weather."),

("🗺️","Pohang & Gyeongju combined itinerary","🔁 planning",
 "Gyeongju and Pohang are 40 minutes apart; a common plan is Gyeongju heritage by day and Pohang coast and seafood by evening",
 "Buses roughly every 20 min",
 "Bus **₩4,500**",
 "[kobus.co.kr](https://www.kobus.co.kr) · [pohang.go.kr](https://www.pohang.go.kr)",
 "**Base in Gyeongju, day-trip to Pohang** — or the reverse if you want the sea view from your window."),

("📸","Pohang Photo Spots — the definitive list","🔁 daily (FREE)",
 "Space Walk against the sky, the Hands of Harmony at sunrise, Yeongildae pavilion with the lit steelworks, and Oeosa's reflected maples",
 "Best at sunrise and after dark",
 "**FREE**",
 "[ipohang.org](https://www.ipohang.org) · [pohang.go.kr](https://www.pohang.go.kr)",
 "**Sunrise at Homigot around 07:00 in November** and the steelworks after 18:00 are the two unmissable shots."),
]

append("/home/user/KoreaFun/pohang.md", E, 176, 3,
       "\n---\n\n## 🧭 Beginner-friendly essentials", "Pohang")
