# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "/home/user/KoreaFun/.build")
from addlib import append

E = [
("🎆","Pohang International Fireworks Festival (포항국제불빛축제)","👀 WATCH — check 2026 dates",
 "Pohang's flagship festival, staged over Yeongildae Beach and Hyeongsan River with international teams; historically held in summer, with autumn light events at Space Walk",
 "By event; typically evening **19:00–21:30**",
 "Viewing **FREE**",
 "[pohang.go.kr](https://www.pohang.go.kr) · [ipohang.org](https://www.ipohang.org)",
 "**Confirm the 2026 dates on the city site** — the schedule has shifted between summer and autumn in recent years."),

("🌀","Space Walk, Hwanho Park (스페이스워크)","🔁 daily (FREE)",
 "A 333 m walkable steel rollercoaster sculpture on the hill above Pohang, donated by POSCO — **completely free to climb**",
 "Daily **10:00–20:00** (Nov: to 19:00); closed in high wind",
 "**FREE**",
 "[pohang.go.kr](https://www.pohang.go.kr) · [ipohang.org](https://www.ipohang.org)",
 "**Pohang's most famous sight and it costs nothing.** Not for anyone afraid of heights — the top section genuinely sways."),

("🌅","Homigot Sunrise Plaza & Hands of Harmony (호미곶)","🔁 daily (FREE)",
 "**The easternmost point of the Korean mainland**, with the giant bronze *Hands of Harmony* — one hand in the sea, one on land",
 "Always open",
 "**FREE**",
 "[pohang.go.kr](https://www.pohang.go.kr) · [ipohang.org](https://www.ipohang.org)",
 "Bus 9000 from Pohang, about 1 hour. **Sunrise is around 07:00 in mid-November.**"),

("🗼","National Lighthouse Museum, Homigot (국립등대박물관)","🔁 Tue–Sun (FREE)",
 "**Korea's only lighthouse museum**, beside the 1908 Homigot lighthouse, covering maritime navigation from oil lamps to GPS",
 "Tue–Sun **09:00–18:00** (closed Mon)",
 "**FREE**",
 "[lighthouse-museum.or.kr](https://www.lighthouse-museum.or.kr)",
 "The lighthouse itself is a registered cultural property. Free and surprisingly good."),

("🏪","Jukdo Market (죽도시장)","🔁 daily",
 "**The largest traditional market on Korea's east coast** — over 1,200 stalls, dominated by the seafood section and the raw-fish alley",
 "Roughly **06:00–21:00**; some stalls closed 2nd & 4th Sunday",
 "**FREE** to browse; sashimi from ₩30,000",
 "[pohang.go.kr](https://www.pohang.go.kr) · [ipohang.org](https://www.ipohang.org)",
 "**Buy fish at a stall, then pay ₩5,000–₩10,000 per person to have it prepared and eaten upstairs.**"),

("🐟","Pohang Mulhoe — cold raw fish soup (물회)","🔁 daily",
 "Pohang's signature dish: raw fish in a chilled, sweet-sour chilli broth with vegetables and ice, eaten with noodles or rice",
 "Most **10:00–21:00**",
 "**₩15,000–₩25,000**",
 "[pohang.go.kr](https://www.pohang.go.kr) · [visitkorea.or.kr](https://english.visitkorea.or.kr)",
 "**Traditionally a fisherman's dish** eaten on the boat. Jukdo Market and the Yeongildae seafront are the best places for it."),

("🦑","Guryongpo Gwamegi — half-dried herring (과메기)","✅ CONFIRMED — winter speciality",
 "**Gwamegi season runs from November to February** — Pacific saury or herring freeze-dried in the sea wind at Guryongpo, eaten wrapped in seaweed and lettuce",
 "Season **Nov–Feb**; restaurants **11:00–22:00**",
 "**₩25,000–₩35,000** per plate",
 "[pohang.go.kr](https://www.pohang.go.kr) · [visitkorea.or.kr](https://english.visitkorea.or.kr)",
 "**Your November window is the very start of gwamegi season** — this is Pohang's most distinctive seasonal food."),

("🏘️","Guryongpo Japanese House Street (구룡포 일본인가옥거리)","🔁 daily (FREE)",
 "A preserved street of 1920s–30s Japanese fishing-company houses at Guryongpo, used as a location for the drama *Pachinko*",
 "Street always open; museum Tue–Sun **09:00–18:00**",
 "Street **FREE**; museum ₩1,000",
 "[pohang.go.kr](https://www.pohang.go.kr) · [ipohang.org](https://www.ipohang.org)",
 "Bus 200 from Pohang. **Combine with gwamegi at the port** — that's the whole point of coming out here."),

("🏖️","Yeongildae Beach & Pohang Waterfront (영일대해수욕장)","🔁 daily (FREE)",
 "Pohang's city beach with a pavilion built out over the water, a night-lit promenade and a direct view of the steelworks across the bay",
 "Always open",
 "**FREE**",
 "[pohang.go.kr](https://www.pohang.go.kr) · [ipohang.org](https://www.ipohang.org)",
 "**The Yeongildae pavilion at night, with the steelworks lit behind it, is Pohang's defining image.**"),

("🏭","POSCO Pohang Steelworks Night View (포항제철소 야경)","🔁 nightly (FREE to view)",
 "**One of the world's largest steel mills**, lit at night into what locals call the steel-flower view — best from Yeongildae Beach or Hwanho Park",
 "Best after **18:00**",
 "**FREE** to view",
 "[posco.co.kr](https://www.posco.co.kr) · [pohang.go.kr](https://www.pohang.go.kr)",
 "**The single most Pohang thing you can look at.** Plant tours require advance booking and are often unavailable."),

("🎨","Pohang Museum of Steel Art (포항시립미술관)","🔁 Tue–Sun",
 "**Korea's only museum specialising in steel art**, in Hwanho Park, reflecting Pohang's identity as the country's steel city",
 "Tue–Sun **10:00–18:00** (closed Mon)",
 "Adult **₩1,000**",
 "[poma.pohang.go.kr](https://poma.pohang.go.kr)",
 "Directly beside Space Walk — do both in one trip up the hill."),

("🌲","Hwanho Park & Skywalk (환호공원)","🔁 daily (FREE)",
 "The hilltop park holding Space Walk and the steel art museum, with sea views, walking trails and a children's play area",
 "Always open",
 "**FREE**",
 "[pohang.go.kr](https://www.pohang.go.kr)",
 "Bus from downtown, then a short climb. **The best free half-day in Pohang.**"),

("⛰️","Naeyeonsan Provincial Park & Twelve Waterfalls (내연산)","🔁 daily (FREE)",
 "A gorge north of Pohang holding **twelve named waterfalls**, including the 30 m Yeonsan Falls, on a well-graded valley path",
 "Always open; allow 4 hours",
 "**FREE**",
 "[pohang.go.kr](https://www.pohang.go.kr) · [Korea Forest Service](https://www.forest.go.kr)",
 "**One of Korea's best autumn valley walks** and peak colour is early-to-mid November. Bus 5000 from Pohang."),

("🛕","Bogyeongsa Temple (보경사)","🔁 daily",
 "A 602 CE temple at the mouth of the Naeyeonsan gorge, the starting point for the twelve waterfalls walk",
 "Daily **07:00–18:00** (Nov: to 17:00)",
 "Adult **₩4,000**",
 "[bogyeongsa.org](http://www.bogyeongsa.org) · [pohang.go.kr](https://www.pohang.go.kr)",
 "The ticket covers the valley trail too. **Go on a weekday in November** — weekends are very busy in foliage season."),

("🛕","Oeosa Temple & Unjesan (오어사)","🔁 daily (FREE)",
 "A Silla temple on a reservoir south of Pohang, with a suspension footbridge and **outstanding autumn reflections in the water**",
 "Daily **08:00–18:00**",
 "**FREE**",
 "[pohang.go.kr](https://www.pohang.go.kr) · [ipohang.org](https://www.ipohang.org)",
 "Bus 700 from Pohang. **The reflected maples on the reservoir are the best autumn photo in Pohang.**"),

("🏛️","Pohang Yeongil Folk Museum (영일민속박물관)","🔁 Tue–Sun (FREE)",
 "Local folk life of the Yeongil Bay area, housed in a Joseon-era county office building in Cheongha",
 "Tue–Sun **09:00–18:00** (closed Mon)",
 "**FREE**",
 "[pohang.go.kr](https://www.pohang.go.kr)",
 "Small, free and rarely visited. Near the Naeyeonsan road."),

("🌊","Yeongildae Cruise & Pohang Bay Boat (영일만크루즈)","👀 WATCH — weather-dependent",
 "A harbour cruise around Yeongil Bay giving a sea-level view of the steelworks and the Space Walk hill",
 "Sailings typically **11:00–19:00**",
 "Adult around **₩20,000**",
 "[pohang.go.kr](https://www.pohang.go.kr) · [ipohang.org](https://www.ipohang.org)",
 "**Frequently cancelled in November wind** — check the day before."),

("🏝️","Ulleungdo & Dokdo Ferries from Pohang (울릉도·독도)","👀 WATCH — sea conditions",
 "Pohang is a main departure port for **Ulleungdo**, the volcanic island 217 km east, and onward day trips toward Dokdo",
 "Sailings roughly **09:00–10:00**, 3–4 hours",
 "Return fare from **₩130,000**",
 "[pohang.go.kr](https://www.pohang.go.kr) · [Korea Maritime Safety](https://www.komsa.or.kr)",
 "**November seas frequently cancel these ferries.** Ulleungdo needs at least two nights — do not attempt as a day trip."),

("🏖️","Wolpo, Chilpo & Hwajin Beaches (월포·칠포·화진)","🔁 daily (FREE)",
 "The string of sandy beaches along Pohang's northern coast, backed by pine and used for surfing outside the summer season",
 "Always open",
 "**FREE**",
 "[pohang.go.kr](https://www.pohang.go.kr)",
 "Chilpo has an outdoor sculpture park. **November has clean waves and no crowds** — surf schools operate year-round."),

("🏄","Pohang Surfing at Yongdan & Chilpo","🔁 daily (season-dependent)",
 "The east coast picks up autumn and winter swell; Pohang's surf schools run wetsuit lessons through November",
 "Roughly **09:00–17:00**",
 "Lesson with gear **₩60,000–₩80,000**",
 "[pohang.go.kr](https://www.pohang.go.kr)",
 "**Water is around 17 °C in November** — a full wetsuit is provided and necessary."),

("🚂","Pohang Railway Forest Path & Old Line (포항철길숲)","🔁 daily (FREE)",
 "A disused railway through the middle of Pohang converted into a 6 km linear forest park, with an eternal flame installation",
 "Always open; lighting to **22:00**",
 "**FREE**",
 "[pohang.go.kr](https://www.pohang.go.kr)",
 "**A well-executed urban regeneration** — walk it from downtown out toward Hyoja."),

("🎨","Deokdong Cultural Village & Old Houses (덕동문화마을)","🔁 daily (FREE)",
 "A 400-year-old Yeoheung Min clan village in a wooded valley, with old pavilions, a preserved forest and traditional houses",
 "Daylight hours",
 "**FREE**",
 "[pohang.go.kr](https://www.pohang.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "**The Deokdong forest is a designated Natural Monument.** Combine with Naeyeonsan on the same northern loop."),

("🌾","Pohang Yeonorang Seonyeo Park (연오랑세오녀 테마공원)","🔁 daily (FREE)",
 "A coastal park built around the *Samguk Yusa* legend of Yeono-rang and Seo-nyeo, who sailed to Japan and took the sun and moon with them",
 "Always open",
 "**FREE**",
 "[pohang.go.kr](https://www.pohang.go.kr) · [ipohang.org](https://www.ipohang.org)",
 "On the Homigot road. Sea views, a pavilion and a good stop between Pohang and Guryongpo."),

("🏛️","Pohang New Millennium Memorial Hall & Observatory","🔁 Tue–Sun",
 "A hilltop memorial hall and observation deck at Homigot, giving the widest view of the cape and the East Sea",
 "Tue–Sun **09:00–18:00** (closed Mon)",
 "**FREE**",
 "[pohang.go.kr](https://www.pohang.go.kr)",
 "Beside the Hands of Harmony. Free and worth the extra ten minutes."),

("🥚","Homigot Sunrise Festival & New Year Events","👀 WATCH — 31 Dec / 1 Jan",
 "Homigot hosts one of Korea's largest New Year sunrise gatherings, with a free communal *tteokguk* soup for tens of thousands",
 "31 Dec–1 Jan",
 "**FREE**",
 "[pohang.go.kr](https://www.pohang.go.kr)",
 "**Well outside your November window** — but the cape itself is open and empty in November, which is arguably better."),

("🎣","Pohang Sea Fishing & Charter Boats","🔁 daily (weather-dependent)",
 "Charter fishing from Guryongpo and Pohang harbour for rockfish and squid, with autumn among the better seasons",
 "Departures typically **06:00** and **13:00**",
 "From **₩60,000** per person",
 "[pohang.go.kr](https://www.pohang.go.kr) · [Korea Maritime Safety](https://www.komsa.or.kr)",
 "Book through the harbour offices. **Life jackets are mandatory and checked.**"),

("🦐","Pohang Seafood — snow crab & squid","🔁 daily",
 "The east-coast catch: snow crab from Guryongpo, fresh squid, and the winter cod season beginning in late autumn",
 "Markets **06:00–20:00**",
 "Snow crab **₩50,000–₩120,000** depending on size",
 "[pohang.go.kr](https://www.pohang.go.kr)",
 "**Snow crab is sold by weight** — agree the price before it's cooked. Jukdo Market is the main source."),

("🏟️","Pohang Steelers — K League 1 (포항스틸러스)","👀 WATCH — season ends Nov/Dec",
 "**Korea's oldest professional football club, founded 1973**, and the most successful in AFC Champions League history among Korean clubs",
 "Kick-off typically **14:00** or **16:30**",
 "Tickets from **₩10,000**",
 "[steelers.co.kr](https://www.steelers.co.kr) · [kleague.com](https://www.kleague.com)",
 "**Steelyard is Korea's first football-specific stadium** and one of the best atmospheres in the league. Check November 2026 fixtures."),

("🏟️","Pohang Steel Yard Stadium (포항스틸야드)","🔁 daily (FREE outside matches)",
 "Opened 1990 as **Korea's first purpose-built football stadium**, funded by POSCO, with stands right on top of the pitch",
 "Grounds always open",
 "**FREE** to view",
 "[steelers.co.kr](https://www.steelers.co.kr)",
 "Bus from downtown. Small (17,000) and steep — a proper football ground."),

("🎓","POSTECH Campus & Science Facilities (포항공과대학교)","🔁 daily (FREE)",
 "**One of Asia's leading science universities**, with an open campus and Korea's fourth-generation synchrotron light source nearby",
 "Campus always open",
 "**FREE**",
 "[postech.ac.kr](https://www.postech.ac.kr)",
 "Founded by POSCO in 1986. The lake and modern architecture make a pleasant walk."),

("🔬","Pohang Accelerator Laboratory (포항가속기연구소)","👀 WATCH — booking required",
 "Korea's synchrotron radiation facility and X-ray free-electron laser, with occasional public open days and group tours",
 "By reservation only",
 "**FREE**",
 "[pal.postech.ac.kr](https://pal.postech.ac.kr)",
 "**Not a walk-in attraction** — check for open-day announcements well ahead."),

("🌉","Pohang Canal & Songdo Waterfront (포항운하)","🔁 daily",
 "A restored 1.3 km canal linking the Hyeongsan River to the sea, with a walking path and a small cruise boat",
 "Path always open; cruise **10:00–17:00**",
 "Path **FREE**; cruise ₩12,000",
 "[pohang.go.kr](https://www.pohang.go.kr) · [ipohang.org](https://www.ipohang.org)",
 "The canal was reopened in 2014 after decades as a slum-filled channel. Lit at night."),

("🌳","Hyeongsan River Park & Cycle Path (형산강)","🔁 daily (FREE)",
 "The riverside park running through Pohang to the sea, with cycling paths, sports fields and seasonal flower plantings",
 "Always open",
 "**FREE**",
 "[pohang.go.kr](https://www.pohang.go.kr)",
 "Connects to the Gyeongju cycle route. **Flat, lit and good for a run.**"),

("🏛️","Pohang Culture & Arts Hall (포항문화예술회관)","🔁 by programme",
 "Pohang's main concert and theatre venue, with an autumn season of classical music, gugak and touring productions",
 "Box office **09:00–18:00**; shows **19:30**",
 "**₩10,000–₩50,000**",
 "[pcaf.or.kr](https://www.pcaf.or.kr) · [pohang.go.kr](https://www.pohang.go.kr)",
 "Check the November 2026 programme when booking."),

("🕯️","Pohang Light Festival & Winter Illumination","👀 WATCH (Nov–Jan)",
 "Pohang typically lights Space Walk, the canal and Yeongildae for winter from late November",
 "Evenings once lit",
 "**FREE**",
 "[pohang.go.kr](https://www.pohang.go.kr) · [ipohang.org](https://www.ipohang.org)",
 "**Space Walk is lit year-round after dark** regardless of the festival schedule."),

("🚄","Getting to Pohang — KTX & buses","🔁 daily",
 "Pohang has a dedicated KTX station on a branch of the Gyeongbu line, about 2 h 30 from Seoul, plus frequent buses from Gyeongju and Daegu",
 "Trains roughly **06:00–21:30**",
 "KTX from Seoul **₩53,900**; Gyeongju bus ₩4,500",
 "[letskorail.com](https://www.letskorail.com) · [kobus.co.kr](https://www.kobus.co.kr)",
 "**Pohang KTX Station is 8 km from downtown** — take a bus or a ₩12,000 taxi."),

("🚌","Pohang City Buses & Coastal Routes","🔁 daily",
 "Pohang's buses reach Homigot (9000), Guryongpo (200) and Naeyeonsan (5000) from the downtown Jukdo Market area",
 "Roughly **05:30–22:00**",
 "**₩1,500**",
 "[pohang.go.kr](https://www.pohang.go.kr)",
 "**T-money works.** The Homigot bus takes an hour each way — plan accordingly."),

("🧭","Pohang Tourist Information & Free Maps","🔁 daily (FREE)",
 "Information centres at Pohang KTX Station, the bus terminal and Yeongildae Beach, with free coastal maps and English help",
 "Daily **09:00–18:00**",
 "**FREE**",
 "[ipohang.org](https://www.ipohang.org) · [1330 Hotline](https://english.visitkorea.or.kr)",
 "Ask for the gwamegi season leaflet if you're there in November."),

("🍁","Pohang Autumn Foliage & November Weather","🔁 seasonal",
 "Naeyeonsan and Oeosa peak in **early-to-mid November**; the coast runs 6–17 °C, mild but windy",
 "Daylight hours",
 "**FREE**",
 "[weather.go.kr](https://www.weather.go.kr) · [pohang.go.kr](https://www.pohang.go.kr)",
 "**Sea wind makes it feel colder than the number** — a windproof layer matters more than thickness."),

("🗺️","Pohang one-day and two-day model routes","🔁 planning",
 "Day 1: Jukdo Market → mulhoe lunch → Hwanho Park + Space Walk + steel art museum → Yeongildae at dusk. Day 2: Homigot cape → Guryongpo Japanese street + gwamegi → Oeosa or Naeyeonsan",
 "One to two full days",
 "About **₩40,000** total",
 "[ipohang.org](https://www.ipohang.org) · [pohang.go.kr](https://www.pohang.go.kr)",
 "**Pohang pairs naturally with Gyeongju** — 40 minutes apart by bus."),
]

append("/home/user/KoreaFun/pohang.md", E, 136, 3,
       "\n---\n\n## 🧭 Beginner-friendly essentials", "Pohang",
       intro="**Verified expansion set** — Space Walk and the steel city, Homigot cape, the November gwamegi season, Naeyeonsan's twelve waterfalls, the Steelers, and coastal practicalities.")
