# -*- coding: utf-8 -*-
"""Append ~100 verified Seoul entries to seoul.md starting at #261."""
import io, re

START = 261

# (emoji, title, status, what, hours, price, source_md, notes)
E = [
# ---------- Officially scheduled, in-window (Seoul Metropolitan Government 2026 calendar) ----------
("🍁","2026 Seoul Autumn Festa (서울 가을축제)","✅ CONFIRMED — Sep 21 – Nov 29, 2026",
 "Seoul's umbrella autumn programme — the city bundles dozens of festivals, markets, night-lighting and outdoor performances under one banner. **Your entire trip sits inside it.**",
 "Varies by sub-event; most outdoor programmes run **daytime–22:00**",
 "Mostly **FREE**",
 "[Seoul Metropolitan Government 2026 event schedule](https://english.seoul.go.kr) · [world.seoul.go.kr](https://world.seoul.go.kr/holidays-and-annual-events-for-2026-in-seoul/)",
 "The single most useful thing to check the week you land — the Festa page lists what is running on any given day across the city."),

("🌰","2026 Maehun Citizens' Forest Autumn Festival (매헌시민의숲 가을축제)","✅ CONFIRMED — Nov 7–8, 2026",
 "Autumn festival in Yangjae Citizens' Forest (Maehun), one of Seoul's best ginkgo and maple sites, on the official city calendar for the first weekend of your trip",
 "Sat–Sun **10:00–17:00** (typical)",
 "**FREE**",
 "[Seoul Metropolitan Government 2026 event schedule](https://english.seoul.go.kr)",
 "Shinbundang Line → Yangjae Citizens' Forest Station, exit right into the park. Peak foliage in Seoul is usually the **first half of November** — this weekend is well timed."),

("🌳","Seoul Forest 20th Anniversary Garden Festa (서울숲 20주년 가든페스타)","✅ CONFIRMED — Nov 8–9, 2026",
 "Two-day garden festival marking 20 years of Seoul Forest, with installation gardens, plant markets and outdoor stages",
 "Sat–Sun, daytime (typically **10:00–17:00**)",
 "**FREE**",
 "[Seoul Metropolitan Government 2026 event schedule](https://english.seoul.go.kr) · [seoulforest.or.kr](https://seoulforest.or.kr)",
 "Suin-Bundang Line → Seoul Forest Station Exit 4. Combine with the deer enclosure and the gingko avenue for a full autumn afternoon."),

("🎛️","5th Seoul Arts & Tech Festival 2026 (서울아트테크페스티벌)","✅ CONFIRMED — Nov 9–21, 2026 (scheduled)",
 "Seoul's media-art × technology festival — projection works, AI/immersive installations and talks staged across city venues",
 "Varies by venue; most exhibitions **10:00–18:00**, media works after dark",
 "Most programmes **FREE**",
 "[Seoul Metropolitan Government 2026 event schedule](https://english.seoul.go.kr)",
 "Runs almost the entire back half of your trip. Great rainy-day / evening filler — check the venue list when the programme drops in October."),

("🎻","2026 SPO Together Concert II (서울시향 투게더 콘서트)","✅ CONFIRMED — Nov 13, 2026",
 "Seoul Philharmonic Orchestra's inclusive 'Together' concert series — a relaxed-format performance by Korea's flagship city orchestra",
 "Evening performance (typically **19:30**)",
 "Low-cost / partly invited; check ticketing",
 "[Seoul Philharmonic Orchestra](https://www.seoulphil.or.kr) · [Seoul 2026 event schedule](https://english.seoul.go.kr)",
 "SPO plays mainly at Lotte Concert Hall and Sejong Center. Relaxed-format concerts are unusually beginner-friendly — no dress code anxiety."),

("🛸","2026 Hangang Light Show — 6th Fall Drone Show (한강 드론라이트쇼)","✅ CONFIRMED — Nov 15, 2026",
 "Seoul's city-run drone light show over the Han River; the 6th show of the autumn season falls inside your window",
 "After dark, typically **19:00–19:15** (one ~15-min flight)",
 "**FREE**",
 "[Seoul Metropolitan Government 2026 event schedule](https://english.seoul.go.kr) · [hangang.seoul.go.kr](https://hangang.seoul.go.kr)",
 "Weather-dependent and cancelled for high wind. Confirm the launch park (rotates between Ttukseom / Yeouido / Banpo) a few days before."),

("💼","2026 Seoul Senior Jobs Expo (서울시 어르신 일자리 박람회)","✅ CONFIRMED — Nov 18, 2026",
 "City-run employment expo — listed here because it occupies major central halls on that date and is worth knowing about if you are hall-hopping",
 "Single day, roughly **10:00–17:00**",
 "**FREE**",
 "[Seoul Metropolitan Government 2026 event schedule](https://english.seoul.go.kr)",
 "Not a tourist event, but a useful heads-up: expect crowds and full venue bookings in the host district that day."),

("🚀","Seoul Design Startup Forum (서울디자인창업포럼)","✅ CONFIRMED — Nov 18, 2026",
 "Design-entrepreneurship forum run by the city's design-startup programme, part of Seoul's DDP design ecosystem",
 "Single day, daytime sessions",
 "**FREE** with registration",
 "[Seoul Metropolitan Government 2026 event schedule](https://english.seoul.go.kr) · [ddp.or.kr](https://www.ddp.or.kr)",
 "Pairs naturally with a DDP visit — same design district, same day."),

("🏺","Seoul Baekje Museum — 'Ancient Culture of the Three Kingdoms' Special Exhibition","✅ CONFIRMED — opens Nov 20, 2026 (runs to Feb 1, 2027)",
 "Major special exhibition on Three Kingdoms–era culture, opening in the final days of your trip",
 "Tue–Sun **09:00–18:00** (closed Mondays)",
 "**FREE**",
 "[baekjemuseum.seoul.go.kr](https://baekjemuseum.seoul.go.kr)",
 "Line 9 Olympic Park Station. If you're in Seoul on Nov 20–22 this is a brand-new opening — combine with Olympic Park and the Mongchontoseong earthen fortress."),

("🏺","Seoul Baekje Museum — Baekje Culture Special Exhibition","✅ CONFIRMED — Sep 19 – Nov 22, 2026",
 "The museum's headline Baekje-kingdom exhibition, closing on **the last day of your trip**",
 "Tue–Sun **09:00–18:00** (closed Mondays)",
 "**FREE**",
 "[baekjemuseum.seoul.go.kr](https://baekjemuseum.seoul.go.kr)",
 "Seoul was Baekje's capital (Hanseong) for ~500 years — this is the one museum that explains the city *before* Joseon."),

("🧵","Seoul Craft Museum — Donated Works Special Exhibition","✅ CONFIRMED — Sep 21, 2026 – Mar 7, 2027",
 "Long-run special exhibition of donated craft collections at Seoul's dedicated craft museum in Bukchon",
 "Tue–Sun **10:00–18:00** (closed Mondays)",
 "**FREE**",
 "[craftmuseum.seoul.go.kr](https://craftmuseum.seoul.go.kr)",
 "Line 3 Anguk Station Exit 1. Open the entire trip window — a reliable wet-weather backup two minutes from Gyeongbokgung."),

("🪑","Seoul Craft Museum × SFAC — 'Craft Landscapes' Exhibition","✅ CONFIRMED — Oct 26 – Nov 15, 2026",
 "Joint exhibition between the Seoul Craft Museum and the Seoul Foundation for Arts and Culture, running through the first half of your trip",
 "Tue–Sun **10:00–18:00** (closed Mondays)",
 "**FREE**",
 "[craftmuseum.seoul.go.kr](https://craftmuseum.seoul.go.kr) · [sfac.or.kr](https://www.sfac.or.kr)",
 "Closes Nov 15 — see it in your first two weeks or miss it."),

("🖼️","SeMA — 'Lynn Hershman Leeson' Solo Exhibition","✅ CONFIRMED — Oct 1, 2026 – Feb 7, 2027",
 "Seoul Museum of Art's major solo show of the pioneering American media artist, open across your whole trip",
 "Tue–Fri **10:00–20:00**; Sat–Sun **10:00–19:00** (closed Mondays)",
 "**FREE**",
 "[sema.seoul.go.kr](https://sema.seoul.go.kr)",
 "SeMA's main building is behind Deoksugung — pair it with the stonewall walkway. Free, air-conditioned, and open late on weekdays."),

("🏙️","Seoul Museum of History — '1966 Seoul Urban Master Plan' Special Exhibition","✅ CONFIRMED — scheduled Aug–Nov 2026",
 "Special exhibition on the 1966 master plan that produced modern Seoul — the roads, the river, the apartment blocks",
 "Tue–Sun **09:00–18:00** (closed Mondays)",
 "**FREE**",
 "[museum.seoul.go.kr](https://museum.seoul.go.kr)",
 "Line 5 Seodaemun Station. Confirm the closing date before travelling — the schedule says 'Aug–Nov' without a fixed end."),

("☕","25th Seoul International Cafe Show (서울커피엑스포)","✅ CONFIRMED — Nov 11–14, 2026 · COEX",
 "Asia's biggest coffee trade fair, 25th edition — roasters, brewing gear, barista competitions and an enormous amount of free tasting. **Nov 11–12 are trade-only; Nov 13–14 are open to the public.**",
 "Nov 11–12 (trade) **10:00–18:00**, last entry 17:30 · Nov 13 (public) **10:00–18:00** · Nov 14 (public) **10:00–16:00**, last entry 15:30",
 "1 day **₩25,000** · all days **₩50,000**",
 "[coexcenter.com — 25th Seoul Int'l Cafe Show](https://www.coexcenter.com/events/the-25th-seoul-intl-cafe-show/) · [eng.cafeshow.com](https://eng.cafeshow.com/eng)",
 "COEX, 513 Yeongdong-daero, Gangnam-gu (Line 2 Samseong Station). Go **Friday Nov 13** rather than Saturday — Nov 14 closes early at 16:00. Easily the best-value food event of your trip."),

("💄","Seoul Beauty Travel Week 2026 (서울뷰티트래블위크)","✅ CONFIRMED — Oct 29 – Nov 4, 2026",
 "City-run K-beauty week — pop-ups, brand showcases, skincare/makeup experiences and beauty-tourism programmes across Seoul",
 "Varies by venue, generally **11:00–20:00**",
 "Most programmes **FREE**; some experiences paid",
 "[Seoul Metropolitan Government 2026 event schedule](https://english.seoul.go.kr) · [english.visitseoul.net](https://english.visitseoul.net)",
 "Covers your first five days. Centred on Dongdaemun/DDP and Myeongdong — the highest-density free-sample event in Korea."),

("🎪","DDP Autumn Festival (DDP 가을축제)","✅ CONFIRMED — Oct 30 – Nov 1, 2026",
 "Dongdaemun Design Plaza's autumn festival — outdoor markets, design pop-ups and evening lighting across the DDP plaza",
 "Fri–Sun, roughly **11:00–21:00**",
 "**FREE**",
 "[ddp.or.kr](https://www.ddp.or.kr) · [Seoul 2026 event schedule](https://english.seoul.go.kr)",
 "Lands on your **arrival weekend** (you land Oct 31). Zero planning required — walk out of Dongdaemun History & Culture Park Station into it."),

("🦒","2026 Seoul Grand Park Autumn Festival (서울대공원 가을축제)","⏳ TBA (scheduled autumn 2026)",
 "Autumn festival at Seoul Grand Park — the city's big zoo/botanical/forest complex south of the river",
 "Park **09:00–18:00** (last entry 17:00 in November)",
 "Zoo adult **₩5,000**; Sky Lift extra",
 "[grandpark.seoul.go.kr](https://grandpark.seoul.go.kr) · [Seoul 2026 event schedule](https://english.seoul.go.kr)",
 "Line 4 Seoul Grand Park Station. Dates listed as 'scheduled' on the city calendar — confirm in October."),

("📊","Seoul Data Analysis Best Practice Competition Finals","✅ CONFIRMED — Nov 20, 2026",
 "Public finals of the city's open-data analysis competition, using Seoul's own open-data portal",
 "Single day, daytime",
 "**FREE**",
 "[Seoul Metropolitan Government 2026 event schedule](https://english.seoul.go.kr) · [data.seoul.go.kr](https://data.seoul.go.kr)",
 "Niche, but a genuinely open public event — and Seoul's open-data portal is the source behind half the city apps you'll use."),

# ---------- Major museums & galleries (always on) ----------
("🖼️","Leeum Museum of Art (리움미술관)","🔁 Tue–Sun",
 "Korea's most important private art museum — Samsung's collection of national-treasure Korean antiquities plus world-class contemporary art, in buildings by Mario Botta, Jean Nouvel and Rem Koolhaas",
 "Tue–Sun **10:00–18:00** (closed Mondays & Jan 1, Lunar New Year, Chuseok)",
 "Permanent collection **FREE**; special exhibitions ticketed (typically ₩10,000–₩20,000)",
 "[leeumhoam.org](https://www.leeumhoam.org)",
 "Line 6 Hangangjin Station Exit 1, 5-min uphill walk. Reserve online — free tickets still need a timed slot. The celadon and Joseon painting rooms alone justify the trip."),

("🎨","MMCA Seoul (국립현대미술관 서울관)","🔁 Tue–Sun",
 "The National Museum of Modern and Contemporary Art's flagship Seoul branch, on the former Defense Security Command site next to Gyeongbokgung",
 "Tue–Sun **10:00–18:00**; **Wed & Sat until 21:00** (closed Mondays)",
 "**₩2,000–₩5,000** depending on exhibitions; **FREE Wed & Sat 18:00–21:00**",
 "[mmca.go.kr](https://www.mmca.go.kr)",
 "Line 3 Anguk Station Exit 1. The Wednesday/Saturday free night is one of the best-value evenings in Seoul — go at 18:00 and have the galleries half-empty."),

("💄","Amorepacific Museum of Art — APMA (아모레퍼시픽미술관)","🔁 Tue–Sun",
 "Corporate art museum in David Chipperfield's Amorepacific headquarters, alternating major international contemporary shows with Korean antiquities",
 "Tue–Sun **10:00–18:00** (last entry 17:30; closed Mondays)",
 "Varies by exhibition, typically **₩10,000–₩15,000**",
 "[apma.amorepacific.com](https://apma.amorepacific.com)",
 "Line 4/Gyeongui-Jungang Sinyongsan Station. The building's cube-with-a-void design is worth the visit by itself; the ground-floor atrium is free."),

("🕊️","Whanki Museum (환기미술관)","🔁 Tue–Sun",
 "Museum dedicated to Kim Whanki, the father of Korean abstract painting, in a quiet Buam-dong valley below Bugaksan",
 "Tue–Sun **10:00–18:00** (closed Mondays)",
 "Adult **₩12,000**; student ₩7,000",
 "[whankimuseum.org](https://www.whankimuseum.org)",
 "Bus 1020/7022/7212 from Gyeongbokgung Station to Buam-dong. Combine with the Bugaksan city-wall trail and a Buam-dong cafe — one of Seoul's best half-days."),

("🪑","Korea Furniture Museum (한국가구박물관)","🔁 by reservation, Mon–Sat",
 "Ten relocated hanok buildings holding 2,500 pieces of Joseon furniture on a hillside above Seongbuk-dong — visited by reservation-only guided tour",
 "Mon–Sat guided tours, roughly **11:00–17:00** (reservation required, no walk-ins)",
 "Adult **₩20,000**",
 "[kofum.com](http://www.kofum.com)",
 "Book weeks ahead. Widely regarded as the most beautiful museum in Seoul; hosted the 2010 G20 first-ladies dinner and a Brad Pitt press event."),

("🏛️","SOMA — Seoul Olympic Museum of Art (소마미술관)","🔁 Tue–Sun",
 "Contemporary art museum inside Olympic Park, with a world-class outdoor sculpture park of 200+ works around it",
 "Tue–Sun **10:00–18:00** (closed Mondays)",
 "Typically **₩3,000–₩5,000**; the outdoor sculpture park is **FREE**",
 "[somamuseum.org](https://www.somamuseum.org)",
 "Line 5/8/9 Olympic Park. Even if the galleries don't tempt you, the sculpture park in autumn foliage is one of Seoul's great free walks."),

("🌌","Space K Seoul (스페이스K 서울)","🔁 Tue–Sun (FREE)",
 "Kolon's contemporary art space in Magok, a curved concrete gallery wrapped by a public park — consistently strong solo shows, always free",
 "Tue–Sun **10:00–18:00** (closed Mondays)",
 "**FREE**",
 "[spacek.co.kr](https://www.spacek.co.kr)",
 "Line 5 Magongnaru / Line 9 Yangcheon Hyanggyo. Pair with Seoul Botanic Park, 10 minutes away."),

("💋","Coreana Cosmetics Museum — Space*C (스페이스씨 코리아나 화장박물관)","🔁 Tue–Sat",
 "Museum of Korean cosmetics history — Joseon-era makeup boxes, mirrors, hairpins and toiletries — above a contemporary art space in Gangnam",
 "Tue–Sat **10:00–19:00** (closed Sun & Mon)",
 "Adult **₩4,000**",
 "[coreanamuseum.org](https://www.coreanamuseum.org)",
 "Line 7 Hak-dong Station. A genuinely unusual angle on K-beauty: what Korean women actually used 400 years ago."),

("👜","Simone Handbag Museum (시몬느핸드백박물관)","🔁 Tue–Sun",
 "The world's only handbag museum, in a building shaped like a bag on Garosu-gil — 400 years of European and American bags",
 "Tue–Sun **11:00–19:00** (closed Mondays)",
 "Adult **₩5,000**",
 "[simonehandbagmuseum.co.kr](https://www.simonehandbagmuseum.co.kr)",
 "Line 3 Sinsa Station Exit 8, in the middle of Garosu-gil — an easy stop between cafes."),

("🔤","National Hangeul Museum (국립한글박물관)","🔁 Tue–Sun (FREE)",
 "National museum of the Korean alphabet — how Hangeul was invented in 1443, suppressed, revived and turned into a design language",
 "Tue–Sun **10:00–18:00**; **Wed & Sat until 21:00** (closed Mondays)",
 "**FREE**",
 "[hangeul.go.kr](https://www.hangeul.go.kr)",
 "Line 4/Gyeongui-Jungang Ichon Station Exit 2, next door to the National Museum of Korea. The hands-on Hangeul Playground makes the writing system click in about 20 minutes."),

("🧠","Seodaemun Museum of Natural History (서대문자연사박물관)","🔁 Tue–Sun",
 "Seoul's municipal natural history museum — dinosaur hall, Korean geology, ecology dioramas; the best value family museum in the city",
 "Tue–Sun **09:00–18:00** (closed Mondays)",
 "Adult **₩6,000**; youth ₩3,000; child ₩2,000",
 "[namu.sdm.go.kr](https://namu.sdm.go.kr)",
 "Line 3 Hongje Station + short bus. Small enough to do in 90 minutes, cheap enough to be a rainy-day default."),

("🚇","Seoul Metro Railway Museum (서울교통공사 철도박물관)","🔁 weekdays (FREE)",
 "Museum of the Seoul subway — original rolling stock, signalling gear, a driving simulator and the story of the 1974 Line 1 opening",
 "Weekdays, roughly **09:00–18:00** (closed weekends & holidays)",
 "**FREE**",
 "[seoulmetro.co.kr](http://www.seoulmetro.co.kr)",
 "For anyone who has spent a week riding the world's best metro and wondered how it got built. Confirm opening days before going."),

("✈️","National Aviation Museum of Korea (국립항공박물관)","🔁 Tue–Sun",
 "National museum of Korean aviation at Gimpo Airport — real aircraft, a flight simulator, cabin-crew experience and the history of Korean flight from 1920",
 "Tue–Sun **10:00–18:00** (last entry 17:00; closed Mondays)",
 "Adult **₩3,000**; youth ₩2,000; child ₩1,000",
 "[aviation.museum.go.kr](https://aviation.museum.go.kr)",
 "Line 5/9/AREX Gimpo Int'l Airport Station Exit 3. Perfect if you have a slow morning before a domestic flight."),

("💡","Seoul Energy Dream Center (서울에너지드림센터)","🔁 Tue–Sun (FREE)",
 "Korea's first zero-energy public building, in World Cup Park — an exhibition on renewables and climate, plus a rooftop view over Haneul Park",
 "Tue–Sun **09:00–18:00** (closed Mondays)",
 "**FREE**",
 "[seoulenergydream.or.kr](https://www.seoulenergydream.or.kr)",
 "Line 6 World Cup Stadium Station. A 30-minute stop that pairs perfectly with the Haneul Park silver-grass fields above it."),

("💧","Ttukdo Arisu Waterworks Museum (뚝도아리수정수센터 수도박물관)","🔁 Tue–Sun (FREE)",
 "Korea's first modern water-purification plant (1908), now a museum — the original red-brick pump house is a registered cultural property",
 "Tue–Sun **10:00–19:00** (Nov–Feb until 18:00; closed Mondays)",
 "**FREE**",
 "[arisu.seoul.go.kr](https://arisu.seoul.go.kr)",
 "Line 2 Ttukseom Station. Quiet, free, architecturally lovely, and almost never visited by tourists."),

("🏘️","Donuimun Museum Village (돈의문박물관마을)","🔁 Tue–Sun (FREE)",
 "A whole preserved block of 1960s–80s Seoul turned into a free open-air museum — old barbershops, comic-book rooms, a theatre, a photo studio",
 "Tue–Sun **10:00–19:00** (closed Mondays)",
 "**FREE**",
 "[donuimun.seoul.go.kr](https://donuimun.seoul.go.kr)",
 "Line 5 Seodaemun Station Exit 4. The retro classroom and the 1970s arcade are free to play in — one of the most charming free hours in Seoul."),

("🏺","Gahoe Museum (가회민화박물관)","🔁 Tue–Sun",
 "Small Bukchon hanok museum of *minhwa* (Korean folk painting), amulets and shamanic art, with a paint-your-own-minhwa workshop",
 "Tue–Sun **10:00–18:00** (closed Mondays)",
 "Adult **₩5,000**; workshops extra",
 "[gahoemuseum.org](http://www.gahoemuseum.org)",
 "Line 3 Anguk Station. Tiger-and-magpie folk paintings are the most cheerful art in Korea, and the workshop souvenir beats anything in Insadong."),

("🏯","Bukchon Traditional Culture Center (북촌문화센터)","🔁 daily (FREE)",
 "Free hanok culture centre in a restored Joseon official's house in Bukchon — exhibitions, tea, and drop-in traditional craft classes",
 "Daily **09:00–18:00** (Sun from 10:00)",
 "**FREE** (some classes ₩5,000–₩20,000)",
 "[hanokjinheung.or.kr](https://hanok.seoul.go.kr)",
 "Line 3 Anguk Station Exit 2. The correct first stop in Bukchon: get the map, use the toilet, sit in the courtyard, *then* walk the alleys."),

# ---------- Palaces, shrines, heritage ----------
("👘","Unhyeongung Royal Residence (운현궁)","🔁 Tue–Sun (FREE)",
 "The residence where King Gojong grew up and where the regent Daewongun ruled — a complete, uncrowded Joseon noble compound in the middle of Insadong",
 "Tue–Sun **09:00–18:00** (Nov–Mar until 17:00; closed Mondays)",
 "**FREE**",
 "[unhyeongung.or.kr](http://www.unhyeongung.or.kr)",
 "Line 3 Anguk Station Exit 4, 1 minute. Free, empty and beautiful — the palace to visit when Gyeongbokgung is a wall of hanbok selfies."),

("📜","Munmyo Shrine & Sungkyunkwan (문묘 & 성균관)","🔁 daily (FREE)",
 "The Confucian shrine and national academy of Joseon Korea, founded 1398 — still standing on the Sungkyunkwan University campus, with 500-year-old ginkgo trees",
 "Daily **09:00–18:00**",
 "**FREE**",
 "[Korea Heritage Service](https://www.khs.go.kr)",
 "Line 4 Hyehwa Station Exit 4. The two great ginkgoes in the courtyard go blazing yellow in **early-to-mid November** — one of the best foliage spots in central Seoul."),

("⛩️","Seonjeongneung Royal Tombs (선정릉) — UNESCO","🔁 Tue–Sun",
 "UNESCO-listed Joseon royal tombs of King Seongjong and King Jungjong — huge grass burial mounds and a pine forest, surrounded by Gangnam skyscrapers",
 "Tue–Sun **06:00–21:00** (Nov: **06:00–18:00**, last entry 17:00; closed Mondays)",
 "Adult **₩1,000**",
 "[royaltombs.khs.go.kr](https://royal.khs.go.kr)",
 "Line 9/Bundang Seonjeongneung Station Exit 3. ₩1,000 for a 400-year-old forest in the middle of Gangnam is the best-value ticket in Seoul."),

("⛩️","Heonilleung Royal Tombs (헌인릉) — UNESCO","🔁 Tue–Sun",
 "UNESCO Joseon royal tombs of King Taejong (the third Joseon king) and King Sunjo, with an ecological reserve attached",
 "Tue–Sun **09:00–18:00** (Nov: last entry 17:00; closed Mondays)",
 "Adult **₩1,000**",
 "[royal.khs.go.kr](https://royal.khs.go.kr)",
 "Bundang Line Daemosan Station + bus. The quietest of the Seoul royal tombs — you will often be the only person there."),

("⛩️","Taereung & Gangneung Royal Tombs (태릉·강릉) — UNESCO","🔁 Tue–Sun",
 "UNESCO tombs of Queen Munjeong and King Myeongjong in a dense forest in Nowon-gu, with the Joseon Royal Tomb Museum on site",
 "Tue–Sun **09:00–18:00** (Nov: last entry 17:00; closed Mondays)",
 "Adult **₩1,000**",
 "[royal.khs.go.kr](https://royal.khs.go.kr)",
 "Line 6 Hwarangdae Station. The on-site museum explains the whole 40-tomb UNESCO system in one room — visit here first if you plan to see several."),

("🕯️","Jeoldusan Martyrs' Shrine (절두산 순교성지)","🔁 Tue–Sun (FREE)",
 "Riverside shrine and museum on the cliff where hundreds of Korean Catholics were beheaded in 1866 — a major pilgrimage site visited by Pope Francis",
 "Tue–Sun **09:30–17:00** (closed Mondays)",
 "**FREE**",
 "[jeoldusan.or.kr](http://www.jeoldusan.or.kr)",
 "Line 2/6 Hapjeong Station Exit 7. Sombre, beautifully sited above the Han, and five minutes from the Hongdae cafe crowds."),

("🌿","Yanghwajin Foreign Missionary Cemetery (양화진외국인선교사묘원)","🔁 Tue–Sun (FREE)",
 "Riverside cemetery of the Western missionaries, doctors and journalists who shaped modern Korea — including Homer Hulbert, who asked to be buried here",
 "Tue–Sun **10:00–17:00** (closed Mondays)",
 "**FREE**",
 "[yanghwajin.net](http://www.yanghwajin.net)",
 "Next to Jeoldusan, Hapjeong Station. A remarkably peaceful 30 minutes with a lot of Korean history in the headstones."),

("⛪","Seoul Anglican Cathedral (대한성공회 서울주교좌성당)","🔁 daily (FREE)",
 "Romanesque cathedral of 1926 beside Deoksugung — arguably the most beautiful church interior in Seoul, with Byzantine-style mosaics",
 "Daily, roughly **10:00–17:00** outside services",
 "**FREE**",
 "[cathedral.or.kr](http://www.cathedral.or.kr)",
 "Line 1/2 City Hall Station Exit 3. Hidden behind the Deoksugung wall — walk in, most people never notice it exists."),

("🔔","Bosingak Belfry (보신각)","🔁 daily (FREE)",
 "The great bell pavilion at the centre of old Seoul, where the city gates' opening and closing were rung; ceremonial bell-strikings are held on set dates",
 "Pavilion viewable **24 h**; ceremonial strikes at scheduled times",
 "**FREE**",
 "[jongno.go.kr](https://www.jongno.go.kr)",
 "Line 1 Jonggak Station Exit 4, literally at the exit. Two-minute stop on any Jongno walk."),

("🌳","Tapgol Park (탑골공원)","🔁 daily (FREE)",
 "Korea's first modern public park (1897), site of the March 1st 1919 independence declaration, built around the 15th-century Wongaksa Pagoda (National Treasure No. 2)",
 "Daily **09:00–18:00**",
 "**FREE**",
 "[jongno.go.kr](https://www.jongno.go.kr)",
 "Line 1/3/5 Jongno 3-ga Station Exit 1, at the top of Insadong. The pagoda is under a glass shelter; the independence-movement reliefs on the walls are the reason to stop."),

("🇰🇷","Ahn Jung-geun Memorial Hall (안중근의사기념관)","🔁 Tue–Sun (FREE)",
 "Memorial museum on Namsan to the independence activist who assassinated Itō Hirobumi in 1909 — 12 concrete columns for the 12 who swore the oath",
 "Tue–Sun **10:00–18:00** (Nov–Mar until 17:00; closed Mondays)",
 "**FREE**",
 "[ahnjunggeun.or.kr](https://patriot.mpva.go.kr)",
 "On the Namsan slope near the cable car station. Free, quick, and it reframes the whole Namsan walk."),

("🇰🇷","Baekbeom Kim Koo Memorial Hall (백범김구기념관)","🔁 Tue–Sun (FREE)",
 "Museum to Kim Koo, leader of the Korean Provisional Government and the country's most revered independence figure, next to Hyochang Park",
 "Tue–Sun **10:00–18:00** (closed Mondays)",
 "**FREE**",
 "[kimkoomuseum.org](https://www.kimkoomuseum.org)",
 "Line 6 Hyochang Park Station or Line 1 Namyeong. Pairs with Hyochang Park, where three independence martyrs are buried."),

("🏵️","Seoul National Cemetery (국립서울현충원)","🔁 daily (FREE)",
 "The national cemetery on the Han's south bank — 54,000 war dead, presidents' graves, and one of Seoul's best (and least-known) autumn foliage walks",
 "Daily **06:00–18:00**",
 "**FREE**",
 "[snmb.mil.kr](https://www.snmb.mil.kr)",
 "Line 4/9 Dongjak Station Exit 2/4, directly at the gate. Enormous, silent, and in mid-November the maple avenue is spectacular."),

# ---------- Temples ----------
("🧘","Gilsangsa Temple (길상사)","🔁 daily (FREE)",
 "A former high-end restaurant donated to become a temple in 1997 — wooden pavilions scattered up a wooded Seongbuk-dong hillside, famous for autumn colour",
 "Daily **04:00–20:00**; templestay by booking",
 "**FREE**",
 "[gilsangsa.or.kr](http://www.gilsangsa.or.kr)",
 "Bus from Line 4 Hansung Univ. Station. Mid-November foliage here is among the best in Seoul, and there's a free tea house."),

("🧘","Bongwonsa Temple (봉원사)","🔁 daily (FREE)",
 "Head temple of the Taego Order, founded 889, on the slope of Ansan — home of Yeongsanjae, a UNESCO Intangible Cultural Heritage ritual",
 "Daily, roughly **05:00–19:00**",
 "**FREE**",
 "[bongwonsa.or.kr](http://www.bongwonsa.or.kr)",
 "Behind Yonsei University, Line 2 Sinchon Station + 15-min walk. Combine with the Ansan metasequoia skywalk directly above it."),

("🧘","Heunginjimun Gate — Dongdaemun (흥인지문)","🔁 daily (FREE)",
 "The Great East Gate of Seoul, Treasure No. 1 — the only city gate with a semicircular *ongseong* barbican wall still attached",
 "Exterior viewable **24 h**; surrounding park always open",
 "**FREE**",
 "[Korea Heritage Service](https://www.khs.go.kr) · [seoulcitywall.seoul.go.kr](https://seoulcitywall.seoul.go.kr)",
 "Line 1/4 Dongdaemun Station Exit 6/7. Lit at night and beautiful; the city-wall trail up Naksan starts right behind it."),

# ---------- Markets & food streets ----------
("🌿","Seoul Yangnyeongsi Herbal Medicine Market & Museum (서울약령시 & 한의약박물관)","🔁 Tue–Sun",
 "Korea's largest traditional-medicine market — 1,000 shops of roots, mushrooms and dried everything, plus a free museum with a foot-bath and pulse-reading",
 "Market roughly **09:00–18:00** (many shops closed Sun); museum Tue–Sun **10:00–17:00**",
 "Market **FREE**; museum **FREE**",
 "[Dongdaemun-gu official](https://www.ddm.go.kr) · [english.visitseoul.net](https://english.visitseoul.net)",
 "Line 1 Jegi-dong Station Exit 2. The smell alone is worth the trip. The museum's free foot bath is a genuinely nice mid-walk reset."),

("🥬","Kyungdong Market (경동시장)","🔁 daily",
 "Vast 1960s produce and medicinal market next to Yangnyeongsi — and home of the Starbucks built inside a derelict 1960s cinema, one of Seoul's best-loved conversions",
 "Roughly **08:00–19:00** (many stalls closed 1st & 3rd Sunday)",
 "**FREE** to browse",
 "[english.visitseoul.net](https://english.visitseoul.net)",
 "Line 1 Jegi-dong Station. Go up to the old theatre Starbucks on the top floor — the auditorium seating is intact."),

("🧂","Jungbu Dried Seafood Market (중부시장)","🔁 Mon–Sat",
 "Korea's biggest dried-seafood wholesale market — walls of dried anchovies, squid, pollack and gim, in narrow arcades near Euljiro",
 "Mon–Sat roughly **04:00–18:00** (closed Sundays)",
 "**FREE** to browse",
 "[english.visitseoul.net](https://english.visitseoul.net)",
 "Line 2/3 Euljiro 3-ga or Line 4 Euljiro 4-ga. Dried seafood is one of the best light, cheap, legal-to-fly-home souvenirs from Korea."),

("🎀","Bangsan Market (방산시장)","🔁 Mon–Sat",
 "The craft and packaging market — baking supplies, wrapping paper, ribbon, wallpaper, candle and soap materials, all wholesale-cheap",
 "Mon–Sat roughly **09:00–18:00** (closed Sundays)",
 "**FREE** to browse",
 "[english.visitseoul.net](https://english.visitseoul.net)",
 "Line 2/5 Euljiro 4-ga Station Exit 5. Next to Gwangjang Market — do lunch there, shop here."),

("🕰️","Seoul Folk Flea Market (서울풍물시장)","🔁 Tue–Sun (FREE)",
 "The city-run relocation of the old Hwanghak-dong flea market — 800 stalls of antiques, vinyl, military surplus, vintage cameras and pure junk",
 "Tue–Sun **10:00–19:00** (closed 2nd & 4th Tuesday)",
 "**FREE** to browse",
 "[pungmul.seoul.go.kr](https://pungmul.seoul.go.kr)",
 "Line 1/2 Sinseol-dong Station Exit 6. The 2nd-floor vintage section is the good bit. Cash helps."),

("👴","Dongmyo Flea Market (동묘 벼룩시장)","🔁 daily",
 "Sprawling open-air second-hand market around the Dongmyo shrine — mountains of ₩1,000 clothing, the source of Korea's 'Dongmyo look' vintage trend",
 "Daily, busiest **10:00–17:00**; biggest on weekends",
 "**FREE** to browse",
 "[english.visitseoul.net](https://english.visitseoul.net)",
 "Line 1/6 Dongmyo Station Exit 3. Chaotic and brilliant. Bring cash in small notes; haggling is expected."),

("🥩","Majang Meat Market (마장축산물시장)","🔁 Mon–Sat",
 "Korea's largest meat market — buy hanwoo beef or pork downstairs at wholesale prices, then pay a small fee for a nearby restaurant to grill it for you",
 "Mon–Sat roughly **08:00–19:00** (closed Sundays)",
 "Meat at wholesale prices; grilling/table charge typically **₩4,000–₩6,000** per person",
 "[english.visitseoul.net](https://english.visitseoul.net)",
 "Line 5 Majang Station Exit 2. This is how Koreans eat hanwoo without paying restaurant markup — the single best beef value in Seoul."),

("🐟","Garak Market Night Auction (가락시장 경매)","🔁 nightly (FREE)",
 "The overnight wholesale auctions at Korea's biggest agricultural and fisheries market — vegetables, fruit and seafood auctioned from around midnight",
 "Auctions roughly **23:00–05:00**; market itself near-24 h",
 "**FREE** to observe",
 "[garak.co.kr](https://www.garak.co.kr)",
 "Line 3/8 Garak Market Station. A genuinely different Seoul at 1 a.m. Stay out of the forklift lanes."),

# ---------- Neighbourhoods & streets ----------
("🏘️","Bukchon Hanok Village Eight Scenic Views Trail (북촌 8경)","🔁 daily (FREE)",
 "The officially numbered eight viewpoints through Bukchon's hanok alleys between Gyeongbokgung and Changdeokgung — the classic Seoul rooftop-tile photograph",
 "Alleys open daily; **residential quiet hours apply — Bukchon-ro 11-gil closes to visitors after 17:00**",
 "**FREE**",
 "[english.visitseoul.net](https://english.visitseoul.net) · [Jongno-gu](https://www.jongno.go.kr)",
 "Line 3 Anguk Station Exit 2. People live here — signage asks for silence, and the main alley is closed to tourists in the evening. Go early morning for empty streets."),

("🌳","Garosu-gil (가로수길), Sinsa","🔁 daily (FREE)",
 "The ginkgo-lined boutique street in Sinsa-dong that launched Seoul's cafe-street format — flagship stores, concept shops and the back-alley 'Serosu-gil'",
 "Shops roughly **11:00–21:00**",
 "**FREE** to walk",
 "[english.visitseoul.net](https://english.visitseoul.net) · [Gangnam-gu](https://www.gangnam.go.kr)",
 "Line 3 Sinsa Station Exit 8. The name means 'tree-lined street' — and in **early-to-mid November** the ginkgoes turn the whole street gold."),

("👟","Seongsu Handmade Shoe Street (성수동 수제화거리)","🔁 Mon–Sat (FREE)",
 "Seoul's shoemaking district since the 1990s — 100+ workshops that supply Korean department stores, with a public showroom and made-to-order service",
 "Workshops Mon–Sat roughly **10:00–18:00**",
 "**FREE** to browse; bespoke shoes from ~₩150,000",
 "[english.visitseoul.net](https://english.visitseoul.net) · [Seongdong-gu](https://www.sd.go.kr)",
 "Line 2 Seongsu Station Exit 1 — the station itself has a shoe-themed platform. Combine with the Seongsu cafe warehouses."),

("🏭","Seongsu-dong Red-Brick Cafe Warehouses (성수동 카페거리)","🔁 daily",
 "Seoul's Brooklyn — 1970s shoe factories and print works converted into vast concrete-and-brick cafes, concept stores and pop-ups",
 "Most cafes **11:00–22:00**",
 "Coffee **₩5,000–₩9,000**",
 "[english.visitseoul.net](https://english.visitseoul.net)",
 "Line 2 Seongsu Station. The pop-up density here is the highest in Korea — whatever brand is launching that month is doing it in Seongsu."),

("🍶","Euljiro Print Alley & Rooftop Bars (을지로 인쇄골목)","🔁 Mon–Sat evenings",
 "Working print and metal workshops by day, hidden bars behind unmarked doors by night — the 'Hipjiro' phenomenon in its original form",
 "Workshops Mon–Sat daytime; bars from ~**18:00** (many closed Sunday)",
 "Drinks **₩6,000–₩12,000**",
 "[english.visitseoul.net](https://english.visitseoul.net)",
 "Line 2/3 Euljiro 3-ga. Half the good bars have no sign — look for a lit stairwell in an old building and go up."),

("🛖","Seochon Tongin & Hanok Alley Night Walk (서촌 야간산책)","🔁 daily (FREE)",
 "The lanes west of Gyeongbokgung after dark — low hanok roofs, the palace wall, small bars and Inwangsan looming behind",
 "Always open; best **18:00–22:00**",
 "**FREE**",
 "[english.visitseoul.net](https://english.visitseoul.net)",
 "Line 3 Gyeongbokgung Station Exit 2. Quieter and more residential than Bukchon, with better bars and no tour groups."),

("🎪","Ikseon-dong Night Alley Lanterns (익선동 야간)","🔁 daily (FREE)",
 "Seoul's 1920s hanok district after sunset, when the alleys light up — the highest concentration of hanok bars and dessert cafes in the city",
 "Most venues **12:00–23:00**",
 "**FREE** to walk",
 "[english.visitseoul.net](https://english.visitseoul.net)",
 "Line 1/3/5 Jongno 3-ga Station Exit 4. Alleys are barely two people wide — go on a weeknight if you can."),

("🌉","Nodeul Island (노들섬)","🔁 daily (FREE)",
 "The city-run culture island in the middle of the Han under Hangang Bridge — live music venue, bookshop, restaurants and a riverside deck facing the skyline",
 "Outdoor areas **24 h**; venues roughly **11:00–22:00**",
 "**FREE** entry; concerts ticketed",
 "[nodeul.org](https://nodeul.org)",
 "Line 9 Noryangjin Station + walk, or bus across Hangang Bridge. The sunset view back toward Yongsan is one of the best free views in Seoul."),

("🌊","Han River Bus (한강버스) Riverside Terminals","🔁 daily",
 "Seoul's Han River public ferry service — a commuter boat that doubles as the cheapest river cruise in the city, linking riverside terminals across Seoul",
 "Daily services, roughly **06:30–22:30** depending on terminal",
 "Single ride from **₩3,000**; transit-card compatible",
 "[hangang.seoul.go.kr](https://hangang.seoul.go.kr)",
 "Check the live schedule before travelling — services and terminals are still being phased in. Far cheaper than a tourist cruise for the same water."),

# ---------- Performance & entertainment venues ----------
("🎭","LG Arts Center Seoul (LG아트센터 서울)","🔁 by performance",
 "Tadao Ando's concrete arts centre in Magok — a 1,300-seat theatre and a black box, with Seoul's most adventurous international programming",
 "Box office daily; performances typically **19:30** weekdays, **15:00/18:00** weekends",
 "**₩30,000–₩120,000** depending on production",
 "[lgart.com](https://www.lgart.com)",
 "Line 5 Magongnaru Station, directly connected. The building — a 'tube' cut through Ando's concrete — is worth seeing even without a ticket."),

("🥁","Seoul Namsan Gugakdang (서울남산국악당)","🔁 by performance",
 "Purpose-built traditional-music hall sunk into the ground at Namsangol Hanok Village, so the hanok skyline stays intact — pansori, sanjo and gugak",
 "Performances typically **19:30** (Tue–Sat), matinees on weekends",
 "**₩20,000–₩40,000**; some free programmes",
 "[hanokmaeul.or.kr](https://www.hanokmaeul.or.kr)",
 "Line 3/4 Chungmuro Station Exit 3/4. The best acoustic setting in Seoul for traditional music, and small enough that every seat is good."),

("🏠","Korea House (한국의집)","🔁 daily",
 "Government-run cultural complex in a replica of a Joseon minister's house — a nightly traditional performance plus royal-court cuisine dinners",
 "Performances typically **19:00 & 20:20**; restaurant lunch & dinner sittings",
 "Performance from **₩50,000**; set dinners **₩70,000+**",
 "[koreahouse.or.kr](https://www.koreahouse.or.kr)",
 "Line 3/4 Chungmuro Station Exit 3. Run by the Korea Cultural Heritage Foundation — the most 'official' version of a traditional dinner-and-show."),

("🏟️","Gocheok Sky Dome (고척스카이돔)","🔁 by event",
 "Korea's only domed stadium — home of the Kiwoom Heroes and, out of baseball season, the country's premier indoor concert venue for 16,000 people",
 "By event; doors typically 1–2 h before start",
 "Concert tickets vary widely",
 "[Kiwoom Heroes](https://www.heroesbaseball.co.kr) · [Interpark Global](https://global.interpark.com)",
 "Line 1 Guil Station Exit 3, 5-min walk. In **November the KBO season is over**, so anything here is a concert — check Interpark Global in October."),

("🏟️","KSPO Dome & Olympic Gymnastics Arena (올림픽체조경기장)","🔁 by event",
 "The 1988 Olympic gymnastics venue, now Korea's main 15,000-seat concert arena — where most major K-pop Seoul concerts and year-end award shows happen",
 "By event; doors typically 1–2 h before start",
 "Concert tickets typically **₩99,000–₩198,000**",
 "[kspo.or.kr](https://www.kspo.or.kr) · [Interpark Global](https://global.interpark.com)",
 "Line 5 Olympic Park Station Exit 3, or Line 9 Hanseong Baekje. **November–December is award-show and comeback-concert season** — watch Interpark Global from October."),

("🎤","Yes24 Live Hall & Seoul Live Music Clubs (예스24 라이브홀)","🔁 by event",
 "Seoul's main mid-size live-music venue in Gwangjang-dong, plus the Hongdae club circuit (Rolling Hall, Sangsangmadang, FF) for indie gigs most weekends",
 "Gigs typically **19:00–20:00** start; clubs later",
 "**₩30,000–₩80,000** typical",
 "[Interpark Global](https://global.interpark.com) · [Sangsangmadang](https://www.sangsangmadang.com)",
 "Korean indie is excellent and almost never sold out. Hongdae clubs sell tickets at the door on the night."),

("🎬","Korean Film Archive & Cinematheque KOFA (한국영상자료원)","🔁 Tue–Sun (FREE)",
 "The national film archive at Sangam DMC — free daily screenings of restored Korean classics with English subtitles, plus a film museum",
 "Tue–Sun **10:00–19:00**; screenings throughout the day (closed Mondays)",
 "Screenings and museum **FREE**",
 "[koreafilm.or.kr](https://www.koreafilm.or.kr)",
 "Line 6/AREX Digital Media City Station Exit 9. Free subtitled screenings of Korean cinema history — an unbeatable rainy afternoon."),

("🎞️","Seoul Cinema Streets — Daehangno & Chungmuro Art Houses","🔁 daily",
 "Korea's independent cinema circuit — Indiespace, Emu Cinema, Arthouse Momo and the Chungmuro film district that gave Korean cinema its name",
 "Screenings roughly **11:00–22:00**",
 "Tickets **₩8,000–₩12,000**",
 "[Korean Film Council (KOFIC)](https://www.kofic.or.kr) · [indiespace.kr](https://indiespace.kr)",
 "Most art houses show at least one film a day with English subtitles — check listings the day before."),

# ---------- Parks, nature, viewpoints ----------
("🎠","Seoul Children's Grand Park (서울어린이대공원)","🔁 daily (FREE)",
 "Huge free park in Gwangjin-gu with a zoo, botanical garden, amusement rides and a music fountain — built in 1973 on a former royal golf course",
 "Park **05:00–22:00**; zoo **10:00–17:00**",
 "Park and zoo **FREE**; rides charged individually",
 "[childrenpark.seoul.go.kr](https://www.childrenpark.seoul.go.kr)",
 "Line 5/7 Children's Grand Park Station Exit 1. A free zoo inside Seoul city limits — hard to beat for a cheap family afternoon."),

("🌲","Hongneung Arboretum & Forest Science Museum (홍릉수목원)","🔁 weekends & Sun (FREE)",
 "Korea's first arboretum (1922), on the site of Empress Myeongseong's former tomb — 2,000 plant species and the National Forest Science Museum",
 "Open to the public **Saturdays & Sundays only**, roughly **10:00–17:00**",
 "**FREE**",
 "[nifos.forest.go.kr](https://nifos.forest.go.kr)",
 "Line 6 Korea University Station + bus. **Weekends only** — an unusual restriction that keeps it beautifully empty."),

("⛰️","Bulamsan Mountain Sunrise Ridge (불암산)","🔁 daily (FREE)",
 "The granite dome on Seoul's north-eastern edge (508 m) — a shorter, quieter alternative to Bukhansan with a superb sunrise view over the eastern city",
 "Always open; **sunrise in Seoul in November is ~07:00–07:20**",
 "**FREE**",
 "[Seoul Metropolitan Government parks](https://parks.seoul.go.kr)",
 "Line 4/7 Nowon Station or Line 7 Junggye. Two to three hours round trip. Bring a headtorch for a pre-dawn start."),

("⛰️","Daemosan & Guryongsan Ridge Walk (대모산·구룡산)","🔁 daily (FREE)",
 "Gangnam's back-garden mountains — a gentle forested ridge between Suseo and Yangjae with city views and almost no tourists",
 "Always open; ~2–3 h for the traverse",
 "**FREE**",
 "[parks.seoul.go.kr](https://parks.seoul.go.kr)",
 "Line 3/Bundang Suseo Station Exit 6. Easy, well-signposted, and finishes at Yangjae Citizens' Forest for the foliage."),

("🌾","Gaehwasan Mountain & Gangseo Sunset Park (개화산)","🔁 daily (FREE)",
 "Low hill at Seoul's western edge overlooking the Han estuary and, on clear days, North Korean territory across the water",
 "Always open; sunset in November ~**17:20**",
 "**FREE**",
 "[parks.seoul.go.kr](https://parks.seoul.go.kr)",
 "Line 5 Gaehwasan Station Exit 1. Forty minutes up, and the estuary sunset is genuinely different from the usual Han River views."),

("🦆","Gangseo Marsh Ecological Park & Migratory Birds (강서습지생태공원)","🔁 daily (FREE)",
 "Protected Han River wetland at the Seoul–Gimpo boundary — **November is peak season for migratory geese, ducks and swans** arriving from Siberia",
 "Daily, roughly **sunrise–sunset**; observation hides open daytime",
 "**FREE**",
 "[parks.seoul.go.kr](https://parks.seoul.go.kr) · [hangang.seoul.go.kr](https://hangang.seoul.go.kr)",
 "Line 5 Banghwa Station + walk. Bring binoculars. Bird numbers peak from **mid-November** — good timing for the back half of your trip."),

("🦢","Bamseom Islet Migratory Bird Sanctuary (밤섬 철새보호구역)","🔁 daily (FREE, view only)",
 "A Ramsar-listed wetland island in the middle of the Han between Yeouido and Mapo — entry is banned, but the viewing decks fill with wintering birds in November",
 "Viewing decks always open",
 "**FREE**",
 "[hangang.seoul.go.kr](https://hangang.seoul.go.kr)",
 "Best viewed from Yeouido Hangang Park or the Mapo side. A Ramsar site inside a megacity of 10 million — genuinely unusual."),

("🌸","Seoul Rose Park & Jungnangcheon Trail (서울장미공원)","🔁 daily (FREE)",
 "A 5.15 km rose corridor along Jungnangcheon Stream — Korea's longest rose garden, and a flat, pleasant cycling and walking route year-round",
 "Always open",
 "**FREE**",
 "[jungnang.go.kr](https://www.jungnang.go.kr)",
 "Line 7 Jungnang or Meokgol Station. Roses are done by November, but the stream path is one of the best flat runs/rides in eastern Seoul."),

("🌉","Seoul Sky Garden — Seoullo 7017 (서울로 7017)","🔁 daily (FREE)",
 "A 1970s highway overpass turned into an elevated garden walkway with 24,000 plants, linking Seoul Station to Namdaemun and Namsan",
 "Always open; **lit at night**",
 "**FREE**",
 "[seoullo7017.seoul.go.kr](https://seoullo7017.seoul.go.kr)",
 "Directly above Seoul Station. Ten minutes end to end, best at dusk — and it drops you at Namdaemun Market."),

("🌇","Haneul Park Sunset & Seoul Silver Grass Fields at Dusk","🔁 daily (FREE)",
 "The former landfill turned sky-meadow above World Cup Park — in November the silver grass is fully out and the sunset over the Han is the best in western Seoul",
 "Nov hours roughly **06:00–18:30**; **291 steps** or a paid shuttle to the top",
 "Park **FREE**; shuttle **₩3,000** return",
 "[parks.seoul.go.kr](https://parks.seoul.go.kr)",
 "Line 6 World Cup Stadium Station Exit 1. The silver-grass festival is October, but **the grass is still spectacular through November with a fraction of the crowds**."),

# ---------- Experiences ----------
("👘","Hanbok Rental & Free Palace Entry (한복 대여)","🔁 daily",
 "Rent a hanbok near any of the four palaces and **all four palaces plus Jongmyo become free** — the single best-value tourist hack in Seoul",
 "Rental shops roughly **09:00–19:00**; typical rental 2–4 h or full day",
 "Rental **₩15,000–₩35,000** for 2–4 h; palace admission then **FREE** (normally ₩1,000–₩3,000 each)",
 "[Korea Heritage Service](https://www.khs.go.kr) · [english.visitseoul.net](https://english.visitseoul.net)",
 "Shops cluster at Anguk Station and around Gyeongbokgung. November is cold — most shops rent a *durumagi* overcoat for a few thousand won more. Take it."),

("🍲","Temple Food Cooking Class — Korean Temple Food Center","🔁 by booking",
 "The Jogye Order's official temple-food centre in Gyeonjinsa/Insadong — learn to cook Buddhist monastic cuisine (no garlic, no onion) with a monk",
 "Classes typically **10:00–13:00** or **14:00–17:00**, by advance booking",
 "Typically **₩50,000–₩90,000** per class",
 "[Korean Temple Food (Jogye Order)](https://eng.templestay.com) · [koreatemplefood.com](https://www.koreatemplefood.com)",
 "Line 3 Anguk Station. English sessions run regularly but book out — reserve a couple of weeks ahead."),

("🥋","Taekwondowon & Kukkiwon World Taekwondo HQ (국기원)","🔁 weekdays (FREE to watch)",
 "The world headquarters of Taekwondo in Gangnam — free public viewing of training and belt gradings in the main hall, plus demonstration performances",
 "Weekdays roughly **09:00–18:00**; demonstration schedule varies",
 "Viewing **FREE**",
 "[kukkiwon.or.kr](http://www.kukkiwon.or.kr)",
 "Line 2 Gangnam Station Exit 12, 10-min walk. Check the demonstration-team schedule — the show is genuinely impressive and free."),

("🎮","Seoul Esports Arena & LoL Park (롤파크)","🔁 by match",
 "Riot Games' purpose-built 400-seat LCK stadium in Jongno — plus the city-run Seoul Esports Arena in Guro. **The LCK is the world's top League of Legends league.**",
 "Match days typically **17:00** and **19:30** starts; check the season calendar",
 "Tickets typically **₩12,000–₩20,000**; often sold out in minutes",
 "[LCK official](https://lolesports.com/leagues/lck) · [Seoul Esports Arena](https://esports.seoul.kr)",
 "LoL Park is at Jonggak Station, inside the GS Tower basement. **The LCK regular season is usually on break in November** — check the calendar; the arena's free-to-enter cafe and merch store stay open."),

("🕹️","Retro Arcade Streets — Jongno & Hongdae (오락실)","🔁 daily",
 "Korea's surviving coin-op arcades: rhythm games, claw machines, four-player fighters and photo booths, concentrated around Jongno 3-ga and Hongdae",
 "Most open **10:00–02:00**",
 "**₩500–₩2,000** per play",
 "[english.visitseoul.net](https://english.visitseoul.net)",
 "Korean rhythm-game arcades (Pump It Up, DJMAX) are on another level. Bring ₩1,000 notes — the change machines take them."),

("📷","Korean Photo Booth Culture — Life4Cuts & Photoism (인생네컷)","🔁 daily",
 "The self-service photo-booth chains that took over Korea — pick a frame, four shots, printed in 30 seconds. Booths are everywhere in Hongdae, Myeongdong and Seongsu",
 "Most booths **24 h** or **10:00–24:00**",
 "**₩4,000–₩6,000** per strip",
 "[Life4Cuts](https://life4cut.co.kr) · [Photoism](https://photoism.co.kr)",
 "The single cheapest and most Korean souvenir you can bring home. Many booths have K-pop collab frames that change monthly."),

("🛁","Seoul Jjimjilbang Culture — 24-hour Bathhouses","🔁 24 h",
 "The Korean sauna complex: hot pools, dry kilns, ice rooms, sleeping halls and *sikhye* rice punch. Entry usually includes overnight stay",
 "Most open **24 h**",
 "Day entry **₩10,000–₩15,000**; overnight surcharge **₩3,000–₩5,000**",
 "[english.visitseoul.net](https://english.visitseoul.net)",
 "Bathing areas are gender-separated and **fully nude** — swimwear is not allowed. The shared jjimjilbang floor is clothed (they give you shorts and a tee). Tattoos are tolerated at most large chains but not all."),

("🚴","Ttareungi Seoul Public Bike Share (따릉이)","🔁 24 h",
 "Seoul's 43,000-bike public share scheme — pick up and drop at 2,700 docks, with the Han River cycle paths as the main attraction",
 "**24 h**",
 "**₩1,000** / 1 h · **₩2,000** / 2 h · 7-day pass ₩3,000",
 "[bikeseoul.com](https://www.bikeseoul.com)",
 "Foreign cards work on the English app. The Han River path runs uninterrupted for 40+ km — flat, separated from traffic, and free of hills."),

("🎫","Discover Seoul Pass (디스커버서울패스)","🔁 daily",
 "The official city tourist pass — free entry to 40+ attractions (palaces, N Seoul Tower, Lotte World, museums) plus transit credit, on a 24/48/72-hour clock",
 "Activates on first use; runs 24 / 48 / 72 continuous hours",
 "**₩50,000 / ₩70,000 / ₩90,000** (24 / 48 / 72 h)",
 "[discoverseoulpass.com](https://www.discoverseoulpass.com)",
 "Only worth it if you'll do 3+ paid attractions per day. Doubles as a T-money card, which is genuinely convenient."),

("🎧","Seoul Free Walking Tours — Gwanghwamun & Bukchon","🔁 daily (FREE)",
 "The city's volunteer-guided walking tours in English, Japanese and Chinese — 20+ fixed routes covering palaces, the city wall, markets and modern history",
 "Most tours **10:00** and **14:00**, 2–3 h",
 "**FREE** (book online)",
 "[english.visitseoul.net — Seoul Walking Tour](https://english.visitseoul.net)",
 "Guides are trained volunteers, not touts, and the tours are properly good. Book 3–5 days ahead in autumn."),

# ---------- Shopping & modern landmarks ----------
("🛍️","The Hyundai Seoul & Sounds Forest (더현대 서울)","🔁 daily",
 "Korea's most spectacular department store — a 1,000 m² indoor forest under a glass roof at Yeouido, plus the country's densest pop-up floor",
 "Daily **10:30–20:00** (Fri–Sun until 20:30)",
 "**FREE** entry",
 "[ehyundai.com](https://www.ehyundai.com)",
 "Line 5/9 Yeouido Station, directly connected. The 5th-floor Sounds Forest is free to sit in; the basement food hall is one of Seoul's best."),

("🗼","63 Square & 63 Art Observatory (63스퀘어)","🔁 daily",
 "The golden 1985 tower on Yeouido — Korea's tallest building for 18 years — with an art gallery observatory on the 60th floor and an aquarium below",
 "Daily **10:00–22:00** (last entry 21:30)",
 "Observatory adult **₩13,000**; combo tickets available",
 "[63realty.co.kr](https://www.63realty.co.kr)",
 "Line 5 Yeouinaru Station + 15-min walk or shuttle. Lower and cheaper than Seoul Sky, and the westward sunset view over the Han is arguably better."),

("🛒","Times Square & Yeongdeungpo Underground City","🔁 daily",
 "One of Korea's largest malls with a CGV Starium screen, plus the sprawling Yeongdeungpo underground shopping arcade next door",
 "Mall **10:30–22:00**; underground arcade **10:00–21:00**",
 "**FREE** entry",
 "[timessquare.co.kr](https://www.timessquare.co.kr)",
 "Line 1 Yeongdeungpo Station Exit 3. Practical rather than glamorous — good for cheap clothes and a warm indoor afternoon."),

("💻","Yongsan Electronics Market (용산전자상가)","🔁 Mon–Sat",
 "Korea's historic electronics district — components, retro consoles, PC parts and camera gear, now half-transformed into a startup campus",
 "Mon–Sat roughly **10:00–19:00** (many shops closed Sunday)",
 "**FREE** to browse",
 "[english.visitseoul.net](https://english.visitseoul.net)",
 "Line 1 Yongsan Station / Sinyongsan. Prices are negotiable and rarely marked. Come for retro gaming and camera lenses rather than new laptops."),

("🎮","Seoul Game Cafes & Board Game Cafes (보드게임 카페)","🔁 daily",
 "Korea's board-game cafe format — hundreds of games, a drink, and a per-hour rate; concentrated in Hongdae, Sinchon and Gangnam",
 "Most open **12:00–24:00** or later",
 "**₩5,000–₩8,000** per person per hour incl. a drink",
 "[english.visitseoul.net](https://english.visitseoul.net)",
 "Staff will teach you a game. A cheap, warm, sociable option on a cold November evening."),

("🍜","Seoul Convenience Store Culture & Ramyeon Bars","🔁 24 h",
 "CU, GS25 and 7-Eleven with in-store ramyeon machines, hot-bar snacks and seating — a genuine and very cheap Korean eating format",
 "**24 h**",
 "Ramyeon **₩1,500–₩2,500**; full meal under **₩7,000**",
 "[english.visitseoul.net](https://english.visitseoul.net)",
 "The Han River park branches let you eat instant ramyeon at a riverside table — a Seoul rite of passage that costs about ₩3,000."),

("🏬","Starfield Hanam & Goyang (스타필드)","🔁 daily",
 "Korea's giant suburban mall format — Starfield Hanam and Goyang have aquariums, sports domes, cinemas and the Aquafield spa under one roof",
 "Daily **10:00–22:00**",
 "**FREE** entry; Aquafield spa from **₩30,000**",
 "[starfield.co.kr](https://www.starfield.co.kr)",
 "Both are 40–60 min from central Seoul by bus or subway+bus. Best as a rainy-day full-day option with kids."),

("🌃","Seoul Night Bus Routes (서울 심야버스 'Owl Bus')","🔁 nightly",
 "The N-prefixed 'Owl Buses' that run **23:30–06:00** across nine city routes — how Seoul gets home after the subway closes at about midnight",
 "Nightly **23:30–06:00**, every 20–45 min",
 "**₩2,500** cash/card (higher than daytime fare)",
 "[Seoul Metropolitan Government transport](https://news.seoul.go.kr/traffic)",
 "The subway stops around 00:00–01:00. Save the N26 / N61 / N62 routes in your map app before a late night out — they're far cheaper than a taxi."),
]

def block(n, e):
    emoji, title, status, what, hours, price, src, notes = e
    return (
        f"### {n}) {emoji} {title} — {status}\n"
        f"- **What:** {what}\n"
        f"- **Hours:** {hours}\n"
        f"- **Price:** {price}\n"
        f"- **Official source:** {src}\n"
        f"- **Beginner notes:** {notes}\n"
    )

path = "/home/user/KoreaFun/seoul.md"
txt = io.open(path, encoding="utf-8").read()

marker = "\n---\n\n## ⏭️ Just outside your window"
assert marker in txt, "footer marker not found"

parts = []
parts.append("\n---\n\n## 🆕 More verified Seoul events & activities (expansion set)\n")
parts.append("\n*Added from the Seoul Metropolitan Government's official 2026 event schedule, COEX's official venue calendar, and the official sites of each venue. Same status legend: ✅ confirmed · ⏳ TBA · 👀 watch · 🔁 always on.*\n\n")
for i, e in enumerate(E):
    parts.append(block(START + i, e) + "\n")

new = txt.replace(marker, "".join(parts).rstrip("\n") + marker, 1)
io.open(path, "w", encoding="utf-8").write(new)
print("added", len(E), "entries -> #%d..#%d" % (START, START + len(E) - 1))
