# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "/home/user/KoreaFun/.build")
from addlib import append

E = [
("🏞️","Gwanggyo Museum & Suwon Convention Center (수원컨벤션센터)","🔁 by event",
 "Suwon's convention centre at Gwanggyo, hosting trade fairs and exhibitions, next to a department store and the lake park",
 "By event, typically **10:00–18:00**",
 "Varies by show; many **FREE**",
 "[suwoncc.or.kr](https://www.suwoncc.or.kr)",
 "Sinbundang Line Gwanggyo Jungang Station, connected. **Check the November 2026 exhibition calendar.**"),

("🛒","Motgol & Yeongdong Traditional Markets (못골시장·영동시장)","🔁 daily",
 "Two of the nine Paldalmun-area markets — Motgol known for its radio station and market band, Yeongdong for hanbok and fabric",
 "Roughly **09:00–20:00**",
 "**FREE** to browse",
 "[suwon.go.kr](https://www.suwon.go.kr)",
 "**Motgol Market runs its own broadcast station** from a booth in the aisle — a well-known regeneration story."),

("🥟","Suwon Market Street Food — sundae, hotteok, tteokgalbi","🔁 daily",
 "The Paldalmun market cluster's cheap eats: blood sausage from Jidong, seed-filled hotteok, and grilled minced-rib patties",
 "Roughly **10:00–20:00**",
 "**₩2,000–₩10,000**",
 "[suwon.go.kr](https://www.suwon.go.kr)",
 "**Far cheaper than the wanggalbi restaurants** and arguably more interesting."),

("🏛️","Suwon Hwaseong Fortress Uigwe & Restoration Story","🔁 daily (FREE reading)",
 "Hwaseong was rebuilt after Korean War damage using the *Hwaseong Seongyeok Uigwe*, a complete illustrated construction record from 1801",
 "Displays at the Hwaseong Museum",
 "Museum **₩2,000**",
 "[UNESCO](https://whc.unesco.org/en/list/817) · [swmuseum.suwon.go.kr](https://swmuseum.suwon.go.kr)",
 "**This record is why UNESCO accepted a reconstructed fortress** — the restoration is documented to the brick."),

("🧱","Hwaseong Secret Gates, Ammun & Bastions (암문·포루)","🔁 daily (FREE)",
 "The fortress's five hidden sally ports, ten bastions, four watchtowers and the crossbow platforms — the details most walkers pass without noticing",
 "Always accessible on the wall walk",
 "**FREE** (wall ticket ₩1,000)",
 "[swcf.or.kr](https://www.swcf.or.kr) · [UNESCO](https://whc.unesco.org/en/list/817)",
 "**Look for the Gongsimdon hollow towers** — the design was borrowed from Chinese and Western military texts."),

("🔥","Bongdon Beacon Tower (봉돈)","🔁 daily (FREE)",
 "The five-chimney signal beacon on the east wall, part of the national fire-signal network, still fired on ceremonial occasions",
 "Always visible",
 "**FREE**",
 "[swcf.or.kr](https://www.swcf.or.kr)",
 "On the eastern stretch between Changnyongmun and Paldalmun. Occasional lighting ceremonies — ask at the information centre."),

("🌉","Suwon Hwaseong Wall Walk — accessible sections","🔁 daily",
 "Not all of Hwaseong is steep: the eastern and northern stretches between Changnyongmun, Yeonmudae and Hwahongmun are almost flat",
 "Always open",
 "Wall ticket **₩1,000**",
 "[swcf.or.kr](https://www.swcf.or.kr) · [suwon.go.kr](https://www.suwon.go.kr)",
 "**Avoid Paldalsan if mobility is limited** — take the trolley up and walk the flat half instead."),

("🐦","Suwon Chilbosan & Ilwolsuwon Reservoir Nature","🔁 daily (FREE)",
 "Low wooded hills and a reservoir west of the city, used by locals for short walks and by wintering birds from November",
 "Always open",
 "**FREE**",
 "[suwon.go.kr](https://www.suwon.go.kr)",
 "Bus from Suwon Station. Quiet, local and free — no tourist presence at all."),

("🌲","Suwon Ecological Park & Hwaseong Green Belt","🔁 daily (FREE)",
 "The green corridors linking Gwanggyo Lake, Yeongtong and the Wongcheon stream, with continuous walking and cycling paths",
 "Always open",
 "**FREE**",
 "[suwon.go.kr](https://www.suwon.go.kr)",
 "Suwon markets itself as an ecological city — the stream network is genuinely well-built."),

("🏫","Sungkyunkwan University Natural Sciences Campus","🔁 daily (FREE)",
 "The Suwon campus of Korea's oldest university lineage, with open grounds and cheap student cafeterias",
 "Campus always open",
 "**FREE**",
 "[skku.edu](https://www.skku.edu)",
 "Line 1 Sungkyunkwan University Station. Cafeteria meals around ₩5,000."),

("🎓","Kyonggi & Ajou University Districts","🔁 daily",
 "The student quarters around Suwon's universities, with the cheapest food and busiest late-night streets in the city",
 "Roughly **11:00–02:00**",
 "Meals **₩6,000–₩12,000**",
 "[suwon.go.kr](https://www.suwon.go.kr)",
 "Ajou University area near Woncheon is the largest. Good for budget travellers."),

("🍺","Suwon Craft Beer & Bar Scene","🔁 nightly",
 "Craft taprooms in Haenggung-dong and Ingye-dong, several brewing on site, plus the standard Korean beer-and-fried-chicken pairing",
 "Roughly **17:00–01:00**",
 "Pints **₩7,000–₩10,000**",
 "[suwon.go.kr](https://www.suwon.go.kr)",
 "**Chicken street plus a craft pint is the classic Suwon evening.**"),

("☕","Suwon Rooftop Cafes with Fortress Views","🔁 daily",
 "Several Haenggung-dong cafes have rooftop terraces looking directly onto the fortress wall and Paldalsan",
 "Roughly **11:00–22:00**",
 "Coffee **₩5,000–₩7,000**",
 "[suwon.go.kr](https://www.suwon.go.kr)",
 "**The cheapest 'paid view' of Hwaseong** — a coffee costs less than the balloon and you sit down."),

("🎡","Suwon Family Attractions — Zoo & Children's Museum","🔁 Tue–Sun",
 "Suwon's family facilities include the Gyeonggi Children's Museum in Yongin and municipal indoor play centres",
 "Tue–Sun **10:00–18:00** (closed Mon)",
 "Children's museum **₩7,000**",
 "[gcm.ggcf.kr](https://gcm.ggcf.kr) · [suwon.go.kr](https://www.suwon.go.kr)",
 "**Book timed entry online** for the children's museum — it sells out at weekends."),

("🎳","Suwon Indoor Activities — screen golf, bowling, jjimjilbang","🔁 daily",
 "Standard Korean indoor options across Suwon, useful on a cold or wet November day: screen golf, bowling alleys and 24-hour bathhouses",
 "Many **24 hours**",
 "Jjimjilbang **₩10,000–₩15,000**",
 "[suwon.go.kr](https://www.suwon.go.kr)",
 "**A jjimjilbang after the full 5.7 km wall walk is the correct decision.**"),

("♨️","Suwon Spa & Bathhouse Options","🔁 daily",
 "Large sauna and bathhouse complexes near Suwon Station and Ingye-dong, most open around the clock",
 "Many **24 hours**",
 "**₩10,000–₩18,000**",
 "[suwon.go.kr](https://www.suwon.go.kr)",
 "Tattoo policies vary — check before paying. Bring nothing; towels and clothes are issued."),

("🚗","Suwon Car Rental & Regional Driving","🔁 daily",
 "Rental desks at Suwon Station give access to Yongin, Hwaseong, the royal tombs and the west-coast mudflats without bus changes",
 "Roughly **08:00–20:00**",
 "From **₩60,000** per day",
 "[suwon.go.kr](https://www.suwon.go.kr) · [visitkorea.or.kr](https://english.visitkorea.or.kr)",
 "**An International Driving Permit is required.** Public transport covers the fortress fine; a car helps for the tombs and Yongjusa."),

("🚕","Suwon Taxis & App-Based Rides","🔁 24 h",
 "Metered taxis throughout Suwon; Kakao T works with a foreign phone number and avoids language problems",
 "**24 hours**",
 "Base fare **₩4,800**",
 "[suwon.go.kr](https://www.suwon.go.kr)",
 "Suwon Station to Paldalmun is about ₩6,000. **Cheap enough to skip the bus.**"),

("🎫","Suwon Integrated Ticket & Discounts","🔁 daily",
 "A combined ticket covers Hwaseong wall, Haenggung, the Hwaseong Museum and Suwon Museum at a discount over separate entry",
 "During site hours",
 "Combined adult **₩3,500**",
 "[swcf.or.kr](https://www.swcf.or.kr) · [suwon.go.kr](https://www.suwon.go.kr)",
 "**Buy it at the first site you enter.** Suwon's admission prices are among the lowest of any UNESCO site in the world."),

("🗓️","Suwon Monday Closures — planning warning","🔁 planning",
 "Suwon's museums, the trolley and the martial arts demonstration all pause on **Mondays**, though the fortress wall itself stays open",
 "N/A",
 "N/A",
 "[swcf.or.kr](https://www.swcf.or.kr) · [suwon.go.kr](https://www.suwon.go.kr)",
 "**Do not plan your Suwon day on a Monday** unless you only want the wall walk."),

("🏯","Hwaseong Haenggung Night Opening (야간개장)","👀 WATCH — seasonal",
 "Haenggung palace runs periodic evening openings with lighting and performances; schedules are published seasonally by the cultural foundation",
 "Evenings, typically **18:00–21:00** when running",
 "Adult **₩1,500–₩5,000**",
 "[swcf.or.kr](https://www.swcf.or.kr)",
 "**Check the November 2026 schedule** — night openings are usually spring and autumn."),

("🥁","Suwon Traditional Performance & Gugak Programmes","🔁 weekends",
 "Free and low-cost traditional music and dance at Haenggung Square and the Suwon Traditional Culture Center on weekends",
 "Weekend afternoons",
 "Many **FREE**",
 "[swcf.or.kr](https://www.swcf.or.kr) · [suwon.go.kr](https://www.suwon.go.kr)",
 "Programmes are posted at the Haenggung ticket office. Combine with the 11:00 martial arts show."),

("🖼️","Suwon Art Space Gwanggyo & Public Art","🔁 Tue–Sun (FREE)",
 "A contemporary art space in the Gwanggyo new town, plus a substantial public-sculpture programme around the lake park",
 "Tue–Sun **10:00–19:00** (closed Mon)",
 "Often **FREE**",
 "[suma.suwon.go.kr](https://suma.suwon.go.kr) · [suwon.go.kr](https://www.suwon.go.kr)",
 "The lake park sculptures are free and lit at night."),

("🏛️","Gyeonggi Provincial Government & Suwon as capital","🔁 weekdays (FREE)",
 "Suwon is the provincial capital of Gyeonggi-do; the provincial complex and the new Gwanggyo government town are open to visitors",
 "Weekdays **09:00–18:00**",
 "**FREE**",
 "[gg.go.kr](https://www.gg.go.kr)",
 "Mainly of interest for the modern-Korea contrast with the fortress a few kilometres away."),

("🌏","Suwon Global Center & Foreign Resident Services","🔁 weekdays (FREE)",
 "Suwon has a large foreign resident population; the Global Center provides free interpretation, advice and cultural programmes",
 "Weekdays **09:00–18:00**",
 "**FREE**",
 "[suwon.go.kr](https://www.suwon.go.kr) · [1330 Hotline](https://english.visitkorea.or.kr)",
 "**Dial 1330 for free 24-hour English tourist help.**"),

("🕌","Suwon Halal & International Food Options","🔁 daily",
 "Suwon's international districts near the industrial belt offer halal, Central Asian, Vietnamese and Nepali food",
 "Roughly **11:00–22:00**",
 "Meals **₩9,000–₩15,000**",
 "[suwon.go.kr](https://www.suwon.go.kr)",
 "Concentrated around Suwon Station's west side and the Ansan-bound bus corridor."),

("🥬","Suwon Vegetarian & Temple Food","🔁 daily",
 "Vegetarian options at Yongjusa's temple kitchen and several Haenggung-dong cafes, plus bibimbap adaptable on request",
 "Roughly **11:00–20:00**",
 "Temple set **₩12,000–₩20,000**",
 "[yongjoosa.or.kr](http://www.yongjoosa.or.kr) · [suwon.go.kr](https://www.suwon.go.kr)",
 "**Book temple meals ahead** — they are not walk-in."),

("🎒","Suwon Station Lockers & Luggage","🔁 daily",
 "Coin lockers at Suwon Station and the bus terminal make Suwon easy to do as a stopover between Seoul and the south",
 "Roughly **05:00–24:00**",
 "**₩2,000–₩5,000** per day",
 "[letskorail.com](https://www.letskorail.com) · [suwon.go.kr](https://www.suwon.go.kr)",
 "**Suwon is a KTX stop on the Gyeongbu line** — a natural half-day break on the way to Busan."),

("🛤️","Suwon to Yongin & Everland connections","🔁 daily",
 "Direct buses from Suwon Station to Everland and the Korean Folk Village, both under 40 minutes away",
 "Roughly **07:00–22:00**",
 "Bus **₩2,000–₩2,800**",
 "[everland.com](https://www.everland.com) · [koreanfolk.co.kr](https://www.koreanfolk.co.kr)",
 "**Bus 37 from Suwon Station to the Korean Folk Village** is the standard route — about 30 minutes."),

("🗺️","Suwon two-day plan with Yongin & the royal tombs","🔁 planning",
 "Day 1: fortress, Haenggung, museums, illumination. Day 2: Yungneung/Geolleung tombs + Yongjusa, or the Korean Folk Village in Yongin",
 "Two full days",
 "About **₩60,000** total",
 "[swcf.or.kr](https://www.swcf.or.kr) · [royaltombs.khs.go.kr](https://royaltombs.khs.go.kr)",
 "**Two UNESCO sites — Hwaseong and the Joseon royal tombs — within 15 km of each other.**"),
]

append("/home/user/KoreaFun/suwon.md", E, 189, 3,
       "\n---\n\n## 🧭 Beginner-friendly essentials", "Suwon")
