# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "/home/user/KoreaFun/.build")
from addlib import append

E = [
("🏰","Hwaseong Fortress full 5.7 km wall walk — UNESCO (수원화성)","🔁 daily",
 "**UNESCO World Heritage**: King Jeongjo's 1794–1796 fortress, built with Jeong Yak-yong's crane and pulley engineering — the wall is walkable in full",
 "Daily **09:00–18:00** (Nov: to 17:00); wall paths accessible longer",
 "Adult **₩1,000**; youth ₩700; child ₩500",
 "[UNESCO](https://whc.unesco.org/en/list/817) · [swcf.or.kr](https://www.swcf.or.kr)",
 "**Allow 2.5–3 hours for the full circuit.** Start at Paldalmun and go clockwise up Paldalsan first while fresh."),

("👑","Hwaseong Haenggung Temporary Palace (화성행궁)","🔁 daily",
 "The largest surviving Joseon detached palace, where King Jeongjo stayed on visits to his father's tomb — 576 rooms, reconstructed from 1996",
 "Daily **09:00–18:00** (Nov: to 17:00)",
 "Adult **₩1,500**; youth ₩1,000; child ₩700",
 "[swcf.or.kr](https://www.swcf.or.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "**Free martial arts (24 Ban Muye) demonstrations Tue–Sun at 11:00** in the courtyard — check the seasonal schedule."),

("⚔️","24 Ban Muye Martial Arts Demonstration (무예24기)","✅ CONFIRMED — Tue–Sun",
 "A daily performance of the 24 martial arts codified in King Jeongjo's 1790 manual, by the Suwon city troupe in Haenggung courtyard",
 "**Tue–Sun 11:00** (about 30 min); no show Mondays",
 "**FREE** with Haenggung admission",
 "[swcf.or.kr](https://www.swcf.or.kr) · [suwon.go.kr](https://www.suwon.go.kr)",
 "**Winter schedule can change** — confirm on the foundation site before travelling."),

("🚩","Paldalmun Gate — South Gate (팔달문)","🔁 daily (FREE)",
 "The southern gate of Hwaseong, **Treasure No. 402**, a two-storey gatehouse with a semicircular protective barbican, now on a traffic island",
 "Always visible",
 "**FREE**",
 "[swcf.or.kr](https://www.swcf.or.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "Suwon Line 1 Suwon Station + bus, or a 20-minute walk. The market district begins right here."),

("🏯","Janganmun Gate — North Gate (장안문)","🔁 daily (FREE)",
 "**The largest surviving city gate in Korea**, bigger than Seoul's Namdaemun, and the ceremonial main entrance King Jeongjo used",
 "Always visible; upper floor by event",
 "**FREE**",
 "[swcf.or.kr](https://www.swcf.or.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "Illuminated at night. The wall walk north of here is the quietest and best-preserved stretch."),

("🌅","Changnyongmun & Hwaseomun Gates (창룡문·화서문)","🔁 daily (FREE)",
 "The east and west gates of Hwaseong; **Hwaseomun with its Seobuk Gongsimdon observation tower is a Treasure** and the classic photo of the fortress",
 "Always open",
 "**FREE**",
 "[swcf.or.kr](https://www.swcf.or.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "Changnyongmun's field is where the archery experience and the flying balloon operate."),

("🎯","Hwaseong Traditional Korean Archery (국궁체험)","🔁 Tue–Sun",
 "Shoot a traditional Korean bow from the Changnyongmun field, run by the city with instructors and equipment provided",
 "Tue–Sun **09:30–17:00** (Nov: to 16:30)",
 "**₩2,000** for 10 arrows",
 "[swcf.or.kr](https://www.swcf.or.kr) · [suwon.go.kr](https://www.suwon.go.kr)",
 "**Absurdly cheap and genuinely fun.** No booking needed — just turn up."),

("🎈","Hwaseong Flying Balloon — tethered helium (플라잉수원)","🔁 daily, weather permitting",
 "A tethered helium balloon rising 150 m over Changnyongmun for an aerial view of the whole fortress circuit",
 "Daily **10:00–18:00** (Nov: to 17:00); wind-dependent",
 "Adult **₩18,000**; child ₩12,000",
 "[swcf.or.kr](https://www.swcf.or.kr) · [suwon.go.kr](https://www.suwon.go.kr)",
 "**Cancelled in wind** — phone ahead. The only way to see the fortress plan from above."),

("🚂","Hwaseong Trolley Tourist Train (화성어차)","🔁 Tue–Sun",
 "A dragon-headed trolley running between Yeonmudae, Haenggung and Paldalsan — the easy way to link the fortress sights",
 "Tue–Sun **10:00–17:00** (closed Mon)",
 "Adult **₩4,000**; child ₩2,000",
 "[swcf.or.kr](https://www.swcf.or.kr)",
 "Doesn't cover the whole wall. **Best used one way, uphill, then walk back down.**"),

("🛡️","Yeonmudae Command Post & Dongjangdae (연무대)","🔁 daily (FREE)",
 "The eastern military training ground of Hwaseong, on a rise with a commanding view — the departure point for the trolley and archery",
 "Always open",
 "**FREE**",
 "[swcf.or.kr](https://www.swcf.or.kr)",
 "Large open lawn; the most relaxed spot on the whole circuit for a break."),

("🌊","Hwahongmun Water Gate & Banghwasuryujeong (화홍문·방화수류정)","🔁 daily (FREE)",
 "**The most beautiful structure in Hwaseong** — a seven-arched water gate over the Suwoncheon with a pavilion above a lotus pond, floodlit at night",
 "Always open",
 "**FREE**",
 "[swcf.or.kr](https://www.swcf.or.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "**Go after dark.** The reflection in the pond with the pavilion lit is the single best free sight in Suwon."),

("🏛️","Suwon Hwaseong Museum (수원화성박물관)","🔁 Tue–Sun",
 "The construction of Hwaseong explained in detail — Jeong Yak-yong's crane, the *Uigwe* royal record, and a huge model of Jeongjo's 1795 procession",
 "Tue–Sun **09:00–18:00** (closed Mon)",
 "Adult **₩2,000**; youth ₩1,000",
 "[swmuseum.suwon.go.kr](https://swmuseum.suwon.go.kr)",
 "**Do this before walking the wall** — the engineering makes far more sense afterwards."),

("🏛️","Suwon Museum & Korean Calligraphy Museum (수원박물관)","🔁 Tue–Sun",
 "The city history museum, sharing a building with **Korea's largest public calligraphy collection**",
 "Tue–Sun **09:00–18:00** (closed Mon)",
 "Adult **₩2,000**",
 "[suwon.go.kr](https://www.suwon.go.kr)",
 "Bundang Line Maetan-Gwonseon Station. A recreated 1960s Suwon street runs through the middle."),

("🖼️","Suwon Museum of Art (수원시립미술관)","🔁 Tue–Sun",
 "The city art museum beside Haenggung Square, showing Korean modern and contemporary art and the work of Suwon-born artist Na Hye-sok",
 "Tue–Sun **10:00–19:00** (closed Mon)",
 "Adult **₩4,000**; often free for special weeks",
 "[suma.suwon.go.kr](https://suma.suwon.go.kr)",
 "**Free on the last Wednesday of each month (Culture Day).** Right beside the palace."),

("🚽","Mr. Toilet House — Haewoojae Museum (해우재)","🔁 Tue–Sun (FREE)",
 "**The world's only toilet-themed museum**, in the toilet-shaped former house of Suwon mayor Sim Jae-duck, founder of the World Toilet Association",
 "Tue–Sun **10:00–18:00** (closed Mon)",
 "**FREE**",
 "[haewoojae.suwon.go.kr](https://haewoojae.suwon.go.kr) · [suwon.go.kr](https://www.suwon.go.kr)",
 "Bus from Suwon Station, 25 min. **Genuinely informative about global sanitation — and free.**"),

("🏢","Samsung Innovation Museum, Suwon (삼성이노베이션뮤지엄)","🔁 weekdays — reservation required",
 "Samsung Electronics' corporate museum at its Suwon Digital City campus, tracing the history of electronics from Edison to semiconductors",
 "Weekdays **09:30–17:30**; **advance reservation required**",
 "**FREE**",
 "[samsung.com](https://www.samsung.com/sec/sim/) · [suwon.go.kr](https://www.suwon.go.kr)",
 "**Book online well ahead** — walk-ins are not admitted. Photo ID needed at the gate."),

("🛍️","Starfield Suwon (스타필드 수원)","🔁 daily (FREE)",
 "Shinsegae's 2024 mega-mall in Suwon, with the **Byeolmadang Library**, a rooftop sports park and a large food hall",
 "Daily **10:00–22:00**",
 "**FREE** entry",
 "[starfield.co.kr](https://www.starfield.co.kr)",
 "Suwon Line 1 Hwaseo Station, connected. **The best wet-weather fallback in Suwon.**"),

("🌳","Gwanggyo Lake Park (광교호수공원)","🔁 daily (FREE)",
 "Two linked reservoirs in Suwon's new town, with 5 km of boardwalk, floating decks, art installations and a night-lit promenade",
 "Always open",
 "**FREE**",
 "[suwon.go.kr](https://www.suwon.go.kr)",
 "Sinbundang Line Gwanggyo Jungang Station. **The best modern counterpoint to the fortress** — go at sunset."),

("⛰️","Gwanggyosan Trails & Suwon Ridge Walk (광교산)","🔁 daily (FREE)",
 "Suwon's home mountain at 582 m, with well-signed trails from the city edge and a ridge that continues toward Yongin",
 "Always open; start before 13:00",
 "**FREE**",
 "[suwon.go.kr](https://www.suwon.go.kr) · [Korea Forest Service](https://www.forest.go.kr)",
 "Bus to Gyeonggidae entrance. **Three to four hours for the standard loop** — good November hiking weather."),

("🌺","Wolhwawon Chinese Garden (월화원)","🔁 daily (FREE)",
 "An authentic Guangdong-style Chinese garden built by Guangdong province in Suwon's Hyowon Park, with a pond, pavilions and rockeries",
 "Daily **09:00–22:00**",
 "**FREE**",
 "[suwon.go.kr](https://www.suwon.go.kr)",
 "In Hyowon Park, bus from Suwon Station. Small — 30 minutes — but a complete and free garden."),

("🎨","Haenggung-dong Mural Village & Jidong (행궁동벽화마을)","🔁 daily (FREE)",
 "The residential lanes behind Haenggung, painted by artists and residents in a widely-cited urban-regeneration project",
 "Always open",
 "**FREE**",
 "[suwon.go.kr](https://www.suwon.go.kr)",
 "Residential — go quietly. The **Suwon Chicken Street** is a five-minute walk away."),

("🍗","Suwon Fried Chicken Street — Tongdak Alley (통닭거리)","🔁 daily",
 "A street of a dozen whole-chicken fryers near Paldalmun, using an oil-frying method local to Suwon since the 1970s",
 "Roughly **11:00–24:00**",
 "Whole chicken **₩20,000–₩24,000**",
 "[suwon.go.kr](https://www.suwon.go.kr)",
 "**Order whole and share; expect a 30–60 minute wait at weekends.** Jinmi and Yongseong are the long-standing names."),

("🥩","Suwon Wanggalbi — the original king ribs (수원왕갈비)","🔁 daily",
 "Suwon's beef short ribs, invented at a market restaurant in 1945 and now a nationally protected regional speciality",
 "Most **11:30–22:00**",
 "**₩45,000–₩70,000** per person",
 "[suwon.go.kr](https://www.suwon.go.kr) · [visitkorea.or.kr](https://english.visitkorea.or.kr)",
 "**Expensive but this is the dish Suwon is famous for.** Lunch sets are considerably cheaper than dinner."),

("🏪","Paldalmun & Jidong Traditional Markets (팔달문시장·지동시장)","🔁 daily",
 "Nine linked traditional markets around Paldalmun, together forming one of the largest market clusters in Gyeonggi Province",
 "Roughly **09:00–21:00**",
 "**FREE** to browse",
 "[suwon.go.kr](https://www.suwon.go.kr)",
 "**Jidong Market's sundae alley** is the local speciality here. Cheap and busy."),

("🌃","Suwon Nammun Rodeo Street & Youth Quarter","🔁 daily",
 "The shopping and nightlife strip immediately inside Paldalmun, busy with students from Suwon's universities",
 "Shops **11:00–22:00**; bars later",
 "**FREE** to walk",
 "[suwon.go.kr](https://www.suwon.go.kr)",
 "Directly between the fortress wall and the market — an easy evening after the wall walk."),

("⚽","Suwon Samsung Bluewings — K League (수원삼성)","👀 WATCH — check 2026 division & fixtures",
 "One of Korea's biggest clubs, playing at Suwon World Cup Stadium, with the **Super Match against FC Seoul** as its defining fixture",
 "Kick-off typically **14:00** or **19:00**",
 "Tickets from **₩12,000**",
 "[bluewings.kr](https://www.bluewings.kr) · [kleague.com](https://www.kleague.com)",
 "**Confirm the club's 2026 division and November fixtures on the K League site** before planning around a match."),

("⚽","Suwon FC — K League 1 (수원FC)","👀 WATCH — season ends Nov/Dec",
 "Suwon's second professional club, playing at Suwon Sports Complex in the city centre — closer to the fortress than the World Cup stadium",
 "Kick-off typically **14:00** or **16:30**",
 "Tickets from **₩10,000**",
 "[suwonfc.com](https://www.suwonfc.com) · [kleague.com](https://www.kleague.com)",
 "**A short walk from Hwaseong** — an easy add-on to a fortress day if a fixture lands right."),

("🏟️","Suwon World Cup Stadium — Big Bird (수원월드컵경기장)","🔁 daily (FREE outside matches)",
 "A 2002 World Cup venue seating 43,000, nicknamed Big Bird for its wing-like roof, with a football museum on site",
 "Grounds always open",
 "**FREE** to view",
 "[kfa.or.kr](https://www.kfa.or.kr) · [suwon.go.kr](https://www.suwon.go.kr)",
 "Bus from Suwon Station. Hosted four matches including a semi-final in 2002."),

("🥎","KT Wiz — KBO baseball, Suwon (kt wiz)","👀 WATCH — KBO season ends October",
 "Suwon's KBO team at KT Wiz Park, one of Korea's newest baseball stadiums",
 "Season roughly **April–October**",
 "Tickets from **₩8,000**",
 "[ktwiz.co.kr](https://www.ktwiz.co.kr) · [koreabaseball.com](https://www.koreabaseball.com)",
 "**The KBO regular season and Korean Series finish before late November** — likely outside your window."),

("🏛️","Suwon Hwaseong Fortress Night Illumination (야간경관)","🔁 nightly (FREE)",
 "The whole 5.7 km wall, the four gates and Banghwasuryujeong are floodlit after dark — one of Korea's best free night walks",
 "Roughly **sunset–23:00**",
 "**FREE**",
 "[swcf.or.kr](https://www.swcf.or.kr) · [suwon.go.kr](https://www.suwon.go.kr)",
 "**Sunset is around 17:20 in November.** The Janganmun-to-Hwahongmun stretch is the best lit section."),

("🎪","Suwon Hwaseong Cultural Festival & Media Art","👀 WATCH — usually October",
 "Suwon's flagship festival re-enacts King Jeongjo's 1795 royal procession with thousands of participants; it normally runs in early October",
 "By event",
 "Mostly **FREE**",
 "[shcf.or.kr](https://www.shcf.or.kr) · [suwon.go.kr](https://www.suwon.go.kr)",
 "**Usually just before your window** — but check the 2026 dates, as they occasionally shift into late autumn."),

("🏮","Suwon Lantern & Winter Light Events","👀 WATCH (Nov–Jan)",
 "Suwon typically mounts lantern displays around Haenggung Square and winter lighting on the fortress walls from late autumn",
 "Evenings once lit",
 "Usually **FREE**",
 "[suwon.go.kr](https://www.suwon.go.kr) · [swcf.or.kr](https://www.swcf.or.kr)",
 "Dates are announced by the city in October. **Watch the tourism page.**"),

("🚇","Getting to Suwon — Line 1, Sinbundang & KTX","🔁 daily",
 "Suwon is on **Seoul Metro Line 1** (about 1 hour from Seoul Station), the Sinbundang Line to Gwanggyo, and the KTX Gyeongbu line",
 "Roughly **05:30–24:00**",
 "Line 1 from Seoul **₩1,850**; KTX ₩8,400",
 "[letskorail.com](https://www.letskorail.com) · [seoulmetro.co.kr](https://www.seoulmetro.co.kr)",
 "**Line 1 with a T-money card is the simple option** — no reservation and it runs constantly."),

("🚌","Suwon City Bus & Fortress Loop Access","🔁 daily",
 "City buses 11, 13, 36 and 39 connect Suwon Station to Paldalmun and the fortress; T-money works throughout",
 "Roughly **05:30–23:30**",
 "**₩1,450** card",
 "[suwon.go.kr](https://www.suwon.go.kr) · [gbis.go.kr](https://www.gbis.go.kr)",
 "**Suwon Station to Paldalmun is only 2 km** — walkable if you'd rather see the market street."),

("🚲","Suwon Public Bicycles & Fortress Cycling","🔁 daily",
 "The Suwoncheon stream path and Gwanggyo Lake are cycle-friendly, and public rental stands operate across the city",
 "Roughly **06:00–22:00**",
 "**₩1,000** per hour",
 "[suwon.go.kr](https://www.suwon.go.kr)",
 "**Do not try to cycle the fortress wall itself** — it's stepped and pedestrian-only in sections."),

("🧭","Suwon Tourist Information & Free Guided Tours","🔁 daily (FREE)",
 "Information centres at Suwon Station, Paldalmun and Haenggung, with free English guided tours of the fortress by prior booking",
 "Daily **09:00–18:00**",
 "**FREE**",
 "[swcf.or.kr](https://www.swcf.or.kr) · [visitkorea.or.kr](https://english.visitkorea.or.kr)",
 "**Book the free English guide at least 3 days ahead** through the cultural foundation."),

("👘","Suwon Hanbok Rental & Fortress Photos","🔁 daily",
 "Hanbok rental near Haenggung Square, with **free admission to Haenggung and the fortress while wearing it**",
 "Roughly **10:00–18:00**",
 "**₩15,000–₩25,000** for 2–4 hours",
 "[swcf.or.kr](https://www.swcf.or.kr) · [suwon.go.kr](https://www.suwon.go.kr)",
 "The Haenggung courtyard and Hwahongmun are the two best backdrops. November: rent the winter overcoat."),

("🍚","Suwon Haenggung-dong Cafe Street (행리단길)","🔁 daily",
 "The independent cafe and bistro strip in the old lanes beside Haenggung, in converted 1970s houses — Suwon's answer to Seoul's Ikseon-dong",
 "Cafes **11:00–22:00**",
 "Coffee **₩5,000**",
 "[suwon.go.kr](https://www.suwon.go.kr)",
 "**Directly adjacent to the palace** — the natural lunch or coffee stop mid-wall-walk."),

("🌰","Suwon Autumn Foliage & November Weather","🔁 seasonal",
 "Gwanggyosan and the fortress wall's tree line peak in **late October to mid-November**; November days run 3–14 °C, dry and clear",
 "Daylight hours",
 "**FREE**",
 "[weather.go.kr](https://www.weather.go.kr) · [suwon.go.kr](https://www.suwon.go.kr)",
 "**Ideal wall-walking weather** — cool enough for the uphill sections, clear enough for the views."),

("📋","Suwon as a Seoul day trip — model route","🔁 planning",
 "Line 1 from Seoul → Paldalmun → market → Haenggung + martial arts 11:00 → Hwaseong Museum → wall walk to Hwahongmun → dusk illumination → chicken street",
 "Full day, roughly **09:00–20:00**",
 "About **₩30,000** including admissions and travel",
 "[swcf.or.kr](https://www.swcf.or.kr) · [visitkorea.or.kr](https://english.visitkorea.or.kr)",
 "**Suwon is the single best day trip from Seoul** — a full UNESCO site an hour away on a metro card."),

("⛲","Suwon Hwaseong Suwoncheon Stream Walk (수원천)","🔁 daily (FREE)",
 "The restored stream running through the fortress under Hwahongmun, with a continuous walking path linking the market to the north wall",
 "Always open",
 "**FREE**",
 "[suwon.go.kr](https://www.suwon.go.kr)",
 "**A flat alternative to the hill sections** of the wall if you want an easier route north."),

("🏯","Seojangdae Command Post & Paldalsan Summit (서장대)","🔁 daily (FREE)",
 "The western command post at the top of Paldalsan, the highest point of Hwaseong, with the whole city laid out below",
 "Always open",
 "**FREE**",
 "[swcf.or.kr](https://www.swcf.or.kr)",
 "**The steepest climb on the circuit** — 15 minutes of steps from Paldalmun, and the best view of the fortress."),

("🔔","Hyowon Bell of Filial Piety (효원의 종)","🔁 daily",
 "A large bell in Hyowon Park that visitors may ring three times — for parents, family and self — reflecting Jeongjo's filial devotion",
 "Daily **10:00–17:00**",
 "**₩1,000** for three strikes",
 "[suwon.go.kr](https://www.suwon.go.kr)",
 "Beside the Chinese garden. A one-minute, slightly odd, memorable stop."),

("🛕","Yongjusa Temple & Jeongjo's Filial Devotion (용주사)","🔁 daily",
 "The temple King Jeongjo restored in 1790 to honour his father Prince Sado, with a bronze bell that is a **National Treasure**",
 "Daily **09:00–18:00** (Nov: to 17:00)",
 "**₩1,500**",
 "[yongjoosa.or.kr](http://www.yongjoosa.or.kr) · [hscity.go.kr](https://www.hscity.go.kr)",
 "In Hwaseong City, bus from Suwon Station. **The reason Hwaseong Fortress exists is buried nearby.**"),

("⚰️","Yungneung & Geolleung Royal Tombs — UNESCO (융릉·건릉)","🔁 Tue–Sun",
 "Part of the **UNESCO Royal Tombs of the Joseon Dynasty**: Prince Sado's tomb and King Jeongjo's own, in a wooded valley south of Suwon",
 "Tue–Sun **09:00–18:00** (Nov: to 17:00; closed Mon)",
 "Adult **₩1,000**",
 "[UNESCO](https://whc.unesco.org/en/list/1319) · [royaltombs.khs.go.kr](https://royaltombs.khs.go.kr)",
 "Beside Yongjusa. **The forest walk between the two tombs is superb in November.**"),

("🌾","Suwon Agricultural Heritage & Seoho Reservoir (서호)","🔁 daily (FREE)",
 "The reservoir King Jeongjo built in 1799 for model farming, now a bird sanctuary with a lakeside path and the old agricultural station",
 "Always open",
 "**FREE**",
 "[suwon.go.kr](https://www.suwon.go.kr)",
 "Ten minutes' walk from Suwon Station. **Migratory waterfowl arrive in November.**"),

("🏫","Suwon Ancient Culture & Gwanggyo Museum (경기도박물관)","🔁 Tue–Sun (FREE)",
 "The **Gyeonggi Provincial Museum** in nearby Yongin covers the whole province's history, with strong Joseon and folk collections",
 "Tue–Sun **10:00–18:00** (closed Mon)",
 "**FREE**",
 "[musenet.ggcf.kr](https://musenet.ggcf.kr)",
 "Sinbundang Line to Sanggal, or bus from Suwon. Free and rarely crowded."),

("🎭","Gyeonggi Arts Center & Suwon SK Artrium","🔁 by programme",
 "Suwon's two main performance venues, running an autumn season of orchestral concerts, gugak and theatre",
 "Box office **09:00–18:00**; shows **19:30**",
 "**₩10,000–₩60,000**",
 "[ggac.or.kr](https://www.ggac.or.kr) · [suwonsk.com](https://www.suwonsk.com)",
 "Check November programmes when booking. English-friendly booking on the venue sites."),

("🍜","Suwon University District Food — Ingye-dong","🔁 daily",
 "Ingye-dong is Suwon's dense restaurant and bar district, cheaper and busier than the fortress area, with late-night food",
 "Roughly **11:00–02:00**",
 "Meals **₩8,000–₩15,000**",
 "[suwon.go.kr](https://www.suwon.go.kr)",
 "Bundang Line Suwon City Hall Station. **Where locals actually eat and drink on a Friday night.**"),

("🧳","Suwon Accommodation & Staying vs Day-Tripping","🔁 planning",
 "Suwon has hotels around the station and guesthouses in Haenggung-dong, at markedly lower prices than Seoul",
 "Check-in typically **15:00**",
 "From **₩50,000** per night",
 "[suwon.go.kr](https://www.suwon.go.kr) · [visitkorea.or.kr](https://english.visitkorea.or.kr)",
 "**Staying a night lets you see the illuminated wall properly** — the strongest argument for not day-tripping."),
]

append("/home/user/KoreaFun/suwon.md", E, 139, 3,
       "\n---\n\n## 🧭 Beginner-friendly essentials", "Suwon",
       intro="**Verified expansion set** — the complete UNESCO Hwaseong Fortress inventory, Jeongjo-era heritage, museums, markets, sport, transit and the Joseon royal tombs south of the city.")
