# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "/home/user/KoreaFun/.build")
from addlib import append

E = [
("🐋","Bangudae Petroglyphs — UNESCO World Heritage (반구대 암각화)","🔁 daily (FREE)",
 "**Inscribed on the UNESCO World Heritage List in July 2025**: Neolithic rock carvings including **the world's oldest known depictions of whaling**, on a cliff above the Daegokcheon",
 "Museum Tue–Sun **09:00–18:00**; site always viewable",
 "**FREE**",
 "[UNESCO](https://whc.unesco.org/en/list/1727) · [ulsan.go.kr](https://www.ulsan.go.kr)",
 "**Bring binoculars** — the carvings are across the water and hard to see unaided. Water levels affect visibility; autumn is usually good."),

("🖼️","Ulsan Petroglyph Museum (울산암각화박물관)","🔁 Tue–Sun (FREE)",
 "The interpretation centre for the Bangudae and Cheonjeon-ri petroglyphs, with full-size replicas you can actually see up close",
 "Tue–Sun **09:00–18:00** (closed Mon)",
 "**FREE**",
 "[ulsan.go.kr](https://www.ulsan.go.kr) · [UNESCO](https://whc.unesco.org/en/list/1727)",
 "**Visit this before walking to the cliff** — otherwise you won't know what you're looking at."),

("🪨","Cheonjeon-ri Petroglyphs — UNESCO (천전리 각석)","🔁 daily (FREE)",
 "The second **UNESCO-listed** petroglyph panel, with Bronze Age geometric designs and **Silla-era inscriptions dated to 525 and 539 CE**",
 "Always open",
 "**FREE**",
 "[UNESCO](https://whc.unesco.org/en/list/1727) · [Korea Heritage Service](https://www.khs.go.kr)",
 "Two kilometres upstream from Bangudae. **Dinosaur footprints are exposed on the riverbed nearby.**"),

("🦕","Daegokcheon Dinosaur Footprints & Valley Walk","🔁 daily (FREE)",
 "Cretaceous dinosaur trackways in the streambed beside the Cheonjeon-ri panel, in the same UNESCO-inscribed valley",
 "Always open; best at low water",
 "**FREE**",
 "[ulsan.go.kr](https://www.ulsan.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "**Autumn low water exposes the tracks best** — good timing for a November visit."),

("🐳","Jangsaengpo Whale Culture Village (장생포고래문화마을)","🔁 Tue–Sun",
 "A recreated 1960s–70s whaling village on the site of Korea's whaling port, with a whale museum, a life-size blue whale model and a monorail",
 "Tue–Sun **09:00–18:00** (Nov: to 17:00; closed Mon)",
 "Village **₩2,000**; combined with museum ₩5,000",
 "[whalecity.kr](https://www.whalecity.kr) · [ulsan.go.kr](https://www.ulsan.go.kr)",
 "**Ulsan was Korea's whaling capital until the 1986 moratorium** — this is where that history is told."),

("🏛️","Jangsaengpo Whale Museum (고래박물관)","🔁 Tue–Sun",
 "**Korea's only whale museum**, with real skeletons, whaling equipment preserved after the 1986 ban, and a small whale ecology aquarium",
 "Tue–Sun **09:00–18:00** (closed Mon)",
 "Adult **₩2,000**",
 "[whalemuseum.go.kr](https://www.whalemuseum.go.kr) · [ulsan.go.kr](https://www.ulsan.go.kr)",
 "Bus 256 from Ulsan Station area. The blue whale skeleton is the centrepiece."),

("⛴️","Whale Watching Cruise, Jangsaengpo (고래바다여행선)","👀 WATCH — seasonal, weather-dependent",
 "A research-linked cruise into the East Sea looking for minke and dolphin pods; sightings of large dolphin schools are common",
 "Sailings typically **spring–autumn**, weather permitting",
 "Adult around **₩30,000**",
 "[whalecity.kr](https://www.whalecity.kr) · [ulsan.go.kr](https://www.ulsan.go.kr)",
 "**Confirm the November 2026 sailing schedule** — winter operations are reduced and cancellations are frequent."),

("🎨","Jangsaengpo Modern History Village & 5D Cinema","🔁 Tue–Sun",
 "Twenty-eight recreated buildings — a barber, a photo studio, a school, a whale-meat restaurant — reconstructing Jangsaengpo's whaling boom",
 "Tue–Sun **09:00–18:00** (closed Mon)",
 "Included with village ticket **₩2,000**",
 "[whalecity.kr](https://www.whalecity.kr)",
 "The costume rental and the 5D cinema are extra. Good for families."),

("🌊","Daewangam Park & Coastal Rocks (대왕암공원)","🔁 daily (FREE)",
 "A pine-forested headland ending in dramatic sea rocks, said to hold the spirit of **Queen Munmu**, with a red iron bridge over the water",
 "Always open",
 "**FREE**",
 "[ulsan.go.kr](https://www.ulsan.go.kr) · [Dong-gu Ulsan](https://www.donggu.ulsan.kr)",
 "**Ulsan's best free sight.** The 100-year-old pine avenue and the sunrise over the rocks are the highlights."),

("🚡","Daewangam Marine Cable Car & Zip Line (울산대왕암 해상케이블카)","🔁 daily",
 "A cable car over the sea at Daewangam and an adjacent zip line, opened in recent years as Ulsan's headline coastal attraction",
 "Daily **09:30–18:00** (Nov: to 17:30)",
 "Cable car round trip from **₩18,000**; zip line ₩35,000",
 "[ulsan.go.kr](https://www.ulsan.go.kr) · [Dong-gu Ulsan](https://www.donggu.ulsan.kr)",
 "**Wind closures are common in November** — check before travelling out."),

("🏖️","Ilsan Beach, Dong-gu (일산해수욕장)","🔁 daily (FREE)",
 "Ulsan's city beach beside Daewangam, with a promenade, cafes and a view straight across to the Hyundai shipyard cranes",
 "Always open",
 "**FREE**",
 "[Dong-gu Ulsan](https://www.donggu.ulsan.kr) · [ulsan.go.kr](https://www.ulsan.go.kr)",
 "**The industrial-and-sea contrast is the whole character of Ulsan** — nowhere shows it better."),

("🚢","Hyundai Heavy Industries Shipyard viewpoint (현대중공업)","🔁 daily (FREE to view)",
 "**The world's largest shipbuilding yard**, visible from the Dong-gu hillsides and Ilsan Beach — a genuinely staggering industrial landscape",
 "Viewpoints always open; tours by arrangement",
 "**FREE** to view",
 "[hhi.co.kr](https://www.hhi.co.kr) · [ulsan.go.kr](https://www.ulsan.go.kr)",
 "Public tours are limited and must be arranged in advance. **The free hillside view is the practical option.**"),

("🚗","Hyundai Motor Ulsan Plant Tour (현대자동차 울산공장)","👀 WATCH — booking required",
 "**The world's largest single automobile plant**, producing over a million cars a year, with a visitor tour of the assembly line and export dock",
 "Weekday tours by reservation",
 "**FREE**",
 "[hyundai.com](https://www.hyundai.com) · [ulsan.go.kr](https://www.ulsan.go.kr)",
 "**Reserve weeks ahead and bring photo ID.** Tours are frequently suspended — confirm availability before planning around it."),

("🏭","Ulsan Industrial Complex Night View (울산 공단 야경)","🔁 nightly (FREE)",
 "The petrochemical complex lit at night — a designated Ulsan night-view attraction, best seen from the Ulsan Bridge observatory",
 "Best **18:00–22:00**",
 "**FREE**",
 "[ulsan.go.kr](https://www.ulsan.go.kr)",
 "**Sunset is around 17:20 in November** — you can see this early in the evening."),

("🌉","Ulsan Bridge & Observatory (울산대교 전망대)","🔁 daily (FREE)",
 "A 1,150 m suspension bridge with a free hilltop observatory looking over the harbour, the shipyard and the industrial complex",
 "Observatory daily **09:00–22:00** (Nov: from 10:00)",
 "**FREE**",
 "[ulsan.go.kr](https://www.ulsan.go.kr) · [Dong-gu Ulsan](https://www.donggu.ulsan.kr)",
 "**The single best free viewpoint in Ulsan**, day or night. Bus or taxi up the hill."),

("⛰️","Yeongnam Alps — Sinbulsan & Ganwolsan (영남알프스)","🔁 daily (FREE)",
 "A cluster of nine peaks over 1,000 m south-west of Ulsan, famous for vast **silver grass fields on the Sinbulsan and Ganwolsan plateaus**",
 "Always open; start early",
 "**FREE**",
 "[ulsan.go.kr](https://www.ulsan.go.kr) · [Korea Forest Service](https://www.forest.go.kr)",
 "**Silver grass peaks in October and holds into early November** — one of Korea's great autumn landscapes."),

("🌾","Ganwoljae Silver Grass Field (간월재 억새평원)","🔁 daily (FREE)",
 "A high saddle between Ganwolsan and Sinbulsan covered in 100 hectares of silver grass, reachable by a well-graded 4 km trail",
 "Always open; allow 4–5 hours return",
 "**FREE**",
 "[ulsan.go.kr](https://www.ulsan.go.kr) · [Korea Forest Service](https://www.forest.go.kr)",
 "**The most photographed autumn landscape in Yeongnam.** A shelter at the saddle sells hot ramyeon."),

("🚡","Yeongnam Alps Eonyang Cable Car (영남알프스 복합웰컴센터)","🔁 daily",
 "The Yeongnam Alps Welcome Center with its cable car up toward Sinbulsan, cutting most of the climb to the silver grass",
 "Daily **09:00–17:30** (Nov: to 17:00)",
 "Round trip around **₩15,000**",
 "[ulsan.go.kr](https://www.ulsan.go.kr) · [Ulju-gun](https://www.ulju.ulsan.kr)",
 "**Check operating status** — the cable car has had extended maintenance closures. Confirm before travelling."),

("🛕","Tongdosa Temple — UNESCO Sansa (통도사)","🔁 daily",
 "One of Korea's **Three Jewel Temples** and a **UNESCO World Heritage Sansa**, founded 646 CE, holding relics of the Buddha in place of a statue",
 "Daily **08:30–17:30** (Nov: to 17:00)",
 "Adult **₩3,000**",
 "[UNESCO](https://whc.unesco.org/en/list/1562) · [tongdosa.or.kr](http://www.tongdosa.or.kr)",
 "Technically in Yangsan, 30 minutes from Ulsan. **The 1 km pine approach avenue is superb in November.**"),

("🍂","Seoknamsa Temple & Gajisan (석남사)","🔁 daily",
 "A 9th-century nunnery on Gajisan, the highest of the Yeongnam Alps, at the end of one of Ulsan's best autumn valleys",
 "Daily **08:00–18:00** (Nov: to 17:00)",
 "Adult **₩2,000**",
 "[ulsan.go.kr](https://www.ulsan.go.kr) · [Ulju-gun](https://www.ulju.ulsan.kr)",
 "Bus 807 from Ulsan. **The valley walk to the temple is the point** — it's a well-known foliage route."),

("🎋","Taehwa River National Garden Bamboo Grove (태화강 십리대숲)","🔁 daily (FREE)",
 "**Korea's second National Garden**: a 4 km riverside bamboo forest through the middle of Ulsan, with lit night paths",
 "Always open; night lighting to **22:00**",
 "**FREE**",
 "[ulsan.go.kr](https://www.ulsan.go.kr) · [Korea Forest Service](https://www.forest.go.kr)",
 "**Ulsan's signature sight and completely free.** Walk in from Taehwagang Station."),

("🐦","Taehwa River Rookery & Winter Bird Roost","👀 WATCH — Nov peak",
 "Tens of thousands of **rooks and daurian jackdaws roost along the Taehwa each winter**, arriving from October and swarming at dusk",
 "Best at dusk, roughly **17:00–18:00** in November",
 "**FREE**",
 "[ulsan.go.kr](https://www.ulsan.go.kr) · [me.go.kr](https://www.me.go.kr)",
 "**November is peak season for this** — the dusk murmuration over the river is a genuine spectacle."),

("🦅","Taehwa River Ecology & Otter Habitat","🔁 daily (FREE)",
 "The Taehwa was one of Korea's most polluted rivers in the 1990s and is now clean enough for otters, salmon and egrets — a flagship restoration",
 "Always open",
 "**FREE**",
 "[ulsan.go.kr](https://www.ulsan.go.kr) · [me.go.kr](https://www.me.go.kr)",
 "Interpretive panels along the path explain the clean-up. Ulsan is proud of this, rightly."),

("🌷","Taehwa River Garden Flower Fields & Events","🔁 daily (FREE)",
 "Seasonal flower plantings across the national garden's meadows, with autumn cosmos and pink muhly typically running into early November",
 "Always open",
 "**FREE**",
 "[ulsan.go.kr](https://www.ulsan.go.kr)",
 "**Pink muhly grass usually peaks mid-October to early November** — check the city site for the current display."),

("🏛️","Ulsan Museum (울산박물관)","🔁 Tue–Sun (FREE)",
 "The city museum covering Ulsan from the petroglyph era to the Hyundai industrial boom, with a large industrial history hall",
 "Tue–Sun **09:00–18:00** (closed Mon)",
 "**FREE**",
 "[museum.ulsan.go.kr](https://museum.ulsan.go.kr)",
 "In Ulsan Grand Park. **The industrialisation gallery is the most interesting part** and unusual among Korean museums."),

("🌳","Ulsan Grand Park (울산대공원)","🔁 daily (FREE)",
 "**Korea's largest urban park**, 3.6 km², donated by SK Group, with a rose garden, a butterfly house, a zoo and long walking trails",
 "Always open; facilities **09:00–18:00**",
 "Park **FREE**; zoo ₩3,000",
 "[ulsan.go.kr](https://www.ulsan.go.kr)",
 "Bus from downtown. **Free, huge and genuinely well-maintained.**"),

("🎢","Ulsan Grand Park Zoo & Botanical Facilities","🔁 daily",
 "The park's zoo, butterfly ecology hall and rose garden — cheap family facilities inside a free park",
 "Daily **09:30–18:00** (Nov: to 17:00)",
 "Zoo adult **₩3,000**; child ₩1,000",
 "[ulsan.go.kr](https://www.ulsan.go.kr)",
 "The butterfly house is warm — useful on a cold November day."),

("🏛️","Ulsan Art Museum (울산시립미술관)","🔁 Tue–Sun",
 "Ulsan's city art museum, opened 2022 on the old Confucian school site, specialising in **media and XR art**",
 "Tue–Sun **10:00–19:00** (closed Mon)",
 "Often **FREE**; specials ₩3,000",
 "[ulsan.go.kr](https://www.ulsan.go.kr)",
 "Downtown near Ulsan Jungang. Built over an excavated Joseon site visible under glass in the basement."),

("🏯","Ulsan Oesong & Ulsan Japanese Castle (울산왜성)","🔁 daily (FREE)",
 "The remains of the 1597 Japanese fortress built during the Imjin War, site of the brutal Siege of Ulsan, now a hilltop park",
 "Always open",
 "**FREE**",
 "[ulsan.go.kr](https://www.ulsan.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "Central Ulsan, walkable from downtown. Cherry trees and a city view; almost no visitors."),

("🐟","Ulsan Jujeon Beach & Pebble Coast (주전몽돌해변)","🔁 daily (FREE)",
 "A 1.5 km beach of black pebbles rather than sand, which rattle audibly as the waves pull back",
 "Always open",
 "**FREE**",
 "[Dong-gu Ulsan](https://www.donggu.ulsan.kr) · [ulsan.go.kr](https://www.ulsan.go.kr)",
 "North of Daewangam on the coast road. **The sound of the pebbles is the reason to come.**"),

("🌅","Ganjeolgot Cape — Korea's first mainland sunrise (간절곶)","🔁 daily (FREE)",
 "**The point on the Korean mainland that sees the sunrise earliest**, with a lighthouse, a giant postbox and a wide grass headland",
 "Always open",
 "**FREE**",
 "[Ulju-gun](https://www.ulju.ulsan.kr) · [ulsan.go.kr](https://www.ulsan.go.kr)",
 "Bus 715 from Ulsan. **Sunrise is around 07:05 in mid-November** — a realistic early start."),

("💌","Ganjeolgot Giant Postbox & Lighthouse","🔁 daily (FREE)",
 "A 5 m working postbox at Ganjeolgot where you can post a letter for delivery, beside the 1920 lighthouse",
 "Always open; lighthouse grounds daylight",
 "**FREE** (stamps extra)",
 "[Ulju-gun](https://www.ulju.ulsan.kr) · [koreapost.go.kr](https://www.koreapost.go.kr)",
 "**Postcards are sold at the visitor centre** — genuinely collected and delivered."),

("🏖️","Jinha Beach & Myeongseondo (진하해수욕장)","🔁 daily (FREE)",
 "A wide sandy beach in southern Ulsan with a small island reachable on foot at low tide, popular for windsurfing",
 "Always open",
 "**FREE**",
 "[Ulju-gun](https://www.ulju.ulsan.kr) · [ulsan.go.kr](https://www.ulsan.go.kr)",
 "**Check the tide table** if you want to walk out to Myeongseondo."),

("🦀","Ulsan Seafood — Jangsaengpo & Bangeojin ports","🔁 daily",
 "Ulsan's fish markets at Bangeojin and Jangsaengpo, strong on snow crab, hairtail and East Sea whitefish",
 "Roughly **06:00–20:00**",
 "Sashimi platter **₩40,000–₩70,000**",
 "[ulsan.go.kr](https://www.ulsan.go.kr) · [Dong-gu Ulsan](https://www.donggu.ulsan.kr)",
 "**Buy fish downstairs, pay a small fee to have it cut and served upstairs** — the standard Korean port routine."),

("🍲","Ulsan Specialities — gomjangeo & eonyang bulgogi","🔁 daily",
 "Ulsan's two signature dishes: **Eonyang bulgogi**, hand-chopped charcoal-grilled beef, and *gomjangeo* hagfish grilled at Jangsaengpo",
 "Most **11:00–22:00**",
 "Eonyang bulgogi **₩25,000–₩40,000**",
 "[ulsan.go.kr](https://www.ulsan.go.kr) · [visitkorea.or.kr](https://english.visitkorea.or.kr)",
 "**Eonyang bulgogi is the one to try** — a designated regional speciality with a dedicated restaurant street in Eonyang."),

("🍜","Ulsan Traditional Markets — Jungang & Sinjeong","🔁 daily",
 "Ulsan's downtown markets, with a covered arcade, a food alley and the everyday commerce of an industrial city",
 "Roughly **08:00–20:00**",
 "**FREE** to browse",
 "[ulsan.go.kr](https://www.ulsan.go.kr)",
 "Ulsan Jungang area. Cheap, unglamorous and completely local."),

("⚽","Ulsan HD FC — K League 1 (울산HD)","👀 WATCH — season ends Nov/Dec",
 "**Reigning multiple-time K League champions**, playing at Munsu Football Stadium; the season's final rounds fall in late November",
 "Kick-off typically **14:00** or **19:00**",
 "Tickets from **₩12,000**",
 "[uhfc.tv](https://www.uhfc.tv) · [kleague.com](https://www.kleague.com)",
 "**Ulsan is one of Korea's strongest clubs** — check the K League November 2026 fixture list. Munsu is a superb football-specific ground."),

("🏟️","Munsu Football Stadium (문수축구경기장)","🔁 daily (FREE outside matches)",
 "A 44,000-seat 2002 World Cup venue, widely considered one of Korea's best-designed stadiums, set against a wooded hillside",
 "Grounds always open",
 "**FREE** to view",
 "[uhfc.tv](https://www.uhfc.tv) · [ulsan.go.kr](https://www.ulsan.go.kr)",
 "Bus from downtown. The surrounding sports park has free trails and courts."),

("🏀","Ulsan Hyundai Mobis Phoebus — KBL basketball","👀 WATCH — season runs Oct–Apr",
 "**One of the KBL's most successful franchises**, playing at Dongchun Gymnasium through the winter season",
 "Tip-off typically **19:00**",
 "Tickets from **₩8,000**",
 "[kbl.or.kr](https://www.kbl.or.kr) · [hyundai-mobisbasketball.com](https://www.hyundai-mobisbasketball.com)",
 "**The KBL season is fully underway in November** — a reliable indoor evening option."),

("🚄","Getting to Ulsan — KTX & Ulsan Airport","🔁 daily",
 "Ulsan Station (Ulsan-KTX) is on the Gyeongbu high-speed line, about 2 h 15 from Seoul; Ulsan Airport serves Gimpo and Jeju",
 "Trains roughly **05:30–22:30**",
 "KTX from Seoul **₩53,500**",
 "[letskorail.com](https://www.letskorail.com) · [airport.co.kr](https://www.airport.co.kr)",
 "**Ulsan KTX Station is 20 km west of the city centre** — allow 40 minutes on the limousine bus."),

("🚌","Ulsan City Buses & Regional Connections","🔁 daily",
 "Ulsan has no metro; the city runs an extensive bus network, plus frequent intercity buses to Busan (1 h) and Gyeongju (50 min)",
 "Roughly **05:30–23:00**",
 "City bus **₩1,500**; Busan ₩5,500",
 "[its.ulsan.kr](https://its.ulsan.kr) · [ulsan.go.kr](https://www.ulsan.go.kr)",
 "**T-money and Cashbee both work.** Ulsan is an easy add-on between Busan and Gyeongju."),
]

append("/home/user/KoreaFun/ulsan.md", E, 140, 3,
       "\n---\n\n## 🧭 Beginner-friendly essentials", "Ulsan",
       intro="**Verified expansion set** — the newly UNESCO-inscribed Bangudae petroglyphs, whaling heritage, Yeongnam Alps silver grass, the Taehwa National Garden, industrial Ulsan, coast and sport.")
