# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "/home/user/KoreaFun/.build")
from addlib import append

E = [
("🖌️","Ulsan Public Art Programme — Shepard Fairey, Vhils, JonOne","🔁 daily (FREE)",
 "To mark the 2025 UNESCO inscription, Ulsan commissioned murals and sculptures from international street artists including **Shepard Fairey, Vhils and JonOne**",
 "Always visible",
 "**FREE**",
 "[ulsan.go.kr](https://www.ulsan.go.kr)",
 "Works are spread across the city centre and Jangsaengpo. **Ask at the tourist office for the current public-art map.**"),

("🏞️","Bangucheon Stream Valley Walk & Banguseowon (반구서원)","🔁 daily (FREE)",
 "The valley containing both UNESCO petroglyph panels also holds Banguseowon, a Confucian academy honouring scholars exiled here",
 "Always open",
 "**FREE**",
 "[ulsan.go.kr](https://www.ulsan.go.kr) · [Ulju-gun](https://www.ulju.ulsan.kr)",
 "**A 4 km walk links the museum, Bangudae and Cheonjeon-ri** — the best way to see the whole UNESCO property."),

("🚌","Getting to the Bangudae petroglyphs","🔁 daily",
 "The UNESCO site is in rural Ulju County; bus 807 or 1713 from Ulsan runs to Eonyang, then a local bus or taxi covers the last stretch",
 "Buses roughly **06:00–21:00**",
 "Bus **₩1,500**; taxi from Eonyang ₩12,000",
 "[its.ulsan.kr](https://its.ulsan.kr) · [ulsan.go.kr](https://www.ulsan.go.kr)",
 "**Allow a full half-day.** Public transport is sparse — a taxi from Eonyang is the practical choice."),

("🏛️","Ulsan Daegok Museum (울산대곡박물관)","🔁 Tue–Sun (FREE)",
 "A museum of the Daegokcheon valley's history from prehistory through Silla to the Joseon period, beside the petroglyph site",
 "Tue–Sun **09:00–18:00** (closed Mon)",
 "**FREE**",
 "[ulsan.go.kr](https://www.ulsan.go.kr)",
 "Combine with the Petroglyph Museum — both are free and 10 minutes apart."),

("⛰️","Sinbulsan Falls & Ulju Mountain Trails (신불산폭포)","🔁 daily (FREE)",
 "Waterfall and gorge trails on the Ulsan side of the Yeongnam Alps, including the Paraeso Falls and the Jakcheonjeong valley",
 "Always open",
 "**FREE**",
 "[Ulju-gun](https://www.ulju.ulsan.kr) · [Korea Forest Service](https://www.forest.go.kr)",
 "**Paraeso Falls is the most accessible** — a 30-minute walk from the car park."),

("🏕️","Yeongnam Alps Welcome Center & Sky Trails","🔁 daily",
 "Ulju County's mountain gateway complex, with an observatory, a planetarium, hiking information and a camping area",
 "Daily **09:00–18:00**",
 "Facilities **FREE**–₩5,000",
 "[Ulju-gun](https://www.ulju.ulsan.kr) · [ulsan.go.kr](https://www.ulsan.go.kr)",
 "The obvious starting point for any Yeongnam Alps hike. Free maps and English trail advice."),

("🎬","Ulju Mountain Film Festival & Mountain Culture","👀 WATCH — usually September",
 "Korea's dedicated mountain film festival, held annually in Ulju at the foot of the Yeongnam Alps",
 "By event",
 "Screenings from **₩5,000**",
 "[umff.kr](https://www.umff.kr) · [Ulju-gun](https://www.ulju.ulsan.kr)",
 "**Normally September** — outside your window, but the festival park and its trails are open year-round."),

("🌲","Ulsan Daewangam Pine Forest & Songrim-gil","🔁 daily (FREE)",
 "The 15,000 black pines planted at Daewangam over a century ago, forming a shaded avenue out to the sea rocks",
 "Always open",
 "**FREE**",
 "[Dong-gu Ulsan](https://www.donggu.ulsan.kr)",
 "**Designated one of Korea's most beautiful forests.** The walk from the gate to the rocks takes 20 minutes."),

("🚶","Ulsan Haemaji-gil Coastal Trail (해맞이길)","🔁 daily (FREE)",
 "The coastal walking route linking Ilsan Beach, Daewangam and Jujeon pebble beach along the Dong-gu shoreline",
 "Always open",
 "**FREE**",
 "[Dong-gu Ulsan](https://www.donggu.ulsan.kr) · [ulsan.go.kr](https://www.ulsan.go.kr)",
 "About 8 km end to end. **Cool clear November days are ideal for this.**"),

("🐠","Ulsan Bangeojin Port & Fish Market (방어진항)","🔁 daily",
 "A working fishing port on the Dong-gu peninsula, with an auction hall, a raw-fish market and a lighthouse walk",
 "Auction from **05:00**; market **08:00–20:00**",
 "**FREE** to browse",
 "[Dong-gu Ulsan](https://www.donggu.ulsan.kr)",
 "Bangeojin means 'yellowtail port'. **The dawn auction is open to watch.**"),

("🌊","Slow City Ulju & Seosaengpo Fortress (서생포왜성)","🔁 daily (FREE)",
 "The best-preserved Japanese-built fortress in Korea, constructed 1592–93 on a hill over the coast in southern Ulsan",
 "Always open",
 "**FREE**",
 "[Ulju-gun](https://www.ulju.ulsan.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "Near Jinha Beach. **Multiple concentric stone walls still standing** — remarkable and almost unvisited."),

("🚂","Ulsan Coastal Rail & Namchang Old Station","🔁 daily (FREE)",
 "Disused sections of the old Donghae coastal railway in southern Ulsan, converted into walking and cycling paths",
 "Always open",
 "**FREE**",
 "[ulsan.go.kr](https://www.ulsan.go.kr) · [Ulju-gun](https://www.ulju.ulsan.kr)",
 "The Namchang station building is preserved as a small heritage stop."),

("🍶","Eonyang Bulgogi Street (언양불고기거리)","🔁 daily",
 "The Eonyang district where Ulsan's designated regional beef dish originated, with a dozen specialists on one street",
 "Most **11:00–21:30**",
 "**₩25,000–₩45,000** per person",
 "[Ulju-gun](https://www.ulju.ulsan.kr) · [ulsan.go.kr](https://www.ulsan.go.kr)",
 "**Combine with the petroglyph trip** — Eonyang is the town you change buses in anyway."),

("🥘","Ulsan Bongye Hanwoo Beef Village (봉계한우마을)","🔁 daily",
 "A whole village in Ulju given over to Korean hanwoo beef, where you buy raw cuts from a butcher and pay a small grilling fee",
 "Most **11:00–21:00**",
 "Beef from **₩35,000** per 200 g plus ₩5,000 table fee",
 "[Ulju-gun](https://www.ulju.ulsan.kr) · [ulsan.go.kr](https://www.ulsan.go.kr)",
 "**Substantially cheaper than a restaurant** for the same quality. Bus or taxi from Eonyang."),

("🍚","Ulsan Everyday Food — dolgorae & haejangguk","🔁 daily",
 "Ulsan's working-city food: hangover soups near the industrial gates, cheap set lunches and shift-worker restaurants open at odd hours",
 "Many **24 hours**",
 "**₩8,000–₩12,000**",
 "[ulsan.go.kr](https://www.ulsan.go.kr)",
 "**The area around the Hyundai plant gates has 24-hour food** because of the shift patterns."),

("☕","Ulsan Cafe Streets — Samsan-dong & Taehwa-dong","🔁 daily",
 "Ulsan's cafe and shopping districts, with Samsan-dong the main downtown commercial core and Taehwa-dong the riverside quarter",
 "Roughly **10:00–22:00**",
 "Coffee **₩5,000**",
 "[ulsan.go.kr](https://www.ulsan.go.kr)",
 "Samsan-dong has the department stores and the largest restaurant concentration."),

("🛍️","Ulsan Department Stores & Shopping","🔁 daily",
 "Lotte and Hyundai department stores in Samsan-dong, plus large discount stores — the practical shopping options in Ulsan",
 "Daily **10:30–20:00**",
 "**FREE** entry",
 "[lotteshopping.com](https://www.lotteshopping.com) · [ehyundai.com](https://www.ehyundai.com)",
 "Tax-free counters available for foreign passports."),

("🎭","Ulsan Culture & Arts Center (울산문화예술회관)","🔁 by programme",
 "Ulsan's main concert and theatre venue, home to the Ulsan Philharmonic and a full autumn season",
 "Box office **09:00–18:00**; shows **19:30**",
 "**₩10,000–₩60,000**",
 "[ucac.or.kr](https://www.ucac.or.kr) · [ulsan.go.kr](https://www.ulsan.go.kr)",
 "Beside Ulsan Grand Park. **Check the November 2026 programme when you book.**"),

("🎪","Ulsan Whale Festival & City Event Calendar","👀 WATCH",
 "Ulsan's festival year includes the Whale Festival at Jangsaengpo, the Taehwa River Grand Park events and the Ulsan Fireworks Festival",
 "By event",
 "Many **FREE**",
 "[ulsan.go.kr](https://www.ulsan.go.kr) · [whalecity.kr](https://www.whalecity.kr)",
 "**Most Ulsan festivals fall between April and October** — check the city calendar for anything in your November window."),

("🎆","Ulsan Taehwa River Winter Lighting","👀 WATCH (from late Nov)",
 "The national garden and downtown bridges are typically lit for winter from late November into the new year",
 "Evenings once lit",
 "**FREE**",
 "[ulsan.go.kr](https://www.ulsan.go.kr)",
 "**Switch-on is usually around the end of November** — possibly right at the edge of your window."),

("🏊","Ulsan Sports Facilities & Public Pools","🔁 daily",
 "Ulsan's municipal sports complexes offer cheap public swimming, gyms and courts — a legacy of the industrial welfare system",
 "Roughly **06:00–21:00**",
 "Pool **₩4,000–₩6,000**",
 "[ulsan.go.kr](https://www.ulsan.go.kr)",
 "Bring a swimming cap — mandatory in all Korean public pools."),

("🚴","Taehwa River Cycle Path & Ulsan Bike Routes","🔁 daily (FREE)",
 "A continuous riverside cycle path from the mountains to the sea along the Taehwa, part of the national bike network",
 "Always open",
 "**FREE**; rental from ₩10,000/day",
 "[riverguide.go.kr](https://www.riverguide.go.kr) · [ulsan.go.kr](https://www.ulsan.go.kr)",
 "Flat and separated. **The bamboo grove section is the highlight.**"),

("♨️","Ulsan Hot Springs — Ganwol & Deoksan","🔁 daily",
 "Natural hot spring bathhouses in Ulju County at the foot of the Yeongnam Alps, useful after a mountain day",
 "Roughly **06:00–20:00**",
 "**₩8,000–₩12,000**",
 "[Ulju-gun](https://www.ulju.ulsan.kr) · [ulsan.go.kr](https://www.ulsan.go.kr)",
 "**The obvious end to a Ganwoljae hike.** Towels are usually rentable for ₩1,000."),

("🏨","Ulsan Accommodation — where to base yourself","🔁 planning",
 "Samsan-dong for downtown convenience, Dong-gu for the coast and Daewangam, Eonyang for the petroglyphs and mountains",
 "Check-in typically **15:00**",
 "From **₩50,000** per night",
 "[ulsan.go.kr](https://www.ulsan.go.kr) · [visitkorea.or.kr](https://english.visitkorea.or.kr)",
 "**Ulsan is a business city** — hotel rates drop noticeably at weekends."),

("🧭","Ulsan Tourist Information & English Support","🔁 daily (FREE)",
 "Information centres at Ulsan KTX Station, the express bus terminal and Taehwa River park, with free maps and English staff",
 "Daily **09:00–18:00**",
 "**FREE**",
 "[ulsan.go.kr](https://www.ulsan.go.kr) · [1330 Hotline](https://english.visitkorea.or.kr)",
 "**Dial 1330 for free 24-hour English tourist help.** Ulsan sees few foreign visitors, so the offices are helpful and unhurried."),

("🗺️","Ulsan combined with Gyeongju & Busan","🔁 planning",
 "Ulsan sits between Gyeongju (50 min) and Busan (1 h), making a three-city loop straightforward by bus or train",
 "Daily",
 "Bus fares **₩5,000–₩6,500**",
 "[kobus.co.kr](https://www.kobus.co.kr) · [letskorail.com](https://www.letskorail.com)",
 "**Gyeongju in the morning, Ulsan petroglyphs in the afternoon** is a workable single day if you start early."),

("📅","Ulsan November Weather & What's Realistic","🔁 seasonal",
 "Ulsan in November runs **5–17 °C**, milder than inland Korea, dry and often clear — good for coast walks and mountain hiking",
 "N/A",
 "**FREE**",
 "[weather.go.kr](https://www.weather.go.kr) · [ulsan.go.kr](https://www.ulsan.go.kr)",
 "**Coastal wind is the main factor** — the cable car and boat trips are the things that get cancelled."),

("🎯","Ulsan one-day model route","🔁 planning",
 "Taehwa bamboo grove morning → Ulsan Museum → Jangsaengpo whale village → Ulsan Bridge observatory at dusk → Samsan-dong dinner",
 "Full day",
 "About **₩25,000** including admissions",
 "[ulsan.go.kr](https://www.ulsan.go.kr)",
 "**Add a second day for the UNESCO petroglyphs and the Yeongnam Alps** — they're in the opposite direction from the coast."),

("🌏","Ulsan Foreign Resident Services & Global Center","🔁 weekdays (FREE)",
 "Ulsan's large industrial workforce includes many foreign residents; the Global Center offers free interpretation and advice",
 "Weekdays **09:00–18:00**",
 "**FREE**",
 "[ulsan.go.kr](https://www.ulsan.go.kr)",
 "Useful for anything administrative. For tourism questions, 1330 is faster."),

("🚑","Ulsan Emergency & Medical Services","🔁 24 h",
 "Ulsan University Hospital and several large general hospitals run 24-hour emergency departments with some English capability",
 "Emergency **24 h**",
 "Consultation from **₩20,000** for visitors",
 "[uuh.ulsan.kr](https://www.uuh.ulsan.kr) · [1339 Medical Hotline](https://www.kdca.go.kr)",
 "**119 for ambulance, 1339 for medical advice in English.**"),
]

append("/home/user/KoreaFun/ulsan.md", E, 181, 3,
       "\n---\n\n## 🧭 Beginner-friendly essentials", "Ulsan")
