# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "/home/user/KoreaFun/.build")
from addlib import append

E = [
("🎢","Everland Resort — Korea's largest theme park","🔁 daily",
 "**Korea's biggest theme park**, opened 1976, with five themed zones, the wooden coaster T Express and a large zoo",
 "Daily **10:00–21:00** (Nov: often to 20:00)",
 "Adult 1-day **₩68,000**; after-4pm ticket cheaper",
 "[everland.com](https://www.everland.com)",
 "**Buy online — gate prices are the highest.** Free shuttle from Gangnam and Jamsil in Seoul."),

("🎃","Everland Autumn & Halloween Season","👀 WATCH — season overlap",
 "Everland runs a large-scale Halloween season through October and a **Christmas Fantasy season from mid-November**, with parades and full-park illumination",
 "Park hours; parades typically **19:00**",
 "Included with admission",
 "[everland.com](https://www.everland.com)",
 "**Your window catches the changeover** — check the site for the Christmas season start date."),

("🌷","Everland Four Seasons Garden & Autumn Chrysanthemums","✅ CONFIRMED — Nov",
 "Everland's central garden stages a large **autumn chrysanthemum and maple display through November**, one of the park's signature seasonal set-pieces",
 "Park hours",
 "Included with admission",
 "[everland.com](https://www.everland.com)",
 "**The autumn garden is genuinely the best part of Everland in November** — better than queuing for rides."),

("🎢","T Express & Everland's headline rides","🔁 daily",
 "**T Express is one of the world's steepest wooden coasters** at 77 degrees, alongside the Amazon Express rapids and the Rolling X-Train",
 "Park hours",
 "Included with admission",
 "[everland.com](https://www.everland.com)",
 "**Ride T Express first thing** — the queue reaches two hours by midday even off-season."),

("🐼","Everland Zootopia & Panda World","🔁 daily",
 "Everland's zoo section, including **Panda World**, home to the giant pandas Ai Bao and Le Bao and their Korean-born cubs",
 "Park hours",
 "Included with admission",
 "[everland.com](https://www.everland.com)",
 "**Fu Bao's birth in 2020 made Panda World a national phenomenon.** Expect queues at Panda World specifically."),

("🦁","Everland Lost Valley Safari","🔁 daily (weather-dependent)",
 "An amphibious safari vehicle route through a mixed-species enclosure with giraffes, elephants and lions",
 "Park hours; suspended in bad weather",
 "Included with admission",
 "[everland.com](https://www.everland.com)",
 "**Suspends in heavy rain or cold snaps** — check on arrival."),

("🏎️","Everland Speedway & Korea International Circuit events","👀 WATCH — check calendar",
 "The motorsport circuit beside Everland hosts Korean touring car and endurance rounds",
 "By event",
 "From **₩20,000**",
 "[everland.com](https://www.everland.com) · [kmsa.or.kr](https://www.kmsa.or.kr)",
 "**Check the autumn race calendar** — the season typically closes in November."),

("🏯","Korean Folk Village (한국민속촌)","🔁 daily",
 "**Over 260 relocated and reconstructed Joseon-era buildings** across a large open-air site, with live performances of farmers' music, tightrope walking and equestrian arts",
 "Daily **10:00–18:00** (Nov: to 18:00, last entry 17:00)",
 "Adult **₩32,000** full pass; ₩25,000 entry only",
 "[koreanfolk.co.kr](https://www.koreanfolk.co.kr)",
 "**The best single sight in Yongin.** Free shuttle from Suwon Station; performances run to a fixed daily timetable — get it at the gate."),

("🤹","Korean Folk Village performances — farmers' music, tightrope, equestrian","🔁 daily",
 "Scheduled daily shows including *nongak* farmers' band music, *jultagi* tightrope walking (**UNESCO Intangible Heritage**) and Joseon cavalry displays",
 "Shows roughly **11:00–16:00**, several daily",
 "Included with admission",
 "[koreanfolk.co.kr](https://www.koreanfolk.co.kr) · [UNESCO ICH](https://ich.unesco.org)",
 "**Jultagi tightrope walking was inscribed by UNESCO in 2011.** The performer talks and jokes throughout — that's the art form."),

("👰","Korean Folk Village traditional wedding & seasonal events","🔁 daily",
 "Re-enacted Joseon wedding ceremonies, coming-of-age rites and a seasonal autumn harvest programme",
 "Scheduled through the day",
 "Included with admission",
 "[koreanfolk.co.kr](https://www.koreanfolk.co.kr)",
 "**November is harvest and kimjang season** at the village — check the seasonal programme."),

("🎭","Korean Folk Village Market Street & Nostalgia Zone","🔁 daily",
 "The village's traditional market street with period food stalls, plus a recreated 1970s–80s street",
 "Village hours",
 "Food **₩5,000–₩15,000**",
 "[koreanfolk.co.kr](https://www.koreanfolk.co.kr)",
 "**Eat here rather than outside** — the market-street food is part of the experience."),

("🏰","Yongin Daejanggeum Park / MBC Dramia (대장금파크)","🔁 Wed–Mon",
 "**Korea's largest historical drama set**, built by MBC across 2.5 million m², with Goguryeo, Silla and Joseon palace sets used for *Dae Jang Geum*, *Dong Yi* and *Moon Embracing the Sun*",
 "Wed–Mon **09:00–18:00** (Nov: to 17:00); closed Tue",
 "Adult **₩9,500**",
 "[djgpark.imbc.com](https://djgpark.imbc.com)",
 "**Closed Tuesdays.** Filming can close individual sets without notice — check before travelling."),

("🌿","Hwadam Forest / Hwadam Botanic Garden (화담숲)","👀 WATCH — season closes",
 "A 165,000 m² mountain botanical garden with 4,000 plant species, famous nationally for its **maple season and monorail through the canopy**",
 "Season typically **March–mid November**, **08:30–18:00**",
 "Adult **₩11,000**; monorail ₩8,000",
 "[hwadamsup.com](https://www.hwadamsup.com)",
 "**Reservation-only in peak autumn and the season closes in mid-November** — book online the moment you fix dates, and confirm the closing date."),

("🍁","Hwadam Forest Autumn Maple Season","✅ CONFIRMED — Oct–early Nov",
 "Hwadam's maple season is one of Korea's most sought-after autumn tickets, with timed entry and a monorail running through the colour",
 "Peak roughly **late October–early November**",
 "Adult **₩11,000** plus timed reservation",
 "[hwadamsup.com](https://www.hwadamsup.com)",
 "**The very start of your window is the tail of peak colour.** Tickets sell out weeks ahead."),

("🖼️","Ho-Am Art Museum (호암미술관)","🔁 Tue–Sun",
 "The Samsung foundation's museum of Korean traditional art beside Everland, with a **traditional Korean garden, Hee Won**, and a major collection of Buddhist art and ceramics",
 "Tue–Sun **10:00–18:00** (closed Mon)",
 "Adult **₩14,000**",
 "[hoammuseum.org](https://hoam.samsungfoundation.org)",
 "**Hee Won garden is worth the ticket by itself in autumn.** Book timed entry online."),

("🏛️","Gyeonggi Provincial Museum (경기도박물관)","🔁 Tue–Sun (FREE)",
 "The provincial museum in Yongin, covering Gyeonggi-do's history from prehistory through the Joseon court, with English labelling",
 "Tue–Sun **10:00–18:00** (closed Mon)",
 "**FREE**",
 "[musenet.ggcf.kr](https://musenet.ggcf.kr)",
 "**Free, large and rarely crowded.** Part of the Yongin museum cluster with the Baekunsan sites."),

("🎵","Gyeonggi Provincial Gugak Center","👀 WATCH — check programme",
 "The province's traditional-music institution, staging *gugak* concerts, *pansori* and fusion performances",
 "Box office **09:00–18:00**",
 "**FREE**–₩30,000",
 "[ggcf.kr](https://www.ggcf.kr) · [gugak.go.kr](https://www.gugak.go.kr)",
 "**Many performances are free** — check the November calendar."),

("🏛️","Gyeonggi Children's Museum, Yongin","🔁 Tue–Sun",
 "A large hands-on children's museum on the provincial museum campus, with timed sessions",
 "Tue–Sun **10:00–18:00** (closed Mon)",
 "Child **₩7,000**; adult ₩4,000",
 "[gcmuseum.ggcf.kr](https://gcmuseum.ggcf.kr)",
 "**Timed-entry sessions and often fully booked at weekends** — reserve online."),

("🛕","Waujeongsa Temple & the giant Buddha head (와우정사)","🔁 daily",
 "A modern temple on Yeonhwasan holding a **62 m reclining Buddha carved from a single juniper log** and an 8 m stone Buddha head",
 "Daily **07:00–19:00**",
 "**FREE**",
 "[yongin.go.kr](https://www.yongin.go.kr)",
 "**Genuinely strange and photogenic** — an eclectic mix of Buddhist traditions from across Asia."),

("⛰️","Gwanggyosan & Yongin Hiking Trails (광교산)","🔁 daily (FREE)",
 "The 582 m mountain shared between Yongin and Suwon, with well-graded ridge trails and autumn colour",
 "Always open",
 "**FREE**",
 "[yongin.go.kr](https://www.yongin.go.kr) · [Korea Forest Service](https://www.forest.go.kr)",
 "**Accessible by Sinbundang Line to Gwanggyo** — three to four hours for the ridge."),

("🌲","Yongin Jayeon Hyuyangnim & Recreational Forests","🔁 daily",
 "National and municipal recreation forests around Yongin with forest-bathing paths, decks and cabins",
 "Daily **09:00–18:00**",
 "Entry **₩1,000–₩3,000**",
 "[Korea Forest Service](https://www.forest.go.kr) · [yongin.go.kr](https://www.yongin.go.kr)",
 "Quiet on weekdays in November."),

("🚶","Yongin Dulle-gil Circuit Trails","🔁 daily (FREE)",
 "Yongin's signed circuit walking network linking the city's hills, reservoirs and villages in graded sections",
 "Always open",
 "**FREE**",
 "[yongin.go.kr](https://www.yongin.go.kr) · [durunubi.kr](https://www.durunubi.kr)",
 "Maps and GPS tracks on the Durunubi national trail portal."),

("🏞️","Yongin Jeongmongju Tomb & Confucian sites (정몽주 묘)","🔁 daily (FREE)",
 "The tomb of **Jeong Mong-ju**, the Goryeo loyalist assassinated in 1392 for refusing to serve the new Joseon dynasty — a national symbol of loyalty",
 "Daylight hours",
 "**FREE**",
 "[Korea Heritage Service](https://www.khs.go.kr) · [yongin.go.kr](https://www.yongin.go.kr)",
 "**His poem refusing to switch allegiance is memorised by every Korean schoolchild.** Quiet, dignified and free."),

("🏛️","Simgok Seowon & Yongin Confucian academies","🔁 daily (FREE)",
 "Yongin's Confucian academies and shrines, including sites associated with the Joseon scholar-official tradition",
 "Daylight hours",
 "**FREE**",
 "[Korea Heritage Service](https://www.khs.go.kr) · [yongin.go.kr](https://www.yongin.go.kr)",
 "Small, uncrowded and usually combined with the Jeong Mong-ju tomb."),

("🏛️","Yongin Mureung & local heritage houses","🔁 daily (FREE)",
 "Preserved Joseon *hanok* residences and clan halls scattered through Yongin's older villages",
 "Daylight hours",
 "**FREE**",
 "[yongin.go.kr](https://www.yongin.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "Best reached by car; the city site lists locations."),

("🚇","Yongin Everline Light Rail (용인경전철)","🔁 daily",
 "A driverless light-rail line running from Giheung to Jeondae-Everland via central Yongin — **sit at the front for the driver's view**",
 "Roughly **05:30–24:00**",
 "**₩1,450** with T-money",
 "[yongin.go.kr](https://www.yongin.go.kr)",
 "**Jeondae-Everland Station is the stop for both Everland and Daejanggeum Park.** Transfers from Bundang Line at Giheung."),

("🚇","Bundang & Sinbundang Lines into Yongin","🔁 daily",
 "Yongin is served by the Bundang Line, the Sinbundang express line and the Everline, putting Gangnam within 40 minutes",
 "Roughly **05:30–24:00**",
 "**₩1,400–₩2,500**",
 "[letskorail.com](https://www.letskorail.com) · [yongin.go.kr](https://www.yongin.go.kr)",
 "**Sinbundang from Gangnam to Suji is the fastest route in** — about 25 minutes."),

("🚌","Everland & Folk Village free shuttles","🔁 daily",
 "Everland runs free shuttle buses from Seoul (Gangnam, Jamsil, Sinchon); the Korean Folk Village runs a free shuttle from Suwon Station",
 "Several departures **08:00–11:00**",
 "**FREE** with admission",
 "[everland.com](https://www.everland.com) · [koreanfolk.co.kr](https://www.koreanfolk.co.kr)",
 "**Reserve the Everland shuttle online** — it fills up. The Folk Village shuttle is first-come."),

("🛍️","Yongin Shopping — Suji, Giheung & outlets","🔁 daily",
 "Yongin's retail is concentrated in Suji and Giheung, with department stores, large marts and a premium outlet nearby",
 "Roughly **10:30–21:00**",
 "**FREE** entry",
 "[yongin.go.kr](https://www.yongin.go.kr)",
 "The nearby Yeoju and Icheon outlets are the region's big shopping draws."),

("🍜","Yongin Food — baeksuk, duck and Korean country dining","🔁 daily",
 "Yongin's semi-rural restaurants specialise in *baeksuk* chicken stew, duck bulgogi and mountain-vegetable meals",
 "Roughly **11:00–21:00**",
 "**₩15,000–₩30,000** per person",
 "[yongin.go.kr](https://www.yongin.go.kr)",
 "**The restaurants around Waujeongsa and the recreation forests** are where locals actually eat."),

("☕","Yongin Cafe Culture & Garden Cafes","🔁 daily",
 "Yongin's large garden and greenhouse cafes are a Gyeonggi-do speciality, built for weekend drives from Seoul",
 "Roughly **10:00–22:00**",
 "Coffee **₩6,000–₩9,000**",
 "[yongin.go.kr](https://www.yongin.go.kr)",
 "**Busy on Saturday and Sunday afternoons** — go on a weekday."),

("🍚","Yongin Traditional Markets","🔁 daily",
 "Yongin Jungang Market and the district markets, with five-day market days retained in the older quarters",
 "Roughly **08:00–19:00**",
 "**FREE** to browse",
 "[yongin.go.kr](https://www.yongin.go.kr)",
 "**Yongin Jungang Market's five-day cycle** falls on dates ending 5 and 0."),

("🏟️","Yongin Sports Complex & Mireu Stadium","👀 WATCH — check fixtures",
 "Yongin's municipal sports complex hosts football, athletics and provincial competitions",
 "By event",
 "From **₩5,000**",
 "[yongin.go.kr](https://www.yongin.go.kr) · [kleague.com](https://www.kleague.com)",
 "Check the K League 2 and amateur calendars for November fixtures."),

("⛳","Yongin Golf & Country Clubs","🔁 daily",
 "Yongin has one of Korea's highest concentrations of golf courses, several open to visitor bookings",
 "Tee times from **06:30**",
 "Green fees from **₩120,000**",
 "[yongin.go.kr](https://www.yongin.go.kr)",
 "**November is still playable** in Gyeonggi-do, at lower off-season rates."),

("🎿","Yongin Winter Sports & Everland Snow Buster","👀 WATCH — opens December",
 "Everland's winter sledding and snow attractions typically open in December, after your window",
 "Season typically **December–February**",
 "Extra charge",
 "[everland.com](https://www.everland.com)",
 "**Won't be open during your trip** — noted so you don't plan around it."),

("🏨","Yongin Accommodation — Everland area vs Suji","🔁 planning",
 "Home Bridge and the Everland resort hotels for park access, business hotels in Suji and Giheung for transit",
 "Check-in typically **15:00**",
 "From **₩70,000** per night",
 "[everland.com](https://www.everland.com) · [yongin.go.kr](https://www.yongin.go.kr)",
 "**Most visitors day-trip from Seoul** — Yongin is under an hour from Gangnam."),

("🗺️","Yongin as a Seoul day trip","🔁 planning",
 "Yongin's attractions are all within 60–90 minutes of central Seoul, making it the standard Seoul day-trip destination for families",
 "N/A",
 "Transit **₩2,000–₩3,000** each way",
 "[yongin.go.kr](https://www.yongin.go.kr) · [visitkorea.or.kr](https://english.visitkorea.or.kr)",
 "**Don't try Everland and the Folk Village on the same day** — each needs five hours."),

("🗺️","Yongin one-day route — Folk Village + heritage","🔁 planning",
 "Suwon Station → free shuttle → Korean Folk Village (5 h, catch two performances) → shuttle back → Suwon Hwaseong in the evening",
 "One full day",
 "About **₩35,000**",
 "[koreanfolk.co.kr](https://www.koreanfolk.co.kr) · [yongin.go.kr](https://www.yongin.go.kr)",
 "**The Folk Village and Suwon Hwaseong pair perfectly** — both Joseon, ten minutes apart."),

("🗺️","Yongin one-day route — Everland + Ho-Am","🔁 planning",
 "Seoul shuttle → Everland (open to 20:00) or Everland morning → Ho-Am Art Museum afternoon → Everland illumination in the evening",
 "One full day",
 "About **₩80,000**",
 "[everland.com](https://www.everland.com) · [hoammuseum.org](https://hoam.samsungfoundation.org)",
 "**Ho-Am is a five-minute shuttle from Everland's gate** and almost nobody combines them."),

("🌡️","Yongin November Weather & Park Conditions","🔁 planning",
 "Inland Gyeonggi-do: November highs around **11°C**, lows near 1°C, with the first frosts — theme parks are cold in the evening",
 "N/A",
 "N/A",
 "[weather.go.kr](https://www.weather.go.kr) · [yongin.go.kr](https://www.yongin.go.kr)",
 "**Everland after dark in November is genuinely cold** — hats and gloves if you're staying for the parade."),

("🚑","Yongin Emergency & Medical Services","🔁 24 h",
 "Yongin Severance Hospital and the Myongji hospital network provide 24-hour emergency care",
 "Emergency **24 h**",
 "Consultation from **₩20,000** for visitors",
 "[1339 Medical Hotline](https://www.kdca.go.kr) · [yongin.go.kr](https://www.yongin.go.kr)",
 "**119 for ambulance, 1339 for English medical advice.**"),

("🧭","Yongin Tourist Information & English Support","🔁 daily (FREE)",
 "Information desks at Everland, the Korean Folk Village and Yongin City Hall, with English materials",
 "Daily **09:00–18:00**",
 "**FREE**",
 "[yongin.go.kr](https://www.yongin.go.kr) · [1330 Hotline](https://english.visitkorea.or.kr)",
 "**Everland and the Folk Village both have full English signage** — the rest of Yongin does not."),

("📸","Yongin Photo Spots","🔁 daily (FREE)",
 "The Folk Village's thatched lanes, Daejanggeum Park's palace courtyards, Hee Won garden in autumn, Waujeongsa's Buddha head and Everland's illuminated garden",
 "Best in afternoon light",
 "Varies by site",
 "[yongin.go.kr](https://www.yongin.go.kr)",
 "**Daejanggeum Park is the best value photo location in Gyeonggi-do** — real palace sets at ₩9,500."),
]

append("/home/user/KoreaFun/yongin.md", E, 131, 3,
       "\n---\n\n## 🧭 Beginner-friendly essentials", "Yongin",
       intro="**Verified expansion set** — Everland and its autumn season, the Korean Folk Village and its UNESCO-listed performances, MBC Daejanggeum Park, Hwadam Forest, Ho-Am Art Museum, Yongin's Joseon heritage sites, transit and day-trip routing.")
