# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "/home/user/KoreaFun/.build")
from addlib import append

E = [
("🏛️","Yongin Poeun Art Hall & city performances","👀 WATCH — check programme",
 "Yongin's municipal arts centre, named after Jeong Mong-ju's pen name Poeun, staging concerts, plays and family shows",
 "Box office **09:00–18:00**",
 "**₩10,000–₩50,000**",
 "[yongin.go.kr](https://www.yongin.go.kr) · [culture.go.kr](https://www.culture.go.kr)",
 "**Check the November programme** — the autumn season is well filled."),

("🎨","Yongin Public Art & Suji cultural spaces","🔁 daily (FREE)",
 "Municipal galleries and public art in Suji and Giheung, including exhibition spaces in the district cultural centres",
 "Tue–Sun **10:00–18:00**",
 "**FREE**",
 "[yongin.go.kr](https://www.yongin.go.kr)",
 "Free, local and a reasonable stop between transit connections."),

("📚","Yongin Libraries & Feel Good Library","🔁 Tue–Sun (FREE)",
 "Yongin's modern municipal libraries, several architecturally notable, open to visitors with free wifi and reading space",
 "Tue–Sun **09:00–21:00**",
 "**FREE**",
 "[yongin.go.kr](https://www.yongin.go.kr)",
 "A warm free stop on a cold Gyeonggi-do afternoon."),

("🏞️","Giheung Reservoir & Waterfront Trail (기흥호수)","🔁 daily (FREE)",
 "A 10 km loop path around Giheung Reservoir with boardwalks, reed beds and birdlife, popular with local walkers and runners",
 "Always open",
 "**FREE**",
 "[yongin.go.kr](https://www.yongin.go.kr) · [durunubi.kr](https://www.durunubi.kr)",
 "**The best free walk in Yongin.** Two to three hours for the full loop; Giheung Station is at one end."),

("🦆","Giheung Reservoir Birdwatching — autumn migration","✅ CONFIRMED — Nov",
 "The reservoir draws wintering ducks, herons and geese from November, with observation decks along the loop",
 "Best at dawn and dusk",
 "**FREE**",
 "[yongin.go.kr](https://www.yongin.go.kr)",
 "**November brings the wintering flocks in** — bring binoculars."),

("🌳","Yongin Central Park & Suji parks","🔁 daily (FREE)",
 "Yongin's district parks, with autumn planting, playgrounds and walking loops in Suji and Sanghyeon",
 "Always open",
 "**FREE**",
 "[yongin.go.kr](https://www.yongin.go.kr)",
 "Useful if you're staying in Suji rather than day-tripping."),

("🏛️","Yongin Kimchi & food museums","🔁 Tue–Sun",
 "Small specialist museums in the Yongin area covering kimchi, traditional liquor and Korean food history",
 "Tue–Sun **10:00–17:00**",
 "**₩3,000–₩8,000**",
 "[yongin.go.kr](https://www.yongin.go.kr)",
 "**Hands-on kimjang sessions run in November** — the traditional kimchi-making month."),

("🥬","Kimjang season in Gyeonggi-do — November","✅ CONFIRMED — Nov",
 "**Kimjang, communal winter kimchi-making, is UNESCO Intangible Cultural Heritage** and takes place across Korea in November",
 "Throughout November",
 "Workshops **₩20,000–₩40,000**",
 "[UNESCO ICH](https://ich.unesco.org/en/RL/kimjang-making-and-sharing-kimchi-in-the-republic-of-korea-00881) · [yongin.go.kr](https://www.yongin.go.kr)",
 "**Your window is kimjang month.** The Korean Folk Village and local centres run participatory sessions."),

("🐄","Yongin Farm Experiences & Dairy Visits","🔁 daily (booking)",
 "Working farms around Yongin offer milking, cheese-making and harvest experiences aimed at families",
 "Sessions **10:00–16:00**",
 "**₩10,000–₩25,000**",
 "[yongin.go.kr](https://www.yongin.go.kr) · [Rural Development Administration](https://www.rda.go.kr)",
 "Book through the city tourism site; most require a day's notice."),

("🍇","Yongin & Gyeonggi Farm Stays","🔁 daily (booking)",
 "Officially registered rural stay programmes in the Yongin countryside, combining accommodation with farm activities",
 "Overnight",
 "From **₩60,000** per night",
 "[welchon.com](https://www.welchon.com) · [yongin.go.kr](https://www.yongin.go.kr)",
 "**Welchon is the official rural-tourism portal** for booking these."),

("🏛️","Suwon–Yongin heritage combination day","🔁 planning",
 "Hwaseong Fortress, the Korean Folk Village and Yungneung royal tombs are all within 20 minutes of each other",
 "One full day",
 "About **₩40,000**",
 "[koreanfolk.co.kr](https://www.koreanfolk.co.kr) · [yongin.go.kr](https://www.yongin.go.kr)",
 "**Three major Joseon sites in one day** — the strongest heritage itinerary in Gyeonggi-do."),

("🏛️","Yongin & Icheon ceramics day trip","🔁 daily",
 "Icheon, 40 minutes east, is a **UNESCO Creative City of Crafts and Folk Art** with working ceramic kilns and studios",
 "Studios roughly **09:00–18:00**",
 "Workshops from **₩20,000**",
 "[icheon.go.kr](https://www.icheon.go.kr) · [UNESCO Creative Cities](https://www.unesco.org/en/creative-cities)",
 "**Throw your own pot at a working kiln.** Icheon also has famous rice and hot springs."),

("♨️","Icheon & Yongin Hot Springs","🔁 daily",
 "Icheon's alkaline hot springs, 40 minutes from Yongin, plus large spa complexes in the Yongin area",
 "Roughly **06:00–21:00**",
 "**₩10,000–₩20,000**",
 "[icheon.go.kr](https://www.icheon.go.kr) · [yongin.go.kr](https://www.yongin.go.kr)",
 "A good pairing with a cold November hiking day."),

("🏛️","Yeoju day trip — Sejong's tomb & UNESCO Yeongneung","🔁 daily",
 "Yeoju holds **Yeongneung, the tomb of King Sejong**, part of the UNESCO-inscribed Royal Tombs of the Joseon Dynasty, plus Silleuksa Temple",
 "Tue–Sun **09:00–18:00** (Nov: to 17:00)",
 "Adult **₩500**",
 "[UNESCO ref 1319](https://whc.unesco.org/en/list/1319) · [yeoju.go.kr](https://www.yeoju.go.kr)",
 "**Sejong invented Hangul** — this is his tomb, and it costs ₩500."),

("🛍️","Yeoju & Icheon Premium Outlets","🔁 daily",
 "Two of Korea's largest outlet malls, both within an hour of Yongin, with shuttle buses from Seoul",
 "Daily **10:30–21:00**",
 "**FREE** entry",
 "[premiumoutlets.co.kr](https://www.premiumoutlets.co.kr)",
 "**November has pre-Christmas sales.** Shuttles run from Gangnam and Jamsil."),

("🚌","Yongin bus network & Seoul express routes","🔁 daily",
 "Red express buses connect Yongin's districts directly to Gangnam, Seoul Station and Jamsil in 40–60 minutes",
 "Roughly **05:00–24:00**",
 "**₩2,800–₩3,200**",
 "[yongin.go.kr](https://www.yongin.go.kr) · [gbis.go.kr](https://www.gbis.go.kr)",
 "**Red buses are seated-only** — you may have to wait for a seat at peak times."),

("🚕","Yongin taxis & getting between attractions","🔁 24 h",
 "Yongin's attractions are far apart; taxis fill the gaps between Everland, the Folk Village and the museums",
 "**24 hours**",
 "Base **₩4,800**; typical hop ₩10,000–₩20,000",
 "[yongin.go.kr](https://www.yongin.go.kr)",
 "**Kakao T works throughout Yongin** and is far easier than flagging."),

("💰","Yongin on a budget","🔁 daily (FREE)",
 "Giheung Reservoir, Waujeongsa, the Gyeonggi Provincial Museum, Jeong Mong-ju's tomb and Gwanggyosan are all free",
 "Various",
 "**FREE**",
 "[yongin.go.kr](https://www.yongin.go.kr)",
 "**Everland is the expensive part of Yongin** — everything else is cheap or free."),

("🎫","Yongin discount tickets & combined passes","🔁 daily",
 "Everland sells discounted after-4pm and online tickets; the Folk Village offers combined performance passes",
 "N/A",
 "Savings of **₩10,000–₩25,000**",
 "[everland.com](https://www.everland.com) · [koreanfolk.co.kr](https://www.koreanfolk.co.kr)",
 "**Never buy an Everland ticket at the gate** — online is substantially cheaper."),

("🧳","Yongin practicalities — lockers, food, closures","🔁 daily",
 "Lockers at Everland and the Folk Village; note that **Daejanggeum Park closes Tuesdays** and Hwadam Forest closes for winter",
 "N/A",
 "Lockers **₩1,000–₩3,000**",
 "[yongin.go.kr](https://www.yongin.go.kr)",
 "**Check closing days before you travel** — Yongin's sites are far apart and a wasted trip costs an hour each way."),

("🗺️","Yongin three-day deep itinerary","🔁 planning",
 "Day 1 Everland + Ho-Am; Day 2 Korean Folk Village + Daejanggeum Park; Day 3 Giheung Reservoir + Gyeonggi Provincial Museum + Waujeongsa",
 "Three days",
 "About **₩130,000**",
 "[yongin.go.kr](https://www.yongin.go.kr)",
 "**Only Day 1 and Day 2 are essential** — Day 3 is for a slower pace or bad weather."),
]

append("/home/user/KoreaFun/yongin.md", E, 174, 3,
       "\n---\n\n## 🧭 Beginner-friendly essentials", "Yongin")
