# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "/home/user/KoreaFun/.build")
from addlib import append

E = [
("🚡","Yeosu Maritime Cable Car (여수해상케이블카)","🔁 daily",
 "**Korea's first cable car to cross the sea**, running 1.5 km between Dolsan Park and Jasan Park over Yeosu harbour, with glass-floor crystal cabins",
 "Daily **09:30–21:30** (Nov: to 21:00)",
 "Round trip adult **₩17,000** standard / **₩24,000** crystal cabin",
 "[yeosucablecar.com](https://www.yeosucablecar.com) · [yeosu.go.kr](https://www.yeosu.go.kr)",
 "**Ride it after dark** — the night view over the lit bridge and harbour is far better than the daytime one."),

("🌉","Dolsan Bridge Night View (돌산대교)","🔁 nightly (FREE)",
 "The 1984 cable-stayed bridge to Dolsan Island, floodlit in changing colours and the centrepiece of Yeosu's night skyline",
 "Lit roughly **sunset–24:00**",
 "**FREE**",
 "[yeosu.go.kr](https://www.yeosu.go.kr)",
 "**Yeosu is famous nationally for its night view** — this bridge is why. Best seen from Jasan Park or the cable car."),

("🌊","Yeosu Ocean Railbike & Manseongri Black Sand Beach","🔁 daily",
 "A pedal railbike running along the coast on a disused rail line, beside **Manseongri's rare black sand beach**",
 "Daily **09:00–18:00** (Nov: to 17:00)",
 "Railbike from **₩30,000** per 2-seat cart",
 "[yeosu.go.kr](https://www.yeosu.go.kr) · [visitkorea.or.kr](https://english.visitkorea.or.kr)",
 "**Book ahead at weekends.** The black sand is a designated natural monument, said to have health benefits."),

("⛪","Odongdo Island & Camellia Forest (오동도)","🔁 daily (FREE)",
 "A small island joined to Yeosu by a 768 m breakwater, covered in **3,000 camellia trees** and ringed by a coastal path with a lighthouse",
 "Always open; lighthouse **09:00–18:00**",
 "Island **FREE**; dongbaek train ₩1,000",
 "[yeosu.go.kr](https://www.yeosu.go.kr) · [visitkorea.or.kr](https://english.visitkorea.or.kr)",
 "**Camellias bloom from November to April** — your window catches the very start of the season."),

("🎆","Odongdo Music Fountain & Light Show","🔁 nightly (FREE)",
 "A large musical fountain at the Odongdo entrance, running scheduled shows in the evening beside the harbour",
 "Shows typically **19:00, 20:00, 21:00**",
 "**FREE**",
 "[yeosu.go.kr](https://www.yeosu.go.kr)",
 "**Check the winter schedule** — showtimes reduce after October."),

("🏛️","Yeosu Expo 2012 Site & Big-O Show (여수엑스포)","🔁 daily",
 "The waterfront site of **Expo 2012**, with the Sky Tower, the Digital Gallery and the Big-O water-screen show over the sea",
 "Site always open; attractions **10:00–18:00**",
 "Site **FREE**; Big-O show from ₩12,000",
 "[yeosu.go.kr](https://www.yeosu.go.kr) · [expo2012.kr](https://www.expo2012.kr)",
 "**Big-O runs a reduced winter schedule** — confirm before planning an evening around it."),

("🐠","Yeosu Aqua Planet (아쿠아플라넷 여수)","🔁 daily",
 "**One of Korea's largest aquariums**, built for Expo 2012, with beluga whales, sea lions and a 4.5 m-deep main tank",
 "Daily **09:30–18:00** (Nov: to 17:00)",
 "Adult **₩44,900**; child ₩41,900",
 "[aquaplanet.co.kr](https://www.aquaplanet.co.kr/yeosu)",
 "**Buy online for a substantial discount.** Directly beside Yeosu Expo KTX Station."),

("🗼","Yeosu Expo Sky Tower (스카이타워)","🔁 daily",
 "An observation tower converted from two disused cement silos, with a sea-water desalination cafe and **the world's largest pipe organ made from silos**",
 "Daily **10:00–20:00**",
 "Adult **₩2,000**",
 "[yeosu.go.kr](https://www.yeosu.go.kr) · [expo2012.kr](https://www.expo2012.kr)",
 "Cheap, quick and the horn sounds across the harbour on the hour."),

("⚓","Jinnamgwan Hall — National Treasure (진남관)","🔁 daily (FREE)",
 "**Korea's largest single-storey wooden building**, built 1599 as the naval headquarters of Admiral Yi Sun-sin's Jeolla Left Navy — a National Treasure",
 "Daily **09:00–18:00**",
 "**FREE**",
 "[yeosu.go.kr](https://www.yeosu.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "**Check restoration status before visiting** — Jinnamgwan has been under long-term conservation work."),

("🐢","Turtle Ship Replica & Yi Sun-sin Square (거북선)","🔁 daily (FREE)",
 "A full-size replica of the *geobukseon* turtle ship, built at Yeosu — the base from which Admiral Yi commanded the Imjin War naval campaign",
 "Daily **09:00–18:00**",
 "**FREE** to view; boarding ₩1,000",
 "[yeosu.go.kr](https://www.yeosu.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "**Yeosu was Yi Sun-sin's home port** — the whole city's identity runs through him."),

("🏛️","Yi Sun-sin Square & Jeolla Left Navy Heritage","🔁 daily (FREE)",
 "The waterfront square commemorating Admiral Yi, with the turtle ship, statues and interpretive panels on the 1592–98 naval war",
 "Always open",
 "**FREE**",
 "[yeosu.go.kr](https://www.yeosu.go.kr)",
 "Lit at night and a short walk from the Jongpo waterfront restaurants."),

("🛕","Hyangiram Hermitage (향일암)","🔁 daily",
 "A 644 CE hermitage clinging to a cliff at the southern tip of Dolsan Island, reached through natural rock crevices — **one of Korea's four great Gwaneum sites**",
 "Daily **07:00–18:00** (Nov: to 17:30)",
 "Adult **₩2,000**",
 "[yeosu.go.kr](https://www.yeosu.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "Bus 111 from Yeosu, about 1 hour. **The sunrise view over the South Sea is the reason people come** — around 07:05 in November."),

("🌅","Dolsan Island Coastal Drive & Viewpoints (돌산도)","🔁 daily (FREE)",
 "The island south of Yeosu, linked by two bridges, with a coastal road running past fishing villages to Hyangiram",
 "Always open",
 "**FREE**",
 "[yeosu.go.kr](https://www.yeosu.go.kr)",
 "Dolsan is also where Yeosu's famous *gat* mustard-leaf kimchi is grown."),

("🌿","Dolsan Gat Kimchi — mustard leaf kimchi (돌산갓김치)","🔁 daily",
 "Yeosu's most famous product: kimchi made from Dolsan mustard leaves, pungent and slightly bitter, sold across the island and at the market",
 "Shops roughly **08:00–19:00**",
 "**₩10,000–₩20,000** per kg",
 "[yeosu.go.kr](https://www.yeosu.go.kr) · [visitkorea.or.kr](https://english.visitkorea.or.kr)",
 "**Vacuum-packed for travel at the Dolsan roadside shops.** A genuinely distinctive souvenir."),

("🌉","Yi Sun-sin Bridge & Myodo Island (이순신대교)","🔁 daily (FREE)",
 "A 2,260 m suspension bridge with a main span of 1,545 m — **chosen to mark Yi Sun-sin's birth year, 1545** — linking Yeosu to Gwangyang",
 "Always open",
 "**FREE**",
 "[yeosu.go.kr](https://www.yeosu.go.kr)",
 "There's a free observation hall at the Myodo end explaining the engineering."),

("🏝️","Geomundo & Baekdo Islands (거문도·백도)","👀 WATCH — ferry, weather-dependent",
 "A remote archipelago 115 km south of Yeosu, with the uninhabited **Baekdo rock islands** and a British naval occupation history from 1885–87",
 "Ferry roughly **07:30**, 2 hours each way",
 "Return fare around **₩60,000**",
 "[yeosu.go.kr](https://www.yeosu.go.kr) · [Korea Maritime Safety](https://www.komsa.or.kr)",
 "**November seas frequently cancel this.** Plan an overnight rather than a day return."),

("⛵","Yeosu Island Ferries — Geumodo, Sado, Nangdo","🔁 daily (weather-dependent)",
 "Yeosu administers over 300 islands; regular ferries reach Geumodo, Sado with its dinosaur footprints, and small fishing islands",
 "Sailings roughly **07:00–17:00**",
 "**₩10,000–₩30,000** each way",
 "[yeosu.go.kr](https://www.yeosu.go.kr) · [Korea Maritime Safety](https://www.komsa.or.kr)",
 "**Sado has Cretaceous dinosaur trackways** visible on the shore at low tide."),

("🦕","Sado Island Dinosaur Footprints (사도 공룡발자국)","👀 WATCH — ferry + tide",
 "Over 3,500 dinosaur footprints on the shores of Sado and neighbouring islets, a designated Natural Monument",
 "Tide-dependent; ferry from Baegya port",
 "Ferry around **₩15,000** return",
 "[yeosu.go.kr](https://www.yeosu.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "**Needs both a ferry and a low tide** — check both before committing a day."),

("🏖️","Mosageum, Bangjukpo & Yeosu Beaches","🔁 daily (FREE)",
 "Yeosu's small sandy and pebble beaches on Dolsan and the mainland coast, quiet and free outside summer",
 "Always open",
 "**FREE**",
 "[yeosu.go.kr](https://www.yeosu.go.kr)",
 "**Empty in November** — good for a walk rather than a swim."),

("🐟","Yeosu Seafood — seonji-haejang & jangeo-tang","🔁 daily",
 "The South Sea catch at its best: grilled eel soup, *seodae* sole sashimi, and the Yeosu speciality of *gejang* soy-marinated crab",
 "Most **10:00–22:00**",
 "**₩15,000–₩40,000**",
 "[yeosu.go.kr](https://www.yeosu.go.kr) · [visitkorea.or.kr](https://english.visitkorea.or.kr)",
 "**Gejang is eaten with rice mixed into the shell.** Jongpo and Gyodong markets are the places."),

("🦐","Yeosu Gyodong Market & Seafood Alley (교동시장)","🔁 daily",
 "Yeosu's central market, with a large wet-fish section, a night raw-fish alley and cheap seafood restaurants upstairs",
 "Roughly **06:00–21:00**",
 "**FREE** to browse",
 "[yeosu.go.kr](https://www.yeosu.go.kr)",
 "**Buy downstairs, eat upstairs** for a small preparation fee — the standard south-coast routine."),

("🍢","Yeosu Jongpo Seafood Village (종포해양공원)","🔁 daily",
 "The waterfront restaurant strip along Jongpo Marine Park, looking directly at the lit Dolsan Bridge",
 "Roughly **11:00–24:00**",
 "**₩20,000–₩50,000** per person",
 "[yeosu.go.kr](https://www.yeosu.go.kr)",
 "**The bridge view at night from a Jongpo table is the classic Yeosu evening.**"),

("🍜","Yeosu Street Food — gungjung tteokbokki & Yeosu bread","🔁 daily",
 "The Yeosu specialities that aren't seafood: soy-based royal tteokbokki, Yeosu chestnut bread, and camellia-flavoured sweets",
 "Roughly **10:00–21:00**",
 "**₩3,000–₩10,000**",
 "[yeosu.go.kr](https://www.yeosu.go.kr)",
 "The Gyodong Market food alley has all of them within fifty metres."),

("🏛️","Yeosu Jinnamje & Local History Museum","🔁 Tue–Sun (FREE)",
 "Yeosu's municipal museum covering the city's naval history, island culture and the Expo, with English panels",
 "Tue–Sun **09:00–18:00** (closed Mon)",
 "**FREE**",
 "[yeosu.go.kr](https://www.yeosu.go.kr)",
 "Free, small and a good primer on Yi Sun-sin before visiting the turtle ship."),

("⛰️","Yeongchwisan Mountain & Azalea Ridge (영취산)","🔁 daily (FREE)",
 "A 510 m mountain behind Yeosu, nationally famous for spring azaleas but with year-round ridge trails and harbour views",
 "Always open",
 "**FREE**",
 "[yeosu.go.kr](https://www.yeosu.go.kr) · [Korea Forest Service](https://www.forest.go.kr)",
 "Two to three hours for the loop. **The industrial complex view from the ridge is unexpectedly dramatic.**"),

("🌄","Gubongsan & Yeosu Night View Points (구봉산)","🔁 daily (FREE)",
 "The hill with Yeosu's designated night-view observatory, looking over the harbour, both bridges and the industrial complex",
 "Always open",
 "**FREE**",
 "[yeosu.go.kr](https://www.yeosu.go.kr)",
 "Taxi up, walk down. **The best free night view in Yeosu** and better than the cable car for photography."),

("🌲","Jasan Park & Yeosu Coastal Walk (자산공원)","🔁 daily (FREE)",
 "The park at the mainland cable-car station, with a Yi Sun-sin statue, harbour views and a path down to Odongdo",
 "Always open",
 "**FREE**",
 "[yeosu.go.kr](https://www.yeosu.go.kr)",
 "**Walk from Jasan Park to Odongdo along the shore** — about 20 minutes and free."),

("🚶","Yeosu Romantic Coastal Trail & Sea Walkway","🔁 daily (FREE)",
 "The continuous waterfront path from the Expo site through Jongpo to Dolsan Bridge, lit at night and lined with cafes",
 "Always open",
 "**FREE**",
 "[yeosu.go.kr](https://www.yeosu.go.kr)",
 "About 4 km end to end. **The core Yeosu experience and it costs nothing.**"),

("🎵","Yeosu Bam-bada & the song that made the city","🔁 daily (FREE)",
 "Busker Busker's 2012 hit *Yeosu Night Sea* turned the city into a domestic tourism phenomenon; the lyrics are inscribed on the waterfront",
 "Always open",
 "**FREE**",
 "[yeosu.go.kr](https://www.yeosu.go.kr)",
 "**This song is genuinely why most Korean visitors come.** The monument is on the Jongpo waterfront."),

("🏛️","Yeosu Art Land & Sky Bridge (여수예술랜드)","🔁 daily",
 "A cliff-top sculpture park on Dolsan Island with a glass-floored sea skywalk and coastal art installations",
 "Daily **09:00–18:00** (Nov: to 17:30)",
 "Adult **₩15,000**",
 "[yeosu.go.kr](https://www.yeosu.go.kr)",
 "Bus from Dolsan Bridge. **Wind closes the skywalk** on rough days."),

("⛲","Yeosu Ungcheon Beach & Waterfront New Town","🔁 daily (FREE)",
 "Yeosu's newer waterfront district with an artificial beach, a night-lit promenade and modern cafes and hotels",
 "Always open",
 "**FREE**",
 "[yeosu.go.kr](https://www.yeosu.go.kr)",
 "Quieter than the Expo waterfront and where much of Yeosu's newer accommodation sits."),

("🌸","Yeosu Camellia Season — November onwards","✅ CONFIRMED — Nov–Apr",
 "**Camellias begin flowering in November** on Odongdo and across Yeosu — the city's official flower and the origin of Odongdo's nickname, Camellia Island",
 "Daylight hours",
 "**FREE**",
 "[yeosu.go.kr](https://www.yeosu.go.kr) · [Korea Forest Service](https://www.forest.go.kr)",
 "**Early flowers appear in your window**, with peak bloom in February. Odongdo's forest is the place to see them."),

("🎪","Yeosu Festival Calendar & November Events","👀 WATCH",
 "Yeosu's festival year includes the Turtle Ship Festival, the Camellia Festival and the Yeosu Night Sea Festival; 2026 dates are published by the city",
 "By event",
 "Many **FREE**",
 "[yeosu.go.kr](https://www.yeosu.go.kr)",
 "**Check the city calendar in October 2026.** Most Yeosu festivals fall in spring and summer."),

("🎄","Yeosu Winter Illumination & Christmas Lights","👀 WATCH (from late Nov)",
 "Yeosu lights its waterfront, the Expo site and Odongdo for winter, typically switching on in late November",
 "Evenings once lit",
 "**FREE**",
 "[yeosu.go.kr](https://www.yeosu.go.kr)",
 "**Switch-on may fall right at the end of your window** — check the city site."),

("🚄","Getting to Yeosu — KTX to Yeosu-Expo","🔁 daily",
 "The Jeolla Line KTX runs from Seoul Yongsan to **Yeosu-Expo Station in about 3 hours** — the station is on the waterfront beside the aquarium",
 "Trains roughly **05:30–21:00**",
 "KTX from Yongsan **₩47,200**",
 "[letskorail.com](https://www.letskorail.com) · [yeosu.go.kr](https://www.yeosu.go.kr)",
 "**Yeosu-Expo is one of the best-placed stations in Korea** — you arrive in the middle of everything."),

("✈️","Yeosu Airport & Regional Access (여수공항)","🔁 daily",
 "Yeosu Airport serves Gimpo and Jeju, with a bus into the city taking about 30 minutes",
 "Flights daily",
 "Airport bus **₩1,500**",
 "[airport.co.kr](https://www.airport.co.kr) · [yeosu.go.kr](https://www.yeosu.go.kr)",
 "Actually located in Yeosu, unlike many Korean regional airports."),

("🚌","Yeosu City Buses & Dolsan Access","🔁 daily",
 "City buses connect the Expo site, downtown, Dolsan Island and Hyangiram; T-money and Cashbee both work",
 "Roughly **05:30–22:30**",
 "**₩1,500**",
 "[yeosu.go.kr](https://www.yeosu.go.kr)",
 "**Bus 111 to Hyangiram takes about an hour** and runs roughly every 30 minutes."),

("🚕","Yeosu Taxis & Island Driving","🔁 24 h",
 "Metered taxis throughout Yeosu; Dolsan Island and Hyangiram are common taxi runs where buses are slow",
 "**24 hours**",
 "Base **₩4,300**; Hyangiram about ₩30,000",
 "[yeosu.go.kr](https://www.yeosu.go.kr)",
 "**Agree a return arrangement for Hyangiram** — taxis are scarce at the temple end."),

("🧭","Yeosu Tourist Information & English Help","🔁 daily (FREE)",
 "Information centres at Yeosu-Expo Station, the Expo site and the cable car, with free maps and English staff",
 "Daily **09:00–18:00**",
 "**FREE**",
 "[yeosu.go.kr](https://www.yeosu.go.kr) · [1330 Hotline](https://english.visitkorea.or.kr)",
 "Ask for the night-view map — it marks all the illuminated viewpoints."),

("🏨","Yeosu Accommodation — where to stay","🔁 planning",
 "Expo waterfront for convenience, Jongpo for the bridge view, Dolsan for quiet, and Ungcheon for newer hotels",
 "Check-in typically **15:00**",
 "From **₩50,000** per night",
 "[yeosu.go.kr](https://www.yeosu.go.kr) · [visitkorea.or.kr](https://english.visitkorea.or.kr)",
 "**A harbour-facing room is worth the premium here** — the night view is the point of Yeosu."),

("🗺️","Yeosu one-day and two-day model routes","🔁 planning",
 "Day 1: Expo site → Aqua Planet → Odongdo → Jasan Park → cable car at dusk → Jongpo seafood. Day 2: Dolsan Bridge → Hyangiram sunrise → gat kimchi → railbike → Gubongsan night view",
 "One to two full days",
 "About **₩80,000** with the aquarium and cable car",
 "[yeosu.go.kr](https://www.yeosu.go.kr)",
 "**Yeosu is a night city** — arrange your day so you're on the water after dark."),
]

append("/home/user/KoreaFun/yeosu.md", E, 137, 3,
       "\n---\n\n## 🧭 Beginner-friendly essentials", "Yeosu",
       intro="**Verified expansion set** — the maritime cable car and night views, Yi Sun-sin naval heritage, Odongdo camellias opening in November, the Expo waterfront, islands, seafood and transit.")
