# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "/home/user/KoreaFun/.build")
from addlib import append

E = [
("🏭","Yeosu National Industrial Complex Night View","🔁 nightly (FREE)",
 "**Korea's largest petrochemical complex**, whose lit towers and flare stacks form a famous industrial nightscape across the bay",
 "Best after **19:00**",
 "**FREE** to view",
 "[yeosu.go.kr](https://www.yeosu.go.kr)",
 "Viewed from Yeongchwisan or the Yi Sun-sin Bridge observation hall. **Strange and genuinely spectacular.**"),

("🌉","Myodo Marine Park & Bridge Observatory","🔁 daily (FREE)",
 "The park at the Yeosu end of the Yi Sun-sin Bridge, with an observation hall explaining the suspension bridge's construction",
 "Observatory **09:00–18:00**",
 "**FREE**",
 "[yeosu.go.kr](https://www.yeosu.go.kr)",
 "Combines well with the industrial night view."),

("🕍","Heungguksa Temple (흥국사)","🔁 daily",
 "A 1195 temple whose warrior-monks fought under Admiral Yi; it holds a Treasure-designated main hall and a stone bridge from 1639",
 "Daily **08:00–18:00**",
 "**FREE**",
 "[yeosu.go.kr](https://www.yeosu.go.kr) · [Korea Heritage Service](https://www.khs.go.kr)",
 "**Excellent autumn maples in early November** and far quieter than Hyangiram."),

("🍁","Yeosu Autumn Foliage — early to mid November","✅ CONFIRMED — seasonal",
 "The south coast turns latest in Korea; Yeosu's peak foliage typically lands in **the first half of November**, right inside your window",
 "Daylight hours",
 "**FREE**",
 "[Korea Forest Service](https://www.forest.go.kr) · [yeosu.go.kr](https://www.yeosu.go.kr)",
 "**Heungguksa and Yeongchwisan are the two best foliage spots.**"),

("🌡️","Yeosu November Weather & What to Pack","🔁 planning",
 "Yeosu is among Korea's mildest cities: November daytime highs around **15–17°C**, lows near 7°C, but strong sea wind on the waterfront",
 "N/A",
 "N/A",
 "[weather.go.kr](https://www.weather.go.kr) · [yeosu.go.kr](https://www.yeosu.go.kr)",
 "**Noticeably warmer than Seoul.** A windproof layer matters more than a thick coat."),

("🚢","Yeosu Cruise Terminal & Harbour Tours","🔁 daily (weather-dependent)",
 "Sightseeing boats from the Expo marina circle the harbour, Odongdo and Dolsan Bridge, with evening night-view sailings",
 "Roughly **10:00–21:00**",
 "From **₩18,000**",
 "[yeosu.go.kr](https://www.yeosu.go.kr) · [Korea Maritime Safety](https://www.komsa.or.kr)",
 "**Take the night sailing.** Cancelled in high wind."),

("⛵","Yeosu Marina & Yachting","🔁 daily",
 "The Expo marina offers yacht charters and short sailing experiences around the harbour",
 "Roughly **10:00–18:00**",
 "From **₩30,000** per person",
 "[yeosu.go.kr](https://www.yeosu.go.kr)",
 "Sunset sailings are the popular option. Book a day ahead."),

("🎣","Yeosu Sea Fishing Charters","🔁 daily (weather-dependent)",
 "Charter boats from Dolsan and Baegya ports for autumn rockfish and sea bream, with gear included",
 "Departures around **06:00**",
 "**₩70,000–₩100,000** per person",
 "[yeosu.go.kr](https://www.yeosu.go.kr) · [Korea Maritime Safety](https://www.komsa.or.kr)",
 "**Bring your passport** — boat manifests require ID."),

("🏛️","Yeosu Gosohang & the Old Town Alleys","🔁 daily (FREE)",
 "The old port quarter around Gosohang, with narrow alleys, a mural street and views back across the inner harbour",
 "Always open",
 "**FREE**",
 "[yeosu.go.kr](https://www.yeosu.go.kr)",
 "**The Gosohang mural alley** is a short, pleasant detour from Jinnamgwan."),

("🖼️","Yeosu Gosohang Mural Village (고소동 벽화골목)","🔁 daily (FREE)",
 "A 1.5 km painted alley climbing the hill behind the harbour, illustrating Yi Sun-sin's naval campaigns",
 "Always open",
 "**FREE**",
 "[yeosu.go.kr](https://www.yeosu.go.kr)",
 "Ends near Jasan Park — a natural walking link to the cable car."),

("☕","Yeosu Cafe Culture & Sea-view Roasters","🔁 daily",
 "Cafes along the Jongpo waterfront, on Dolsan Island and at Manseongri, most built around a sea view",
 "Roughly **10:00–22:00**",
 "Coffee **₩5,000–₩8,000**",
 "[yeosu.go.kr](https://www.yeosu.go.kr)",
 "**Dolsan's cliff-side cafes look back at the whole city** — the best coffee view in Yeosu."),

("🛍️","Yeosu Shopping & Souvenirs","🔁 daily",
 "Gat kimchi, dried seafood, camellia oil cosmetics and Yeosu bread — sold at Gyodong Market and the Expo shops",
 "Roughly **09:00–20:00**",
 "**FREE** entry",
 "[yeosu.go.kr](https://www.yeosu.go.kr)",
 "**Camellia oil is a genuine Yeosu product**, pressed from Odongdo-region seeds."),

("🍶","Yeosu Traditional Liquor & Local Brews","🔁 daily",
 "Local makgeolli and camellia-infused spirits, sold at the market and served in the Jongpo restaurants",
 "Roughly **11:00–24:00**",
 "**₩5,000–₩15,000** per bottle",
 "[yeosu.go.kr](https://www.yeosu.go.kr)",
 "Order it with gejang — the standard local pairing."),

("🏟️","Jeonnam Dragons & Gwangyang Football Stadium","👀 WATCH — season ending",
 "The K League club nearest Yeosu plays at Gwangyang Football Stadium, about 50 minutes away — **a rare purpose-built football ground in Korea**",
 "Kick-off typically **14:00/16:00**",
 "Tickets from **₩10,000**",
 "[kleague.com](https://www.kleague.com) · [dragons.co.kr](https://www.dragons.co.kr)",
 "**The K League season ends in early November** — check the fixture list for any home game in your first week."),

("🏛️","Suncheon Bay National Garden — day trip","🔁 daily",
 "**Korea's first national garden**, 30 minutes from Yeosu, laid out beside the Suncheon Bay wetlands",
 "Daily **09:00–18:00** (Nov: to 17:00)",
 "Adult **₩10,000** (combined with wetlands)",
 "[scbay.suncheon.go.kr](https://scbay.suncheon.go.kr)",
 "**Do this with the wetlands on one combined ticket.**"),

("🦢","Suncheon Bay Wetland Reserve — Ramsar site","🔁 daily",
 "A vast reed-bed estuary and Ramsar wetland where **hooded cranes arrive from Siberia in November** — one of Korea's great wildlife sights",
 "Daily **08:00–18:00** (Nov: to 17:00)",
 "Adult **₩10,000**",
 "[scbay.suncheon.go.kr](https://scbay.suncheon.go.kr) · [ramsar.org](https://www.ramsar.org)",
 "**November is peak crane arrival and peak reed colour.** Climb Yongsan observatory for the classic view."),

("🏯","Naganeupseong Folk Village — day trip","🔁 daily",
 "A walled Joseon town near Suncheon, **still inhabited**, with intact fortress walls and thatched houses — on Korea's UNESCO Tentative List",
 "Daily **09:00–18:00** (Nov: to 17:00)",
 "Adult **₩4,000**",
 "[suncheon.go.kr](https://www.suncheon.go.kr) · [UNESCO](https://whc.unesco.org)",
 "**People actually live here** — it isn't a reconstruction. About 1 hour from Yeosu."),

("🛕","Seonamsa Temple — UNESCO World Heritage","🔁 daily",
 "One of the **seven Sansa Buddhist mountain monasteries inscribed by UNESCO in 2018**, near Suncheon, with the Seungseon arched bridge",
 "Daily **08:00–18:00** (Nov: to 17:00)",
 "Adult **₩3,000**",
 "[UNESCO ref 1562](https://whc.unesco.org/en/list/1562) · [suncheon.go.kr](https://www.suncheon.go.kr)",
 "**A World Heritage site 90 minutes from Yeosu.** The stone bridge is a National Treasure."),

("🛕","Songgwangsa Temple — one of the Three Jewels","🔁 daily",
 "The Sangha Jewel temple of Korean Buddhism, near Suncheon, holding more National Treasures than almost any other monastery",
 "Daily **06:00–19:00** (Nov: to 18:00)",
 "Adult **₩3,000**",
 "[songgwangsa.org](http://www.songgwangsa.org) · [suncheon.go.kr](https://www.suncheon.go.kr)",
 "**Templestay available** — one of the most established programmes in Korea."),

("🚂","Suncheon Open Film Set & Railway Village","🔁 Tue–Sun",
 "A recreated 1960s–80s Korean streetscape used for film and drama shoots, near Suncheon station",
 "Tue–Sun **09:00–18:00**",
 "Adult **₩3,000**",
 "[suncheon.go.kr](https://www.suncheon.go.kr)",
 "Easy to combine with the national garden on the same day trip."),

("🌊","Gwangyang & Seomjin River — day trip","🔁 daily (FREE)",
 "The Seomjin River estuary between Gwangyang and Hadong, famous for clams, plum groves and an unusually clear river",
 "Always open",
 "**FREE**",
 "[gwangyang.go.kr](https://www.gwangyang.go.kr)",
 "**Seomjin clam soup** is the thing to eat, at the river-mouth restaurants."),

("🗺️","Yeosu as a base for the South Coast","🔁 planning",
 "Yeosu, Suncheon, Gwangyang and Boseong are all within an hour, giving one of Korea's densest clusters of day trips",
 "N/A",
 "Buses **₩3,000–₩8,000**",
 "[yeosu.go.kr](https://www.yeosu.go.kr) · [kobus.co.kr](https://www.kobus.co.kr)",
 "**Three nights in Yeosu covers the whole south coast.** Suncheon Bay in November is the strongest single day trip."),

("🍵","Boseong Green Tea Fields — day trip","🔁 daily",
 "Korea's most photographed tea plantation, terraced up a hillside about 90 minutes from Yeosu, with a winter light festival from December",
 "Daily **09:00–18:00** (Nov: to 17:00)",
 "Adult **₩4,000**",
 "[boseong.go.kr](https://www.boseong.go.kr)",
 "**Green year-round** — the terraces don't go brown in November."),

("🚑","Yeosu Emergency & Medical Services","🔁 24 h",
 "Yeosu Jeil Hospital and the Chonnam National University Hospital network provide 24-hour emergency care",
 "Emergency **24 h**",
 "Consultation from **₩20,000** for visitors",
 "[1339 Medical Hotline](https://www.kdca.go.kr) · [yeosu.go.kr](https://www.yeosu.go.kr)",
 "**119 for ambulance, 1339 for English medical advice.**"),

("🌏","Yeosu accessibility & barrier-free routes","🔁 daily",
 "The Expo waterfront, Odongdo's main path and the cable car stations are step-free; Hyangiram and Gosohang are not",
 "N/A",
 "N/A",
 "[yeosu.go.kr](https://www.yeosu.go.kr) · [visitkorea.or.kr](https://english.visitkorea.or.kr)",
 "**Hyangiram involves steep steps and rock passages** — not wheelchair accessible."),

("💰","Yeosu on a budget — free things to do","🔁 daily (FREE)",
 "Odongdo, Jinnamgwan, the turtle ship, the coastal trail, the mural village, Gubongsan night view and Jasan Park are all free",
 "Various",
 "**FREE**",
 "[yeosu.go.kr](https://www.yeosu.go.kr)",
 "**A full Yeosu day can cost only your meals** — the night view, the best thing here, is free."),

("📸","Yeosu Photo Spots — the definitive list","🔁 daily (FREE)",
 "Dolsan Bridge from Jongpo at blue hour, the harbour from Gubongsan, the cable car over the sea, Hyangiram at sunrise and camellias on Odongdo",
 "Best at dawn and after dark",
 "**FREE**",
 "[yeosu.go.kr](https://www.yeosu.go.kr)",
 "**Blue hour in mid-November is around 17:30** — be in position at Jongpo by 17:15."),

("🎫","Yeosu integrated passes & discounts","🔁 daily",
 "Combined tickets link Aqua Planet, the Sky Tower and the Big-O show; the cable car offers online discounts",
 "N/A",
 "Savings of **₩5,000–₩15,000**",
 "[yeosucablecar.com](https://www.yeosucablecar.com) · [aquaplanet.co.kr](https://www.aquaplanet.co.kr/yeosu)",
 "**Buy the aquarium ticket online** — it is meaningfully cheaper than the gate price."),

("🧳","Yeosu luggage storage & station facilities","🔁 daily",
 "Coin lockers at Yeosu-Expo Station and the bus terminal, letting you do the city on a train-day layover",
 "Roughly **06:00–23:00**",
 "**₩2,000–₩5,000** per day",
 "[letskorail.com](https://www.letskorail.com) · [yeosu.go.kr](https://www.yeosu.go.kr)",
 "**Yeosu works as a long stopover** — the station is walking distance from Odongdo and the aquarium."),

("🗺️","Yeosu half-day route from the KTX station","🔁 planning",
 "Arrive Yeosu-Expo → Aqua Planet or Sky Tower → walk the waterfront to Odongdo → Jasan Park → cable car → Jongpo dinner → evening train",
 "About 6 hours",
 "**₩30,000–₩60,000**",
 "[yeosu.go.kr](https://www.yeosu.go.kr)",
 "**Everything on this route is within 3 km of the station** — no transport needed beyond the cable car."),
]

append("/home/user/KoreaFun/yeosu.md", E, 178, 3,
       "\n---\n\n## 🧭 Beginner-friendly essentials", "Yeosu")
